node-red-1881/node_modules/nan/nan_implementation_pre_12_inl.h File Reference
Namespaces
  imp
Macros
#define NAN_IMPLEMENTATION_PRE_12_INL_H_
Functions
template<typename T >
v8::Local< T > New (v8::Handle< T > h)
template<typename T >
v8::Local< T > New (v8::Persistent< T > const &p)
template<typename T , typename M >
v8::Local< T > New (Persistent< T, M > const &p)
template<typename T >
v8::Local< T > New (Global< T > const &p)
Macro Definition Documentation
NAN_IMPLEMENTATION_PRE_12_INL_H_
#define NAN_IMPLEMENTATION_PRE_12_INL_H_
Definition at line 11 of file nan.h.
Function Documentation
New() [1/4]
template<typename T >
v8::Local<T> New (v8::Handle< T > h)
Definition at line 244 of file nan_implementation_pre_12_inl.h.
Referenced by New().
                                     {
  return v8::Local<T>::New(h);
}
New() [2/4]
template<typename T >
v8::Local<T> New (v8::Persistent< T > const & p)
Definition at line 249 of file nan_implementation_pre_12_inl.h.
References New().
                                                {
  return v8::Local<T>::New(p);
}
New() [3/4]
template<typename T , typename M >
v8::Local<T> New (Persistent< T, M > const & p)
Definition at line 254 of file nan_implementation_pre_12_inl.h.
References New().
                                                 {
  return v8::Local<T>::New(p.persistent);
}
New() [4/4]
template<typename T >
v8::Local<T> New (Global< T > const & p)
Definition at line 259 of file nan_implementation_pre_12_inl.h.
References New().
                                          {
  return v8::Local<T>::New(p.persistent);
}