node-red-1881/node_modules/nan/nan_private.h File Reference
Macros
#define NAN_PRIVATE_H_
Functions
Maybe< bool > HasPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
 MaybeLocal< v8::Value > GetPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
Maybe< bool > SetPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key, v8::Local< v8::Value > value)
Maybe< bool > DeletePrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
Macro Definition Documentation
NAN_PRIVATE_H_
#define NAN_PRIVATE_H_
Definition at line 11 of file nan.h.
Function Documentation
DeletePrivate()
Maybe<bool> DeletePrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
Definition at line 59 of file nan_private.h.
References Nan::Just().
                           {
#if NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION
  HandleScope scope;
  v8::Isolate *isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Private> private_key = v8::Private::ForApi(isolate, key);
  return object->DeletePrivate(isolate->GetCurrentContext(), private_key);
#else
  return Just(object->DeleteHiddenValue(key));
#endif
}
GetPrivate()
 MaybeLocal<v8::Value> GetPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
Definition at line 26 of file nan_private.h.
References Nan::Undefined().
                                                            {
#if NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION
  v8::Isolate *isolate = v8::Isolate::GetCurrent();
  v8::EscapableHandleScope scope(isolate);
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Private> private_key = v8::Private::ForApi(isolate, key);
  v8::MaybeLocal<v8::Value> v = object->GetPrivate(context, private_key);
  return scope.Escape(v.ToLocalChecked());
#else
  EscapableHandleScope scope;
  v8::Local<v8::Value> v = object->GetHiddenValue(key);
  if (v.IsEmpty()) {
    v = Undefined();
  }
  return scope.Escape(v);
#endif
}
HasPrivate()
Maybe<bool> HasPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key)
Definition at line 13 of file nan_private.h.
References Nan::Just().
                                                            {
  HandleScope scope;
#if NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION
  v8::Isolate *isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Private> private_key = v8::Private::ForApi(isolate, key);
  return object->HasPrivate(context, private_key);
#else
  return Just(!object->GetHiddenValue(key).IsEmpty());
#endif
}
SetPrivate()
Maybe<bool> SetPrivate (v8::Local< v8::Object > object, v8::Local< v8::String > key, v8::Local< v8::Value > value)
Definition at line 44 of file nan_private.h.
References Nan::Just().
                            {
#if NODE_MODULE_VERSION >= NODE_6_0_MODULE_VERSION
  HandleScope scope;
  v8::Isolate *isolate = v8::Isolate::GetCurrent();
  v8::Local<v8::Context> context = isolate->GetCurrentContext();
  v8::Local<v8::Private> private_key = v8::Private::ForApi(isolate, key);
  return object->SetPrivate(context, private_key, value);
#else
  return Just(object->SetHiddenValue(key, value));
#endif
}