node-red-1881/node_modules/nan/nan_new.h File Reference
#include `nan_implementation_pre_12_inl.h`
Classes
struct imp::FactoryBase< T >
struct imp::MaybeFactoryBase< T >
struct imp::Factory< T >
struct imp::Factory< v8::Array >
struct imp::Factory< v8::Boolean >
struct imp::Factory< v8::BooleanObject >
struct imp::Factory< v8::Context >
struct imp::Factory< v8::Date >
struct imp::Factory< v8::External >
struct imp::Factory< v8::Function >
struct imp::Factory< v8::FunctionTemplate >
struct imp::Factory< v8::Number >
struct imp::Factory< v8::NumberObject >
struct imp::IntegerFactory< T >
struct imp::Factory< v8::Integer >
struct imp::Factory< v8::Int32 >
struct imp::Factory< v8::Uint32 >
struct imp::Factory< v8::Object >
struct imp::Factory< v8::ObjectTemplate >
struct imp::Factory< v8::RegExp >
struct imp::Factory< v8::Script >
struct imp::Factory< v8::Signature >
struct imp::Factory< v8::String >
struct imp::Factory< v8::StringObject >
Namespaces
  imp
Macros
#define NAN_NEW_H_
Functions
template<typename T >
v8::Local< T > imp::To (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Integer > imp::To< v8::Integer > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Int32 > imp::To< v8::Int32 > (v8::Local< v8::Integer > i)
template<>
v8::Local< v8::Uint32 > imp::To< v8::Uint32 > (v8::Local< v8::Integer > i)
template<typename T >
 imp::Factory< T >::return_t New ()
template<typename T , typename A0 >
 imp::Factory< T >::return_t New (A0 arg0)
template<typename T , typename A0 , typename A1 >
 imp::Factory< T >::return_t New (A0 arg0, A1 arg1)
template<typename T , typename A0 , typename A1 , typename A2 >
 imp::Factory< T >::return_t New (A0 arg0, A1 arg1, A2 arg2)
template<typename T , typename A0 , typename A1 , typename A2 , typename A3 >
 imp::Factory< T >::return_t New (A0 arg0, A1 arg1, A2 arg2, A3 arg3)
template<typename T >
 imp::Factory< T >::return_t New (FunctionCallback callback, v8::Local< v8::Value > data=v8::Local< v8::Value >())
template<typename T , typename A2 >
 imp::Factory< T >::return_t New (FunctionCallback callback, v8::Local< v8::Value > data=v8::Local< v8::Value >(), A2 a2=A2())
template<typename T >
v8::Local< T > New (v8::Persistent< T > const &p)
template<typename T , typename M >
v8::Local< T > New (Persistent< T, M > const &p)
template<typename T >
v8::Local< T > New (Global< T > const &p)
 imp::Factory< v8::Boolean >::return_t New (bool value)
 imp::Factory< v8::Int32 >::return_t New (int32_t value)
 imp::Factory< v8::Uint32 >::return_t New (uint32_t value)
 imp::Factory< v8::Number >::return_t New (double value)
 imp::Factory< v8::String >::return_t New (std::string const &value)
 imp::Factory< v8::String >::return_t New (const char *value, int length)
 imp::Factory< v8::String >::return_t New (const uint16_t *value, int length)
 imp::Factory< v8::String >::return_t New (const char *value)
 imp::Factory< v8::String >::return_t New (const uint16_t *value)
 imp::Factory< v8::String >::return_t New (v8::String::ExternalStringResource *value)
 imp::Factory< v8::String >::return_t New (ExternalOneByteStringResource *value)
 imp::Factory< v8::RegExp >::return_t New (v8::Local< v8::String > pattern, v8::RegExp::Flags flags)
Macro Definition Documentation
NAN_NEW_H_
#define NAN_NEW_H_
Definition at line 11 of file nan.h.
Function Documentation
New() [1/22]
template<typename T >
 imp::Factory<T>::return_t New ()
Definition at line 201 of file nan_new.h.
Referenced by New().
      {
  return imp::Factory<T>::New();
}
New() [2/22]
template<typename T , typename A0 >
 imp::Factory<T>::return_t New (A0 arg0)
Definition at line 207 of file nan_new.h.
References New().
             {
  return imp::Factory<T>::New(arg0);
}
New() [3/22]
template<typename T , typename A0 , typename A1 >
 imp::Factory<T>::return_t New (A0 arg0, A1 arg1)
Definition at line 213 of file nan_new.h.
References New().
                      {
  return imp::Factory<T>::New(arg0, arg1);
}
New() [4/22]
template<typename T , typename A0 , typename A1 , typename A2 >
 imp::Factory<T>::return_t New (A0 arg0, A1 arg1, A2 arg2)
Definition at line 219 of file nan_new.h.
References New().
                               {
  return imp::Factory<T>::New(arg0, arg1, arg2);
}
New() [5/22]
template<typename T , typename A0 , typename A1 , typename A2 , typename A3 >
 imp::Factory<T>::return_t New (A0 arg0, A1 arg1, A2 arg2, A3 arg3)
Definition at line 225 of file nan_new.h.
References New().
                                        {
  return imp::Factory<T>::New(arg0, arg1, arg2, arg3);
}
New() [6/22]
template<typename T >
 imp::Factory<T>::return_t New (FunctionCallback callback, v8::Local< v8::Value > data = v8::Local<v8::Value>())
Definition at line 237 of file nan_new.h.
References main3::data, and New().
                                                    {
    return imp::Factory<T>::New(callback, data);
}
New() [7/22]
template<typename T , typename A2 >
 imp::Factory<T>::return_t New (FunctionCallback callback, v8::Local< v8::Value > data = v8::Local<v8::Value>(), A2 a2 = A2())
Definition at line 245 of file nan_new.h.
References main3::data, and New().
                      {
    return imp::Factory<T>::New(callback, data, a2);
}
New() [8/22]
template<typename T >
v8::Local<T> New (v8::Persistent< T > const & p)
Definition at line 250 of file nan.h.
References New().
New() [9/22]
template<typename T , typename M >
v8::Local<T> New (Persistent< T, M > const & p)
Definition at line 416 of file nan_implementation_12_inl.h.
References New().
Referenced by imp::Factory< v8::Array >::New(), imp::Factory< v8::Boolean >::New(), imp::Factory< v8::BooleanObject >::New(), imp::Factory< v8::Context >::New(), imp::Factory< v8::Date >::New(), imp::Factory< v8::External >::New(), imp::Factory< v8::Function >::New(), imp::Factory< v8::FunctionTemplate >::New(), imp::Factory< v8::Number >::New(), imp::Factory< v8::NumberObject >::New(), imp::IntegerFactory< v8::Int32 >::New(), imp::Factory< v8::Object >::New(), imp::Factory< v8::ObjectTemplate >::New(), imp::Factory< v8::RegExp >::New(), imp::Factory< v8::Script >::New(), imp::Factory< v8::String >::New(), imp::Factory< v8::StringObject >::New(), and New().
                                                   {
  return v8::Local<T>::New(v8::Isolate::GetCurrent(), p);
}
New() [10/22]
template<typename T >
v8::Local<T> New (Global< T > const & p)
Definition at line 426 of file nan_implementation_12_inl.h.
References New().
                                          {
  return v8::Local<T>::New(v8::Isolate::GetCurrent(), p);
}
New() [11/22]
 imp::Factory<v8::Boolean>::return_t New (bool value)
Definition at line 270 of file nan_new.h.
                {
  return New<v8::Boolean>(value);
}
New() [12/22]
 imp::Factory<v8::Int32>::return_t New (int32_t value)
Definition at line 276 of file nan_new.h.
                   {
  return New<v8::Int32>(value);
}
New() [13/22]
 imp::Factory<v8::Uint32>::return_t New (uint32_t value)
Definition at line 282 of file nan_new.h.
                    {
  return New<v8::Uint32>(value);
}
New() [14/22]
 imp::Factory<v8::Number>::return_t New (double value)
Definition at line 288 of file nan_new.h.
                  {
  return New<v8::Number>(value);
}
New() [15/22]
 imp::Factory<v8::String>::return_t New (std::string const & value)
Definition at line 294 of file nan_new.h.
                            { // NOLINT(build/include_what_you_use)
  return New<v8::String>(value);
}
New() [16/22]
 imp::Factory<v8::String>::return_t New (const char * value, int length)
Definition at line 300 of file nan_new.h.
                                    {
  return New<v8::String>(value, length);
}
New() [17/22]
 imp::Factory<v8::String>::return_t New (const uint16_t * value, int length)
Definition at line 306 of file nan_new.h.
                                        {
  return New<v8::String>(value, length);
}
New() [18/22]
 imp::Factory<v8::String>::return_t New (const char * value)
Definition at line 312 of file nan_new.h.
                        {
  return New<v8::String>(value);
}
New() [19/22]
 imp::Factory<v8::String>::return_t New (const uint16_t * value)
Definition at line 318 of file nan_new.h.
                            {
  return New<v8::String>(value);
}
New() [20/22]
 imp::Factory<v8::String>::return_t New (v8::String::ExternalStringResource * value)
Definition at line 324 of file nan_new.h.
                                            {
  return New<v8::String>(value);
}
New() [21/22]
 imp::Factory<v8::String>::return_t New (ExternalOneByteStringResource * value)
Definition at line 330 of file nan_new.h.
                                           {
  return New<v8::String>(value);
}
New() [22/22]
 imp::Factory<v8::RegExp>::return_t New (v8::Local< v8::String > pattern, v8::RegExp::Flags flags)
Definition at line 336 of file nan_new.h.
                                                    {
  return New<v8::RegExp>(pattern, flags);
}