node-red-1881/node_modules/nan/nan_implementation_12_inl.h File Reference
Namespaces
  imp
Functions
template<typename T , typename M >
v8::Local< T > New (v8::Persistent< T, M > const &p)
template<typename T , typename M >
v8::Local< T > New (Persistent< T, M > const &p)
template<typename T >
v8::Local< T > New (Global< T > const &p)
Function Documentation
New() [1/3]
template<typename T , typename M >
v8::Local<T> New (v8::Persistent< T, M > const & p)
Definition at line 416 of file nan_implementation_12_inl.h.
Referenced by imp::Factory< v8::Array >::New(), imp::Factory< v8::Boolean >::New(), imp::Factory< v8::BooleanObject >::New(), imp::Factory< v8::Context >::New(), imp::Factory< v8::Date >::New(), imp::Factory< v8::External >::New(), imp::Factory< v8::Function >::New(), imp::Factory< v8::FunctionTemplate >::New(), imp::Factory< v8::Number >::New(), imp::Factory< v8::NumberObject >::New(), imp::IntegerFactory< v8::Int32 >::New(), imp::Factory< v8::Object >::New(), imp::Factory< v8::ObjectTemplate >::New(), imp::Factory< v8::RegExp >::New(), imp::Factory< v8::Script >::New(), imp::Factory< v8::String >::New(), imp::Factory< v8::StringObject >::New(), and New().
                                                   {
  return v8::Local<T>::New(v8::Isolate::GetCurrent(), p);
}
New() [2/3]
template<typename T , typename M >
v8::Local<T> New (Persistent< T, M > const & p)
Definition at line 421 of file nan_implementation_12_inl.h.
References New().
                                                 {
  return v8::Local<T>::New(v8::Isolate::GetCurrent(), p);
}
New() [3/3]
template<typename T >
v8::Local<T> New (Global< T > const & p)
Definition at line 426 of file nan_implementation_12_inl.h.
                                          {
  return v8::Local<T>::New(v8::Isolate::GetCurrent(), p);
}