node-red-1881/node_modules/sqlite3/build/Release/obj/gen/sqlite-autoconf-3310100/shell.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <assert.h>
#include `sqlite3.h`
#include <ctype.h>
#include <stdarg.h>
#include <signal.h>
#include <pwd.h>
#include <unistd.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <utime.h>
#include <time.h>
#include <errno.h>
Classes
struct ShellText
struct SHA3Context
struct FsdirLevel
struct fsdir_cursor
struct fsdir_tab
struct completion_vtab
struct completion_cursor
struct ApndFile
struct IdxConstraint
struct IdxScan
struct IdxColumn
struct IdxTable
struct IdxWrite
struct IdxStatement
struct IdxHashEntry
struct IdxHash
struct sqlite3expert
struct ExpertVtab
struct ExpertCsr
struct IdxSampleCtx
struct IdxRemCtx
struct IdxRemCtx::IdxRemSlot
struct SavedModeInfo
struct ExpertInfo
struct EQPGraphRow
struct EQPGraph
struct ShellState
struct ImportCtx
Macros
#define _LARGE_FILE 1
#define _FILE_OFFSET_BITS 64
#define _LARGEFILE_SOURCE 1
#define GETPID getpid
#define shell_read_history(X)
#define shell_write_history(X)
#define shell_stifle_history(X)
#define SHELL_USE_LOCAL_GETLINE 1
#define IsSpace(X) isspace((unsigned char) X)
#define IsDigit(X) isdigit((unsigned char) X)
#define ToLower(X) (char)tolower((unsigned char) X)
#define setBinaryMode(X, Y)
#define setTextMode(X, Y)
#define BEGIN_TIMER beginTimer()
#define END_TIMER endTimer()
#define HAS_TIMER 1
#define UNUSED_PARAMETER(x) (void)(x)
#define ArraySize(X) (int)(sizeof(X)/sizeof(X[0]))
#define utf8_printf fprintf
#define raw_printf fprintf
#define SQLITE_EXTENSION_INIT1
#define SQLITE_EXTENSION_INIT2(X) (void)(X)
#define SHA3_BYTEORDER 0
#define a00 (p->u.s[0])
#define a01 (p->u.s[1])
#define a02 (p->u.s[2])
#define a03 (p->u.s[3])
#define a04 (p->u.s[4])
#define a10 (p->u.s[5])
#define a11 (p->u.s[6])
#define a12 (p->u.s[7])
#define a13 (p->u.s[8])
#define a14 (p->u.s[9])
#define a20 (p->u.s[10])
#define a21 (p->u.s[11])
#define a22 (p->u.s[12])
#define a23 (p->u.s[13])
#define a24 (p->u.s[14])
#define a30 (p->u.s[15])
#define a31 (p->u.s[16])
#define a32 (p->u.s[17])
#define a33 (p->u.s[18])
#define a34 (p->u.s[19])
#define a40 (p->u.s[20])
#define a41 (p->u.s[21])
#define a42 (p->u.s[22])
#define a43 (p->u.s[23])
#define a44 (p->u.s[24])
#define ROL64(a, x) ((a<<x)|(a>>(64-x)))
#define FSDIR_SCHEMA `(name,mode,mtime,data,path HIDDEN,dir HIDDEN)`
#define FSDIR_COLUMN_NAME 0 /* Name of the file */
#define FSDIR_COLUMN_MODE 1 /* Access mode */
#define FSDIR_COLUMN_MTIME 2 /* Last modification time */
#define FSDIR_COLUMN_DATA 3 /* File content */
#define FSDIR_COLUMN_PATH 4 /* Path to top of search */
#define FSDIR_COLUMN_DIR 5 /* Path is relative to this directory */
#define COMPLETION_FIRST_PHASE 1
#define COMPLETION_KEYWORDS 1
#define COMPLETION_PRAGMAS 2
#define COMPLETION_FUNCTIONS 3
#define COMPLETION_COLLATIONS 4
#define COMPLETION_INDEXES 5
#define COMPLETION_TRIGGERS 6
#define COMPLETION_DATABASES 7
#define COMPLETION_TABLES 8 /* Also VIEWs and TRIGGERs */
#define COMPLETION_COLUMNS 9
#define COMPLETION_MODULES 10
#define COMPLETION_EOF 11
#define COMPLETION_COLUMN_CANDIDATE 0 /* Suggested completion of the input */
#define COMPLETION_COLUMN_PREFIX 1 /* Prefix of the word to be completed */
#define COMPLETION_COLUMN_WHOLELINE 2 /* Entire line seen so far */
#define COMPLETION_COLUMN_PHASE 3 /* ePhase - used for debugging only */
#define APND_MARK_PREFIX `Start-Of-SQLite3-`
#define APND_MARK_PREFIX_SZ 17
#define APND_MARK_SIZE 25
#define APND_MAX_SIZE (65536*15259)
#define ORIGVFS(p) ((sqlite3_vfs*)((p)->pAppData))
#define ORIGFILE(p) ((sqlite3_file*)(((ApndFile*)(p))+1))
#define SQLITEEXPERT_H 1
#define EXPERT_CONFIG_SAMPLE 1 /* int */
#define EXPERT_REPORT_SQL 1
#define EXPERT_REPORT_INDEXES 2
#define EXPERT_REPORT_PLAN 3
#define EXPERT_REPORT_CANDIDATES 4
#define STRLEN (int)strlen
#define UNIQUE_TABLE_NAME `t592690916721053953805701627921227776`
#define IDX_HASH_SIZE 1023
#define AUTOEQP_off 0 /* Automatic EXPLAIN QUERY PLAN is off */
#define AUTOEQP_on 1 /* Automatic EQP is on */
#define AUTOEQP_trigger 2 /* On and also show plans for triggers */
#define AUTOEQP_full 3 /* Show full EXPLAIN */
#define SHELL_OPEN_UNSPEC 0 /* No open-mode specified */
#define SHELL_OPEN_NORMAL 1 /* Normal database file */
#define SHELL_OPEN_APPENDVFS 2 /* Use appendvfs */
#define SHELL_OPEN_ZIPFILE 3 /* Use the zipfile virtual table */
#define SHELL_OPEN_READONLY 4 /* Open a normal database read-only */
#define SHELL_OPEN_DESERIALIZE 5 /* Open using sqlite3_deserialize() */
#define SHELL_OPEN_HEXDB 6 /* Use `dbtotxt` output as data source */
#define SHELL_TRACE_PLAIN 0 /* Show input SQL text */
#define SHELL_TRACE_EXPANDED 1 /* Show expanded SQL text */
#define SHELL_TRACE_NORMALIZED 2 /* Show normalized SQL text */
#define SHELL_PROGRESS_QUIET 0x01 /* Omit announcing every progress callback */
#define SHELL_PROGRESS_RESET
#define SHELL_PROGRESS_ONCE 0x04 /* Cancel the --limit after firing once */
#define SHFLG_Pagecache 0x00000001 /* The --pagecache option is used */
#define SHFLG_Lookaside 0x00000002 /* Lookaside memory is used */
#define SHFLG_Backslash 0x00000004 /* The --backslash option is used */
#define SHFLG_PreserveRowid 0x00000008 /* .dump preserves rowid values */
#define SHFLG_Newlines 0x00000010 /* .dump --newline flag */
#define SHFLG_CountChanges 0x00000020 /* .changes setting */
#define SHFLG_Echo 0x00000040 /* .echo or --echo setting */
#define ShellHasFlag(P, X) (((P)->shellFlgs & (X))!=0)
#define ShellSetFlag(P, X) ((P)->shellFlgs|=(X))
#define ShellClearFlag(P, X) ((P)->shellFlgs&=(~(X)))
#define MODE_Line 0 /* One column per line. Blank line between records */
#define MODE_Column 1 /* One record per line in neat columns */
#define MODE_List 2 /* One record per line with a separator */
#define MODE_Semi 3 /* Same as MODE_List but append `;` to each line */
#define MODE_Html 4 /* Generate an XHTML table */
#define MODE_Insert 5 /* Generate SQL `insert` statements */
#define MODE_Quote 6 /* Quote values as for SQL */
#define MODE_Tcl 7 /* Generate ANSI-C or TCL quoted elements */
#define MODE_Csv 8 /* Quote strings, numbers are plain */
#define MODE_Explain 9 /* Like MODE_Column, but do not truncate data */
#define MODE_Ascii 10 /* Use ASCII unit and record separators (0x1F/0x1E) */
#define MODE_Pretty 11 /* Pretty-print schemas */
#define MODE_EQP 12 /* Converts EXPLAIN QUERY PLAN output into a graph */
#define SEP_Column `|`
#define SEP_Row `\n`
#define SEP_Tab `\t`
#define SEP_Space ` `
#define SEP_Comma `,`
#define SEP_CrLf `\r\n`
#define SEP_Unit `\x1F`
#define SEP_Record `\x1E`
#define session_close_all(X)
#define OPEN_DB_KEEPALIVE 0x001 /* Return after error if true */
#define OPEN_DB_ZIPFILE 0x002 /* Open as ZIP if name matches *.zip */
#define CTIMEOPT_VAL_(opt) #opt
#define CTIMEOPT_VAL(opt) CTIMEOPT_VAL_(opt)
#define SQLITE_SHELL_IS_UTF8 (1)
Typedefs
typedef sqlite3_int64 i64
typedef sqlite3_uint64 u64
typedef unsigned char u8
typedef struct ShellText ShellText
typedef struct SHA3Context SHA3Context
typedef struct fsdir_cursor fsdir_cursor
typedef struct FsdirLevel FsdirLevel
typedef struct fsdir_tab fsdir_tab
typedef typedefSQLITE_EXTENSION_INIT1 struct completion_vtab completion_vtab
typedef struct completion_cursor completion_cursor
typedef struct sqlite3_vfs ApndVfs
typedef struct ApndFile ApndFile
typedef struct sqlite3expert sqlite3expert
typedef struct IdxColumn IdxColumn
typedef struct IdxConstraint IdxConstraint
typedef struct IdxScan IdxScan
typedef struct IdxStatement IdxStatement
typedef struct IdxTable IdxTable
typedef struct IdxWrite IdxWrite
typedef struct IdxHashEntry IdxHashEntry
typedef struct IdxHash IdxHash
typedef struct ExpertVtab ExpertVtab
typedef struct ExpertCsr ExpertCsr
typedef struct SavedModeInfo SavedModeInfo
typedef struct ExpertInfo ExpertInfo
typedef struct EQPGraphRow EQPGraphRow
typedef struct EQPGraph EQPGraph
typedef struct ShellState ShellState
typedef struct ImportCtx ImportCtx
Functions
int isatty (int)
FILE * popen (const char *, const char *)
int pclose (FILE *)
static sqlite3_int64 timeOfDay (void)
static void beginTimer (void)
static double timeDiff (struct timeval *pStart, struct timeval *pEnd)
static void endTimer (void)
static void shell_out_of_memory (void)
static void utf8_width_print (FILE *pOut, int w, const char *zUtf)
static int isNumber (const char *z, int *realnum)
static int strlen30 (const char *z)
static int strlenChar (const char *z)
static char * local_getline (char *zLine, FILE *in)
static char * one_input_line (FILE *in, char *zPrior, int isContinuation)
static int hexDigitValue (char c)
static sqlite3_int64 integerValue (const char *zArg)
static void initText (ShellText *p)
static void freeText (ShellText *p)
static void appendText (ShellText *p, char const *zAppend, char quote)
static char quoteChar (const char * zName)
static char * shellFakeSchema (sqlite3 *db, const char *zSchema, const char * zName)
static void shellModuleSchema (sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
static void shellAddSchemaName (sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
static void KeccakF1600Step (SHA3Context *p)
static void SHA3Init (SHA3Context *p, int iSize)
static void SHA3Update (SHA3Context *p, const unsigned char *aData, unsigned int nData)
static unsigned char * SHA3Final (SHA3Context *p)
static void sha3Func (sqlite3_context *context, int argc, sqlite3_value **argv)
static void hash_step_vformat (SHA3Context *p, const char *zFormat,...)
static void sha3QueryFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
int sqlite3_shathree_init (sqlite3 *db, char **pzErrMsg, const sqlite3_api_routines *pApi)
static void readFileContents (sqlite3_context *ctx, const char * zName)
static void readfileFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void ctxErrorMsg (sqlite3_context *ctx, const char *zFmt,...)
static int fileStat (const char *zPath, struct stat *pStatBuf)
static int fileLinkStat (const char *zPath, struct stat *pStatBuf)
static int makeDirectory (const char *zFile)
static int writeFile (sqlite3_context *pCtx, const char *zFile, sqlite3_value *pData, mode_t mode, sqlite3_int64 mtime)
static void writefileFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void lsModeFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static int fsdirConnect (sqlite3 *db, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVtab, char **pzErr)
static int fsdirDisconnect (sqlite3_vtab *pVtab)
static int fsdirOpen (sqlite3_vtab *p, sqlite3_vtab_cursor **ppCursor)
static void fsdirResetCursor (fsdir_cursor *pCur)
static int fsdirClose (sqlite3_vtab_cursor *cur)
static void fsdirSetErrmsg (fsdir_cursor *pCur, const char *zFmt,...)
static int fsdirNext (sqlite3_vtab_cursor *cur)
static int fsdirColumn (sqlite3_vtab_cursor *cur, sqlite3_context *ctx, int i)
static int fsdirRowid (sqlite3_vtab_cursor *cur, sqlite_int64 *pRowid)
static int fsdirEof (sqlite3_vtab_cursor *cur)
static int fsdirFilter (sqlite3_vtab_cursor *cur, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
static int fsdirBestIndex (sqlite3_vtab *tab, sqlite3_index_info *pIdxInfo)
static int fsdirRegister (sqlite3 *db)
int sqlite3_fileio_init (sqlite3 *db, char **pzErrMsg, const sqlite3_api_routines *pApi)
static int completionConnect (sqlite3 *db, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVtab, char **pzErr)
static int completionDisconnect (sqlite3_vtab *pVtab)
static int completionOpen (sqlite3_vtab *p, sqlite3_vtab_cursor **ppCursor)
static void completionCursorReset (completion_cursor *pCur)
static int completionClose (sqlite3_vtab_cursor *cur)
static int completionNext (sqlite3_vtab_cursor *cur)
static int completionColumn (sqlite3_vtab_cursor *cur, sqlite3_context *ctx, int i)
static int completionRowid (sqlite3_vtab_cursor *cur, sqlite_int64 *pRowid)
static int completionEof (sqlite3_vtab_cursor *cur)
static int completionFilter (sqlite3_vtab_cursor *pVtabCursor, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
static int completionBestIndex (sqlite3_vtab *tab, sqlite3_index_info *pIdxInfo)
int sqlite3CompletionVtabInit (sqlite3 *db)
int sqlite3_completion_init (sqlite3 *db, char **pzErrMsg, const sqlite3_api_routines *pApi)
static int apndClose (sqlite3_file *)
static int apndRead (sqlite3_file *, void *, int iAmt, sqlite3_int64 iOfst)
static int apndWrite (sqlite3_file *, const void *, int iAmt, sqlite3_int64 iOfst)
static int apndTruncate (sqlite3_file *, sqlite3_int64 size)
static int apndSync (sqlite3_file *, int flags)
static int apndFileSize (sqlite3_file *, sqlite3_int64 *pSize)
static int apndLock (sqlite3_file *, int)
static int apndUnlock (sqlite3_file *, int)
static int apndCheckReservedLock (sqlite3_file *, int *pResOut)
static int apndFileControl (sqlite3_file *, int op, void *pArg)
static int apndSectorSize (sqlite3_file *)
static int apndDeviceCharacteristics (sqlite3_file *)
static int apndShmMap (sqlite3_file *, int iPg, int pgsz, int, void volatile **)
static int apndShmLock (sqlite3_file *, int offset, int n, int flags)
static void apndShmBarrier (sqlite3_file *)
static int apndShmUnmap (sqlite3_file *, int deleteFlag)
static int apndFetch (sqlite3_file *, sqlite3_int64 iOfst, int iAmt, void **pp)
static int apndUnfetch (sqlite3_file *, sqlite3_int64 iOfst, void *p)
static int apndOpen (sqlite3_vfs *, const char *, sqlite3_file *, int, int *)
static int apndDelete (sqlite3_vfs *, const char * zName, int syncDir)
static int apndAccess (sqlite3_vfs *, const char * zName, int flags, int *)
static int apndFullPathname (sqlite3_vfs *, const char * zName, int, char *zOut)
static void * apndDlOpen (sqlite3_vfs *, const char *zFilename)
static void apndDlError (sqlite3_vfs *, int nByte, char *zErrMsg)
static void apndDlClose (sqlite3_vfs *, void *)
static int apndRandomness (sqlite3_vfs *, int nByte, char *zOut)
static int apndSleep (sqlite3_vfs *, int microseconds)
static int apndCurrentTime (sqlite3_vfs *, double *)
static int apndGetLastError (sqlite3_vfs *, int, char *)
static int apndCurrentTimeInt64 (sqlite3_vfs *, sqlite3_int64 *)
static int apndSetSystemCall (sqlite3_vfs *, const char *, sqlite3_syscall_ptr)
static sqlite3_syscall_ptr apndGetSystemCall (sqlite3_vfs *, const char *z)
static const char * apndNextSystemCall (sqlite3_vfs *, const char * zName)
static int apndWriteMark (ApndFile *p, sqlite3_file *pFile)
static int apndIsOrdinaryDatabaseFile (sqlite3_int64 sz, sqlite3_file *pFile)
static sqlite3_int64 apndReadMark (sqlite3_int64 sz, sqlite3_file *pFile)
int sqlite3_appendvfs_init (sqlite3 *db, char **pzErrMsg, const sqlite3_api_routines *pApi)
static void * memtraceMalloc (int n)
static void memtraceFree (void *p)
static void * memtraceRealloc (void *p, int n)
static int memtraceSize (void *p)
static int memtraceRoundup (int n)
static int memtraceInit (void *p)
static void memtraceShutdown (void *p)
int sqlite3MemTraceActivate (FILE *out)
int sqlite3MemTraceDeactivate (void)
 sqlite3expert * sqlite3_expert_new (sqlite3 *db, char **pzErr)
int sqlite3_expert_config (sqlite3expert *p, int op,...)
int sqlite3_expert_sql (sqlite3expert *p, const char *zSql, char **pzErr)
int sqlite3_expert_analyze (sqlite3expert *p, char **pzErr)
int sqlite3_expert_count (sqlite3expert *)
const char * sqlite3_expert_report (sqlite3expert *, int iStmt, int eReport)
void sqlite3_expert_destroy (sqlite3expert *)
static void * idxMalloc (int *pRc, int nByte)
static void idxHashInit (IdxHash *pHash)
static void idxHashClear (IdxHash *pHash)
static int idxHashString (const char *z, int n)
static int idxHashAdd (int *pRc, IdxHash *pHash, const char *zKey, const char *zVal)
static IdxHashEntry * idxHashFind (IdxHash *pHash, const char *zKey, int nKey)
static const char * idxHashSearch (IdxHash *pHash, const char *zKey, int nKey)
static IdxConstraint * idxNewConstraint (int *pRc, const char *zColl)
static void idxDatabaseError (sqlite3 *db, char **pzErrmsg)
static int idxPrepareStmt (sqlite3 *db, sqlite3_stmt **ppStmt, char **pzErrmsg, const char *zSql)
static int idxPrintfPrepareStmt (sqlite3 *db, sqlite3_stmt **ppStmt, char **pzErrmsg, const char *zFmt,...)
static char * expertDequote (const char *zIn)
static int expertConnect (sqlite3 *db, void *pAux, int argc, const char *const *argv, sqlite3_vtab **ppVtab, char **pzErr)
static int expertDisconnect (sqlite3_vtab *pVtab)
static int expertBestIndex (sqlite3_vtab *pVtab, sqlite3_index_info *pIdxInfo)
static int expertUpdate (sqlite3_vtab *pVtab, int nData, sqlite3_value **azData, sqlite_int64 *pRowid)
static int expertOpen (sqlite3_vtab *pVTab, sqlite3_vtab_cursor **ppCursor)
static int expertClose (sqlite3_vtab_cursor *cur)
static int expertEof (sqlite3_vtab_cursor *cur)
static int expertNext (sqlite3_vtab_cursor *cur)
static int expertRowid (sqlite3_vtab_cursor *cur, sqlite_int64 *pRowid)
static int expertColumn (sqlite3_vtab_cursor *cur, sqlite3_context *ctx, int i)
static int expertFilter (sqlite3_vtab_cursor *cur, int idxNum, const char *idxStr, int argc, sqlite3_value **argv)
static int idxRegisterVtab (sqlite3expert *p)
static void idxFinalize (int *pRc, sqlite3_stmt *pStmt)
static int idxGetTableInfo (sqlite3 *db, const char *zTab, IdxTable **ppOut, char **pzErrmsg)
static char * idxAppendText (int *pRc, char *zIn, const char *zFmt,...)
static int idxIdentifierRequiresQuotes (const char *zId)
static char * idxAppendColDefn (int *pRc, char *zIn, IdxTable *pTab, IdxConstraint *pCons)
static int idxFindCompatible (int *pRc, sqlite3 *dbm, IdxScan *pScan, IdxConstraint *pEq, IdxConstraint *pTail)
static int idxCreateFromCons (sqlite3expert *p, IdxScan *pScan, IdxConstraint *pEq, IdxConstraint *pTail)
static int idxFindConstraint (IdxConstraint *pList, IdxConstraint *p)
static int idxCreateFromWhere (sqlite3expert *p, IdxScan *pScan, IdxConstraint *pTail)
static int idxCreateCandidates (sqlite3expert *p)
static void idxConstraintFree (IdxConstraint *pConstraint)
static void idxScanFree (IdxScan *pScan, IdxScan *pLast)
static void idxStatementFree (IdxStatement *pStatement, IdxStatement *pLast)
static void idxTableFree (IdxTable *pTab)
static void idxWriteFree (IdxWrite *pTab)
int idxFindIndexes (sqlite3expert *p, char **pzErr)
static int idxAuthCallback (void *pCtx, int eOp, const char *z3, const char *z4, const char *zDb, const char *zTrigger)
static int idxProcessOneTrigger (sqlite3expert *p, IdxWrite *pWrite, char **pzErr)
static int idxProcessTriggers (sqlite3expert *p, char **pzErr)
static int idxCreateVtabSchema (sqlite3expert *p, char **pzErrmsg)
static void idxSampleFunc (sqlite3_context *pCtx, int argc, sqlite3_value **argv)
static void idxRemFunc (sqlite3_context *pCtx, int argc, sqlite3_value **argv)
static int idxLargestIndex (sqlite3 *db, int *pnMax, char **pzErr)
static int idxPopulateOneStat1 (sqlite3expert *p, sqlite3_stmt *pIndexXInfo, sqlite3_stmt *pWriteStat, const char *zTab, const char *zIdx, char **pzErr)
static int idxBuildSampleTable (sqlite3expert *p, const char *zTab)
static int idxPopulateStat1 (sqlite3expert *p, char **pzErr)
static void shellLog (void *pArg, int iErrCode, const char *zMsg)
static void shellPutsFunc (sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
static void editFunc (sqlite3_context *context, int argc, sqlite3_value **argv)
static void outputModePush (ShellState *p)
static void outputModePop (ShellState *p)
static void output_hex_blob (FILE *out, const void *pBlob, int nBlob)
static const char * unused_string (const char *z, const char *zA, const char *zB, char *zBuf)
static void output_quoted_string (FILE *out, const char *z)
static void output_quoted_escaped_string (FILE *out, const char *z)
static void output_c_string (FILE *out, const char *z)
static void output_html_string (FILE *out, const char *z)
static void output_csv (ShellState *p, const char *z, int bSep)
static void interrupt_handler (int NotUsed)
static int shellAuth (void *pClientData, int op, const char *zA1, const char *zA2, const char *zA3, const char *zA4)
static void printSchemaLine (FILE *out, const char *z, const char *zTail)
static void printSchemaLineN (FILE *out, char *z, int n, const char *zTail)
static int wsToEol (const char *z)
static void eqp_append (ShellState *p, int iEqpId, int p2, const char *zText)
static void eqp_reset (ShellState *p)
static EQPGraphRow * eqp_next_row (ShellState *p, int iEqpId, EQPGraphRow *pOld)
static void eqp_render_level (ShellState *p, int iEqpId)
static void eqp_render (ShellState *p)
static int progress_handler (void *pClientData)
static int shell_callback (void *pArg, int nArg, char **azArg, char **azCol, int *aiType)
static int callback (void *pArg, int nArg, char **azArg, char **azCol)
static int captureOutputCallback (void *pArg, int nArg, char **azArg, char **az)
static void createSelftestTable (ShellState *p)
static void set_table_name (ShellState *p, const char * zName)
static int run_table_dump_query (ShellState *p, const char *zSelect, const char *zFirstRow)
static char * save_err_msg (sqlite3 *db)
static void displayStatLine (ShellState *p, char *zLabel, char *zFormat, int iStatusCtrl, int bReset)
static int display_stats (sqlite3 *db, ShellState *pArg, int bReset)
static void display_scanstats (sqlite3 *db, ShellState *pArg)
static int str_in_array (const char *zStr, const char **azArray)
static void explain_data_prepare (ShellState *p, sqlite3_stmt *pSql)
static void explain_data_delete (ShellState *p)
static void disable_debug_trace_modes (void)
static void restore_debug_trace_modes (void)
static void bind_table_init (ShellState *p)
static void bind_prepared_stmt (ShellState *pArg, sqlite3_stmt *pStmt)
static void exec_prepared_stmt (ShellState *pArg, sqlite3_stmt *pStmt)
static int expertHandleSQL (ShellState *pState, const char *zSql, char **pzErr)
static int expertFinish (ShellState *pState, int bCancel, char **pzErr)
static int expertDotCommand (ShellState *pState, char **azArg, int nArg)
static int shell_exec (ShellState *pArg, const char *zSql, char **pzErrMsg)
static void freeColumnList (char **azCol)
static char ** tableColumnList (ShellState *p, const char *zTab)
static void toggleSelectOrder (sqlite3 *db)
static int dump_callback (void *pArg, int nArg, char **azArg, char **azNotUsed)
static int run_schema_dump_query (ShellState *p, const char *zQuery)
static int showHelp (FILE *out, const char *zPattern)
static int process_input (ShellState *p)
static char * readFile (const char * zName, int *pnByte)
int deduceDatabaseType (const char * zName, int dfltZip)
static void shellInt32 (sqlite3_context *context, int argc, sqlite3_value **argv)
static void shellIdQuote (sqlite3_context *context, int argc, sqlite3_value **argv)
static void shellEscapeCrnl (sqlite3_context *context, int argc, sqlite3_value **argv)
static void open_db (ShellState *p, int openFlags)
void close_db (sqlite3 *db)
static void resolve_backslashes (char *z)
static int booleanValue (const char *zArg)
static void setOrClearFlag (ShellState *p, unsigned mFlag, const char *zArg)
static void output_file_close (FILE *f)
static FILE * output_file_open (const char *zFile, int bTextMode)
static int sql_trace_callback (unsigned mType, void *pArg, void *pP, void *pX)
static void test_breakpoint (void)
static void import_append_char (ImportCtx *p, int c)
static char * SQLITE_CDECL csv_read_one_field (ImportCtx *p)
static char * SQLITE_CDECL ascii_read_one_field (ImportCtx *p)
static void tryToCloneData (ShellState *p, sqlite3 *newDb, const char *zTable)
static void tryToCloneSchema (ShellState *p, sqlite3 *newDb, const char *zWhere, void(*xForEach)(ShellState *, sqlite3 *, const char *))
static void tryToClone (ShellState *p, const char *zNewDb)
static void output_reset (ShellState *p)
static int db_int (ShellState *p, const char *zSql)
static unsigned int get2byteInt (unsigned char *a)
static unsigned int get4byteInt (unsigned char *a)
static int shell_dbinfo_command (ShellState *p, int nArg, char **azArg)
static int shellDatabaseError (sqlite3 *db)
static int testcase_glob (const char *zGlob, const char *z)
static int optionMatch (const char *zStr, const char *zOpt)
int shellDeleteFile (const char *zFilename)
static void clearTempFile (ShellState *p)
static void newTempFile (ShellState *p, const char *zSuffix)
static void shellFkeyCollateClause (sqlite3_context *pCtx, int nVal, sqlite3_value **apVal)
static int lintFkeyIndexes (ShellState *pState, char **azArg, int nArg)
static int lintDotCommand (ShellState *pState, char **azArg, int nArg)
static void shellPrepare (sqlite3 *db, int *pRc, const char *zSql, sqlite3_stmt **ppStmt)
void shellPreparePrintf (sqlite3 *db, int *pRc, sqlite3_stmt **ppStmt, const char *zFmt,...)
void shellFinalize (int *pRc, sqlite3_stmt *pStmt)
void shellReset (int *pRc, sqlite3_stmt *pStmt)
static int do_meta_command (char *zLine, ShellState *p)
static int line_contains_semicolon (const char *z, int N)
static int _all_whitespace (const char *z)
static int line_is_command_terminator (const char *zLine)
static int line_is_complete (char *zSql, int nSql)
static int runOneSqlLine (ShellState *p, char *zSql, FILE *in, int startline)
static char * find_home_dir (int clearFlag)
static void process_sqliterc (ShellState *p, const char *sqliterc_override)
static void usage (int showDetail)
static void verify_uninitialized (void)
static void main_init (ShellState *data)
static void printBold (const char *zText)
static char * cmdline_option_value (int argc, char **argv, int i)
int SQLITE_CDECL main (int argc, char **argv)
Variables
static int enableTimer = 0
static struct rusage sBegin
static sqlite3_int64 iBegin
static int bail_on_error = 0
static int stdin_is_interactive = 1
static int stdout_is_console = 1
static sqlite3 * globalDb = 0
static volatile int seenInterrupt = 0
static char * Argv0
static char mainPrompt [20]
static char continuePrompt [20]
static sqlite3_module completionModule
static void(*)(void) apndDlSym (sqlite3_vfs *pVfs, void *p, const char *zSym)
static sqlite3_vfs apnd_vfs
static const sqlite3_io_methods apnd_io_methods
static sqlite3_mem_methods memtraceBase
static FILE * memtraceOut
static sqlite3_mem_methods ersaztMethods
static const char * modeDescr []
static const char needCsvQuote []
static const char * azHelp []
static const char zOptions []
Macro Definition Documentation
_FILE_OFFSET_BITS
#define _FILE_OFFSET_BITS 64
Definition at line 72 of file shell.c.
_LARGE_FILE
#define _LARGE_FILE 1
Definition at line 70 of file shell.c.
_LARGEFILE_SOURCE
#define _LARGEFILE_SOURCE 1
Definition at line 74 of file shell.c.
a00
#define a00 (p->u.s[0])
Referenced by KeccakF1600Step().
a01
#define a01 (p->u.s[1])
Referenced by KeccakF1600Step().
a02
#define a02 (p->u.s[2])
Referenced by KeccakF1600Step().
a03
#define a03 (p->u.s[3])
Referenced by KeccakF1600Step().
a04
#define a04 (p->u.s[4])
Referenced by KeccakF1600Step().
a10
#define a10 (p->u.s[5])
Referenced by KeccakF1600Step().
a11
#define a11 (p->u.s[6])
Referenced by KeccakF1600Step().
a12
#define a12 (p->u.s[7])
Referenced by KeccakF1600Step().
a13
#define a13 (p->u.s[8])
Referenced by KeccakF1600Step().
a14
#define a14 (p->u.s[9])
Referenced by KeccakF1600Step().
a20
#define a20 (p->u.s[10])
Referenced by KeccakF1600Step().
a21
#define a21 (p->u.s[11])
Referenced by KeccakF1600Step().
a22
#define a22 (p->u.s[12])
Referenced by KeccakF1600Step().
a23
#define a23 (p->u.s[13])
Referenced by KeccakF1600Step().
a24
#define a24 (p->u.s[14])
Referenced by KeccakF1600Step().
a30
#define a30 (p->u.s[15])
Referenced by KeccakF1600Step().
a31
#define a31 (p->u.s[16])
Referenced by KeccakF1600Step().
a32
#define a32 (p->u.s[17])
Referenced by KeccakF1600Step().
a33
#define a33 (p->u.s[18])
Referenced by KeccakF1600Step().
a34
#define a34 (p->u.s[19])
Referenced by KeccakF1600Step().
a40
#define a40 (p->u.s[20])
Referenced by KeccakF1600Step().
a41
#define a41 (p->u.s[21])
Referenced by KeccakF1600Step().
a42
#define a42 (p->u.s[22])
Referenced by KeccakF1600Step().
a43
#define a43 (p->u.s[23])
Referenced by KeccakF1600Step().
a44
#define a44 (p->u.s[24])
Referenced by KeccakF1600Step().
APND_MARK_PREFIX
#define APND_MARK_PREFIX `Start-Of-SQLite3-`
Definition at line 3600 of file shell.c.
Referenced by apndReadMark(), and apndWriteMark().
APND_MARK_PREFIX_SZ
#define APND_MARK_PREFIX_SZ 17
Definition at line 3601 of file shell.c.
Referenced by apndReadMark(), and apndWriteMark().
APND_MARK_SIZE
#define APND_MARK_SIZE 25
Definition at line 3602 of file shell.c.
Referenced by apndFileSize(), apndReadMark(), apndTruncate(), apndWrite(), and apndWriteMark().
APND_MAX_SIZE
#define APND_MAX_SIZE (65536*15259)
Definition at line 3608 of file shell.c.
Referenced by apndWrite().
ArraySize
#define ArraySize(X) (int)(sizeof(X)/sizeof(X[0]))
Definition at line 385 of file shell.c.
Referenced by do_meta_command(), explain_data_prepare(), integerValue(), save_err_msg(), shell_callback(), shell_dbinfo_command(), and showHelp().
AUTOEQP_full
#define AUTOEQP_full 3 /* Show full EXPLAIN */
Definition at line 9640 of file shell.c.
Referenced by do_meta_command(), main(), and shell_exec().
AUTOEQP_off
#define AUTOEQP_off 0 /* Automatic EXPLAIN QUERY PLAN is off */
Definition at line 9637 of file shell.c.
AUTOEQP_on
#define AUTOEQP_on 1 /* Automatic EQP is on */
Definition at line 9638 of file shell.c.
Referenced by do_meta_command(), and main().
AUTOEQP_trigger
#define AUTOEQP_trigger 2 /* On and also show plans for triggers */
Definition at line 9639 of file shell.c.
Referenced by do_meta_command(), and shell_exec().
BEGIN_TIMER
#define BEGIN_TIMER beginTimer()
Definition at line 290 of file shell.c.
Referenced by runOneSqlLine().
COMPLETION_COLLATIONS
#define COMPLETION_COLLATIONS 4
Definition at line 3111 of file shell.c.
COMPLETION_COLUMN_CANDIDATE
#define COMPLETION_COLUMN_CANDIDATE 0 /* Suggested completion of the input */
Referenced by completionColumn().
COMPLETION_COLUMN_PHASE
#define COMPLETION_COLUMN_PHASE 3 /* ePhase - used for debugging only */
Referenced by completionColumn().
COMPLETION_COLUMN_PREFIX
#define COMPLETION_COLUMN_PREFIX 1 /* Prefix of the word to be completed */
Referenced by completionBestIndex(), and completionColumn().
COMPLETION_COLUMN_WHOLELINE
#define COMPLETION_COLUMN_WHOLELINE 2 /* Entire line seen so far */
Referenced by completionBestIndex(), and completionColumn().
COMPLETION_COLUMNS
#define COMPLETION_COLUMNS 9
Definition at line 3116 of file shell.c.
Referenced by completionNext().
COMPLETION_DATABASES
#define COMPLETION_DATABASES 7
Definition at line 3114 of file shell.c.
Referenced by completionNext().
COMPLETION_EOF
#define COMPLETION_EOF 11
Definition at line 3118 of file shell.c.
Referenced by completionEof(), and completionNext().
COMPLETION_FIRST_PHASE
#define COMPLETION_FIRST_PHASE 1
Definition at line 3107 of file shell.c.
Referenced by completionFilter().
COMPLETION_FUNCTIONS
#define COMPLETION_FUNCTIONS 3
Definition at line 3110 of file shell.c.
COMPLETION_INDEXES
#define COMPLETION_INDEXES 5
Definition at line 3112 of file shell.c.
COMPLETION_KEYWORDS
#define COMPLETION_KEYWORDS 1
Definition at line 3108 of file shell.c.
Referenced by completionNext().
COMPLETION_MODULES
#define COMPLETION_MODULES 10
Definition at line 3117 of file shell.c.
COMPLETION_PRAGMAS
#define COMPLETION_PRAGMAS 2
Definition at line 3109 of file shell.c.
COMPLETION_TABLES
#define COMPLETION_TABLES 8 /* Also VIEWs and TRIGGERs */
Definition at line 3115 of file shell.c.
Referenced by completionNext().
COMPLETION_TRIGGERS
#define COMPLETION_TRIGGERS 6
Definition at line 3113 of file shell.c.
CTIMEOPT_VAL
#define CTIMEOPT_VAL(opt) CTIMEOPT_VAL_(opt)
Referenced by do_meta_command().
CTIMEOPT_VAL_
#define CTIMEOPT_VAL_(opt) #opt
END_TIMER
#define END_TIMER endTimer()
Definition at line 291 of file shell.c.
Referenced by runOneSqlLine().
EXPERT_CONFIG_SAMPLE
#define EXPERT_CONFIG_SAMPLE 1 /* int */
Definition at line 6595 of file shell.c.
Referenced by expertDotCommand(), and sqlite3_expert_config().
EXPERT_REPORT_CANDIDATES
#define EXPERT_REPORT_CANDIDATES 4
Definition at line 6694 of file shell.c.
Referenced by expertFinish(), and sqlite3_expert_report().
EXPERT_REPORT_INDEXES
#define EXPERT_REPORT_INDEXES 2
Definition at line 6692 of file shell.c.
Referenced by expertFinish(), and sqlite3_expert_report().
EXPERT_REPORT_PLAN
#define EXPERT_REPORT_PLAN 3
Definition at line 6693 of file shell.c.
Referenced by expertFinish(), and sqlite3_expert_report().
EXPERT_REPORT_SQL
#define EXPERT_REPORT_SQL 1
Definition at line 6691 of file shell.c.
Referenced by expertFinish(), and sqlite3_expert_report().
FSDIR_COLUMN_DATA
#define FSDIR_COLUMN_DATA 3 /* File content */
Definition at line 2149 of file shell.c.
Referenced by fsdirColumn().
FSDIR_COLUMN_DIR
#define FSDIR_COLUMN_DIR 5 /* Path is relative to this directory */
Definition at line 2151 of file shell.c.
Referenced by fsdirBestIndex().
FSDIR_COLUMN_MODE
#define FSDIR_COLUMN_MODE 1 /* Access mode */
Definition at line 2147 of file shell.c.
Referenced by fsdirColumn().
FSDIR_COLUMN_MTIME
#define FSDIR_COLUMN_MTIME 2 /* Last modification time */
Definition at line 2148 of file shell.c.
Referenced by fsdirColumn().
FSDIR_COLUMN_NAME
#define FSDIR_COLUMN_NAME 0 /* Name of the file */
Definition at line 2146 of file shell.c.
Referenced by fsdirColumn().
FSDIR_COLUMN_PATH
#define FSDIR_COLUMN_PATH 4 /* Path to top of search */
Definition at line 2150 of file shell.c.
Referenced by fsdirBestIndex(), and fsdirColumn().
FSDIR_SCHEMA
#define FSDIR_SCHEMA `(name,mode,mtime,data,path HIDDEN,dir HIDDEN)`
Definition at line 2145 of file shell.c.
Referenced by fsdirConnect().
GETPID
#define GETPID getpid
Definition at line 100 of file shell.c.
Referenced by main().
HAS_TIMER
#define HAS_TIMER 1
Definition at line 292 of file shell.c.
Referenced by do_meta_command().
IDX_HASH_SIZE
#define IDX_HASH_SIZE 1023
Definition at line 6825 of file shell.c.
Referenced by idxHashClear(), and idxHashString().
IsDigit
#define IsDigit(X) isdigit((unsigned char) X)
Definition at line 190 of file shell.c.
Referenced by integerValue(), isNumber(), and testcase_glob().
IsSpace
#define IsSpace(X) isspace((unsigned char) X)
Definition at line 189 of file shell.c.
Referenced by _all_whitespace(), do_meta_command(), line_is_command_terminator(), process_input(), shell_callback(), shell_exec(), testcase_glob(), and wsToEol().
MODE_Ascii
#define MODE_Ascii 10 /* Use ASCII unit and record separators (0x1F/0x1E) */
Definition at line 9696 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_Column
#define MODE_Column 1 /* One record per line in neat columns */
Definition at line 9687 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_Csv
#define MODE_Csv 8 /* Quote strings, numbers are plain */
Definition at line 9694 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_EQP
#define MODE_EQP 12 /* Converts EXPLAIN QUERY PLAN output into a graph */
Definition at line 9698 of file shell.c.
Referenced by shell_callback(), and shell_exec().
MODE_Explain
#define MODE_Explain 9 /* Like MODE_Column, but do not truncate data */
Definition at line 9695 of file shell.c.
Referenced by do_meta_command(), shell_callback(), and shell_exec().
MODE_Html
#define MODE_Html 4 /* Generate an XHTML table */
Definition at line 9690 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_Insert
#define MODE_Insert 5 /* Generate SQL `insert` statements */
Definition at line 9691 of file shell.c.
Referenced by do_meta_command(), dump_callback(), exec_prepared_stmt(), and shell_callback().
MODE_Line
#define MODE_Line 0 /* One column per line. Blank line between records */
Definition at line 9686 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_List
#define MODE_List 2 /* One record per line with a separator */
Definition at line 9688 of file shell.c.
Referenced by do_meta_command(), main(), main_init(), and shell_callback().
MODE_Pretty
#define MODE_Pretty 11 /* Pretty-print schemas */
Definition at line 9697 of file shell.c.
Referenced by do_meta_command(), and shell_callback().
MODE_Quote
#define MODE_Quote 6 /* Quote values as for SQL */
Definition at line 9692 of file shell.c.
Referenced by do_meta_command(), main(), and shell_callback().
MODE_Semi
#define MODE_Semi 3 /* Same as MODE_List but append `;` to each line */
Definition at line 9689 of file shell.c.
Referenced by do_meta_command(), and shell_callback().
MODE_Tcl
#define MODE_Tcl 7 /* Generate ANSI-C or TCL quoted elements */
Definition at line 9693 of file shell.c.
Referenced by do_meta_command(), and shell_callback().
OPEN_DB_KEEPALIVE
#define OPEN_DB_KEEPALIVE 0x001 /* Return after error if true */
Definition at line 12680 of file shell.c.
Referenced by do_meta_command(), and open_db().
OPEN_DB_ZIPFILE
#define OPEN_DB_ZIPFILE 0x002 /* Open as ZIP if name matches *.zip */
Definition at line 12681 of file shell.c.
Referenced by main(), and open_db().
ORIGFILE
#define ORIGFILE(p) ((sqlite3_file*)(((ApndFile*)(p))+1))
Definition at line 3620 of file shell.c.
Referenced by apndCheckReservedLock(), apndClose(), apndDeviceCharacteristics(), apndFetch(), apndFileControl(), apndFileSize(), apndLock(), apndOpen(), apndRead(), apndSectorSize(), apndShmBarrier(), apndShmLock(), apndShmMap(), apndShmUnmap(), apndSync(), apndTruncate(), apndUnfetch(), apndUnlock(), and apndWrite().
ORIGVFS
#define ORIGVFS(p) ((sqlite3_vfs*)((p)->pAppData))
Definition at line 3619 of file shell.c.
Referenced by apndAccess(), apndCurrentTime(), apndCurrentTimeInt64(), apndDelete(), apndDlClose(), apndDlError(), apndDlOpen(), apndFullPathname(), apndGetLastError(), apndGetSystemCall(), apndNextSystemCall(), apndOpen(), apndRandomness(), apndSetSystemCall(), apndSleep(), and sqlite3_os_end().
raw_printf
#define raw_printf fprintf
Definition at line 460 of file shell.c.
Referenced by display_scanstats(), display_stats(), displayStatLine(), do_meta_command(), dump_callback(), expertDotCommand(), expertFinish(), lintDotCommand(), lintFkeyIndexes(), main(), newTempFile(), output_c_string(), output_hex_blob(), output_html_string(), output_quoted_escaped_string(), output_quoted_string(), process_sqliterc(), progress_handler(), run_schema_dump_query(), run_table_dump_query(), runOneSqlLine(), shell_callback(), shell_dbinfo_command(), shell_out_of_memory(), shellAuth(), shellFinalize(), shellPrepare(), shellReset(), and usage().
ROL64
#define ROL64(a, x) ((a<<x)|(a>>(64-x)))
Referenced by KeccakF1600Step().
SEP_Column
#define SEP_Column `|`
Definition at line 9720 of file shell.c.
Referenced by do_meta_command(), and main_init().
SEP_Comma
#define SEP_Comma `,`
Definition at line 9724 of file shell.c.
Referenced by do_meta_command().
SEP_CrLf
#define SEP_CrLf `\r\n`
Definition at line 9725 of file shell.c.
Referenced by do_meta_command().
SEP_Record
#define SEP_Record `\x1E`
Definition at line 9727 of file shell.c.
Referenced by do_meta_command(), and main().
SEP_Row
#define SEP_Row `\n`
Definition at line 9721 of file shell.c.
Referenced by do_meta_command(), main_init(), and shell_callback().
SEP_Space
#define SEP_Space ` `
Definition at line 9723 of file shell.c.
Referenced by do_meta_command().
SEP_Tab
#define SEP_Tab `\t`
Definition at line 9722 of file shell.c.
Referenced by do_meta_command().
SEP_Unit
#define SEP_Unit `\x1F`
Definition at line 9726 of file shell.c.
Referenced by do_meta_command(), and main().
session_close_all
#define session_close_all(X)
Definition at line 12379 of file shell.c.
Referenced by do_meta_command(), main(), and readFile().
setBinaryMode
#define setBinaryMode(X, Y)
Definition at line 219 of file shell.c.
Referenced by do_meta_command(), main(), output_quoted_escaped_string(), output_quoted_string(), and shell_callback().
setTextMode
#define setTextMode(X, Y)
Definition at line 220 of file shell.c.
Referenced by do_meta_command(), output_quoted_escaped_string(), output_quoted_string(), and shell_callback().
SHA3_BYTEORDER
#define SHA3_BYTEORDER 0
Definition at line 1368 of file shell.c.
SHELL_OPEN_APPENDVFS
#define SHELL_OPEN_APPENDVFS 2 /* Use appendvfs */
Definition at line 9646 of file shell.c.
Referenced by deduceDatabaseType(), do_meta_command(), main(), open_db(), and shellReset().
SHELL_OPEN_DESERIALIZE
#define SHELL_OPEN_DESERIALIZE 5 /* Open using sqlite3_deserialize() */
Definition at line 9649 of file shell.c.
Referenced by do_meta_command(), main(), and open_db().
SHELL_OPEN_HEXDB
#define SHELL_OPEN_HEXDB 6 /* Use `dbtotxt` output as data source */
Definition at line 9650 of file shell.c.
Referenced by do_meta_command(), and open_db().
SHELL_OPEN_NORMAL
#define SHELL_OPEN_NORMAL 1 /* Normal database file */
Definition at line 9645 of file shell.c.
Referenced by deduceDatabaseType(), and open_db().
SHELL_OPEN_READONLY
#define SHELL_OPEN_READONLY 4 /* Open a normal database read-only */
Definition at line 9648 of file shell.c.
Referenced by do_meta_command(), main(), and open_db().
SHELL_OPEN_UNSPEC
#define SHELL_OPEN_UNSPEC 0 /* No open-mode specified */
Definition at line 9644 of file shell.c.
Referenced by deduceDatabaseType(), do_meta_command(), open_db(), and shellReset().
SHELL_OPEN_ZIPFILE
#define SHELL_OPEN_ZIPFILE 3 /* Use the zipfile virtual table */
Definition at line 9647 of file shell.c.
Referenced by deduceDatabaseType(), do_meta_command(), main(), open_db(), and shellReset().
SHELL_PROGRESS_ONCE
#define SHELL_PROGRESS_ONCE 0x04 /* Cancel the --limit after firing once */
Definition at line 9663 of file shell.c.
Referenced by do_meta_command(), and progress_handler().
SHELL_PROGRESS_QUIET
#define SHELL_PROGRESS_QUIET 0x01 /* Omit announcing every progress callback */
Definition at line 9659 of file shell.c.
Referenced by do_meta_command(), and progress_handler().
SHELL_PROGRESS_RESET
#define SHELL_PROGRESS_RESET
Value:
x02 /* Reset the count when the progres
                                   ** callback limit is reached, and for each
                                   ** top-level SQL statement */
Definition at line 9660 of file shell.c.
Referenced by do_meta_command(), progress_handler(), and runOneSqlLine().
shell_read_history
#define shell_read_history(X)
Definition at line 141 of file shell.c.
Referenced by main().
shell_stifle_history
#define shell_stifle_history(X)
Definition at line 143 of file shell.c.
Referenced by main().
SHELL_TRACE_EXPANDED
#define SHELL_TRACE_EXPANDED 1 /* Show expanded SQL text */
Definition at line 9655 of file shell.c.
Referenced by do_meta_command(), and sql_trace_callback().
SHELL_TRACE_NORMALIZED
#define SHELL_TRACE_NORMALIZED 2 /* Show normalized SQL text */
Definition at line 9656 of file shell.c.
Referenced by do_meta_command(), and sql_trace_callback().
SHELL_TRACE_PLAIN
#define SHELL_TRACE_PLAIN 0 /* Show input SQL text */
Definition at line 9654 of file shell.c.
Referenced by do_meta_command().
SHELL_USE_LOCAL_GETLINE
#define SHELL_USE_LOCAL_GETLINE 1
Definition at line 145 of file shell.c.
shell_write_history
#define shell_write_history(X)
Definition at line 142 of file shell.c.
Referenced by main().
ShellClearFlag
#define ShellClearFlag(P, X) ((P)->shellFlgs&=(~(X)))
Definition at line 9681 of file shell.c.
Referenced by do_meta_command(), and setOrClearFlag().
ShellHasFlag
#define ShellHasFlag(P, X) (((P)->shellFlgs & (X))!=0)
Definition at line 9679 of file shell.c.
Referenced by do_meta_command(), process_input(), runOneSqlLine(), shell_callback(), shell_exec(), and tableColumnList().
ShellSetFlag
#define ShellSetFlag(P, X) ((P)->shellFlgs|=(X))
Definition at line 9680 of file shell.c.
Referenced by do_meta_command(), main(), and setOrClearFlag().
SHFLG_Backslash
#define SHFLG_Backslash 0x00000004 /* The --backslash option is used */
Definition at line 9670 of file shell.c.
Referenced by main(), and runOneSqlLine().
SHFLG_CountChanges
#define SHFLG_CountChanges 0x00000020 /* .changes setting */
Definition at line 9673 of file shell.c.
Referenced by do_meta_command(), and runOneSqlLine().
SHFLG_Echo
#define SHFLG_Echo 0x00000040 /* .echo or --echo setting */
Definition at line 9674 of file shell.c.
Referenced by do_meta_command(), main(), process_input(), and shell_exec().
SHFLG_Lookaside
#define SHFLG_Lookaside 0x00000002 /* Lookaside memory is used */
Definition at line 9669 of file shell.c.
Referenced by display_stats(), main(), and main_init().
SHFLG_Newlines
#define SHFLG_Newlines 0x00000010 /* .dump --newline flag */
Definition at line 9672 of file shell.c.
Referenced by do_meta_command(), and shell_callback().
SHFLG_Pagecache
#define SHFLG_Pagecache 0x00000001 /* The --pagecache option is used */
Definition at line 9668 of file shell.c.
Referenced by display_stats(), and main().
SHFLG_PreserveRowid
#define SHFLG_PreserveRowid 0x00000008 /* .dump preserves rowid values */
Definition at line 9671 of file shell.c.
Referenced by do_meta_command(), and tableColumnList().
SQLITE_EXTENSION_INIT1
#define SQLITE_EXTENSION_INIT1
Definition at line 949 of file shell.c.
Referenced by sqlite3_completion_init(), sqlite3_expert_destroy(), sqlite3_fileio_init(), sqlite3_shathree_init(), and sqlite3MemTraceDeactivate().
SQLITE_EXTENSION_INIT2
#define SQLITE_EXTENSION_INIT2(X) (void)(X)
Definition at line 950 of file shell.c.
Referenced by sqlite3_appendvfs_init(), sqlite3_completion_init(), sqlite3_expert_destroy(), sqlite3_extension_init(), sqlite3_fileio_init(), sqlite3_shathree_init(), and sqlite3MemTraceDeactivate().
SQLITE_SHELL_IS_UTF8
#define SQLITE_SHELL_IS_UTF8 (1)
Definition at line 18660 of file shell.c.
SQLITEEXPERT_H
#define SQLITEEXPERT_H 1
Definition at line 6549 of file shell.c.
STRLEN
#define STRLEN (int)strlen
Definition at line 6736 of file shell.c.
Referenced by expertDequote(), idxAppendText(), idxFindIndexes(), idxGetTableInfo(), idxHashAdd(), idxHashFind(), idxNewConstraint(), idxPopulateOneStat1(), and sqlite3_expert_sql().
ToLower
#define ToLower(X) (char)tolower((unsigned char) X)
Definition at line 191 of file shell.c.
Referenced by line_is_command_terminator().
UNIQUE_TABLE_NAME
#define UNIQUE_TABLE_NAME `t592690916721053953805701627921227776`
Definition at line 6743 of file shell.c.
Referenced by idxBuildSampleTable(), idxPopulateOneStat1(), idxPopulateStat1(), and idxProcessOneTrigger().
UNUSED_PARAMETER
#define UNUSED_PARAMETER(x) (void)(x)
Definition at line 380 of file shell.c.
Referenced by captureOutputCallback(), display_scanstats(), dump_callback(), interrupt_handler(), shellAddSchemaName(), shellEscapeCrnl(), shellIdQuote(), shellInt32(), and shellModuleSchema().
utf8_printf
#define utf8_printf fprintf
Definition at line 452 of file shell.c.
Referenced by booleanValue(), close_db(), cmdline_option_value(), createSelftestTable(), csv_read_one_field(), deduceDatabaseType(), display_scanstats(), display_stats(), do_meta_command(), dump_callback(), eqp_append(), eqp_render(), eqp_render_level(), main(), open_db(), output_csv(), output_file_open(), output_html_string(), output_quoted_escaped_string(), output_quoted_string(), output_reset(), printSchemaLine(), process_sqliterc(), run_schema_dump_query(), run_table_dump_query(), runOneSqlLine(), save_err_msg(), shell_callback(), shell_dbinfo_command(), shell_exec(), shell_out_of_memory(), shellAuth(), shellDatabaseError(), shellLog(), shellPutsFunc(), shellReset(), showHelp(), sql_trace_callback(), tryToClone(), tryToCloneData(), tryToCloneSchema(), usage(), utf8_width_print(), and verify_uninitialized().
Typedef Documentation
ApndFile
typedef struct ApndFile ApndFile
Definition at line 3614 of file shell.c.
ApndVfs
typedef struct sqlite3_vfs ApndVfs
Definition at line 3613 of file shell.c.
completion_cursor
typedef struct completion_cursor completion_cursor
Definition at line 3090 of file shell.c.
completion_vtab
typedef typedefSQLITE_EXTENSION_INIT1 struct completion_vtab completion_vtab
Definition at line 3080 of file shell.c.
EQPGraph
typedef struct EQPGraph EQPGraph
Definition at line 9561 of file shell.c.
EQPGraphRow
typedef struct EQPGraphRow EQPGraphRow
Definition at line 9552 of file shell.c.
ExpertCsr
typedef struct ExpertCsr ExpertCsr
Definition at line 7063 of file shell.c.
ExpertInfo
typedef struct ExpertInfo ExpertInfo
Definition at line 9545 of file shell.c.
ExpertVtab
typedef struct ExpertVtab ExpertVtab
Definition at line 7056 of file shell.c.
fsdir_cursor
typedef struct fsdir_cursor fsdir_cursor
Definition at line 2571 of file shell.c.
fsdir_tab
typedef struct fsdir_tab fsdir_tab
Definition at line 2594 of file shell.c.
FsdirLevel
typedef struct FsdirLevel FsdirLevel
Definition at line 2572 of file shell.c.
i64
typedef sqlite3_int64 i64
Definition at line 82 of file shell.c.
IdxColumn
typedef struct IdxColumn IdxColumn
Definition at line 6729 of file shell.c.
IdxConstraint
typedef struct IdxConstraint IdxConstraint
Definition at line 6730 of file shell.c.
IdxHash
typedef struct IdxHash IdxHash
Definition at line 6827 of file shell.c.
IdxHashEntry
typedef struct IdxHashEntry IdxHashEntry
Definition at line 6826 of file shell.c.
IdxScan
typedef struct IdxScan IdxScan
Definition at line 6731 of file shell.c.
IdxStatement
typedef struct IdxStatement IdxStatement
Definition at line 6732 of file shell.c.
IdxTable
typedef struct IdxTable IdxTable
Definition at line 6733 of file shell.c.
IdxWrite
typedef struct IdxWrite IdxWrite
Definition at line 6734 of file shell.c.
ImportCtx
typedef struct ImportCtx ImportCtx
Definition at line 13068 of file shell.c.
SavedModeInfo
typedef struct SavedModeInfo SavedModeInfo
Definition at line 9537 of file shell.c.
SHA3Context
typedef struct SHA3Context SHA3Context
Definition at line 1376 of file shell.c.
ShellState
typedef struct ShellState ShellState
Definition at line 9572 of file shell.c.
ShellText
typedef struct ShellText ShellText
Definition at line 724 of file shell.c.
sqlite3expert
typedef struct sqlite3expert sqlite3expert
Definition at line 6552 of file shell.c.
u64
typedef sqlite3_uint64 u64
Definition at line 83 of file shell.c.
u8
typedef unsigned char u8
Definition at line 84 of file shell.c.
Function Documentation
_all_whitespace()
static int _all_whitespace (const char * z) [static]
Definition at line 18221 of file shell.c.
References IsSpace.
Referenced by line_is_command_terminator(), and process_input().
                                         {
  for(; *z; z++){
    if(IsSpace(z[0])) continue;
    if(*z=='/' && z[1]=='*'){
      z += 2;
      while(*z && (*z!='*' || z[1]!='/')){ z++; }
      if(*z==0) return 0;
      z++;
      continue;
    }
    if(*z=='-' && z[1]=='-'){
      z += 2;
      while(*z && *z!='\n'){ z++; }
      if(*z==0) return 1;
      continue;
    }
    return 0;
  }
  return 1;
}
apndAccess()
static int apndAccess (sqlite3_vfs * pVfs, const char * zName, int flags, int * pResOut) [static]
Definition at line 4012 of file shell.c.
References ORIGVFS.
 {
  return ORIGVFS(pVfs)->xAccess(ORIGVFS(pVfs), zPath, flags, pResOut);
}
apndCheckReservedLock()
static int apndCheckReservedLock (sqlite3_file * pFile, int * pResOut) [static]
Definition at line 3839 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xCheckReservedLock.
                                                                   {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xCheckReservedLock(pFile, pResOut);
}
apndClose()
static int apndClose (sqlite3_file * pFile) [static]
Definition at line 3723 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xClose.
                                         {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xClose(pFile);
}
apndCurrentTime()
static int apndCurrentTime (sqlite3_vfs * pVfs, double * pTimeOut) [static]
Definition at line 4046 of file shell.c.
References ORIGVFS.
                                                               {
  return ORIGVFS(pVfs)->xCurrentTime(ORIGVFS(pVfs), pTimeOut);
}
apndCurrentTimeInt64()
static int apndCurrentTimeInt64 (sqlite3_vfs * pVfs, sqlite3_int64 * p) [static]
Definition at line 4052 of file shell.c.
References ORIGVFS.
                                                                    {
  return ORIGVFS(pVfs)->xCurrentTimeInt64(ORIGVFS(pVfs), p);
}
apndDelete()
static int apndDelete (sqlite3_vfs * pVfs, const char * zName, int syncDir) [static]
Definition at line 4009 of file shell.c.
References ORIGVFS.
                                                                        {
  return ORIGVFS(pVfs)->xDelete(ORIGVFS(pVfs), zPath, dirSync);
}
apndDeviceCharacteristics()
static int apndDeviceCharacteristics (sqlite3_file * pFile) [static]
Definition at line 3869 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xDeviceCharacteristics.
                                                         {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xDeviceCharacteristics(pFile);
}
apndDlClose()
static void apndDlClose (sqlite3_vfs * pVfs, void * pHandle) [static]
Definition at line 4037 of file shell.c.
References ORIGVFS.
                                                         {
  ORIGVFS(pVfs)->xDlClose(ORIGVFS(pVfs), pHandle);
}
apndDlError()
static void apndDlError (sqlite3_vfs * pVfs, int nByte, char * zErrMsg) [static]
Definition at line 4031 of file shell.c.
References apndDlSym, and ORIGVFS.
                                                                    {
  ORIGVFS(pVfs)->xDlError(ORIGVFS(pVfs), nByte, zErrMsg);
}
apndDlOpen()
static void * apndDlOpen (sqlite3_vfs * pVfs, const char * zFilename) [static]
Definition at line 4028 of file shell.c.
References ORIGVFS.
                                                             {
  return ORIGVFS(pVfs)->xDlOpen(ORIGVFS(pVfs), zPath);
}
apndFetch()
static int apndFetch (sqlite3_file * pFile, sqlite3_int64 iOfst, int iAmt, void ** pp) [static]
Definition at line 3905 of file shell.c.
References ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xFetch.
 {
  ApndFile *p = (ApndFile *)pFile;
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xFetch(pFile, iOfst+p->iPgOne, iAmt, pp);
}
apndFileControl()
static int apndFileControl (sqlite3_file * pFile, int op, void * pArg) [static]
Definition at line 3847 of file shell.c.
References ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, sqlite3_mprintf, SQLITE_FCNTL_VFSNAME, SQLITE_OK, and sqlite3_io_methods::xFileControl.
                                                                   {
  ApndFile *p = (ApndFile *)pFile;
  int rc;
  pFile = ORIGFILE(pFile);
  rc = pFile->pMethods->xFileControl(pFile, op, pArg);
  if(rc==SQLITE_OK && op==SQLITE_FCNTL_VFSNAME){
    *(char**)pArg = sqlite3_mprintf("apnd(%lld)/%z", p->iPgOne, *(char**)pArg);
  }
  return rc;
}
apndFileSize()
static int apndFileSize (sqlite3_file * pFile, sqlite3_int64 * pSize) [static]
Definition at line 3809 of file shell.c.
References APND_MARK_SIZE, ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, SQLITE_OK, and sqlite3_io_methods::xFileSize.
                                                                 {
  ApndFile *p = (ApndFile *)pFile;
  int rc;
  pFile = ORIGFILE(p);
  rc = pFile->pMethods->xFileSize(pFile, pSize);
  if(rc==SQLITE_OK && p->iPgOne){
    *pSize -= p->iPgOne + APND_MARK_SIZE;
  }
  return rc;
}
apndFullPathname()
static int apndFullPathname (sqlite3_vfs * pVfs, const char * zName, int nOut, char * zOut) [static]
Definition at line 4020 of file shell.c.
References ORIGVFS.
 {
  return ORIGVFS(pVfs)->xFullPathname(ORIGVFS(pVfs),zPath,nOut,zOut);
}
apndGetLastError()
static int apndGetLastError (sqlite3_vfs * pVfs, int a, char * b) [static]
Definition at line 4049 of file shell.c.
References ORIGVFS.
                                                              {
  return ORIGVFS(pVfs)->xGetLastError(ORIGVFS(pVfs), a, b);
}
apndGetSystemCall()
static sqlite3_syscall_ptr apndGetSystemCall (sqlite3_vfs * pVfs, const char * z) [static]
Definition at line 4062 of file shell.c.
References ORIGVFS.
 {
  return ORIGVFS(pVfs)->xGetSystemCall(ORIGVFS(pVfs),zName);
}
apndIsOrdinaryDatabaseFile()
static int apndIsOrdinaryDatabaseFile (sqlite3_int64 sz, sqlite3_file * pFile) [static]
Definition at line 3926 of file shell.c.
References sqlite3_file::pMethods, and sqlite3_io_methods::xRead.
Referenced by apndOpen().
                                                                            {
  int rc;
  char zHdr[16];
  static const char aSqliteHdr[] = "SQLite format 3";
  if(sz<512) return 0;
  rc = pFile->pMethods->xRead(pFile, zHdr, sizeof(zHdr), 0);
  if(rc) return 0;
  return memcmp(zHdr, aSqliteHdr, sizeof(zHdr))==0;
}
apndLock()
static int apndLock (sqlite3_file * pFile, int eLock) [static]
Definition at line 3823 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xLock.
                                                   {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xLock(pFile, eLock);
}
apndNextSystemCall()
static const char * apndNextSystemCall (sqlite3_vfs * pVfs, const char * zName) [static]
Definition at line 4068 of file shell.c.
References ORIGVFS.
                                                                           {
  return ORIGVFS(pVfs)->xNextSystemCall(ORIGVFS(pVfs), zName);
}
apndOpen()
static int apndOpen (sqlite3_vfs * pVfs, const char * zName, sqlite3_file * pFile, int flags, int * pOutFlags) [static]
Definition at line 3960 of file shell.c.
References apnd_io_methods, apndIsOrdinaryDatabaseFile(), apndReadMark(), ApndFile::base, ApndFile::iMark, ApndFile::iPgOne, ORIGFILE, ORIGVFS, sqlite3_file::pMethods, SQLITE_CANTOPEN, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_MAIN_DB, sqlite3_vfs::szOsFile, sqlite3_io_methods::xClose, sqlite3_io_methods::xFileSize, and sqlite3_vfs::xOpen.
 {
  ApndFile *p;
  sqlite3_file *pSubFile;
  sqlite3_vfs *pSubVfs;
  int rc;
  sqlite3_int64 sz;
  pSubVfs = ORIGVFS(pVfs);
  if((flags & SQLITE_OPEN_MAIN_DB)==0){
    return pSubVfs->xOpen(pSubVfs, zName, pFile, flags, pOutFlags);
  }
  p = (ApndFile*)pFile;
  memset(p, 0, sizeof(*p));
  pSubFile = ORIGFILE(pFile);
  p->base.pMethods = &apnd_io_methods;
  rc = pSubVfs->xOpen(pSubVfs, zName, pSubFile, flags, pOutFlags);
  if(rc) goto apnd_open_done;
  rc = pSubFile->pMethods->xFileSize(pSubFile, &sz);
  if(rc){
    pSubFile->pMethods->xClose(pSubFile);
    goto apnd_open_done;
  }
  if(apndIsOrdinaryDatabaseFile(sz, pSubFile)){
    memmove(pFile, pSubFile, pSubVfs->szOsFile);
    return SQLITE_OK;
  }
  p->iMark = 0;
  p->iPgOne = apndReadMark(sz, pFile);
  if(p->iPgOne>0){
    return SQLITE_OK;
  }
  if((flags & SQLITE_OPEN_CREATE)==0){
    pSubFile->pMethods->xClose(pSubFile);
    rc = SQLITE_CANTOPEN;
  }
  p->iPgOne = (sz+0xfff) & ~(sqlite3_int64)0xfff;
apnd_open_done:
  if(rc) pFile->pMethods = 0;
  return rc;
}
apndRandomness()
static int apndRandomness (sqlite3_vfs * pVfs, int nByte, char * zOut) [static]
Definition at line 4040 of file shell.c.
References ORIGVFS.
                                                                      {
  return ORIGVFS(pVfs)->xRandomness(ORIGVFS(pVfs), nByte, zBufOut);
}
apndRead()
static int apndRead (sqlite3_file * pFile, void * zBuf, int iAmt, sqlite3_int64 iOfst) [static]
Definition at line 3731 of file shell.c.
References ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xRead.
 {
  ApndFile *p = (ApndFile *)pFile;
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xRead(pFile, zBuf, iAmt, iOfst+p->iPgOne);
}
apndReadMark()
static sqlite3_int64 apndReadMark (sqlite3_int64 sz, sqlite3_file * pFile) [static]
Definition at line 3941 of file shell.c.
References APND_MARK_PREFIX, APND_MARK_PREFIX_SZ, APND_MARK_SIZE, sqlite3_file::pMethods, and sqlite3_io_methods::xRead.
Referenced by apndOpen().
                                                                        {
  int rc, i;
  sqlite3_int64 iMark;
  unsigned char a[APND_MARK_SIZE];
  if(sz<=APND_MARK_SIZE) return -1;
  rc = pFile->pMethods->xRead(pFile, a, APND_MARK_SIZE, sz-APND_MARK_SIZE);
  if(rc) return -1;
  if(memcmp(a, APND_MARK_PREFIX, APND_MARK_PREFIX_SZ)!=0) return -1;
  iMark = ((sqlite3_int64)(a[APND_MARK_PREFIX_SZ]&0x7f))<<56;
  for(i=1; i<8; i++){
    iMark += (sqlite3_int64)a[APND_MARK_PREFIX_SZ+i]<<(56-8*i);
  }
  return iMark;
}
apndSectorSize()
static int apndSectorSize (sqlite3_file * pFile) [static]
Definition at line 3861 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xSectorSize.
                                              {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xSectorSize(pFile);
}
apndSetSystemCall()
static int apndSetSystemCall (sqlite3_vfs * pVfs, const char * zName, sqlite3_syscall_ptr pCall) [static]
Definition at line 4055 of file shell.c.
References ORIGVFS.
 {
  return ORIGVFS(pVfs)->xSetSystemCall(ORIGVFS(pVfs),zName,pCall);
}
apndShmBarrier()
static void apndShmBarrier (sqlite3_file * pFile) [static]
Definition at line 3893 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xShmBarrier.
                                               {
  pFile = ORIGFILE(pFile);
  pFile->pMethods->xShmBarrier(pFile);
}
apndShmLock()
static int apndShmLock (sqlite3_file * pFile, int offset, int n, int flags) [static]
Definition at line 3887 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xShmLock.
                                                                         {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xShmLock(pFile,offset,n,flags);
}
apndShmMap()
static int apndShmMap (sqlite3_file * pFile, int iPg, int pgsz, int bExtend, void volatile ** pp) [static]
Definition at line 3875 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xShmMap.
 {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xShmMap(pFile,iPg,pgsz,bExtend,pp);
}
apndShmUnmap()
static int apndShmUnmap (sqlite3_file * pFile, int deleteFlag) [static]
Definition at line 3899 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xShmUnmap.
                                                            {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xShmUnmap(pFile,deleteFlag);
}
apndSleep()
static int apndSleep (sqlite3_vfs * pVfs, int microseconds) [static]
Definition at line 4043 of file shell.c.
References ORIGVFS.
                                                   {
  return ORIGVFS(pVfs)->xSleep(ORIGVFS(pVfs), nMicro);
}
apndSync()
static int apndSync (sqlite3_file * pFile, int flags) [static]
Definition at line 3801 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xSync.
                                                   {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xSync(pFile, flags);
}
apndTruncate()
static int apndTruncate (sqlite3_file * pFile, sqlite3_int64 size) [static]
Definition at line 3786 of file shell.c.
References APND_MARK_SIZE, apndWriteMark(), ApndFile::iMark, ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, SQLITE_OK, and sqlite3_io_methods::xTruncate.
                                                               {
  int rc;
  ApndFile *p = (ApndFile *)pFile;
  pFile = ORIGFILE(pFile);
  rc = pFile->pMethods->xTruncate(pFile, size+p->iPgOne+APND_MARK_SIZE);
  if(rc==SQLITE_OK){
    p->iMark = p->iPgOne+size;
    rc = apndWriteMark(p, pFile);
  }
  return rc;
}
apndUnfetch()
static int apndUnfetch (sqlite3_file * pFile, sqlite3_int64 iOfst, void * p) [static]
Definition at line 3917 of file shell.c.
References ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xUnfetch.
                                                                             {
  ApndFile *p = (ApndFile *)pFile;
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xUnfetch(pFile, iOfst+p->iPgOne, pPage);
}
apndUnlock()
static int apndUnlock (sqlite3_file * pFile, int eLock) [static]
Definition at line 3831 of file shell.c.
References ORIGFILE, sqlite3_file::pMethods, and sqlite3_io_methods::xUnlock.
                                                     {
  pFile = ORIGFILE(pFile);
  return pFile->pMethods->xUnlock(pFile, eLock);
}
apndWrite()
static int apndWrite (sqlite3_file * pFile, const void * zBuf, int iAmt, sqlite3_int64 iOfst) [static]
Definition at line 3758 of file shell.c.
References APND_MARK_SIZE, APND_MAX_SIZE, apndWriteMark(), ApndFile::iMark, ApndFile::iPgOne, ORIGFILE, sqlite3_file::pMethods, SQLITE_FULL, SQLITE_OK, sqlite3_io_methods::xFileSize, and sqlite3_io_methods::xWrite.
 {
  int rc;
  ApndFile *p = (ApndFile *)pFile;
  pFile = ORIGFILE(pFile);
  if(iOfst+iAmt>=APND_MAX_SIZE) return SQLITE_FULL;
  rc = pFile->pMethods->xWrite(pFile, zBuf, iAmt, iOfst+p->iPgOne);
  if(rc==SQLITE_OK && iOfst + iAmt + p->iPgOne > p->iMark){
    sqlite3_int64 sz = 0;
    rc = pFile->pMethods->xFileSize(pFile, &sz);
    if(rc==SQLITE_OK){
      p->iMark = sz - APND_MARK_SIZE;
      if(iOfst + iAmt + p->iPgOne > p->iMark){
        p->iMark = p->iPgOne + iOfst + iAmt;
        rc = apndWriteMark(p, pFile);
      }
    }
  }
  return rc;
}
apndWriteMark()
static int apndWriteMark (ApndFile * p, sqlite3_file * pFile) [static]
Definition at line 3745 of file shell.c.
References APND_MARK_PREFIX, APND_MARK_PREFIX_SZ, APND_MARK_SIZE, ApndFile::iMark, ApndFile::iPgOne, sqlite3_file::pMethods, and sqlite3_io_methods::xWrite.
Referenced by apndTruncate(), and apndWrite().
                                                          {
  int i;
  unsigned char a[APND_MARK_SIZE];
  memcpy(a, APND_MARK_PREFIX, APND_MARK_PREFIX_SZ);
  for(i=0; i<8; i++){
    a[APND_MARK_PREFIX_SZ+i] = (p->iPgOne >> (56 - i*8)) & 0xff;
  }
  return pFile->pMethods->xWrite(pFile, a, APND_MARK_SIZE, p->iMark);
}
appendText()
static void appendText (ShellText * p, char const * zAppend, char quote) [static]
Definition at line 750 of file shell.c.
References ShellText::n, ShellText::nAlloc, shell_out_of_memory(), strlen30(), and ShellText::z.
Referenced by captureOutputCallback(), do_meta_command(), dump_callback(), and shellFakeSchema().
                                                                     {
  int len;
  int i;
  int nAppend = strlen30(zAppend);
  len = nAppend+p->n+1;
  if(quote){
    len += 2;
    for(i=0; i<nAppend; i++){
      if(zAppend[i]==quote) len++;
    }
  }
  if(p->n+len>=p->nAlloc){
    p->nAlloc = p->nAlloc*2 + len + 20;
    p->z = realloc(p->z, p->nAlloc);
    if(p->z==0) shell_out_of_memory();
  }
  if(quote){
    char *zCsr = p->z+p->n;
    *zCsr++ = quote;
    for(i=0; i<nAppend; i++){
      *zCsr++ = zAppend[i];
      if(zAppend[i]==quote) *zCsr++ = quote;
    }
    *zCsr++ = quote;
    p->n = (int)(zCsr - p->z);
    *zCsr = '\0';
  }else{
    memcpy(p->z+p->n, zAppend, nAppend);
    p->n += nAppend;
    p->z[p->n] = '\0';
  }
}
ascii_read_one_field()
static char* SQLITE_CDECL ascii_read_one_field (ImportCtx * p) [static]
Definition at line 13195 of file shell.c.
References ImportCtx::cColSep, ImportCtx::cRowSep, ImportCtx::cTerm, import_append_char(), ImportCtx::in, ImportCtx::n, ImportCtx::nLine, and ImportCtx::z.
Referenced by do_meta_command().
                                                            {
  int c;
  int cSep = p->cColSep;
  int rSep = p->cRowSep;
  p->n = 0;
  c = fgetc(p->in);
  if(c==EOF || seenInterrupt){
    p->cTerm = EOF;
    return 0;
  }
  while(c!=EOF && c!=cSep && c!=rSep){
    import_append_char(p, c);
    c = fgetc(p->in);
  }
  if(c==rSep){
    p->nLine++;
  }
  p->cTerm = c;
  if(p->z) p->z[p->n] = 0;
  return p->z;
}
beginTimer()
static void beginTimer (void) [static]
Definition at line 262 of file shell.c.
References sBegin, and timeOfDay().
                            {
  if(enableTimer){
    getrusage(RUSAGE_SELF, &sBegin);
    iBegin = timeOfDay();
  }
}
bind_prepared_stmt()
static void bind_prepared_stmt (ShellState * pArg, sqlite3_stmt * pStmt) [static]
Definition at line 11356 of file shell.c.
References ShellState::db, sqlite3_bind_null, sqlite3_bind_parameter_count, sqlite3_bind_parameter_name, sqlite3_bind_text, sqlite3_bind_value, sqlite3_column_value, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_reset, sqlite3_snprintf, sqlite3_step, sqlite3_table_column_metadata, SQLITE_OK, SQLITE_ROW, and SQLITE_STATIC.
Referenced by shell_exec().
                                                                     {
  int nVar;
  int i;
  int rc;
  sqlite3_stmt *pQ = 0;
  nVar = sqlite3_bind_parameter_count(pStmt);
  if(nVar==0) return; /* Nothing to do */
  if(sqlite3_table_column_metadata(pArg->db, "TEMP", "sqlite_parameters",
                                    "key", 0, 0, 0, 0, 0)!=SQLITE_OK){
    return; /* Parameter table does not exist */
  }
  rc = sqlite3_prepare_v2(pArg->db,
          "SELECT value FROM temp.sqlite_parameters"
          " WHERE key=?1", -1, &pQ, 0);
  if(rc || pQ==0) return;
  for(i=1; i<=nVar; i++){
    char zNum[30];
    const char *zVar = sqlite3_bind_parameter_name(pStmt, i);
    if(zVar==0){
      sqlite3_snprintf(sizeof(zNum),zNum,"?%d",i);
      zVar = zNum;
    }
    sqlite3_bind_text(pQ, 1, zVar, -1, SQLITE_STATIC);
    if(sqlite3_step(pQ)==SQLITE_ROW){
      sqlite3_bind_value(pStmt, i, sqlite3_column_value(pQ, 0));
    }else{
      sqlite3_bind_null(pStmt, i);
    }
    sqlite3_reset(pQ);
  }
  sqlite3_finalize(pQ);
}
bind_table_init()
static void bind_table_init (ShellState * p) [static]
Definition at line 11327 of file shell.c.
References ShellState::db, sqlite3_db_config, sqlite3_exec, SQLITE_DBCONFIG_DEFENSIVE, and SQLITE_DBCONFIG_WRITABLE_SCHEMA.
Referenced by do_meta_command().
                                          {
  int wrSchema = 0;
  int defensiveMode = 0;
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_DEFENSIVE, -1, &defensiveMode);
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_DEFENSIVE, 0, 0);
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_WRITABLE_SCHEMA, -1, &wrSchema);
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_WRITABLE_SCHEMA, 1, 0);
  sqlite3_exec(p->db,
    "CREATE TABLE IF NOT EXISTS temp.sqlite_parameters(\n"
    " key TEXT PRIMARY KEY,\n"
    " value ANY\n"
    ") WITHOUT ROWID;",
    0, 0, 0);
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_WRITABLE_SCHEMA, wrSchema, 0);
  sqlite3_db_config(p->db, SQLITE_DBCONFIG_DEFENSIVE, defensiveMode, 0);
}
booleanValue()
static int booleanValue (const char * zArg) [static]
Definition at line 12938 of file shell.c.
References hexDigitValue(), integerValue(), sqlite3_stricmp, and utf8_printf.
Referenced by do_meta_command(), and setOrClearFlag().
                                         {
  int i;
  if(zArg[0]=='0' && zArg[1]=='x'){
    for(i=2; hexDigitValue(zArg[i])>=0; i++){}
  }else{
    for(i=0; zArg[i]>='0' && zArg[i]<='9'; i++){}
  }
  if(i>0 && zArg[i]==0) return (int)(integerValue(zArg) & 0xffffffff);
  if(sqlite3_stricmp(zArg, "on")==0 || sqlite3_stricmp(zArg,"yes")==0){
    return 1;
  }
  if(sqlite3_stricmp(zArg, "off")==0 || sqlite3_stricmp(zArg,"no")==0){
    return 0;
  }
  utf8_printf(stderr, "ERROR: Not a boolean value: \"%s\". Assuming \"no\".\n",
          zArg);
  return 0;
}
callback()
static int callback (void * pArg, int nArg, char ** azArg, char ** azCol) [static]
Definition at line 10760 of file shell.c.
References shell_callback().
Referenced by node_sqlite3::Statement::Bind(), Nan::ContextDisposedNotification(), Persistent< T, M >::Copy(), do_meta_command(), imp::FunctionCallbackWrapper(), imp::GetterCallbackWrapper(), imp::IndexDeleterCallbackWrapper(), imp::IndexEnumeratorCallbackWrapper(), imp::IndexGetterCallbackWrapper(), imp::IndexQueryCallbackWrapper(), imp::IndexSetterCallbackWrapper(), NAN_METHOD(), PersistentBase< T >::operator!=(), imp::PropertyDeleterCallbackWrapper(), imp::PropertyEnumeratorCallbackWrapper(), imp::PropertyGetterCallbackWrapper(), imp::PropertyQueryCallbackWrapper(), imp::PropertySetterCallbackWrapper(), Persistent< T, M >::Reset(), node_sqlite3::Database::Schedule(), node_sqlite3::Backup::Schedule(), node_sqlite3::Statement::Schedule(), Nan::SetMethod(), Nan::SetPrototypeMethod(), imp::SetterCallbackWrapper(), WeakCallbackInfo< T >::unwrap(), Nan::AsyncWorker::WorkComplete(), Nan::AsyncWorker::~AsyncWorker(), node_sqlite3::Backup::~Backup(), node_sqlite3::Database::~Database(), and node_sqlite3::Statement::~Statement().
                                                                     {
  /* since we don't have type info, call the shell_callback with a NULL value */
  return shell_callback(pArg, nArg, azArg, azCol, NULL);
}
captureOutputCallback()
static int captureOutputCallback (void * pArg, int nArg, char ** azArg, char ** az) [static]
Definition at line 10769 of file shell.c.
References appendText(), ShellText::n, and UNUSED_PARAMETER.
Referenced by do_meta_command().
                                                                               {
  ShellText *p = (ShellText*)pArg;
  int i;
  UNUSED_PARAMETER(az);
  if(azArg==0) return 0;
  if(p->n) appendText(p, "|", 0);
  for(i=0; i<nArg; i++){
    if(i) appendText(p, ",", 0);
    if(azArg[i]) appendText(p, azArg[i], 0);
  }
  return 0;
}
clearTempFile()
static void clearTempFile (ShellState * p) [static]
Definition at line 13732 of file shell.c.
References ShellState::doXdgOpen, shellDeleteFile(), sqlite3_free, and ShellState::zTempFile.
Referenced by do_meta_command(), main(), newTempFile(), and process_input().
                                        {
  if(p->zTempFile==0) return;
  if(p->doXdgOpen) return;
  if(shellDeleteFile(p->zTempFile)) return;
  sqlite3_free(p->zTempFile);
  p->zTempFile = 0;
}
close_db()
void close_db (sqlite3 * db)
Definition at line 12802 of file shell.c.
References sqlite3_close, sqlite3_column_bytes, sqlite3_column_text, sqlite3_errmsg, sqlite3_exec, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, SQLITE_ROW, strlen30(), and utf8_printf.
Referenced by do_meta_command(), main(), shellReset(), and tryToClone().
                          {
  int rc = sqlite3_close(db);
  if(rc){
    utf8_printf(stderr, "Error: sqlite3_close() returns %d: %s\n",
        rc, sqlite3_errmsg(db));
  }
}
cmdline_option_value()
static char* cmdline_option_value (int argc, char ** argv, int i) [static]
Definition at line 18647 of file shell.c.
References utf8_printf.
Referenced by main().
                                                               {
  if(i==argc){
    utf8_printf(stderr, "%s: Error: missing argument to %s\n",
            argv[0], argv[argc-1]);
    exit(1);
  }
  return argv[i];
}
completionBestIndex()
static int completionBestIndex (sqlite3_vtab * tab, sqlite3_index_info * pIdxInfo) [static]
Definition at line 3437 of file shell.c.
References sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, sqlite3_index_info::sqlite3_index_constraint_usage::argvIndex, COMPLETION_COLUMN_PREFIX, COMPLETION_COLUMN_WHOLELINE, sqlite3_index_info::estimatedCost, sqlite3_index_info::estimatedRows, sqlite3_index_info::idxNum, sqlite3_index_info::nConstraint, sqlite3_index_info::sqlite3_index_constraint_usage::omit, SQLITE_INDEX_CONSTRAINT_EQ, and SQLITE_OK.
 {
  int i; /* Loop over constraints */
  int idxNum = 0; /* The query plan bitmask */
  int prefixIdx = -1; /* Index of the start= constraint, or -1 if none */
  int wholelineIdx = -1; /* Index of the stop= constraint, or -1 if none */
  int nArg = 0; /* Number of arguments that completeFilter() expects */
  const struct sqlite3_index_constraint *pConstraint;
  (void)(tab); /* Unused parameter */
  pConstraint = pIdxInfo->aConstraint;
  for(i=0; i<pIdxInfo->nConstraint; i++, pConstraint++){
    if(pConstraint->usable==0) continue;
    if(pConstraint->op!=SQLITE_INDEX_CONSTRAINT_EQ) continue;
    switch(pConstraint->iColumn){
      case COMPLETION_COLUMN_PREFIX:
        prefixIdx = i;
        idxNum |= 1;
        break;
      case COMPLETION_COLUMN_WHOLELINE:
        wholelineIdx = i;
        idxNum |= 2;
        break;
    }
  }
  if(prefixIdx>=0){
    pIdxInfo->aConstraintUsage[prefixIdx].argvIndex = ++nArg;
    pIdxInfo->aConstraintUsage[prefixIdx].omit = 1;
  }
  if(wholelineIdx>=0){
    pIdxInfo->aConstraintUsage[wholelineIdx].argvIndex = ++nArg;
    pIdxInfo->aConstraintUsage[wholelineIdx].omit = 1;
  }
  pIdxInfo->idxNum = idxNum;
  pIdxInfo->estimatedCost = (double)5000 - 1000*nArg;
  pIdxInfo->estimatedRows = 500 - 100*nArg;
  return SQLITE_OK;
}
completionClose()
static int completionClose (sqlite3_vtab_cursor * cur) [static]
Definition at line 3206 of file shell.c.
References completionCursorReset(), sqlite3_free, and SQLITE_OK.
                                                    {
  completionCursorReset((completion_cursor*)cur);
  sqlite3_free(cur);
  return SQLITE_OK;
}
completionColumn()
static int completionColumn (sqlite3_vtab_cursor * cur, sqlite3_context * ctx, int i) [static]
Definition at line 3334 of file shell.c.
References COMPLETION_COLUMN_CANDIDATE, COMPLETION_COLUMN_PHASE, COMPLETION_COLUMN_PREFIX, COMPLETION_COLUMN_WHOLELINE, completion_cursor::ePhase, sqlite3_result_int, sqlite3_result_text, SQLITE_OK, SQLITE_TRANSIENT, completion_cursor::szRow, completion_cursor::zCurrentRow, completion_cursor::zLine, and completion_cursor::zPrefix.
 {
  completion_cursor *pCur = (completion_cursor*)cur;
  switch(i){
    case COMPLETION_COLUMN_CANDIDATE: {
      sqlite3_result_text(ctx, pCur->zCurrentRow, pCur->szRow,SQLITE_TRANSIENT);
      break;
    }
    case COMPLETION_COLUMN_PREFIX: {
      sqlite3_result_text(ctx, pCur->zPrefix, -1, SQLITE_TRANSIENT);
      break;
    }
    case COMPLETION_COLUMN_WHOLELINE: {
      sqlite3_result_text(ctx, pCur->zLine, -1, SQLITE_TRANSIENT);
      break;
    }
    case COMPLETION_COLUMN_PHASE: {
      sqlite3_result_int(ctx, pCur->ePhase);
      break;
    }
  }
  return SQLITE_OK;
}
completionConnect()
static int completionConnect (sqlite3 * db, void * pAux, int argc, const char *const * argv, sqlite3_vtab ** ppVtab, char ** pzErr) [static]
Definition at line 3133 of file shell.c.
References completion_vtab::db, sqlite3_declare_vtab, sqlite3_malloc, sqlite3_vtab_config, SQLITE_NOMEM, SQLITE_OK, and SQLITE_VTAB_INNOCUOUS.
 {
  completion_vtab *pNew;
  int rc;
  (void)(pAux); /* Unused parameter */
  (void)(argc); /* Unused parameter */
  (void)(argv); /* Unused parameter */
  (void)(pzErr); /* Unused parameter */
/* Column numbers */
#define COMPLETION_COLUMN_CANDIDATE 0 /* Suggested completion of the input */
#define COMPLETION_COLUMN_PREFIX 1 /* Prefix of the word to be completed */
#define COMPLETION_COLUMN_WHOLELINE 2 /* Entire line seen so far */
#define COMPLETION_COLUMN_PHASE 3 /* ePhase - used for debugging only */
  sqlite3_vtab_config(db, SQLITE_VTAB_INNOCUOUS);
  rc = sqlite3_declare_vtab(db,
      "CREATE TABLE x("
      " candidate TEXT,"
      " prefix TEXT HIDDEN,"
      " wholeline TEXT HIDDEN,"
      " phase INT HIDDEN" /* Used for debugging only */
      ")");
  if(rc==SQLITE_OK){
    pNew = sqlite3_malloc(sizeof(*pNew));
    *ppVtab = (sqlite3_vtab*)pNew;
    if(pNew==0) return SQLITE_NOMEM;
    memset(pNew, 0, sizeof(*pNew));
    pNew->db = db;
  }
  return rc;
}
completionCursorReset()
static void completionCursorReset (completion_cursor * pCur) [static]
Definition at line 3196 of file shell.c.
References completion_cursor::j, completion_cursor::nLine, completion_cursor::nPrefix, completion_cursor::pStmt, sqlite3_finalize, sqlite3_free, completion_cursor::zLine, and completion_cursor::zPrefix.
Referenced by completionClose(), and completionFilter().
                                                          {
  sqlite3_free(pCur->zPrefix); pCur->zPrefix = 0; pCur->nPrefix = 0;
  sqlite3_free(pCur->zLine); pCur->zLine = 0; pCur->nLine = 0;
  sqlite3_finalize(pCur->pStmt); pCur->pStmt = 0;
  pCur->j = 0;
}
completionDisconnect()
static int completionDisconnect (sqlite3_vtab * pVtab) [static]
Definition at line 3175 of file shell.c.
References sqlite3_free, and SQLITE_OK.
                                                    {
  sqlite3_free(pVtab);
  return SQLITE_OK;
}
completionEof()
static int completionEof (sqlite3_vtab_cursor * cur) [static]
Definition at line 3375 of file shell.c.
References COMPLETION_EOF, and completion_cursor::ePhase.
                                                  {
  completion_cursor *pCur = (completion_cursor*)cur;
  return pCur->ePhase >= COMPLETION_EOF;
}
completionFilter()
static int completionFilter (sqlite3_vtab_cursor * pVtabCursor, int idxNum, const char * idxStr, int argc, sqlite3_value ** argv) [static]
Definition at line 3386 of file shell.c.
References COMPLETION_FIRST_PHASE, completionCursorReset(), completionNext(), completion_cursor::ePhase, completion_cursor::iRowid, completion_cursor::nLine, completion_cursor::nPrefix, sqlite3_mprintf, sqlite3_value_bytes, sqlite3_value_text, SQLITE_NOMEM, completion_cursor::zLine, and completion_cursor::zPrefix.
 {
  completion_cursor *pCur = (completion_cursor *)pVtabCursor;
  int iArg = 0;
  (void)(idxStr); /* Unused parameter */
  (void)(argc); /* Unused parameter */
  completionCursorReset(pCur);
  if(idxNum & 1){
    pCur->nPrefix = sqlite3_value_bytes(argv[iArg]);
    if(pCur->nPrefix>0){
      pCur->zPrefix = sqlite3_mprintf("%s", sqlite3_value_text(argv[iArg]));
      if(pCur->zPrefix==0) return SQLITE_NOMEM;
    }
    iArg = 1;
  }
  if(idxNum & 2){
    pCur->nLine = sqlite3_value_bytes(argv[iArg]);
    if(pCur->nLine>0){
      pCur->zLine = sqlite3_mprintf("%s", sqlite3_value_text(argv[iArg]));
      if(pCur->zLine==0) return SQLITE_NOMEM;
    }
  }
  if(pCur->zLine!=0 && pCur->zPrefix==0){
    int i = pCur->nLine;
    while(i>0 && (isalnum(pCur->zLine[i-1]) || pCur->zLine[i-1]=='_')){
      i--;
    }
    pCur->nPrefix = pCur->nLine - i;
    if(pCur->nPrefix>0){
      pCur->zPrefix = sqlite3_mprintf("%.*s", pCur->nPrefix, pCur->zLine + i);
      if(pCur->zPrefix==0) return SQLITE_NOMEM;
    }
  }
  pCur->iRowid = 0;
  pCur->ePhase = COMPLETION_FIRST_PHASE;
  return completionNext(pVtabCursor);
}
completionNext()
static int completionNext (sqlite3_vtab_cursor * cur) [static]
Definition at line 3226 of file shell.c.
References COMPLETION_COLUMNS, COMPLETION_DATABASES, COMPLETION_EOF, COMPLETION_KEYWORDS, COMPLETION_TABLES, completion_cursor::db, completion_cursor::ePhase, completion_cursor::iRowid, completion_cursor::j, completion_cursor::nPrefix, completion_cursor::pStmt, sqlite3_column_bytes, sqlite3_column_text, sqlite3_finalize, sqlite3_free, sqlite3_keyword_count, sqlite3_keyword_name, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, sqlite3_strnicmp, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, completion_cursor::szRow, completion_cursor::zCurrentRow, and completion_cursor::zPrefix.
Referenced by completionFilter().
                                                   {
  completion_cursor *pCur = (completion_cursor*)cur;
  int eNextPhase = 0; /* Next phase to try if current phase reaches end */
  int iCol = -1; /* If >=0, step pCur->pStmt and use the i-th column */
  pCur->iRowid++;
  while(pCur->ePhase!=COMPLETION_EOF){
    switch(pCur->ePhase){
      case COMPLETION_KEYWORDS: {
        if(pCur->j >= sqlite3_keyword_count()){
          pCur->zCurrentRow = 0;
          pCur->ePhase = COMPLETION_DATABASES;
        }else{
          sqlite3_keyword_name(pCur->j++, &pCur->zCurrentRow, &pCur->szRow);
        }
        iCol = -1;
        break;
      }
      case COMPLETION_DATABASES: {
        if(pCur->pStmt==0){
          sqlite3_prepare_v2(pCur->db, "PRAGMA database_list", -1,
                             &pCur->pStmt, 0);
        }
        iCol = 1;
        eNextPhase = COMPLETION_TABLES;
        break;
      }
      case COMPLETION_TABLES: {
        if(pCur->pStmt==0){
          sqlite3_stmt *pS2;
          char *zSql = 0;
          const char *zSep = "";
          sqlite3_prepare_v2(pCur->db, "PRAGMA database_list", -1, &pS2, 0);
          while(sqlite3_step(pS2)==SQLITE_ROW){
            const char *zDb = (const char*)sqlite3_column_text(pS2, 1);
            zSql = sqlite3_mprintf(
               "%z%s"
               "SELECT name FROM \"%w\".sqlite_master",
               zSql, zSep, zDb
            );
            if(zSql==0) return SQLITE_NOMEM;
            zSep = " UNION ";
          }
          sqlite3_finalize(pS2);
          sqlite3_prepare_v2(pCur->db, zSql, -1, &pCur->pStmt, 0);
          sqlite3_free(zSql);
        }
        iCol = 0;
        eNextPhase = COMPLETION_COLUMNS;
        break;
      }
      case COMPLETION_COLUMNS: {
        if(pCur->pStmt==0){
          sqlite3_stmt *pS2;
          char *zSql = 0;
          const char *zSep = "";
          sqlite3_prepare_v2(pCur->db, "PRAGMA database_list", -1, &pS2, 0);
          while(sqlite3_step(pS2)==SQLITE_ROW){
            const char *zDb = (const char*)sqlite3_column_text(pS2, 1);
            zSql = sqlite3_mprintf(
               "%z%s"
               "SELECT pti.name FROM \"%w\".sqlite_master AS sm"
                       " JOIN pragma_table_info(sm.name,%Q) AS pti"
               " WHERE sm.type='table'",
               zSql, zSep, zDb, zDb
            );
            if(zSql==0) return SQLITE_NOMEM;
            zSep = " UNION ";
          }
          sqlite3_finalize(pS2);
          sqlite3_prepare_v2(pCur->db, zSql, -1, &pCur->pStmt, 0);
          sqlite3_free(zSql);
        }
        iCol = 0;
        eNextPhase = COMPLETION_EOF;
        break;
      }
    }
    if(iCol<0){
      /* This case is when the phase presets zCurrentRow */
      if(pCur->zCurrentRow==0) continue;
    }else{
      if(sqlite3_step(pCur->pStmt)==SQLITE_ROW){
        /* Extract the next row of content */
        pCur->zCurrentRow = (const char*)sqlite3_column_text(pCur->pStmt, iCol);
        pCur->szRow = sqlite3_column_bytes(pCur->pStmt, iCol);
      }else{
        /* When all rows are finished, advance to the next phase */
        sqlite3_finalize(pCur->pStmt);
        pCur->pStmt = 0;
        pCur->ePhase = eNextPhase;
        continue;
      }
    }
    if(pCur->nPrefix==0) break;
    if(pCur->nPrefix<=pCur->szRow
     && sqlite3_strnicmp(pCur->zPrefix, pCur->zCurrentRow, pCur->nPrefix)==0
    ){
      break;
    }
  }
  return SQLITE_OK;
}
completionOpen()
static int completionOpen (sqlite3_vtab * p, sqlite3_vtab_cursor ** ppCursor) [static]
Definition at line 3183 of file shell.c.
References completion_cursor::base, completion_cursor::db, sqlite3_malloc, SQLITE_NOMEM, and SQLITE_OK.
                                                                          {
  completion_cursor *pCur;
  pCur = sqlite3_malloc(sizeof(*pCur));
  if(pCur==0) return SQLITE_NOMEM;
  memset(pCur, 0, sizeof(*pCur));
  pCur->db = ((completion_vtab*)p)->db;
  *ppCursor = &pCur->base;
  return SQLITE_OK;
}
completionRowid()
static int completionRowid (sqlite3_vtab_cursor * cur, sqlite_int64 * pRowid) [static]
Definition at line 3365 of file shell.c.
References completion_cursor::iRowid, and SQLITE_OK.
                                                                          {
  completion_cursor *pCur = (completion_cursor*)cur;
  *pRowid = pCur->iRowid;
  return SQLITE_OK;
}
createSelftestTable()
static void createSelftestTable (ShellState * p) [static]
Definition at line 10785 of file shell.c.
References ShellState::db, sqlite3_exec, sqlite3_free, and utf8_printf.
Referenced by do_meta_command().
                                              {
  char *zErrMsg = 0;
  sqlite3_exec(p->db,
    "SAVEPOINT selftest_init;\n"
    "CREATE TABLE IF NOT EXISTS selftest(\n"
    " tno INTEGER PRIMARY KEY,\n" /* Test number */
    " op TEXT,\n" /* Operator: memo run */
    " cmd TEXT,\n" /* Command text */
    " ans TEXT\n" /* Desired answer */
    ");"
    "CREATE TEMP TABLE [_shell$self](op,cmd,ans);\n"
    "INSERT INTO [_shell$self](rowid,op,cmd)\n"
    " VALUES(coalesce((SELECT (max(tno)+100)/10 FROM selftest),10),\n"
    " 'memo','Tests generated by --init');\n"
    "INSERT INTO [_shell$self]\n"
    " SELECT 'run',\n"
    " 'SELECT hex(sha3_query(''SELECT type,name,tbl_name,sql "
                                 "FROM sqlite_master ORDER BY 2'',224))',\n"
    " hex(sha3_query('SELECT type,name,tbl_name,sql "
                          "FROM sqlite_master ORDER BY 2',224));\n"
    "INSERT INTO [_shell$self]\n"
    " SELECT 'run',"
    " 'SELECT hex(sha3_query(''SELECT * FROM \"' ||"
    " printf('%w',name) || '\" NOT INDEXED'',224))',\n"
    " hex(sha3_query(printf('SELECT * FROM \"%w\" NOT INDEXED',name),224))\n"
    " FROM (\n"
    " SELECT name FROM sqlite_master\n"
    " WHERE type='table'\n"
    " AND name<>'selftest'\n"
    " AND coalesce(rootpage,0)>0\n"
    ")\n"
    " ORDER BY name;\n"
    "INSERT INTO [_shell$self]\n"
    " VALUES('run','PRAGMA integrity_check','ok');\n"
    "INSERT INTO selftest(tno,op,cmd,ans)"
    " SELECT rowid*10,op,cmd,ans FROM [_shell$self];\n"
    "DROP TABLE [_shell$self];"
    ,0,0,&zErrMsg);
  if(zErrMsg){
    utf8_printf(stderr, "SELFTEST initialization failure: %s\n", zErrMsg);
    sqlite3_free(zErrMsg);
  }
  sqlite3_exec(p->db, "RELEASE selftest_init",0,0,0);
}
csv_read_one_field()
static char* SQLITE_CDECL csv_read_one_field (ImportCtx * p) [static]
Definition at line 13105 of file shell.c.
References ImportCtx::bNotFirst, ImportCtx::cColSep, ImportCtx::cRowSep, ImportCtx::cTerm, import_append_char(), ImportCtx::in, ImportCtx::n, ImportCtx::nLine, utf8_printf, ImportCtx::z, and ImportCtx::zFile.
Referenced by do_meta_command().
                                                          {
  int c;
  int cSep = p->cColSep;
  int rSep = p->cRowSep;
  p->n = 0;
  c = fgetc(p->in);
  if(c==EOF || seenInterrupt){
    p->cTerm = EOF;
    return 0;
  }
  if(c=='"'){
    int pc, ppc;
    int startLine = p->nLine;
    int cQuote = c;
    pc = ppc = 0;
    while(1){
      c = fgetc(p->in);
      if(c==rSep) p->nLine++;
      if(c==cQuote){
        if(pc==cQuote){
          pc = 0;
          continue;
        }
      }
      if((c==cSep && pc==cQuote)
       || (c==rSep && pc==cQuote)
       || (c==rSep && pc=='\r' && ppc==cQuote)
       || (c==EOF && pc==cQuote)
      ){
        do{ p->n--; }while(p->z[p->n]!=cQuote);
        p->cTerm = c;
        break;
      }
      if(pc==cQuote && c!='\r'){
        utf8_printf(stderr, "%s:%d: unescaped %c character\n",
                p->zFile, p->nLine, cQuote);
      }
      if(c==EOF){
        utf8_printf(stderr, "%s:%d: unterminated %c-quoted field\n",
                p->zFile, startLine, cQuote);
        p->cTerm = c;
        break;
      }
      import_append_char(p, c);
      ppc = pc;
      pc = c;
    }
  }else{
    /* If this is the first field being parsed and it begins with the
    ** UTF-8 BOM (0xEF BB BF) then skip the BOM */
    if((c&0xff)==0xef && p->bNotFirst==0){
      import_append_char(p, c);
      c = fgetc(p->in);
      if((c&0xff)==0xbb){
        import_append_char(p, c);
        c = fgetc(p->in);
        if((c&0xff)==0xbf){
          p->bNotFirst = 1;
          p->n = 0;
          return csv_read_one_field(p);
        }
      }
    }
    while(c!=EOF && c!=cSep && c!=rSep){
      import_append_char(p, c);
      c = fgetc(p->in);
    }
    if(c==rSep){
      p->nLine++;
      if(p->n>0 && p->z[p->n-1]=='\r') p->n--;
    }
    p->cTerm = c;
  }
  if(p->z) p->z[p->n] = 0;
  p->bNotFirst = 1;
  return p->z;
}
ctxErrorMsg()
static void ctxErrorMsg (sqlite3_context * ctx, const char * zFmt, ...) [static]
Definition at line 2223 of file shell.c.
References sqlite3_free, sqlite3_result_error, and sqlite3_vmprintf.
Referenced by writefileFunc().
                                                                    {
  char *zMsg = 0;
  va_list ap;
  va_start(ap, zFmt);
  zMsg = sqlite3_vmprintf(zFmt, ap);
  sqlite3_result_error(ctx, zMsg, -1);
  sqlite3_free(zMsg);
  va_end(ap);
}
db_int()
static int db_int (ShellState * p, const char * zSql) [static]
Definition at line 13472 of file shell.c.
References ShellState::db, sqlite3_column_int, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_step, and SQLITE_ROW.
Referenced by shell_dbinfo_command().
                                                  {
  sqlite3_stmt *pStmt;
  int res = 0;
  sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
  if(pStmt && sqlite3_step(pStmt)==SQLITE_ROW){
    res = sqlite3_column_int(pStmt,0);
  }
  sqlite3_finalize(pStmt);
  return res;
}
deduceDatabaseType()
int deduceDatabaseType (const char * zName, int dfltZip)
Definition at line 12406 of file shell.c.
References ShellState::in, ShellState::lineno, SHELL_OPEN_APPENDVFS, SHELL_OPEN_NORMAL, SHELL_OPEN_UNSPEC, SHELL_OPEN_ZIPFILE, sqlite3_free, sqlite3_malloc, sqlite3_strlike, utf8_printf, time_test::x, and ShellState::zDbFilename.
Referenced by open_db(), and shellReset().
                                                      {
  FILE *f = fopen(zName, "rb");
  size_t n;
  int rc = SHELL_OPEN_UNSPEC;
  char zBuf[100];
  if(f==0){
    if(dfltZip && sqlite3_strlike("%.zip",zName,0)==0){
       return SHELL_OPEN_ZIPFILE;
    }else{
       return SHELL_OPEN_NORMAL;
    }
  }
  n = fread(zBuf, 16, 1, f);
  if(n==1 && memcmp(zBuf, "SQLite format 3", 16)==0){
    fclose(f);
    return SHELL_OPEN_NORMAL;
  }
  fseek(f, -25, SEEK_END);
  n = fread(zBuf, 25, 1, f);
  if(n==1 && memcmp(zBuf, "Start-Of-SQLite3-", 17)==0){
    rc = SHELL_OPEN_APPENDVFS;
  }else{
    fseek(f, -22, SEEK_END);
    n = fread(zBuf, 22, 1, f);
    if(n==1 && zBuf[0]==0x50 && zBuf[1]==0x4b && zBuf[2]==0x05
       && zBuf[3]==0x06){
      rc = SHELL_OPEN_ZIPFILE;
    }else if(n==0 && dfltZip && sqlite3_strlike("%.zip",zName,0)==0){
      rc = SHELL_OPEN_ZIPFILE;
    }
  }
  fclose(f);
  return rc;
}
disable_debug_trace_modes()
static void disable_debug_trace_modes (void) [static]
Definition at line 11307 of file shell.c.
Referenced by shell_exec().
                                           {
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_SELECTTRACE)
  savedSelectTrace = sqlite3SelectTrace;
  sqlite3SelectTrace = 0;
#endif
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_WHERETRACE)
  savedWhereTrace = sqlite3WhereTrace;
  sqlite3WhereTrace = 0;
#endif
}
display_scanstats()
static void display_scanstats (sqlite3 * db, ShellState * pArg) [static]
Definition at line 11129 of file shell.c.
References ShellState::out, ShellState::pStmt, raw_printf, sqlite3_stmt_scanstatus(), SQLITE_SCANSTAT_EST, SQLITE_SCANSTAT_EXPLAIN, SQLITE_SCANSTAT_NLOOP, SQLITE_SCANSTAT_NVISIT, SQLITE_SCANSTAT_SELECTID, UNUSED_PARAMETER, and utf8_printf.
Referenced by shell_exec().
 {
#ifndef SQLITE_ENABLE_STMT_SCANSTATUS
  UNUSED_PARAMETER(db);
  UNUSED_PARAMETER(pArg);
#else
  int i, k, n, mx;
  raw_printf(pArg->out, "-------- scanstats --------\n");
  mx = 0;
  for(k=0; k<=mx; k++){
    double rEstLoop = 1.0;
    for(i=n=0; 1; i++){
      sqlite3_stmt *p = pArg->pStmt;
      sqlite3_int64 nLoop, nVisit;
      double rEst;
      int iSid;
      const char *zExplain;
      if(sqlite3_stmt_scanstatus(p, i, SQLITE_SCANSTAT_NLOOP, (void*)&nLoop)){
        break;
      }
      sqlite3_stmt_scanstatus(p, i, SQLITE_SCANSTAT_SELECTID, (void*)&iSid);
      if(iSid>mx) mx = iSid;
      if(iSid!=k) continue;
      if(n==0){
        rEstLoop = (double)nLoop;
        if(k>0) raw_printf(pArg->out, "-------- subquery %d -------\n", k);
      }
      n++;
      sqlite3_stmt_scanstatus(p, i, SQLITE_SCANSTAT_NVISIT, (void*)&nVisit);
      sqlite3_stmt_scanstatus(p, i, SQLITE_SCANSTAT_EST, (void*)&rEst);
      sqlite3_stmt_scanstatus(p, i, SQLITE_SCANSTAT_EXPLAIN, (void*)&zExplain);
      utf8_printf(pArg->out, "Loop %2d: %s\n", n, zExplain);
      rEstLoop *= rEst;
      raw_printf(pArg->out,
          " nLoop=%-8lld nRow=%-8lld estRow=%-8lld estRow/Loop=%-8g\n",
          nLoop, nVisit, (sqlite3_int64)(rEstLoop+0.5), rEst
      );
    }
  }
  raw_printf(pArg->out, "---------------------------\n");
#endif
}
display_stats()
static int display_stats (sqlite3 * db, ShellState * pArg, int bReset) [static]
Definition at line 10998 of file shell.c.
References displayStatLine(), ShellState::out, ShellState::pStmt, raw_printf, ShellState::shellFlgs, SHFLG_Lookaside, SHFLG_Pagecache, sqlite3_column_count, sqlite3_column_database_name, sqlite3_column_decltype, sqlite3_column_name, sqlite3_column_origin_name, sqlite3_column_table_name, sqlite3_db_status, sqlite3_snprintf, sqlite3_stmt_status, SQLITE_DBSTATUS_CACHE_HIT, SQLITE_DBSTATUS_CACHE_MISS, SQLITE_DBSTATUS_CACHE_SPILL, SQLITE_DBSTATUS_CACHE_USED, SQLITE_DBSTATUS_CACHE_WRITE, SQLITE_DBSTATUS_LOOKASIDE_HIT, SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL, SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE, SQLITE_DBSTATUS_LOOKASIDE_USED, SQLITE_DBSTATUS_SCHEMA_USED, SQLITE_DBSTATUS_STMT_USED, SQLITE_STATUS_MALLOC_COUNT, SQLITE_STATUS_MALLOC_SIZE, SQLITE_STATUS_MEMORY_USED, SQLITE_STATUS_PAGECACHE_OVERFLOW, SQLITE_STATUS_PAGECACHE_SIZE, SQLITE_STATUS_PAGECACHE_USED, SQLITE_STATUS_PARSER_STACK, SQLITE_STMTSTATUS_AUTOINDEX, SQLITE_STMTSTATUS_FULLSCAN_STEP, SQLITE_STMTSTATUS_MEMUSED, SQLITE_STMTSTATUS_REPREPARE, SQLITE_STMTSTATUS_RUN, SQLITE_STMTSTATUS_SORT, SQLITE_STMTSTATUS_VM_STEP, ShellState::statsOn, utf8_printf, and time_test::x.
Referenced by do_meta_command(), and shell_exec().
 {
  int iCur;
  int iHiwtr;
  FILE *out;
  if(pArg==0 || pArg->out==0) return 0;
  out = pArg->out;
  if(pArg->pStmt && (pArg->statsOn & 2)){
    int nCol, i, x;
    sqlite3_stmt *pStmt = pArg->pStmt;
    char z[100];
    nCol = sqlite3_column_count(pStmt);
    raw_printf(out, "%-36s %d\n", "Number of output columns:", nCol);
    for(i=0; i<nCol; i++){
      sqlite3_snprintf(sizeof(z),z,"Column %d %nname:", i, &x);
      utf8_printf(out, "%-36s %s\n", z, sqlite3_column_name(pStmt,i));
#ifndef SQLITE_OMIT_DECLTYPE
      sqlite3_snprintf(30, z+x, "declared type:");
      utf8_printf(out, "%-36s %s\n", z, sqlite3_column_decltype(pStmt, i));
#endif
#ifdef SQLITE_ENABLE_COLUMN_METADATA
      sqlite3_snprintf(30, z+x, "database name:");
      utf8_printf(out, "%-36s %s\n", z, sqlite3_column_database_name(pStmt,i));
      sqlite3_snprintf(30, z+x, "table name:");
      utf8_printf(out, "%-36s %s\n", z, sqlite3_column_table_name(pStmt,i));
      sqlite3_snprintf(30, z+x, "origin name:");
      utf8_printf(out, "%-36s %s\n", z, sqlite3_column_origin_name(pStmt,i));
#endif
    }
  }
  displayStatLine(pArg, "Memory Used:",
     "%lld (max %lld) bytes", SQLITE_STATUS_MEMORY_USED, bReset);
  displayStatLine(pArg, "Number of Outstanding Allocations:",
     "%lld (max %lld)", SQLITE_STATUS_MALLOC_COUNT, bReset);
  if(pArg->shellFlgs & SHFLG_Pagecache){
    displayStatLine(pArg, "Number of Pcache Pages Used:",
       "%lld (max %lld) pages", SQLITE_STATUS_PAGECACHE_USED, bReset);
  }
  displayStatLine(pArg, "Number of Pcache Overflow Bytes:",
     "%lld (max %lld) bytes", SQLITE_STATUS_PAGECACHE_OVERFLOW, bReset);
  displayStatLine(pArg, "Largest Allocation:",
     "%lld bytes", SQLITE_STATUS_MALLOC_SIZE, bReset);
  displayStatLine(pArg, "Largest Pcache Allocation:",
     "%lld bytes", SQLITE_STATUS_PAGECACHE_SIZE, bReset);
#ifdef YYTRACKMAXSTACKDEPTH
  displayStatLine(pArg, "Deepest Parser Stack:",
     "%lld (max %lld)", SQLITE_STATUS_PARSER_STACK, bReset);
#endif
  if(db){
    if(pArg->shellFlgs & SHFLG_Lookaside){
      iHiwtr = iCur = -1;
      sqlite3_db_status(db, SQLITE_DBSTATUS_LOOKASIDE_USED,
                        &iCur, &iHiwtr, bReset);
      raw_printf(pArg->out,
              "Lookaside Slots Used: %d (max %d)\n",
              iCur, iHiwtr);
      sqlite3_db_status(db, SQLITE_DBSTATUS_LOOKASIDE_HIT,
                        &iCur, &iHiwtr, bReset);
      raw_printf(pArg->out, "Successful lookaside attempts: %d\n",
              iHiwtr);
      sqlite3_db_status(db, SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE,
                        &iCur, &iHiwtr, bReset);
      raw_printf(pArg->out, "Lookaside failures due to size: %d\n",
              iHiwtr);
      sqlite3_db_status(db, SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL,
                        &iCur, &iHiwtr, bReset);
      raw_printf(pArg->out, "Lookaside failures due to OOM: %d\n",
              iHiwtr);
    }
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_CACHE_USED, &iCur, &iHiwtr, bReset);
    raw_printf(pArg->out, "Pager Heap Usage: %d bytes\n",
            iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_CACHE_HIT, &iCur, &iHiwtr, 1);
    raw_printf(pArg->out, "Page cache hits: %d\n", iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_CACHE_MISS, &iCur, &iHiwtr, 1);
    raw_printf(pArg->out, "Page cache misses: %d\n", iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_CACHE_WRITE, &iCur, &iHiwtr, 1);
    raw_printf(pArg->out, "Page cache writes: %d\n", iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_CACHE_SPILL, &iCur, &iHiwtr, 1);
    raw_printf(pArg->out, "Page cache spills: %d\n", iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_SCHEMA_USED, &iCur, &iHiwtr, bReset);
    raw_printf(pArg->out, "Schema Heap Usage: %d bytes\n",
            iCur);
    iHiwtr = iCur = -1;
    sqlite3_db_status(db, SQLITE_DBSTATUS_STMT_USED, &iCur, &iHiwtr, bReset);
    raw_printf(pArg->out, "Statement Heap/Lookaside Usage: %d bytes\n",
            iCur);
  }
  if(pArg->pStmt){
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_FULLSCAN_STEP,
                               bReset);
    raw_printf(pArg->out, "Fullscan Steps: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_SORT, bReset);
    raw_printf(pArg->out, "Sort Operations: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_AUTOINDEX,bReset);
    raw_printf(pArg->out, "Autoindex Inserts: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_VM_STEP, bReset);
    raw_printf(pArg->out, "Virtual Machine Steps: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_REPREPARE,bReset);
    raw_printf(pArg->out, "Reprepare operations: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_RUN, bReset);
    raw_printf(pArg->out, "Number of times run: %d\n", iCur);
    iCur = sqlite3_stmt_status(pArg->pStmt, SQLITE_STMTSTATUS_MEMUSED, bReset);
    raw_printf(pArg->out, "Memory used by prepared stmt: %d\n", iCur);
  }
#ifdef __linux__
  displayLinuxIoStats(pArg->out);
#endif
  /* Do not remove this machine readable comment: extra-stats-output-here */
  return 0;
}
displayStatLine()
static void displayStatLine (ShellState * p, char * zLabel, char * zFormat, int iStatusCtrl, int bReset) [static]
Definition at line 10972 of file shell.c.
References ShellState::out, raw_printf, sqlite3_snprintf, and sqlite3_status64.
Referenced by display_stats().
 {
  sqlite3_int64 iCur = -1;
  sqlite3_int64 iHiwtr = -1;
  int i, nPercent;
  char zLine[200];
  sqlite3_status64(iStatusCtrl, &iCur, &iHiwtr, bReset);
  for(i=0, nPercent=0; zFormat[i]; i++){
    if(zFormat[i]=='%') nPercent++;
  }
  if(nPercent>1){
    sqlite3_snprintf(sizeof(zLine), zLine, zFormat, iCur, iHiwtr);
  }else{
    sqlite3_snprintf(sizeof(zLine), zLine, zFormat, iHiwtr);
  }
  raw_printf(p->out, "%-36s %s\n", zLabel, zLine);
}
do_meta_command()
static int do_meta_command (char * zLine, ShellState * p) [static]
Definition at line 15481 of file shell.c.
References appendText(), ArraySize, ascii_read_one_field(), ShellState::autoEQP, AUTOEQP_full, AUTOEQP_on, AUTOEQP_trigger, ShellState::autoEQPtest, ShellState::autoEQPtrace, ShellState::autoExplain, bind_table_init(), booleanValue(), callback(), captureOutputCallback(), ImportCtx::cColSep, clearTempFile(), close_db(), ShellState::cMode, ShellState::cnt, ShellState::colSeparator, ShellState::colWidth, createSelftestTable(), ImportCtx::cRowSep, csv_read_one_field(), ImportCtx::cTerm, CTIMEOPT_VAL, main3::data, ShellState::db, display_stats(), ShellState::doXdgOpen, ShellState::eTraceType, ShellState::expert, expertDotCommand(), expertFinish(), ShellState::flgProgress, freeText(), HAS_TIMER, import_append_char(), ShellState::in, ImportCtx::in, initText(), integerValue(), IsSpace, sqlite3_vfs::iVersion, ShellState::lineno, lintDotCommand(), ShellState::mode, MODE_Ascii, MODE_Column, MODE_Csv, MODE_Explain, MODE_Html, MODE_Insert, MODE_Line, MODE_List, MODE_Pretty, MODE_Quote, MODE_Semi, MODE_Tcl, sqlite3_vfs::mxPathname, ShellState::mxProgress, ShellText::n, ShellState::nCheck, ShellState::nErr, newTempFile(), ImportCtx::nLine, ShellState::normalMode, ShellState::nProgress, ShellState::nullValue, open_db(), OPEN_DB_KEEPALIVE, ShellState::openFlags, ShellState::openMode, optionMatch(), ShellState::out, ShellState::outCount, ShellState::outfile, output_c_string(), output_file_close(), output_file_open(), output_reset(), outputModePush(), pclose(), ExpertInfo::pExpert, ShellState::pLog, sqlite3_vfs::pNext, popen(), process_input(), progress_handler(), quoteChar(), raw_printf, readFile(), resolve_backslashes(), ShellState::rowSeparator, run_schema_dump_query(), run_table_dump_query(), ShellState::scanstatsOn, SEP_Column, SEP_Comma, SEP_CrLf, SEP_Record, SEP_Row, SEP_Space, SEP_Tab, SEP_Unit, session_close_all, set_table_name(), setBinaryMode, setOrClearFlag(), setTextMode, shell_dbinfo_command(), shell_exec(), SHELL_OPEN_APPENDVFS, SHELL_OPEN_DESERIALIZE, SHELL_OPEN_HEXDB, SHELL_OPEN_READONLY, SHELL_OPEN_UNSPEC, SHELL_OPEN_ZIPFILE, shell_out_of_memory(), SHELL_PROGRESS_ONCE, SHELL_PROGRESS_QUIET, SHELL_PROGRESS_RESET, SHELL_TRACE_EXPANDED, SHELL_TRACE_NORMALIZED, SHELL_TRACE_PLAIN, shellAuth(), ShellClearFlag, shellDatabaseError(), shellDeleteFile(), ShellState::shellFlgs, ShellHasFlag, ShellSetFlag, SHFLG_CountChanges, SHFLG_Echo, SHFLG_Newlines, SHFLG_PreserveRowid, ShellState::showHeader, showHelp(), sql_trace_callback(), sqlite3_backup_finish, sqlite3_backup_init, sqlite3_backup_step, sqlite3_bind_null, sqlite3_bind_text, sqlite3_busy_timeout, sqlite3_column_count, sqlite3_column_int, sqlite3_column_text, sqlite3_create_module, sqlite3_db_config, sqlite3_drop_modules, sqlite3_errmsg, sqlite3_exec, sqlite3_file_control, sqlite3_finalize, sqlite3_free, sqlite3_get_autocommit, sqlite3_libversion, sqlite3_limit, sqlite3_load_extension, sqlite3_malloc, sqlite3_malloc64, sqlite3_mprintf, sqlite3_open, sqlite3_open_v2, sqlite3_prepare_v2, sqlite3_progress_handler, sqlite3_randomness, sqlite3_realloc64, sqlite3_reset, sqlite3_set_authorizer, sqlite3_sleep, sqlite3_snprintf, sqlite3_sourceid, sqlite3_step, sqlite3_strglob, sqlite3_stricmp, sqlite3_strlike, sqlite3_strnicmp, sqlite3_table_column_metadata, sqlite3_test_control, sqlite3_trace_v2, sqlite3_vfs_find, SQLITE_API, SQLITE_BUSY, SQLITE_CDECL, SQLITE_DBCONFIG_DEFENSIVE, SQLITE_DBCONFIG_DQS_DDL, SQLITE_DBCONFIG_DQS_DML, SQLITE_DBCONFIG_ENABLE_FKEY, SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER, SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION, SQLITE_DBCONFIG_ENABLE_QPSG, SQLITE_DBCONFIG_ENABLE_TRIGGER, SQLITE_DBCONFIG_ENABLE_VIEW, SQLITE_DBCONFIG_LEGACY_ALTER_TABLE, SQLITE_DBCONFIG_LEGACY_FILE_FORMAT, SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE, SQLITE_DBCONFIG_RESET_DATABASE, SQLITE_DBCONFIG_TRIGGER_EQP, SQLITE_DBCONFIG_TRUSTED_SCHEMA, SQLITE_DBCONFIG_WRITABLE_SCHEMA, SQLITE_DONE, SQLITE_FCNTL_CHUNK_SIZE, SQLITE_FCNTL_HAS_MOVED, SQLITE_FCNTL_LOCK_TIMEOUT, SQLITE_FCNTL_PERSIST_WAL, SQLITE_FCNTL_POWERSAFE_OVERWRITE, SQLITE_FCNTL_SIZE_LIMIT, SQLITE_FCNTL_TEMPFILENAME, SQLITE_FCNTL_VFS_POINTER, SQLITE_FCNTL_VFSNAME, SQLITE_LIMIT_ATTACHED, SQLITE_LIMIT_COLUMN, SQLITE_LIMIT_COMPOUND_SELECT, SQLITE_LIMIT_EXPR_DEPTH, SQLITE_LIMIT_FUNCTION_ARG, SQLITE_LIMIT_LENGTH, SQLITE_LIMIT_LIKE_PATTERN_LENGTH, SQLITE_LIMIT_SQL_LENGTH, SQLITE_LIMIT_TRIGGER_DEPTH, SQLITE_LIMIT_VARIABLE_NUMBER, SQLITE_LIMIT_VDBE_OP, SQLITE_LIMIT_WORKER_THREADS, SQLITE_LOCKED, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_NOFOLLOW, SQLITE_OPEN_READWRITE, SQLITE_ROW, SQLITE_STATIC, SQLITE_TESTCTRL_ALWAYS, SQLITE_TESTCTRL_ASSERT, SQLITE_TESTCTRL_BYTEORDER, SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS, SQLITE_TESTCTRL_IMPOSTER, SQLITE_TESTCTRL_INTERNAL_FUNCTIONS, SQLITE_TESTCTRL_LOCALTIME_FAULT, SQLITE_TESTCTRL_NEVER_CORRUPT, SQLITE_TESTCTRL_OPTIMIZATIONS, SQLITE_TESTCTRL_PARSER_COVERAGE, SQLITE_TESTCTRL_PENDING_BYTE, SQLITE_TESTCTRL_PRNG_RESET, SQLITE_TESTCTRL_PRNG_RESTORE, SQLITE_TESTCTRL_PRNG_SAVE, SQLITE_TESTCTRL_PRNG_SEED, SQLITE_TESTCTRL_RESERVE, SQLITE_TRACE_CLOSE, SQLITE_TRACE_PROFILE, SQLITE_TRACE_ROW, SQLITE_TRACE_STMT, SQLITE_TRANSIENT, ShellState::statsOn, strlen30(), ShellState::szMax, sqlite3_vfs::szOsFile, test_breakpoint(), testcase_glob(), ShellState::traceOut, tryToClone(), utf8_printf, ShellState::writableSchema, time_test::x, ShellText::z, ImportCtx::z, ShellState::zDbFilename, ShellState::zDestTable, ImportCtx::zFile, ShellState::zFreeOnClose, sqlite3_vfs::zName, zName, ShellState::zTempFile, and ShellState::zTestcase.
Referenced by main(), and process_input().
                                                      {
  int h = 1;
  int nArg = 0;
  int n, c;
  int rc = 0;
  char *azArg[52];
#ifndef SQLITE_OMIT_VIRTUALTABLE
  if(p->expert.pExpert){
    expertFinish(p, 1, 0);
  }
#endif
  /* Parse the input line into tokens.
  */
  while(zLine[h] && nArg<ArraySize(azArg)-1){
    while(IsSpace(zLine[h])){ h++; }
    if(zLine[h]==0) break;
    if(zLine[h]=='\'' || zLine[h]=='"'){
      int delim = zLine[h++];
      azArg[nArg++] = &zLine[h];
      while(zLine[h] && zLine[h]!=delim){
        if(zLine[h]=='\\' && delim=='"' && zLine[h+1]!=0) h++;
        h++;
      }
      if(zLine[h]==delim){
        zLine[h++] = 0;
      }
      if(delim=='"') resolve_backslashes(azArg[nArg-1]);
    }else{
      azArg[nArg++] = &zLine[h];
      while(zLine[h] && !IsSpace(zLine[h])){ h++; }
      if(zLine[h]) zLine[h++] = 0;
      resolve_backslashes(azArg[nArg-1]);
    }
  }
  azArg[nArg] = 0;
  /* Process the input line.
  */
  if(nArg==0) return 0; /* no tokens, no error */
  n = strlen30(azArg[0]);
  c = azArg[0][0];
  clearTempFile(p);
#ifndef SQLITE_OMIT_AUTHORIZATION
  if(c=='a' && strncmp(azArg[0], "auth", n)==0){
    if(nArg!=2){
      raw_printf(stderr, "Usage: .auth ON|OFF\n");
      rc = 1;
      goto meta_command_exit;
    }
    open_db(p, 0);
    if(booleanValue(azArg[1])){
      sqlite3_set_authorizer(p->db, shellAuth, p);
    }else{
      sqlite3_set_authorizer(p->db, 0, 0);
    }
  }else
#endif
#if !defined(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_HAVE_ZLIB)
  if(c=='a' && strncmp(azArg[0], "archive", n)==0){
    open_db(p, 0);
    rc = arDotCommand(p, 0, azArg, nArg);
  }else
#endif
  if((c=='b' && n>=3 && strncmp(azArg[0], "backup", n)==0)
   || (c=='s' && n>=3 && strncmp(azArg[0], "save", n)==0)
  ){
    const char *zDestFile = 0;
    const char *zDb = 0;
    sqlite3 *pDest;
    sqlite3_backup *pBackup;
    int j;
    int bAsync = 0;
    const char *zVfs = 0;
    for(j=1; j<nArg; j++){
      const char *z = azArg[j];
      if(z[0]=='-'){
        if(z[1]=='-') z++;
        if(strcmp(z, "-append")==0){
          zVfs = "apndvfs";
        }else
        if(strcmp(z, "-async")==0){
          bAsync = 1;
        }else
        {
          utf8_printf(stderr, "unknown option: %s\n", azArg[j]);
          return 1;
        }
      }else if(zDestFile==0){
        zDestFile = azArg[j];
      }else if(zDb==0){
        zDb = zDestFile;
        zDestFile = azArg[j];
      }else{
        raw_printf(stderr, "Usage: .backup ?DB? ?OPTIONS? FILENAME\n");
        return 1;
      }
    }
    if(zDestFile==0){
      raw_printf(stderr, "missing FILENAME argument on .backup\n");
      return 1;
    }
    if(zDb==0) zDb = "main";
    rc = sqlite3_open_v2(zDestFile, &pDest,
                  SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE, zVfs);
    if(rc!=SQLITE_OK){
      utf8_printf(stderr, "Error: cannot open \"%s\"\n", zDestFile);
      close_db(pDest);
      return 1;
    }
    if(bAsync){
      sqlite3_exec(pDest, "PRAGMA synchronous=OFF; PRAGMA journal_mode=OFF;",
                   0, 0, 0);
    }
    open_db(p, 0);
    pBackup = sqlite3_backup_init(pDest, "main", p->db, zDb);
    if(pBackup==0){
      utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(pDest));
      close_db(pDest);
      return 1;
    }
    while((rc = sqlite3_backup_step(pBackup,100))==SQLITE_OK){}
    sqlite3_backup_finish(pBackup);
    if(rc==SQLITE_DONE){
      rc = 0;
    }else{
      utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(pDest));
      rc = 1;
    }
    close_db(pDest);
  }else
  if(c=='b' && n>=3 && strncmp(azArg[0], "bail", n)==0){
    if(nArg==2){
      bail_on_error = booleanValue(azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .bail on|off\n");
      rc = 1;
    }
  }else
  if(c=='b' && n>=3 && strncmp(azArg[0], "binary", n)==0){
    if(nArg==2){
      if(booleanValue(azArg[1])){
        setBinaryMode(p->out, 1);
      }else{
        setTextMode(p->out, 1);
      }
    }else{
      raw_printf(stderr, "Usage: .binary on|off\n");
      rc = 1;
    }
  }else
  if(c=='c' && strcmp(azArg[0],"cd")==0){
    if(nArg==2){
#if defined(_WIN32) || defined(WIN32)
      wchar_t *z = sqlite3_win32_utf8_to_unicode(azArg[1]);
      rc = !SetCurrentDirectoryW(z);
      sqlite3_free(z);
#else
      rc = chdir(azArg[1]);
#endif
      if(rc){
        utf8_printf(stderr, "Cannot change to directory \"%s\"\n", azArg[1]);
        rc = 1;
      }
    }else{
      raw_printf(stderr, "Usage: .cd DIRECTORY\n");
      rc = 1;
    }
  }else
  /* The undocumented ".breakpoint" command causes a call to the no-op
  ** routine named test_breakpoint().
  */
  if(c=='b' && n>=3 && strncmp(azArg[0], "breakpoint", n)==0){
    test_breakpoint();
  }else
  if(c=='c' && n>=3 && strncmp(azArg[0], "changes", n)==0){
    if(nArg==2){
      setOrClearFlag(p, SHFLG_CountChanges, azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .changes on|off\n");
      rc = 1;
    }
  }else
  /* Cancel output redirection, if it is currently set (by .testcase)
  ** Then read the content of the testcase-out.txt file and compare against
  ** azArg[1]. If there are differences, report an error and exit.
  */
  if(c=='c' && n>=3 && strncmp(azArg[0], "check", n)==0){
    char *zRes = 0;
    output_reset(p);
    if(nArg!=2){
      raw_printf(stderr, "Usage: .check GLOB-PATTERN\n");
      rc = 2;
    }else if((zRes = readFile("testcase-out.txt", 0))==0){
      raw_printf(stderr, "Error: cannot read 'testcase-out.txt'\n");
      rc = 2;
    }else if(testcase_glob(azArg[1],zRes)==0){
      utf8_printf(stderr,
                 "testcase-%s FAILED\n Expected: [%s]\n Got: [%s]\n",
                 p->zTestcase, azArg[1], zRes);
      rc = 1;
    }else{
      utf8_printf(stdout, "testcase-%s ok\n", p->zTestcase);
      p->nCheck++;
    }
    sqlite3_free(zRes);
  }else
  if(c=='c' && strncmp(azArg[0], "clone", n)==0){
    if(nArg==2){
      tryToClone(p, azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .clone FILENAME\n");
      rc = 1;
    }
  }else
  if(c=='d' && n>1 && strncmp(azArg[0], "databases", n)==0){
    ShellState data;
    char *zErrMsg = 0;
    open_db(p, 0);
    memcpy(&data, p, sizeof(data));
    data.showHeader = 0;
    data.cMode = data.mode = MODE_List;
    sqlite3_snprintf(sizeof(data.colSeparator),data.colSeparator,": ");
    data.cnt = 0;
    sqlite3_exec(p->db, "SELECT name, file FROM pragma_database_list",
                 callback, &data, &zErrMsg);
    if(zErrMsg){
      utf8_printf(stderr,"Error: %s\n", zErrMsg);
      sqlite3_free(zErrMsg);
      rc = 1;
    }
  }else
  if(c=='d' && n>=3 && strncmp(azArg[0], "dbconfig", n)==0){
    static const struct DbConfigChoices {
      const char *zName;
      int op;
    } aDbConfig[] = {
        { "defensive", SQLITE_DBCONFIG_DEFENSIVE },
        { "dqs_ddl", SQLITE_DBCONFIG_DQS_DDL },
        { "dqs_dml", SQLITE_DBCONFIG_DQS_DML },
        { "enable_fkey", SQLITE_DBCONFIG_ENABLE_FKEY },
        { "enable_qpsg", SQLITE_DBCONFIG_ENABLE_QPSG },
        { "enable_trigger", SQLITE_DBCONFIG_ENABLE_TRIGGER },
        { "enable_view", SQLITE_DBCONFIG_ENABLE_VIEW },
        { "fts3_tokenizer", SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER },
        { "legacy_alter_table", SQLITE_DBCONFIG_LEGACY_ALTER_TABLE },
        { "legacy_file_format", SQLITE_DBCONFIG_LEGACY_FILE_FORMAT },
        { "load_extension", SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION },
        { "no_ckpt_on_close", SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE },
        { "reset_database", SQLITE_DBCONFIG_RESET_DATABASE },
        { "trigger_eqp", SQLITE_DBCONFIG_TRIGGER_EQP },
        { "trusted_schema", SQLITE_DBCONFIG_TRUSTED_SCHEMA },
        { "writable_schema", SQLITE_DBCONFIG_WRITABLE_SCHEMA },
    };
    int ii, v;
    open_db(p, 0);
    for(ii=0; ii<ArraySize(aDbConfig); ii++){
      if(nArg>1 && strcmp(azArg[1], aDbConfig[ii].zName)!=0) continue;
      if(nArg>=3){
        sqlite3_db_config(p->db, aDbConfig[ii].op, booleanValue(azArg[2]), 0);
      }
      sqlite3_db_config(p->db, aDbConfig[ii].op, -1, &v);
      utf8_printf(p->out, "%19s %s\n", aDbConfig[ii].zName, v ? "on" : "off");
      if(nArg>1) break;
    }
    if(nArg>1 && ii==ArraySize(aDbConfig)){
      utf8_printf(stderr, "Error: unknown dbconfig \"%s\"\n", azArg[1]);
      utf8_printf(stderr, "Enter \".dbconfig\" with no arguments for a list\n");
    }
  }else
  if(c=='d' && n>=3 && strncmp(azArg[0], "dbinfo", n)==0){
    rc = shell_dbinfo_command(p, nArg, azArg);
  }else
#if !defined(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_ENABLE_DBPAGE_VTAB)
  if(c=='r' && strncmp(azArg[0], "recover", n)==0){
    open_db(p, 0);
    rc = recoverDatabaseCmd(p, nArg, azArg);
  }else
#endif /* !(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_ENABLE_DBPAGE_VTAB) */
  if(c=='d' && strncmp(azArg[0], "dump", n)==0){
    const char *zLike = 0;
    int i;
    int savedShowHeader = p->showHeader;
    int savedShellFlags = p->shellFlgs;
    ShellClearFlag(p, SHFLG_PreserveRowid|SHFLG_Newlines|SHFLG_Echo);
    for(i=1; i<nArg; i++){
      if(azArg[i][0]=='-'){
        const char *z = azArg[i]+1;
        if(z[0]=='-') z++;
        if(strcmp(z,"preserve-rowids")==0){
#ifdef SQLITE_OMIT_VIRTUALTABLE
          raw_printf(stderr, "The --preserve-rowids option is not compatible"
                             " with SQLITE_OMIT_VIRTUALTABLE\n");
          rc = 1;
          goto meta_command_exit;
#else
          ShellSetFlag(p, SHFLG_PreserveRowid);
#endif
        }else
        if(strcmp(z,"newlines")==0){
          ShellSetFlag(p, SHFLG_Newlines);
        }else
        {
          raw_printf(stderr, "Unknown option \"%s\" on \".dump\"\n", azArg[i]);
          rc = 1;
          goto meta_command_exit;
        }
      }else if(zLike){
        raw_printf(stderr, "Usage: .dump ?--preserve-rowids? "
                           "?--newlines? ?LIKE-PATTERN?\n");
        rc = 1;
        goto meta_command_exit;
      }else{
        zLike = azArg[i];
      }
    }
    open_db(p, 0);
    /* When playing back a "dump", the content might appear in an order
    ** which causes immediate foreign key constraints to be violated.
    ** So disable foreign-key constraint enforcement to prevent problems. */
    raw_printf(p->out, "PRAGMA foreign_keys=OFF;\n");
    raw_printf(p->out, "BEGIN TRANSACTION;\n");
    p->writableSchema = 0;
    p->showHeader = 0;
    /* Set writable_schema=ON since doing so forces SQLite to initialize
    ** as much of the schema as it can even if the sqlite_master table is
    ** corrupt. */
    sqlite3_exec(p->db, "SAVEPOINT dump; PRAGMA writable_schema=ON", 0, 0, 0);
    p->nErr = 0;
    if(zLike==0){
      run_schema_dump_query(p,
        "SELECT name, type, sql FROM sqlite_master "
        "WHERE sql NOT NULL AND type=='table' AND name!='sqlite_sequence'"
      );
      run_schema_dump_query(p,
        "SELECT name, type, sql FROM sqlite_master "
        "WHERE name=='sqlite_sequence'"
      );
      run_table_dump_query(p,
        "SELECT sql FROM sqlite_master "
        "WHERE sql NOT NULL AND type IN ('index','trigger','view')", 0
      );
    }else{
      char *zSql;
      zSql = sqlite3_mprintf(
        "SELECT name, type, sql FROM sqlite_master "
        "WHERE tbl_name LIKE %Q AND type=='table'"
        " AND sql NOT NULL", zLike);
      run_schema_dump_query(p,zSql);
      sqlite3_free(zSql);
      zSql = sqlite3_mprintf(
        "SELECT sql FROM sqlite_master "
        "WHERE sql NOT NULL"
        " AND type IN ('index','trigger','view')"
        " AND tbl_name LIKE %Q", zLike);
      run_table_dump_query(p, zSql, 0);
      sqlite3_free(zSql);
    }
    if(p->writableSchema){
      raw_printf(p->out, "PRAGMA writable_schema=OFF;\n");
      p->writableSchema = 0;
    }
    sqlite3_exec(p->db, "PRAGMA writable_schema=OFF;", 0, 0, 0);
    sqlite3_exec(p->db, "RELEASE dump;", 0, 0, 0);
    raw_printf(p->out, p->nErr?"ROLLBACK; -- due to errors\n":"COMMIT;\n");
    p->showHeader = savedShowHeader;
    p->shellFlgs = savedShellFlags;
  }else
  if(c=='e' && strncmp(azArg[0], "echo", n)==0){
    if(nArg==2){
      setOrClearFlag(p, SHFLG_Echo, azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .echo on|off\n");
      rc = 1;
    }
  }else
  if(c=='e' && strncmp(azArg[0], "eqp", n)==0){
    if(nArg==2){
      p->autoEQPtest = 0;
      if(p->autoEQPtrace){
        if(p->db) sqlite3_exec(p->db, "PRAGMA vdbe_trace=OFF;", 0, 0, 0);
        p->autoEQPtrace = 0;
      }
      if(strcmp(azArg[1],"full")==0){
        p->autoEQP = AUTOEQP_full;
      }else if(strcmp(azArg[1],"trigger")==0){
        p->autoEQP = AUTOEQP_trigger;
#ifdef SQLITE_DEBUG
      }else if(strcmp(azArg[1],"test")==0){
        p->autoEQP = AUTOEQP_on;
        p->autoEQPtest = 1;
      }else if(strcmp(azArg[1],"trace")==0){
        p->autoEQP = AUTOEQP_full;
        p->autoEQPtrace = 1;
        open_db(p, 0);
        sqlite3_exec(p->db, "SELECT name FROM sqlite_master LIMIT 1", 0, 0, 0);
        sqlite3_exec(p->db, "PRAGMA vdbe_trace=ON;", 0, 0, 0);
#endif
      }else{
        p->autoEQP = (u8)booleanValue(azArg[1]);
      }
    }else{
      raw_printf(stderr, "Usage: .eqp off|on|trace|trigger|full\n");
      rc = 1;
    }
  }else
  if(c=='e' && strncmp(azArg[0], "exit", n)==0){
    if(nArg>1 && (rc = (int)integerValue(azArg[1]))!=0) exit(rc);
    rc = 2;
  }else
  /* The ".explain" command is automatic now. It is largely pointless. It
  ** retained purely for backwards compatibility */
  if(c=='e' && strncmp(azArg[0], "explain", n)==0){
    int val = 1;
    if(nArg>=2){
      if(strcmp(azArg[1],"auto")==0){
        val = 99;
      }else{
        val = booleanValue(azArg[1]);
      }
    }
    if(val==1 && p->mode!=MODE_Explain){
      p->normalMode = p->mode;
      p->mode = MODE_Explain;
      p->autoExplain = 0;
    }else if(val==0){
      if(p->mode==MODE_Explain) p->mode = p->normalMode;
      p->autoExplain = 0;
    }else if(val==99){
      if(p->mode==MODE_Explain) p->mode = p->normalMode;
      p->autoExplain = 1;
    }
  }else
#ifndef SQLITE_OMIT_VIRTUALTABLE
  if(c=='e' && strncmp(azArg[0], "expert", n)==0){
    open_db(p, 0);
    expertDotCommand(p, azArg, nArg);
  }else
#endif
  if(c=='f' && strncmp(azArg[0], "filectrl", n)==0){
    static const struct {
       const char *zCtrlName; /* Name of a test-control option */
       int ctrlCode; /* Integer code for that option */
       const char *zUsage; /* Usage notes */
    } aCtrl[] = {
      { "size_limit", SQLITE_FCNTL_SIZE_LIMIT, "[LIMIT]" },
      { "chunk_size", SQLITE_FCNTL_CHUNK_SIZE, "SIZE" },
   /* { "win32_av_retry", SQLITE_FCNTL_WIN32_AV_RETRY, "COUNT DELAY" },*/
      { "persist_wal", SQLITE_FCNTL_PERSIST_WAL, "[BOOLEAN]" },
      { "psow", SQLITE_FCNTL_POWERSAFE_OVERWRITE, "[BOOLEAN]" },
   /* { "pragma", SQLITE_FCNTL_PRAGMA, "NAME ARG" },*/
      { "tempfilename", SQLITE_FCNTL_TEMPFILENAME, "" },
      { "has_moved", SQLITE_FCNTL_HAS_MOVED, "" },
      { "lock_timeout", SQLITE_FCNTL_LOCK_TIMEOUT, "MILLISEC" },
    };
    int filectrl = -1;
    int iCtrl = -1;
    sqlite3_int64 iRes = 0; /* Integer result to display if rc2==1 */
    int isOk = 0; /* 0: usage 1: %lld 2: no-result */
    int n2, i;
    const char *zCmd = 0;
    open_db(p, 0);
    zCmd = nArg>=2 ? azArg[1] : "help";
    /* The argument can optionally begin with "-" or "--" */
    if(zCmd[0]=='-' && zCmd[1]){
      zCmd++;
      if(zCmd[0]=='-' && zCmd[1]) zCmd++;
    }
    /* --help lists all file-controls */
    if(strcmp(zCmd,"help")==0){
      utf8_printf(p->out, "Available file-controls:\n");
      for(i=0; i<ArraySize(aCtrl); i++){
        utf8_printf(p->out, " .filectrl %s %s\n",
                    aCtrl[i].zCtrlName, aCtrl[i].zUsage);
      }
      rc = 1;
      goto meta_command_exit;
    }
    /* convert filectrl text option to value. allow any unique prefix
    ** of the option name, or a numerical value. */
    n2 = strlen30(zCmd);
    for(i=0; i<ArraySize(aCtrl); i++){
      if(strncmp(zCmd, aCtrl[i].zCtrlName, n2)==0){
        if(filectrl<0){
          filectrl = aCtrl[i].ctrlCode;
          iCtrl = i;
        }else{
          utf8_printf(stderr, "Error: ambiguous file-control: \"%s\"\n"
                              "Use \".filectrl --help\" for help\n", zCmd);
          rc = 1;
          goto meta_command_exit;
        }
      }
    }
    if(filectrl<0){
      utf8_printf(stderr,"Error: unknown file-control: %s\n"
                         "Use \".filectrl --help\" for help\n", zCmd);
    }else{
      switch(filectrl){
        case SQLITE_FCNTL_SIZE_LIMIT: {
          if(nArg!=2 && nArg!=3) break;
          iRes = nArg==3 ? integerValue(azArg[2]) : -1;
          sqlite3_file_control(p->db, 0, SQLITE_FCNTL_SIZE_LIMIT, &iRes);
          isOk = 1;
          break;
        }
        case SQLITE_FCNTL_LOCK_TIMEOUT:
        case SQLITE_FCNTL_CHUNK_SIZE: {
          int x;
          if(nArg!=3) break;
          x = (int)integerValue(azArg[2]);
          sqlite3_file_control(p->db, 0, filectrl, &x);
          isOk = 2;
          break;
        }
        case SQLITE_FCNTL_PERSIST_WAL:
        case SQLITE_FCNTL_POWERSAFE_OVERWRITE: {
          int x;
          if(nArg!=2 && nArg!=3) break;
          x = nArg==3 ? booleanValue(azArg[2]) : -1;
          sqlite3_file_control(p->db, 0, filectrl, &x);
          iRes = x;
          isOk = 1;
          break;
        }
        case SQLITE_FCNTL_HAS_MOVED: {
          int x;
          if(nArg!=2) break;
          sqlite3_file_control(p->db, 0, filectrl, &x);
          iRes = x;
          isOk = 1;
          break;
        }
        case SQLITE_FCNTL_TEMPFILENAME: {
          char *z = 0;
          if(nArg!=2) break;
          sqlite3_file_control(p->db, 0, filectrl, &z);
          if(z){
            utf8_printf(p->out, "%s\n", z);
            sqlite3_free(z);
          }
          isOk = 2;
          break;
        }
      }
    }
    if(isOk==0 && iCtrl>=0){
      utf8_printf(p->out, "Usage: .filectrl %s %s\n", zCmd,aCtrl[iCtrl].zUsage);
      rc = 1;
    }else if(isOk==1){
      char zBuf[100];
      sqlite3_snprintf(sizeof(zBuf), zBuf, "%lld", iRes);
      raw_printf(p->out, "%s\n", zBuf);
    }
  }else
  if(c=='f' && strncmp(azArg[0], "fullschema", n)==0){
    ShellState data;
    char *zErrMsg = 0;
    int doStats = 0;
    memcpy(&data, p, sizeof(data));
    data.showHeader = 0;
    data.cMode = data.mode = MODE_Semi;
    if(nArg==2 && optionMatch(azArg[1], "indent")){
      data.cMode = data.mode = MODE_Pretty;
      nArg = 1;
    }
    if(nArg!=1){
      raw_printf(stderr, "Usage: .fullschema ?--indent?\n");
      rc = 1;
      goto meta_command_exit;
    }
    open_db(p, 0);
    rc = sqlite3_exec(p->db,
       "SELECT sql FROM"
       " (SELECT sql sql, type type, tbl_name tbl_name, name name, rowid x"
       " FROM sqlite_master UNION ALL"
       " SELECT sql, type, tbl_name, name, rowid FROM sqlite_temp_master) "
       "WHERE type!='meta' AND sql NOTNULL AND name NOT LIKE 'sqlite_%' "
       "ORDER BY rowid",
       callback, &data, &zErrMsg
    );
    if(rc==SQLITE_OK){
      sqlite3_stmt *pStmt;
      rc = sqlite3_prepare_v2(p->db,
               "SELECT rowid FROM sqlite_master"
               " WHERE name GLOB 'sqlite_stat[134]'",
               -1, &pStmt, 0);
      doStats = sqlite3_step(pStmt)==SQLITE_ROW;
      sqlite3_finalize(pStmt);
    }
    if(doStats==0){
      raw_printf(p->out, "/* No STAT tables available */\n");
    }else{
      raw_printf(p->out, "ANALYZE sqlite_master;\n");
      sqlite3_exec(p->db, "SELECT 'ANALYZE sqlite_master'",
                   callback, &data, &zErrMsg);
      data.cMode = data.mode = MODE_Insert;
      data.zDestTable = "sqlite_stat1";
      shell_exec(&data, "SELECT * FROM sqlite_stat1", &zErrMsg);
      data.zDestTable = "sqlite_stat4";
      shell_exec(&data, "SELECT * FROM sqlite_stat4", &zErrMsg);
      raw_printf(p->out, "ANALYZE sqlite_master;\n");
    }
  }else
  if(c=='h' && strncmp(azArg[0], "headers", n)==0){
    if(nArg==2){
      p->showHeader = booleanValue(azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .headers on|off\n");
      rc = 1;
    }
  }else
  if(c=='h' && strncmp(azArg[0], "help", n)==0){
    if(nArg>=2){
      n = showHelp(p->out, azArg[1]);
      if(n==0){
        utf8_printf(p->out, "Nothing matches '%s'\n", azArg[1]);
      }
    }else{
      showHelp(p->out, 0);
    }
  }else
  if(c=='i' && strncmp(azArg[0], "import", n)==0){
    char *zTable; /* Insert data into this table */
    char *zFile; /* Name of file to extra content from */
    sqlite3_stmt *pStmt = NULL; /* A statement */
    int nCol; /* Number of columns in the table */
    int nByte; /* Number of bytes in an SQL string */
    int i, j; /* Loop counters */
    int needCommit; /* True to COMMIT or ROLLBACK at end */
    int nSep; /* Number of bytes in p->colSeparator[] */
    char *zSql; /* An SQL statement */
    ImportCtx sCtx; /* Reader context */
    char *(SQLITE_CDECL *xRead)(ImportCtx*); /* Func to read one value */
    int (SQLITE_CDECL *xCloser)(FILE*); /* Func to close file */
    if(nArg!=3){
      raw_printf(stderr, "Usage: .import FILE TABLE\n");
      goto meta_command_exit;
    }
    zFile = azArg[1];
    zTable = azArg[2];
    seenInterrupt = 0;
    memset(&sCtx, 0, sizeof(sCtx));
    open_db(p, 0);
    nSep = strlen30(p->colSeparator);
    if(nSep==0){
      raw_printf(stderr,
                 "Error: non-null column separator required for import\n");
      return 1;
    }
    if(nSep>1){
      raw_printf(stderr, "Error: multi-character column separators not allowed"
                      " for import\n");
      return 1;
    }
    nSep = strlen30(p->rowSeparator);
    if(nSep==0){
      raw_printf(stderr, "Error: non-null row separator required for import\n");
      return 1;
    }
    if(nSep==2 && p->mode==MODE_Csv && strcmp(p->rowSeparator, SEP_CrLf)==0){
      /* When importing CSV (only), if the row separator is set to the
      ** default output row separator, change it to the default input
      ** row separator. This avoids having to maintain different input
      ** and output row separators. */
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Row);
      nSep = strlen30(p->rowSeparator);
    }
    if(nSep>1){
      raw_printf(stderr, "Error: multi-character row separators not allowed"
                      " for import\n");
      return 1;
    }
    sCtx.zFile = zFile;
    sCtx.nLine = 1;
    if(sCtx.zFile[0]=='|'){
#ifdef SQLITE_OMIT_POPEN
      raw_printf(stderr, "Error: pipes are not supported in this OS\n");
      return 1;
#else
      sCtx.in = popen(sCtx.zFile+1, "r");
      sCtx.zFile = "<pipe>";
      xCloser = pclose;
#endif
    }else{
      sCtx.in = fopen(sCtx.zFile, "rb");
      xCloser = fclose;
    }
    if(p->mode==MODE_Ascii){
      xRead = ascii_read_one_field;
    }else{
      xRead = csv_read_one_field;
    }
    if(sCtx.in==0){
      utf8_printf(stderr, "Error: cannot open \"%s\"\n", zFile);
      return 1;
    }
    sCtx.cColSep = p->colSeparator[0];
    sCtx.cRowSep = p->rowSeparator[0];
    zSql = sqlite3_mprintf("SELECT * FROM %s", zTable);
    if(zSql==0){
      xCloser(sCtx.in);
      shell_out_of_memory();
    }
    nByte = strlen30(zSql);
    rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    import_append_char(&sCtx, 0); /* To ensure sCtx.z is allocated */
    if(rc && sqlite3_strglob("no such table: *", sqlite3_errmsg(p->db))==0){
      char *zCreate = sqlite3_mprintf("CREATE TABLE %s", zTable);
      char cSep = '(';
      while(xRead(&sCtx)){
        zCreate = sqlite3_mprintf("%z%c\n \"%w\" TEXT", zCreate, cSep, sCtx.z);
        cSep = ',';
        if(sCtx.cTerm!=sCtx.cColSep) break;
      }
      if(cSep=='('){
        sqlite3_free(zCreate);
        sqlite3_free(sCtx.z);
        xCloser(sCtx.in);
        utf8_printf(stderr,"%s: empty file\n", sCtx.zFile);
        return 1;
      }
      zCreate = sqlite3_mprintf("%z\n)", zCreate);
      rc = sqlite3_exec(p->db, zCreate, 0, 0, 0);
      sqlite3_free(zCreate);
      if(rc){
        utf8_printf(stderr, "CREATE TABLE %s(...) failed: %s\n", zTable,
                sqlite3_errmsg(p->db));
        sqlite3_free(sCtx.z);
        xCloser(sCtx.in);
        return 1;
      }
      rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    }
    sqlite3_free(zSql);
    if(rc){
      if (pStmt) sqlite3_finalize(pStmt);
      utf8_printf(stderr,"Error: %s\n", sqlite3_errmsg(p->db));
      xCloser(sCtx.in);
      return 1;
    }
    nCol = sqlite3_column_count(pStmt);
    sqlite3_finalize(pStmt);
    pStmt = 0;
    if(nCol==0) return 0; /* no columns, no error */
    zSql = sqlite3_malloc64(nByte*2 + 20 + nCol*2);
    if(zSql==0){
      xCloser(sCtx.in);
      shell_out_of_memory();
    }
    sqlite3_snprintf(nByte+20, zSql, "INSERT INTO \"%w\" VALUES(?", zTable);
    j = strlen30(zSql);
    for(i=1; i<nCol; i++){
      zSql[j++] = ',';
      zSql[j++] = '?';
    }
    zSql[j++] = ')';
    zSql[j] = 0;
    rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    sqlite3_free(zSql);
    if(rc){
      utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(p->db));
      if (pStmt) sqlite3_finalize(pStmt);
      xCloser(sCtx.in);
      return 1;
    }
    needCommit = sqlite3_get_autocommit(p->db);
    if(needCommit) sqlite3_exec(p->db, "BEGIN", 0, 0, 0);
    do{
      int startLine = sCtx.nLine;
      for(i=0; i<nCol; i++){
        char *z = xRead(&sCtx);
        /*
        ** Did we reach end-of-file before finding any columns?
        ** If so, stop instead of NULL filling the remaining columns.
        */
        if(z==0 && i==0) break;
        /*
        ** Did we reach end-of-file OR end-of-line before finding any
        ** columns in ASCII mode? If so, stop instead of NULL filling
        ** the remaining columns.
        */
        if(p->mode==MODE_Ascii && (z==0 || z[0]==0) && i==0) break;
        sqlite3_bind_text(pStmt, i+1, z, -1, SQLITE_TRANSIENT);
        if(i<nCol-1 && sCtx.cTerm!=sCtx.cColSep){
          utf8_printf(stderr, "%s:%d: expected %d columns but found %d - "
                          "filling the rest with NULL\n",
                          sCtx.zFile, startLine, nCol, i+1);
          i += 2;
          while(i<=nCol){ sqlite3_bind_null(pStmt, i); i++; }
        }
      }
      if(sCtx.cTerm==sCtx.cColSep){
        do{
          xRead(&sCtx);
          i++;
        }while(sCtx.cTerm==sCtx.cColSep);
        utf8_printf(stderr, "%s:%d: expected %d columns but found %d - "
                        "extras ignored\n",
                        sCtx.zFile, startLine, nCol, i);
      }
      if(i>=nCol){
        sqlite3_step(pStmt);
        rc = sqlite3_reset(pStmt);
        if(rc!=SQLITE_OK){
          utf8_printf(stderr, "%s:%d: INSERT failed: %s\n", sCtx.zFile,
                      startLine, sqlite3_errmsg(p->db));
        }
      }
    }while(sCtx.cTerm!=EOF);
    xCloser(sCtx.in);
    sqlite3_free(sCtx.z);
    sqlite3_finalize(pStmt);
    if(needCommit) sqlite3_exec(p->db, "COMMIT", 0, 0, 0);
  }else
#ifndef SQLITE_UNTESTABLE
  if(c=='i' && strncmp(azArg[0], "imposter", n)==0){
    char *zSql;
    char *zCollist = 0;
    sqlite3_stmt *pStmt;
    int tnum = 0;
    int isWO = 0; /* True if making an imposter of a WITHOUT ROWID table */
    int lenPK = 0; /* Length of the PRIMARY KEY string for isWO tables */
    int i;
    if(!(nArg==3 || (nArg==2 && sqlite3_stricmp(azArg[1],"off")==0))){
      utf8_printf(stderr, "Usage: .imposter INDEX IMPOSTER\n"
                          " .imposter off\n");
      /* Also allowed, but not documented:
      **
      ** .imposter TABLE IMPOSTER
      **
      ** where TABLE is a WITHOUT ROWID table. In that case, the
      ** imposter is another WITHOUT ROWID table with the columns in
      ** storage order. */
      rc = 1;
      goto meta_command_exit;
    }
    open_db(p, 0);
    if(nArg==2){
      sqlite3_test_control(SQLITE_TESTCTRL_IMPOSTER, p->db, "main", 0, 1);
      goto meta_command_exit;
    }
    zSql = sqlite3_mprintf(
      "SELECT rootpage, 0 FROM sqlite_master"
      " WHERE name='%q' AND type='index'"
      "UNION ALL "
      "SELECT rootpage, 1 FROM sqlite_master"
      " WHERE name='%q' AND type='table'"
      " AND sql LIKE '%%without%%rowid%%'",
      azArg[1], azArg[1]
    );
    sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    sqlite3_free(zSql);
    if(sqlite3_step(pStmt)==SQLITE_ROW){
      tnum = sqlite3_column_int(pStmt, 0);
      isWO = sqlite3_column_int(pStmt, 1);
    }
    sqlite3_finalize(pStmt);
    zSql = sqlite3_mprintf("PRAGMA index_xinfo='%q'", azArg[1]);
    rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    sqlite3_free(zSql);
    i = 0;
    while(sqlite3_step(pStmt)==SQLITE_ROW){
      char zLabel[20];
      const char *zCol = (const char*)sqlite3_column_text(pStmt,2);
      i++;
      if(zCol==0){
        if(sqlite3_column_int(pStmt,1)==-1){
          zCol = "_ROWID_";
        }else{
          sqlite3_snprintf(sizeof(zLabel),zLabel,"expr%d",i);
          zCol = zLabel;
        }
      }
      if(isWO && lenPK==0 && sqlite3_column_int(pStmt,5)==0 && zCollist){
        lenPK = (int)strlen(zCollist);
      }
      if(zCollist==0){
        zCollist = sqlite3_mprintf("\"%w\"", zCol);
      }else{
        zCollist = sqlite3_mprintf("%z,\"%w\"", zCollist, zCol);
      }
    }
    sqlite3_finalize(pStmt);
    if(i==0 || tnum==0){
      utf8_printf(stderr, "no such index: \"%s\"\n", azArg[1]);
      rc = 1;
      sqlite3_free(zCollist);
      goto meta_command_exit;
    }
    if(lenPK==0) lenPK = 100000;
    zSql = sqlite3_mprintf(
          "CREATE TABLE \"%w\"(%s,PRIMARY KEY(%.*s))WITHOUT ROWID",
          azArg[2], zCollist, lenPK, zCollist);
    sqlite3_free(zCollist);
    rc = sqlite3_test_control(SQLITE_TESTCTRL_IMPOSTER, p->db, "main", 1, tnum);
    if(rc==SQLITE_OK){
      rc = sqlite3_exec(p->db, zSql, 0, 0, 0);
      sqlite3_test_control(SQLITE_TESTCTRL_IMPOSTER, p->db, "main", 0, 0);
      if(rc){
        utf8_printf(stderr, "Error in [%s]: %s\n", zSql, sqlite3_errmsg(p->db));
      }else{
        utf8_printf(stdout, "%s;\n", zSql);
        raw_printf(stdout,
          "WARNING: writing to an imposter table will corrupt the \"%s\" %s!\n",
          azArg[1], isWO ? "table" : "index"
        );
      }
    }else{
      raw_printf(stderr, "SQLITE_TESTCTRL_IMPOSTER returns %d\n", rc);
      rc = 1;
    }
    sqlite3_free(zSql);
  }else
#endif /* !defined(SQLITE_OMIT_TEST_CONTROL) */
#ifdef SQLITE_ENABLE_IOTRACE
  if(c=='i' && strncmp(azArg[0], "iotrace", n)==0){
    SQLITE_API extern void (SQLITE_CDECL *sqlite3IoTrace)(const char*, ...);
    if(iotrace && iotrace!=stdout) fclose(iotrace);
    iotrace = 0;
    if(nArg<2){
      sqlite3IoTrace = 0;
    }else if(strcmp(azArg[1], "-")==0){
      sqlite3IoTrace = iotracePrintf;
      iotrace = stdout;
    }else{
      iotrace = fopen(azArg[1], "w");
      if(iotrace==0){
        utf8_printf(stderr, "Error: cannot open \"%s\"\n", azArg[1]);
        sqlite3IoTrace = 0;
        rc = 1;
      }else{
        sqlite3IoTrace = iotracePrintf;
      }
    }
  }else
#endif
  if(c=='l' && n>=5 && strncmp(azArg[0], "limits", n)==0){
    static const struct {
       const char *zLimitName; /* Name of a limit */
       int limitCode; /* Integer code for that limit */
    } aLimit[] = {
      { "length", SQLITE_LIMIT_LENGTH },
      { "sql_length", SQLITE_LIMIT_SQL_LENGTH },
      { "column", SQLITE_LIMIT_COLUMN },
      { "expr_depth", SQLITE_LIMIT_EXPR_DEPTH },
      { "compound_select", SQLITE_LIMIT_COMPOUND_SELECT },
      { "vdbe_op", SQLITE_LIMIT_VDBE_OP },
      { "function_arg", SQLITE_LIMIT_FUNCTION_ARG },
      { "attached", SQLITE_LIMIT_ATTACHED },
      { "like_pattern_length", SQLITE_LIMIT_LIKE_PATTERN_LENGTH },
      { "variable_number", SQLITE_LIMIT_VARIABLE_NUMBER },
      { "trigger_depth", SQLITE_LIMIT_TRIGGER_DEPTH },
      { "worker_threads", SQLITE_LIMIT_WORKER_THREADS },
    };
    int i, n2;
    open_db(p, 0);
    if(nArg==1){
      for(i=0; i<ArraySize(aLimit); i++){
        printf("%20s %d\n", aLimit[i].zLimitName,
               sqlite3_limit(p->db, aLimit[i].limitCode, -1));
      }
    }else if(nArg>3){
      raw_printf(stderr, "Usage: .limit NAME ?NEW-VALUE?\n");
      rc = 1;
      goto meta_command_exit;
    }else{
      int iLimit = -1;
      n2 = strlen30(azArg[1]);
      for(i=0; i<ArraySize(aLimit); i++){
        if(sqlite3_strnicmp(aLimit[i].zLimitName, azArg[1], n2)==0){
          if(iLimit<0){
            iLimit = i;
          }else{
            utf8_printf(stderr, "ambiguous limit: \"%s\"\n", azArg[1]);
            rc = 1;
            goto meta_command_exit;
          }
        }
      }
      if(iLimit<0){
        utf8_printf(stderr, "unknown limit: \"%s\"\n"
                        "enter \".limits\" with no arguments for a list.\n",
                         azArg[1]);
        rc = 1;
        goto meta_command_exit;
      }
      if(nArg==3){
        sqlite3_limit(p->db, aLimit[iLimit].limitCode,
                      (int)integerValue(azArg[2]));
      }
      printf("%20s %d\n", aLimit[iLimit].zLimitName,
             sqlite3_limit(p->db, aLimit[iLimit].limitCode, -1));
    }
  }else
  if(c=='l' && n>2 && strncmp(azArg[0], "lint", n)==0){
    open_db(p, 0);
    lintDotCommand(p, azArg, nArg);
  }else
#ifndef SQLITE_OMIT_LOAD_EXTENSION
  if(c=='l' && strncmp(azArg[0], "load", n)==0){
    const char *zFile, *zProc;
    char *zErrMsg = 0;
    if(nArg<2){
      raw_printf(stderr, "Usage: .load FILE ?ENTRYPOINT?\n");
      rc = 1;
      goto meta_command_exit;
    }
    zFile = azArg[1];
    zProc = nArg>=3 ? azArg[2] : 0;
    open_db(p, 0);
    rc = sqlite3_load_extension(p->db, zFile, zProc, &zErrMsg);
    if(rc!=SQLITE_OK){
      utf8_printf(stderr, "Error: %s\n", zErrMsg);
      sqlite3_free(zErrMsg);
      rc = 1;
    }
  }else
#endif
  if(c=='l' && strncmp(azArg[0], "log", n)==0){
    if(nArg!=2){
      raw_printf(stderr, "Usage: .log FILENAME\n");
      rc = 1;
    }else{
      const char *zFile = azArg[1];
      output_file_close(p->pLog);
      p->pLog = output_file_open(zFile, 0);
    }
  }else
  if(c=='m' && strncmp(azArg[0], "mode", n)==0){
    const char *zMode = nArg>=2 ? azArg[1] : "";
    int n2 = strlen30(zMode);
    int c2 = zMode[0];
    if(c2=='l' && n2>2 && strncmp(azArg[1],"lines",n2)==0){
      p->mode = MODE_Line;
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Row);
    }else if(c2=='c' && strncmp(azArg[1],"columns",n2)==0){
      p->mode = MODE_Column;
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Row);
    }else if(c2=='l' && n2>2 && strncmp(azArg[1],"list",n2)==0){
      p->mode = MODE_List;
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Column);
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Row);
    }else if(c2=='h' && strncmp(azArg[1],"html",n2)==0){
      p->mode = MODE_Html;
    }else if(c2=='t' && strncmp(azArg[1],"tcl",n2)==0){
      p->mode = MODE_Tcl;
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Space);
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Row);
    }else if(c2=='c' && strncmp(azArg[1],"csv",n2)==0){
      p->mode = MODE_Csv;
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Comma);
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_CrLf);
    }else if(c2=='t' && strncmp(azArg[1],"tabs",n2)==0){
      p->mode = MODE_List;
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Tab);
    }else if(c2=='i' && strncmp(azArg[1],"insert",n2)==0){
      p->mode = MODE_Insert;
      set_table_name(p, nArg>=3 ? azArg[2] : "table");
    }else if(c2=='q' && strncmp(azArg[1],"quote",n2)==0){
      p->mode = MODE_Quote;
    }else if(c2=='a' && strncmp(azArg[1],"ascii",n2)==0){
      p->mode = MODE_Ascii;
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Unit);
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_Record);
    }else if(nArg==1){
      raw_printf(p->out, "current output mode: %s\n", modeDescr[p->mode]);
    }else{
      raw_printf(stderr, "Error: mode should be one of: "
         "ascii column csv html insert line list quote tabs tcl\n");
      rc = 1;
    }
    p->cMode = p->mode;
  }else
  if(c=='n' && strncmp(azArg[0], "nullvalue", n)==0){
    if(nArg==2){
      sqlite3_snprintf(sizeof(p->nullValue), p->nullValue,
                       "%.*s", (int)ArraySize(p->nullValue)-1, azArg[1]);
    }else{
      raw_printf(stderr, "Usage: .nullvalue STRING\n");
      rc = 1;
    }
  }else
  if(c=='o' && strncmp(azArg[0], "open", n)==0 && n>=2){
    char *zNewFilename; /* Name of the database file to open */
    int iName = 1; /* Index in azArg[] of the filename */
    int newFlag = 0; /* True to delete file before opening */
    /* Close the existing database */
    session_close_all(p);
    close_db(p->db);
    p->db = 0;
    p->zDbFilename = 0;
    sqlite3_free(p->zFreeOnClose);
    p->zFreeOnClose = 0;
    p->openMode = SHELL_OPEN_UNSPEC;
    p->openFlags = 0;
    p->szMax = 0;
    /* Check for command-line arguments */
    for(iName=1; iName<nArg && azArg[iName][0]=='-'; iName++){
      const char *z = azArg[iName];
      if(optionMatch(z,"new")){
        newFlag = 1;
#ifdef SQLITE_HAVE_ZLIB
      }else if(optionMatch(z, "zip")){
        p->openMode = SHELL_OPEN_ZIPFILE;
#endif
      }else if(optionMatch(z, "append")){
        p->openMode = SHELL_OPEN_APPENDVFS;
      }else if(optionMatch(z, "readonly")){
        p->openMode = SHELL_OPEN_READONLY;
      }else if(optionMatch(z, "nofollow")){
        p->openFlags |= SQLITE_OPEN_NOFOLLOW;
#ifdef SQLITE_ENABLE_DESERIALIZE
      }else if(optionMatch(z, "deserialize")){
        p->openMode = SHELL_OPEN_DESERIALIZE;
      }else if(optionMatch(z, "hexdb")){
        p->openMode = SHELL_OPEN_HEXDB;
      }else if(optionMatch(z, "maxsize") && iName+1<nArg){
        p->szMax = integerValue(azArg[++iName]);
#endif /* SQLITE_ENABLE_DESERIALIZE */
      }else if(z[0]=='-'){
        utf8_printf(stderr, "unknown option: %s\n", z);
        rc = 1;
        goto meta_command_exit;
      }
    }
    /* If a filename is specified, try to open it first */
    zNewFilename = nArg>iName ? sqlite3_mprintf("%s", azArg[iName]) : 0;
    if(zNewFilename || p->openMode==SHELL_OPEN_HEXDB){
      if(newFlag) shellDeleteFile(zNewFilename);
      p->zDbFilename = zNewFilename;
      open_db(p, OPEN_DB_KEEPALIVE);
      if(p->db==0){
        utf8_printf(stderr, "Error: cannot open '%s'\n", zNewFilename);
        sqlite3_free(zNewFilename);
      }else{
        p->zFreeOnClose = zNewFilename;
      }
    }
    if(p->db==0){
      /* As a fall-back open a TEMP database */
      p->zDbFilename = 0;
      open_db(p, 0);
    }
  }else
  if((c=='o'
        && (strncmp(azArg[0], "output", n)==0||strncmp(azArg[0], "once", n)==0))
   || (c=='e' && n==5 && strcmp(azArg[0],"excel")==0)
  ){
    const char *zFile = nArg>=2 ? azArg[1] : "stdout";
    int bTxtMode = 0;
    if(azArg[0][0]=='e'){
      /* Transform the ".excel" command into ".once -x" */
      nArg = 2;
      azArg[0] = "once";
      zFile = azArg[1] = "-x";
      n = 4;
    }
    if(nArg>2){
      utf8_printf(stderr, "Usage: .%s [-e|-x|FILE]\n", azArg[0]);
      rc = 1;
      goto meta_command_exit;
    }
    if(n>1 && strncmp(azArg[0], "once", n)==0){
      if(nArg<2){
        raw_printf(stderr, "Usage: .once (-e|-x|FILE)\n");
        rc = 1;
        goto meta_command_exit;
      }
      p->outCount = 2;
    }else{
      p->outCount = 0;
    }
    output_reset(p);
    if(zFile[0]=='-' && zFile[1]=='-') zFile++;
#ifndef SQLITE_NOHAVE_SYSTEM
    if(strcmp(zFile, "-e")==0 || strcmp(zFile, "-x")==0){
      p->doXdgOpen = 1;
      outputModePush(p);
      if(zFile[1]=='x'){
        newTempFile(p, "csv");
        p->mode = MODE_Csv;
        sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator, SEP_Comma);
        sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator, SEP_CrLf);
      }else{
        newTempFile(p, "txt");
        bTxtMode = 1;
      }
      zFile = p->zTempFile;
    }
#endif /* SQLITE_NOHAVE_SYSTEM */
    if(zFile[0]=='|'){
#ifdef SQLITE_OMIT_POPEN
      raw_printf(stderr, "Error: pipes are not supported in this OS\n");
      rc = 1;
      p->out = stdout;
#else
      p->out = popen(zFile + 1, "w");
      if(p->out==0){
        utf8_printf(stderr,"Error: cannot open pipe \"%s\"\n", zFile + 1);
        p->out = stdout;
        rc = 1;
      }else{
        sqlite3_snprintf(sizeof(p->outfile), p->outfile, "%s", zFile);
      }
#endif
    }else{
      p->out = output_file_open(zFile, bTxtMode);
      if(p->out==0){
        if(strcmp(zFile,"off")!=0){
          utf8_printf(stderr,"Error: cannot write to \"%s\"\n", zFile);
        }
        p->out = stdout;
        rc = 1;
      } else {
        sqlite3_snprintf(sizeof(p->outfile), p->outfile, "%s", zFile);
      }
    }
  }else
  if(c=='p' && n>=3 && strncmp(azArg[0], "parameter", n)==0){
    open_db(p,0);
    if(nArg<=1) goto parameter_syntax_error;
    /* .parameter clear
    ** Clear all bind parameters by dropping the TEMP table that holds them.
    */
    if(nArg==2 && strcmp(azArg[1],"clear")==0){
      sqlite3_exec(p->db, "DROP TABLE IF EXISTS temp.sqlite_parameters;",
                   0, 0, 0);
    }else
    /* .parameter list
    ** List all bind parameters.
    */
    if(nArg==2 && strcmp(azArg[1],"list")==0){
      sqlite3_stmt *pStmt = 0;
      int rx;
      int len = 0;
      rx = sqlite3_prepare_v2(p->db,
             "SELECT max(length(key)) "
             "FROM temp.sqlite_parameters;", -1, &pStmt, 0);
      if(rx==SQLITE_OK && sqlite3_step(pStmt)==SQLITE_ROW){
        len = sqlite3_column_int(pStmt, 0);
        if(len>40) len = 40;
      }
      sqlite3_finalize(pStmt);
      pStmt = 0;
      if(len){
        rx = sqlite3_prepare_v2(p->db,
             "SELECT key, quote(value) "
             "FROM temp.sqlite_parameters;", -1, &pStmt, 0);
        while(sqlite3_step(pStmt)==SQLITE_ROW){
          utf8_printf(p->out, "%-*s %s\n", len, sqlite3_column_text(pStmt,0),
                      sqlite3_column_text(pStmt,1));
        }
        sqlite3_finalize(pStmt);
      }
    }else
    /* .parameter init
    ** Make sure the TEMP table used to hold bind parameters exists.
    ** Create it if necessary.
    */
    if(nArg==2 && strcmp(azArg[1],"init")==0){
      bind_table_init(p);
    }else
    /* .parameter set NAME VALUE
    ** Set or reset a bind parameter. NAME should be the full parameter
    ** name exactly as it appears in the query. (ex: $abc, @def). The
    ** VALUE can be in either SQL literal notation, or if not it will be
    ** understood to be a text string.
    */
    if(nArg==4 && strcmp(azArg[1],"set")==0){
      int rx;
      char *zSql;
      sqlite3_stmt *pStmt;
      const char *zKey = azArg[2];
      const char *zValue = azArg[3];
      bind_table_init(p);
      zSql = sqlite3_mprintf(
                  "REPLACE INTO temp.sqlite_parameters(key,value)"
                  "VALUES(%Q,%s);", zKey, zValue);
      if(zSql==0) shell_out_of_memory();
      pStmt = 0;
      rx = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
      sqlite3_free(zSql);
      if(rx!=SQLITE_OK){
        sqlite3_finalize(pStmt);
        pStmt = 0;
        zSql = sqlite3_mprintf(
                   "REPLACE INTO temp.sqlite_parameters(key,value)"
                   "VALUES(%Q,%Q);", zKey, zValue);
        if(zSql==0) shell_out_of_memory();
        rx = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
        sqlite3_free(zSql);
        if(rx!=SQLITE_OK){
          utf8_printf(p->out, "Error: %s\n", sqlite3_errmsg(p->db));
          sqlite3_finalize(pStmt);
          pStmt = 0;
          rc = 1;
        }
      }
      sqlite3_step(pStmt);
      sqlite3_finalize(pStmt);
    }else
    /* .parameter unset NAME
    ** Remove the NAME binding from the parameter binding table, if it
    ** exists.
    */
    if(nArg==3 && strcmp(azArg[1],"unset")==0){
      char *zSql = sqlite3_mprintf(
          "DELETE FROM temp.sqlite_parameters WHERE key=%Q", azArg[2]);
      if(zSql==0) shell_out_of_memory();
      sqlite3_exec(p->db, zSql, 0, 0, 0);
      sqlite3_free(zSql);
    }else
    /* If no command name matches, show a syntax error */
    parameter_syntax_error:
    showHelp(p->out, "parameter");
  }else
  if(c=='p' && n>=3 && strncmp(azArg[0], "print", n)==0){
    int i;
    for(i=1; i<nArg; i++){
      if(i>1) raw_printf(p->out, " ");
      utf8_printf(p->out, "%s", azArg[i]);
    }
    raw_printf(p->out, "\n");
  }else
#ifndef SQLITE_OMIT_PROGRESS_CALLBACK
  if(c=='p' && n>=3 && strncmp(azArg[0], "progress", n)==0){
    int i;
    int nn = 0;
    p->flgProgress = 0;
    p->mxProgress = 0;
    p->nProgress = 0;
    for(i=1; i<nArg; i++){
      const char *z = azArg[i];
      if(z[0]=='-'){
        z++;
        if(z[0]=='-') z++;
        if(strcmp(z,"quiet")==0 || strcmp(z,"q")==0){
          p->flgProgress |= SHELL_PROGRESS_QUIET;
          continue;
        }
        if(strcmp(z,"reset")==0){
          p->flgProgress |= SHELL_PROGRESS_RESET;
          continue;
        }
        if(strcmp(z,"once")==0){
          p->flgProgress |= SHELL_PROGRESS_ONCE;
          continue;
        }
        if(strcmp(z,"limit")==0){
          if(i+1>=nArg){
            utf8_printf(stderr, "Error: missing argument on --limit\n");
            rc = 1;
            goto meta_command_exit;
          }else{
            p->mxProgress = (int)integerValue(azArg[++i]);
          }
          continue;
        }
        utf8_printf(stderr, "Error: unknown option: \"%s\"\n", azArg[i]);
        rc = 1;
        goto meta_command_exit;
      }else{
        nn = (int)integerValue(z);
      }
    }
    open_db(p, 0);
    sqlite3_progress_handler(p->db, nn, progress_handler, p);
  }else
#endif /* SQLITE_OMIT_PROGRESS_CALLBACK */
  if(c=='p' && strncmp(azArg[0], "prompt", n)==0){
    if(nArg >= 2) {
      strncpy(mainPrompt,azArg[1],(int)ArraySize(mainPrompt)-1);
    }
    if(nArg >= 3) {
      strncpy(continuePrompt,azArg[2],(int)ArraySize(continuePrompt)-1);
    }
  }else
  if(c=='q' && strncmp(azArg[0], "quit", n)==0){
    rc = 2;
  }else
  if(c=='r' && n>=3 && strncmp(azArg[0], "read", n)==0){
    FILE *inSaved = p->in;
    int savedLineno = p->lineno;
    if(nArg!=2){
      raw_printf(stderr, "Usage: .read FILE\n");
      rc = 1;
      goto meta_command_exit;
    }
    p->in = fopen(azArg[1], "rb");
    if(p->in==0){
      utf8_printf(stderr,"Error: cannot open \"%s\"\n", azArg[1]);
      rc = 1;
    }else{
      rc = process_input(p);
      fclose(p->in);
    }
    p->in = inSaved;
    p->lineno = savedLineno;
  }else
  if(c=='r' && n>=3 && strncmp(azArg[0], "restore", n)==0){
    const char *zSrcFile;
    const char *zDb;
    sqlite3 *pSrc;
    sqlite3_backup *pBackup;
    int nTimeout = 0;
    if(nArg==2){
      zSrcFile = azArg[1];
      zDb = "main";
    }else if(nArg==3){
      zSrcFile = azArg[2];
      zDb = azArg[1];
    }else{
      raw_printf(stderr, "Usage: .restore ?DB? FILE\n");
      rc = 1;
      goto meta_command_exit;
    }
    rc = sqlite3_open(zSrcFile, &pSrc);
    if(rc!=SQLITE_OK){
      utf8_printf(stderr, "Error: cannot open \"%s\"\n", zSrcFile);
      close_db(pSrc);
      return 1;
    }
    open_db(p, 0);
    pBackup = sqlite3_backup_init(p->db, zDb, pSrc, "main");
    if(pBackup==0){
      utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(p->db));
      close_db(pSrc);
      return 1;
    }
    while((rc = sqlite3_backup_step(pBackup,100))==SQLITE_OK
          || rc==SQLITE_BUSY){
      if(rc==SQLITE_BUSY){
        if(nTimeout++ >= 3) break;
        sqlite3_sleep(100);
      }
    }
    sqlite3_backup_finish(pBackup);
    if(rc==SQLITE_DONE){
      rc = 0;
    }else if(rc==SQLITE_BUSY || rc==SQLITE_LOCKED){
      raw_printf(stderr, "Error: source database is busy\n");
      rc = 1;
    }else{
      utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(p->db));
      rc = 1;
    }
    close_db(pSrc);
  }else
  if(c=='s' && strncmp(azArg[0], "scanstats", n)==0){
    if(nArg==2){
      p->scanstatsOn = (u8)booleanValue(azArg[1]);
#ifndef SQLITE_ENABLE_STMT_SCANSTATUS
      raw_printf(stderr, "Warning: .scanstats not available in this build.\n");
#endif
    }else{
      raw_printf(stderr, "Usage: .scanstats on|off\n");
      rc = 1;
    }
  }else
  if(c=='s' && strncmp(azArg[0], "schema", n)==0){
    ShellText sSelect;
    ShellState data;
    char *zErrMsg = 0;
    const char *zDiv = "(";
    const char *zName = 0;
    int iSchema = 0;
    int bDebug = 0;
    int ii;
    open_db(p, 0);
    memcpy(&data, p, sizeof(data));
    data.showHeader = 0;
    data.cMode = data.mode = MODE_Semi;
    initText(&sSelect);
    for(ii=1; ii<nArg; ii++){
      if(optionMatch(azArg[ii],"indent")){
        data.cMode = data.mode = MODE_Pretty;
      }else if(optionMatch(azArg[ii],"debug")){
        bDebug = 1;
      }else if(zName==0){
        zName = azArg[ii];
      }else{
        raw_printf(stderr, "Usage: .schema ?--indent? ?LIKE-PATTERN?\n");
        rc = 1;
        goto meta_command_exit;
      }
    }
    if(zName!=0){
      int isMaster = sqlite3_strlike(zName, "sqlite_master", '\\')==0;
      if(isMaster || sqlite3_strlike(zName,"sqlite_temp_master", '\\')==0){
        char *new_argv[2], *new_colv[2];
        new_argv[0] = sqlite3_mprintf(
                      "CREATE TABLE %s (\n"
                      " type text,\n"
                      " name text,\n"
                      " tbl_name text,\n"
                      " rootpage integer,\n"
                      " sql text\n"
                      ")", isMaster ? "sqlite_master" : "sqlite_temp_master");
        new_argv[1] = 0;
        new_colv[0] = "sql";
        new_colv[1] = 0;
        callback(&data, 1, new_argv, new_colv);
        sqlite3_free(new_argv[0]);
      }
    }
    if(zDiv){
      sqlite3_stmt *pStmt = 0;
      rc = sqlite3_prepare_v2(p->db, "SELECT name FROM pragma_database_list",
                              -1, &pStmt, 0);
      if(rc){
        utf8_printf(stderr, "Error: %s\n", sqlite3_errmsg(p->db));
        sqlite3_finalize(pStmt);
        rc = 1;
        goto meta_command_exit;
      }
      appendText(&sSelect, "SELECT sql FROM", 0);
      iSchema = 0;
      while(sqlite3_step(pStmt)==SQLITE_ROW){
        const char *zDb = (const char*)sqlite3_column_text(pStmt, 0);
        char zScNum[30];
        sqlite3_snprintf(sizeof(zScNum), zScNum, "%d", ++iSchema);
        appendText(&sSelect, zDiv, 0);
        zDiv = " UNION ALL ";
        appendText(&sSelect, "SELECT shell_add_schema(sql,", 0);
        if(sqlite3_stricmp(zDb, "main")!=0){
          appendText(&sSelect, zDb, '\'');
        }else{
          appendText(&sSelect, "NULL", 0);
        }
        appendText(&sSelect, ",name) AS sql, type, tbl_name, name, rowid,", 0);
        appendText(&sSelect, zScNum, 0);
        appendText(&sSelect, " AS snum, ", 0);
        appendText(&sSelect, zDb, '\'');
        appendText(&sSelect, " AS sname FROM ", 0);
        appendText(&sSelect, zDb, quoteChar(zDb));
        appendText(&sSelect, ".sqlite_master", 0);
      }
      sqlite3_finalize(pStmt);
#ifndef SQLITE_OMIT_INTROSPECTION_PRAGMAS
      if(zName){
        appendText(&sSelect,
           " UNION ALL SELECT shell_module_schema(name),"
           " 'table', name, name, name, 9e+99, 'main' FROM pragma_module_list",
        0);
      }
#endif
      appendText(&sSelect, ") WHERE ", 0);
      if(zName){
        char *zQarg = sqlite3_mprintf("%Q", zName);
        int bGlob = strchr(zName, '*') != 0 || strchr(zName, '?') != 0 ||
                    strchr(zName, '[') != 0;
        if(strchr(zName, '.')){
          appendText(&sSelect, "lower(printf('%s.%s',sname,tbl_name))", 0);
        }else{
          appendText(&sSelect, "lower(tbl_name)", 0);
        }
        appendText(&sSelect, bGlob ? " GLOB " : " LIKE ", 0);
        appendText(&sSelect, zQarg, 0);
        if(!bGlob){
          appendText(&sSelect, " ESCAPE '\\' ", 0);
        }
        appendText(&sSelect, " AND ", 0);
        sqlite3_free(zQarg);
      }
      appendText(&sSelect, "type!='meta' AND sql IS NOT NULL"
                           " ORDER BY snum, rowid", 0);
      if(bDebug){
        utf8_printf(p->out, "SQL: %s;\n", sSelect.z);
      }else{
        rc = sqlite3_exec(p->db, sSelect.z, callback, &data, &zErrMsg);
      }
      freeText(&sSelect);
    }
    if(zErrMsg){
      utf8_printf(stderr,"Error: %s\n", zErrMsg);
      sqlite3_free(zErrMsg);
      rc = 1;
    }else if(rc != SQLITE_OK){
      raw_printf(stderr,"Error: querying schema information\n");
      rc = 1;
    }else{
      rc = 0;
    }
  }else
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_SELECTTRACE)
  if(c=='s' && n==11 && strncmp(azArg[0], "selecttrace", n)==0){
    sqlite3SelectTrace = (int)integerValue(azArg[1]);
  }else
#endif
#if defined(SQLITE_ENABLE_SESSION)
  if(c=='s' && strncmp(azArg[0],"session",n)==0 && n>=3){
    OpenSession *pSession = &p->aSession[0];
    char **azCmd = &azArg[1];
    int iSes = 0;
    int nCmd = nArg - 1;
    int i;
    if(nArg<=1) goto session_syntax_error;
    open_db(p, 0);
    if(nArg>=3){
      for(iSes=0; iSes<p->nSession; iSes++){
        if(strcmp(p->aSession[iSes].zName, azArg[1])==0) break;
      }
      if(iSes<p->nSession){
        pSession = &p->aSession[iSes];
        azCmd++;
        nCmd--;
      }else{
        pSession = &p->aSession[0];
        iSes = 0;
      }
    }
    /* .session attach TABLE
    ** Invoke the sqlite3session_attach() interface to attach a particular
    ** table so that it is never filtered.
    */
    if(strcmp(azCmd[0],"attach")==0){
      if(nCmd!=2) goto session_syntax_error;
      if(pSession->p==0){
        session_not_open:
        raw_printf(stderr, "ERROR: No sessions are open\n");
      }else{
        rc = sqlite3session_attach(pSession->p, azCmd[1]);
        if(rc){
          raw_printf(stderr, "ERROR: sqlite3session_attach() returns %d\n", rc);
          rc = 0;
        }
      }
    }else
    /* .session changeset FILE
    ** .session patchset FILE
    ** Write a changeset or patchset into a file. The file is overwritten.
    */
    if(strcmp(azCmd[0],"changeset")==0 || strcmp(azCmd[0],"patchset")==0){
      FILE *out = 0;
      if(nCmd!=2) goto session_syntax_error;
      if(pSession->p==0) goto session_not_open;
      out = fopen(azCmd[1], "wb");
      if(out==0){
        utf8_printf(stderr, "ERROR: cannot open \"%s\" for writing\n",
                    azCmd[1]);
      }else{
        int szChng;
        void *pChng;
        if(azCmd[0][0]=='c'){
          rc = sqlite3session_changeset(pSession->p, &szChng, &pChng);
        }else{
          rc = sqlite3session_patchset(pSession->p, &szChng, &pChng);
        }
        if(rc){
          printf("Error: error code %d\n", rc);
          rc = 0;
        }
        if(pChng
          && fwrite(pChng, szChng, 1, out)!=1){
          raw_printf(stderr, "ERROR: Failed to write entire %d-byte output\n",
                  szChng);
        }
        sqlite3_free(pChng);
        fclose(out);
      }
    }else
    /* .session close
    ** Close the identified session
    */
    if(strcmp(azCmd[0], "close")==0){
      if(nCmd!=1) goto session_syntax_error;
      if(p->nSession){
        session_close(pSession);
        p->aSession[iSes] = p->aSession[--p->nSession];
      }
    }else
    /* .session enable ?BOOLEAN?
    ** Query or set the enable flag
    */
    if(strcmp(azCmd[0], "enable")==0){
      int ii;
      if(nCmd>2) goto session_syntax_error;
      ii = nCmd==1 ? -1 : booleanValue(azCmd[1]);
      if(p->nSession){
        ii = sqlite3session_enable(pSession->p, ii);
        utf8_printf(p->out, "session %s enable flag = %d\n",
                    pSession->zName, ii);
      }
    }else
    /* .session filter GLOB ....
    ** Set a list of GLOB patterns of table names to be excluded.
    */
    if(strcmp(azCmd[0], "filter")==0){
      int ii, nByte;
      if(nCmd<2) goto session_syntax_error;
      if(p->nSession){
        for(ii=0; ii<pSession->nFilter; ii++){
          sqlite3_free(pSession->azFilter[ii]);
        }
        sqlite3_free(pSession->azFilter);
        nByte = sizeof(pSession->azFilter[0])*(nCmd-1);
        pSession->azFilter = sqlite3_malloc(nByte);
        if(pSession->azFilter==0){
          raw_printf(stderr, "Error: out or memory\n");
          exit(1);
        }
        for(ii=1; ii<nCmd; ii++){
          pSession->azFilter[ii-1] = sqlite3_mprintf("%s", azCmd[ii]);
        }
        pSession->nFilter = ii-1;
      }
    }else
    /* .session indirect ?BOOLEAN?
    ** Query or set the indirect flag
    */
    if(strcmp(azCmd[0], "indirect")==0){
      int ii;
      if(nCmd>2) goto session_syntax_error;
      ii = nCmd==1 ? -1 : booleanValue(azCmd[1]);
      if(p->nSession){
        ii = sqlite3session_indirect(pSession->p, ii);
        utf8_printf(p->out, "session %s indirect flag = %d\n",
                    pSession->zName, ii);
      }
    }else
    /* .session isempty
    ** Determine if the session is empty
    */
    if(strcmp(azCmd[0], "isempty")==0){
      int ii;
      if(nCmd!=1) goto session_syntax_error;
      if(p->nSession){
        ii = sqlite3session_isempty(pSession->p);
        utf8_printf(p->out, "session %s isempty flag = %d\n",
                    pSession->zName, ii);
      }
    }else
    /* .session list
    ** List all currently open sessions
    */
    if(strcmp(azCmd[0],"list")==0){
      for(i=0; i<p->nSession; i++){
        utf8_printf(p->out, "%d %s\n", i, p->aSession[i].zName);
      }
    }else
    /* .session open DB NAME
    ** Open a new session called NAME on the attached database DB.
    ** DB is normally "main".
    */
    if(strcmp(azCmd[0],"open")==0){
      char *zName;
      if(nCmd!=3) goto session_syntax_error;
      zName = azCmd[2];
      if(zName[0]==0) goto session_syntax_error;
      for(i=0; i<p->nSession; i++){
        if(strcmp(p->aSession[i].zName,zName)==0){
          utf8_printf(stderr, "Session \"%s\" already exists\n", zName);
          goto meta_command_exit;
        }
      }
      if(p->nSession>=ArraySize(p->aSession)){
        raw_printf(stderr, "Maximum of %d sessions\n", ArraySize(p->aSession));
        goto meta_command_exit;
      }
      pSession = &p->aSession[p->nSession];
      rc = sqlite3session_create(p->db, azCmd[1], &pSession->p);
      if(rc){
        raw_printf(stderr, "Cannot open session: error code=%d\n", rc);
        rc = 0;
        goto meta_command_exit;
      }
      pSession->nFilter = 0;
      sqlite3session_table_filter(pSession->p, session_filter, pSession);
      p->nSession++;
      pSession->zName = sqlite3_mprintf("%s", zName);
    }else
    /* If no command name matches, show a syntax error */
    session_syntax_error:
    showHelp(p->out, "session");
  }else
#endif
#ifdef SQLITE_DEBUG
  /* Undocumented commands for internal testing. Subject to change
  ** without notice. */
  if(c=='s' && n>=10 && strncmp(azArg[0], "selftest-", 9)==0){
    if(strncmp(azArg[0]+9, "boolean", n-9)==0){
      int i, v;
      for(i=1; i<nArg; i++){
        v = booleanValue(azArg[i]);
        utf8_printf(p->out, "%s: %d 0x%x\n", azArg[i], v, v);
      }
    }
    if(strncmp(azArg[0]+9, "integer", n-9)==0){
      int i; sqlite3_int64 v;
      for(i=1; i<nArg; i++){
        char zBuf[200];
        v = integerValue(azArg[i]);
        sqlite3_snprintf(sizeof(zBuf),zBuf,"%s: %lld 0x%llx\n", azArg[i],v,v);
        utf8_printf(p->out, "%s", zBuf);
      }
    }
  }else
#endif
  if(c=='s' && n>=4 && strncmp(azArg[0],"selftest",n)==0){
    int bIsInit = 0; /* True to initialize the SELFTEST table */
    int bVerbose = 0; /* Verbose output */
    int bSelftestExists; /* True if SELFTEST already exists */
    int i, k; /* Loop counters */
    int nTest = 0; /* Number of tests runs */
    int nErr = 0; /* Number of errors seen */
    ShellText str; /* Answer for a query */
    sqlite3_stmt *pStmt = 0; /* Query against the SELFTEST table */
    open_db(p,0);
    for(i=1; i<nArg; i++){
      const char *z = azArg[i];
      if(z[0]=='-' && z[1]=='-') z++;
      if(strcmp(z,"-init")==0){
        bIsInit = 1;
      }else
      if(strcmp(z,"-v")==0){
        bVerbose++;
      }else
      {
        utf8_printf(stderr, "Unknown option \"%s\" on \"%s\"\n",
                    azArg[i], azArg[0]);
        raw_printf(stderr, "Should be one of: --init -v\n");
        rc = 1;
        goto meta_command_exit;
      }
    }
    if(sqlite3_table_column_metadata(p->db,"main","selftest",0,0,0,0,0,0)
           != SQLITE_OK){
      bSelftestExists = 0;
    }else{
      bSelftestExists = 1;
    }
    if(bIsInit){
      createSelftestTable(p);
      bSelftestExists = 1;
    }
    initText(&str);
    appendText(&str, "x", 0);
    for(k=bSelftestExists; k>=0; k--){
      if(k==1){
        rc = sqlite3_prepare_v2(p->db,
            "SELECT tno,op,cmd,ans FROM selftest ORDER BY tno",
            -1, &pStmt, 0);
      }else{
        rc = sqlite3_prepare_v2(p->db,
          "VALUES(0,'memo','Missing SELFTEST table - default checks only',''),"
          " (1,'run','PRAGMA integrity_check','ok')",
          -1, &pStmt, 0);
      }
      if(rc){
        raw_printf(stderr, "Error querying the selftest table\n");
        rc = 1;
        sqlite3_finalize(pStmt);
        goto meta_command_exit;
      }
      for(i=1; sqlite3_step(pStmt)==SQLITE_ROW; i++){
        int tno = sqlite3_column_int(pStmt, 0);
        const char *zOp = (const char*)sqlite3_column_text(pStmt, 1);
        const char *zSql = (const char*)sqlite3_column_text(pStmt, 2);
        const char *zAns = (const char*)sqlite3_column_text(pStmt, 3);
        k = 0;
        if(bVerbose>0){
          char *zQuote = sqlite3_mprintf("%q", zSql);
          printf("%d: %s %s\n", tno, zOp, zSql);
          sqlite3_free(zQuote);
        }
        if(strcmp(zOp,"memo")==0){
          utf8_printf(p->out, "%s\n", zSql);
        }else
        if(strcmp(zOp,"run")==0){
          char *zErrMsg = 0;
          str.n = 0;
          str.z[0] = 0;
          rc = sqlite3_exec(p->db, zSql, captureOutputCallback, &str, &zErrMsg);
          nTest++;
          if(bVerbose){
            utf8_printf(p->out, "Result: %s\n", str.z);
          }
          if(rc || zErrMsg){
            nErr++;
            rc = 1;
            utf8_printf(p->out, "%d: error-code-%d: %s\n", tno, rc, zErrMsg);
            sqlite3_free(zErrMsg);
          }else if(strcmp(zAns,str.z)!=0){
            nErr++;
            rc = 1;
            utf8_printf(p->out, "%d: Expected: [%s]\n", tno, zAns);
            utf8_printf(p->out, "%d: Got: [%s]\n", tno, str.z);
          }
        }else
        {
          utf8_printf(stderr,
            "Unknown operation \"%s\" on selftest line %d\n", zOp, tno);
          rc = 1;
          break;
        }
      } /* End loop over rows of content from SELFTEST */
      sqlite3_finalize(pStmt);
    } /* End loop over k */
    freeText(&str);
    utf8_printf(p->out, "%d errors out of %d tests\n", nErr, nTest);
  }else
  if(c=='s' && strncmp(azArg[0], "separator", n)==0){
    if(nArg<2 || nArg>3){
      raw_printf(stderr, "Usage: .separator COL ?ROW?\n");
      rc = 1;
    }
    if(nArg>=2){
      sqlite3_snprintf(sizeof(p->colSeparator), p->colSeparator,
                       "%.*s", (int)ArraySize(p->colSeparator)-1, azArg[1]);
    }
    if(nArg>=3){
      sqlite3_snprintf(sizeof(p->rowSeparator), p->rowSeparator,
                       "%.*s", (int)ArraySize(p->rowSeparator)-1, azArg[2]);
    }
  }else
  if(c=='s' && n>=4 && strncmp(azArg[0],"sha3sum",n)==0){
    const char *zLike = 0; /* Which table to checksum. 0 means everything */
    int i; /* Loop counter */
    int bSchema = 0; /* Also hash the schema */
    int bSeparate = 0; /* Hash each table separately */
    int iSize = 224; /* Hash algorithm to use */
    int bDebug = 0; /* Only show the query that would have run */
    sqlite3_stmt *pStmt; /* For querying tables names */
    char *zSql; /* SQL to be run */
    char *zSep; /* Separator */
    ShellText sSql; /* Complete SQL for the query to run the hash */
    ShellText sQuery; /* Set of queries used to read all content */
    open_db(p, 0);
    for(i=1; i<nArg; i++){
      const char *z = azArg[i];
      if(z[0]=='-'){
        z++;
        if(z[0]=='-') z++;
        if(strcmp(z,"schema")==0){
          bSchema = 1;
        }else
        if(strcmp(z,"sha3-224")==0 || strcmp(z,"sha3-256")==0
         || strcmp(z,"sha3-384")==0 || strcmp(z,"sha3-512")==0
        ){
          iSize = atoi(&z[5]);
        }else
        if(strcmp(z,"debug")==0){
          bDebug = 1;
        }else
        {
          utf8_printf(stderr, "Unknown option \"%s\" on \"%s\"\n",
                      azArg[i], azArg[0]);
          showHelp(p->out, azArg[0]);
          rc = 1;
          goto meta_command_exit;
        }
      }else if(zLike){
        raw_printf(stderr, "Usage: .sha3sum ?OPTIONS? ?LIKE-PATTERN?\n");
        rc = 1;
        goto meta_command_exit;
      }else{
        zLike = z;
        bSeparate = 1;
        if(sqlite3_strlike("sqlite\\_%", zLike, '\\')==0) bSchema = 1;
      }
    }
    if(bSchema){
      zSql = "SELECT lower(name) FROM sqlite_master"
             " WHERE type='table' AND coalesce(rootpage,0)>1"
             " UNION ALL SELECT 'sqlite_master'"
             " ORDER BY 1 collate nocase";
    }else{
      zSql = "SELECT lower(name) FROM sqlite_master"
             " WHERE type='table' AND coalesce(rootpage,0)>1"
             " AND name NOT LIKE 'sqlite_%'"
             " ORDER BY 1 collate nocase";
    }
    sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    initText(&sQuery);
    initText(&sSql);
    appendText(&sSql, "WITH [sha3sum$query](a,b) AS(",0);
    zSep = "VALUES(";
    while(SQLITE_ROW==sqlite3_step(pStmt)){
      const char *zTab = (const char*)sqlite3_column_text(pStmt,0);
      if(zLike && sqlite3_strlike(zLike, zTab, 0)!=0) continue;
      if(strncmp(zTab, "sqlite_",7)!=0){
        appendText(&sQuery,"SELECT * FROM ", 0);
        appendText(&sQuery,zTab,'"');
        appendText(&sQuery," NOT INDEXED;", 0);
      }else if(strcmp(zTab, "sqlite_master")==0){
        appendText(&sQuery,"SELECT type,name,tbl_name,sql FROM sqlite_master"
                           " ORDER BY name;", 0);
      }else if(strcmp(zTab, "sqlite_sequence")==0){
        appendText(&sQuery,"SELECT name,seq FROM sqlite_sequence"
                           " ORDER BY name;", 0);
      }else if(strcmp(zTab, "sqlite_stat1")==0){
        appendText(&sQuery,"SELECT tbl,idx,stat FROM sqlite_stat1"
                           " ORDER BY tbl,idx;", 0);
      }else if(strcmp(zTab, "sqlite_stat4")==0){
        appendText(&sQuery, "SELECT * FROM ", 0);
        appendText(&sQuery, zTab, 0);
        appendText(&sQuery, " ORDER BY tbl, idx, rowid;\n", 0);
      }
      appendText(&sSql, zSep, 0);
      appendText(&sSql, sQuery.z, '\'');
      sQuery.n = 0;
      appendText(&sSql, ",", 0);
      appendText(&sSql, zTab, '\'');
      zSep = "),(";
    }
    sqlite3_finalize(pStmt);
    if(bSeparate){
      zSql = sqlite3_mprintf(
          "%s))"
          " SELECT lower(hex(sha3_query(a,%d))) AS hash, b AS label"
          " FROM [sha3sum$query]",
          sSql.z, iSize);
    }else{
      zSql = sqlite3_mprintf(
          "%s))"
          " SELECT lower(hex(sha3_query(group_concat(a,''),%d))) AS hash"
          " FROM [sha3sum$query]",
          sSql.z, iSize);
    }
    freeText(&sQuery);
    freeText(&sSql);
    if(bDebug){
      utf8_printf(p->out, "%s\n", zSql);
    }else{
      shell_exec(p, zSql, 0);
    }
    sqlite3_free(zSql);
  }else
#ifndef SQLITE_NOHAVE_SYSTEM
  if(c=='s'
   && (strncmp(azArg[0], "shell", n)==0 || strncmp(azArg[0],"system",n)==0)
  ){
    char *zCmd;
    int i, x;
    if(nArg<2){
      raw_printf(stderr, "Usage: .system COMMAND\n");
      rc = 1;
      goto meta_command_exit;
    }
    zCmd = sqlite3_mprintf(strchr(azArg[1],' ')==0?"%s":"\"%s\"", azArg[1]);
    for(i=2; i<nArg; i++){
      zCmd = sqlite3_mprintf(strchr(azArg[i],' ')==0?"%z %s":"%z \"%s\"",
                             zCmd, azArg[i]);
    }
    x = system(zCmd);
    sqlite3_free(zCmd);
    if(x) raw_printf(stderr, "System command returns %d\n", x);
  }else
#endif /* !defined(SQLITE_NOHAVE_SYSTEM) */
  if(c=='s' && strncmp(azArg[0], "show", n)==0){
    static const char *azBool[] = { "off", "on", "trigger", "full"};
    int i;
    if(nArg!=1){
      raw_printf(stderr, "Usage: .show\n");
      rc = 1;
      goto meta_command_exit;
    }
    utf8_printf(p->out, "%12.12s: %s\n","echo",
                                  azBool[ShellHasFlag(p, SHFLG_Echo)]);
    utf8_printf(p->out, "%12.12s: %s\n","eqp", azBool[p->autoEQP&3]);
    utf8_printf(p->out, "%12.12s: %s\n","explain",
         p->mode==MODE_Explain ? "on" : p->autoExplain ? "auto" : "off");
    utf8_printf(p->out,"%12.12s: %s\n","headers", azBool[p->showHeader!=0]);
    utf8_printf(p->out, "%12.12s: %s\n","mode", modeDescr[p->mode]);
    utf8_printf(p->out, "%12.12s: ", "nullvalue");
      output_c_string(p->out, p->nullValue);
      raw_printf(p->out, "\n");
    utf8_printf(p->out,"%12.12s: %s\n","output",
            strlen30(p->outfile) ? p->outfile : "stdout");
    utf8_printf(p->out,"%12.12s: ", "colseparator");
      output_c_string(p->out, p->colSeparator);
      raw_printf(p->out, "\n");
    utf8_printf(p->out,"%12.12s: ", "rowseparator");
      output_c_string(p->out, p->rowSeparator);
      raw_printf(p->out, "\n");
    utf8_printf(p->out, "%12.12s: %s\n","stats", azBool[p->statsOn!=0]);
    utf8_printf(p->out, "%12.12s: ", "width");
    for (i=0;i<(int)ArraySize(p->colWidth) && p->colWidth[i] != 0;i++) {
      raw_printf(p->out, "%d ", p->colWidth[i]);
    }
    raw_printf(p->out, "\n");
    utf8_printf(p->out, "%12.12s: %s\n", "filename",
                p->zDbFilename ? p->zDbFilename : "");
  }else
  if(c=='s' && strncmp(azArg[0], "stats", n)==0){
    if(nArg==2){
      p->statsOn = (u8)booleanValue(azArg[1]);
    }else if(nArg==1){
      display_stats(p->db, p, 0);
    }else{
      raw_printf(stderr, "Usage: .stats ?on|off?\n");
      rc = 1;
    }
  }else
  if((c=='t' && n>1 && strncmp(azArg[0], "tables", n)==0)
   || (c=='i' && (strncmp(azArg[0], "indices", n)==0
                 || strncmp(azArg[0], "indexes", n)==0))
  ){
    sqlite3_stmt *pStmt;
    char **azResult;
    int nRow, nAlloc;
    int ii;
    ShellText s;
    initText(&s);
    open_db(p, 0);
    rc = sqlite3_prepare_v2(p->db, "PRAGMA database_list", -1, &pStmt, 0);
    if(rc){
      sqlite3_finalize(pStmt);
      return shellDatabaseError(p->db);
    }
    if(nArg>2 && c=='i'){
      /* It is an historical accident that the .indexes command shows an error
      ** when called with the wrong number of arguments whereas the .tables
      ** command does not. */
      raw_printf(stderr, "Usage: .indexes ?LIKE-PATTERN?\n");
      rc = 1;
      sqlite3_finalize(pStmt);
      goto meta_command_exit;
    }
    for(ii=0; sqlite3_step(pStmt)==SQLITE_ROW; ii++){
      const char *zDbName = (const char*)sqlite3_column_text(pStmt, 1);
      if(zDbName==0) continue;
      if(s.z && s.z[0]) appendText(&s, " UNION ALL ", 0);
      if(sqlite3_stricmp(zDbName, "main")==0){
        appendText(&s, "SELECT name FROM ", 0);
      }else{
        appendText(&s, "SELECT ", 0);
        appendText(&s, zDbName, '\'');
        appendText(&s, "||'.'||name FROM ", 0);
      }
      appendText(&s, zDbName, '"');
      appendText(&s, ".sqlite_master ", 0);
      if(c=='t'){
        appendText(&s," WHERE type IN ('table','view')"
                      " AND name NOT LIKE 'sqlite_%'"
                      " AND name LIKE ?1", 0);
      }else{
        appendText(&s," WHERE type='index'"
                      " AND tbl_name LIKE ?1", 0);
      }
    }
    rc = sqlite3_finalize(pStmt);
    appendText(&s, " ORDER BY 1", 0);
    rc = sqlite3_prepare_v2(p->db, s.z, -1, &pStmt, 0);
    freeText(&s);
    if(rc) return shellDatabaseError(p->db);
    /* Run the SQL statement prepared by the above block. Store the results
    ** as an array of nul-terminated strings in azResult[]. */
    nRow = nAlloc = 0;
    azResult = 0;
    if(nArg>1){
      sqlite3_bind_text(pStmt, 1, azArg[1], -1, SQLITE_TRANSIENT);
    }else{
      sqlite3_bind_text(pStmt, 1, "%", -1, SQLITE_STATIC);
    }
    while(sqlite3_step(pStmt)==SQLITE_ROW){
      if(nRow>=nAlloc){
        char **azNew;
        int n2 = nAlloc*2 + 10;
        azNew = sqlite3_realloc64(azResult, sizeof(azResult[0])*n2);
        if(azNew==0) shell_out_of_memory();
        nAlloc = n2;
        azResult = azNew;
      }
      azResult[nRow] = sqlite3_mprintf("%s", sqlite3_column_text(pStmt, 0));
      if(0==azResult[nRow]) shell_out_of_memory();
      nRow++;
    }
    if(sqlite3_finalize(pStmt)!=SQLITE_OK){
      rc = shellDatabaseError(p->db);
    }
    /* Pretty-print the contents of array azResult[] to the output */
    if(rc==0 && nRow>0){
      int len, maxlen = 0;
      int i, j;
      int nPrintCol, nPrintRow;
      for(i=0; i<nRow; i++){
        len = strlen30(azResult[i]);
        if(len>maxlen) maxlen = len;
      }
      nPrintCol = 80/(maxlen+2);
      if(nPrintCol<1) nPrintCol = 1;
      nPrintRow = (nRow + nPrintCol - 1)/nPrintCol;
      for(i=0; i<nPrintRow; i++){
        for(j=i; j<nRow; j+=nPrintRow){
          char *zSp = j<nPrintRow ? "" : " ";
          utf8_printf(p->out, "%s%-*s", zSp, maxlen,
                      azResult[j] ? azResult[j]:"");
        }
        raw_printf(p->out, "\n");
      }
    }
    for(ii=0; ii<nRow; ii++) sqlite3_free(azResult[ii]);
    sqlite3_free(azResult);
  }else
  /* Begin redirecting output to the file "testcase-out.txt" */
  if(c=='t' && strcmp(azArg[0],"testcase")==0){
    output_reset(p);
    p->out = output_file_open("testcase-out.txt", 0);
    if(p->out==0){
      raw_printf(stderr, "Error: cannot open 'testcase-out.txt'\n");
    }
    if(nArg>=2){
      sqlite3_snprintf(sizeof(p->zTestcase), p->zTestcase, "%s", azArg[1]);
    }else{
      sqlite3_snprintf(sizeof(p->zTestcase), p->zTestcase, "?");
    }
  }else
#ifndef SQLITE_UNTESTABLE
  if(c=='t' && n>=8 && strncmp(azArg[0], "testctrl", n)==0){
    static const struct {
       const char *zCtrlName; /* Name of a test-control option */
       int ctrlCode; /* Integer code for that option */
       const char *zUsage; /* Usage notes */
    } aCtrl[] = {
      { "always", SQLITE_TESTCTRL_ALWAYS, "BOOLEAN" },
      { "assert", SQLITE_TESTCTRL_ASSERT, "BOOLEAN" },
    /*{ "benign_malloc_hooks",SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS, "" },*/
    /*{ "bitvec_test", SQLITE_TESTCTRL_BITVEC_TEST, "" },*/
      { "byteorder", SQLITE_TESTCTRL_BYTEORDER, "" },
      { "extra_schema_checks",SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS,"BOOLEAN" },
    /*{ "fault_install", SQLITE_TESTCTRL_FAULT_INSTALL, "" },*/
      { "imposter", SQLITE_TESTCTRL_IMPOSTER, "SCHEMA ON/OFF ROOTPAGE"},
      { "internal_functions", SQLITE_TESTCTRL_INTERNAL_FUNCTIONS, "" },
      { "localtime_fault", SQLITE_TESTCTRL_LOCALTIME_FAULT,"BOOLEAN" },
      { "never_corrupt", SQLITE_TESTCTRL_NEVER_CORRUPT, "BOOLEAN" },
      { "optimizations", SQLITE_TESTCTRL_OPTIMIZATIONS, "DISABLE-MASK" },
#ifdef YYCOVERAGE
      { "parser_coverage", SQLITE_TESTCTRL_PARSER_COVERAGE, "" },
#endif
      { "pending_byte", SQLITE_TESTCTRL_PENDING_BYTE, "OFFSET " },
      { "prng_restore", SQLITE_TESTCTRL_PRNG_RESTORE, "" },
      { "prng_save", SQLITE_TESTCTRL_PRNG_SAVE, "" },
      { "prng_seed", SQLITE_TESTCTRL_PRNG_SEED, "SEED ?db?" },
      { "reserve", SQLITE_TESTCTRL_RESERVE, "BYTES-OF-RESERVE"},
    };
    int testctrl = -1;
    int iCtrl = -1;
    int rc2 = 0; /* 0: usage. 1: %d 2: %x 3: no-output */
    int isOk = 0;
    int i, n2;
    const char *zCmd = 0;
    open_db(p, 0);
    zCmd = nArg>=2 ? azArg[1] : "help";
    /* The argument can optionally begin with "-" or "--" */
    if(zCmd[0]=='-' && zCmd[1]){
      zCmd++;
      if(zCmd[0]=='-' && zCmd[1]) zCmd++;
    }
    /* --help lists all test-controls */
    if(strcmp(zCmd,"help")==0){
      utf8_printf(p->out, "Available test-controls:\n");
      for(i=0; i<ArraySize(aCtrl); i++){
        utf8_printf(p->out, " .testctrl %s %s\n",
                    aCtrl[i].zCtrlName, aCtrl[i].zUsage);
      }
      rc = 1;
      goto meta_command_exit;
    }
    /* convert testctrl text option to value. allow any unique prefix
    ** of the option name, or a numerical value. */
    n2 = strlen30(zCmd);
    for(i=0; i<ArraySize(aCtrl); i++){
      if(strncmp(zCmd, aCtrl[i].zCtrlName, n2)==0){
        if(testctrl<0){
          testctrl = aCtrl[i].ctrlCode;
          iCtrl = i;
        }else{
          utf8_printf(stderr, "Error: ambiguous test-control: \"%s\"\n"
                              "Use \".testctrl --help\" for help\n", zCmd);
          rc = 1;
          goto meta_command_exit;
        }
      }
    }
    if(testctrl<0){
      utf8_printf(stderr,"Error: unknown test-control: %s\n"
                         "Use \".testctrl --help\" for help\n", zCmd);
    }else{
      switch(testctrl){
        /* sqlite3_test_control(int, db, int) */
        case SQLITE_TESTCTRL_OPTIMIZATIONS:
        case SQLITE_TESTCTRL_RESERVE:
          if(nArg==3){
            int opt = (int)strtol(azArg[2], 0, 0);
            rc2 = sqlite3_test_control(testctrl, p->db, opt);
            isOk = 3;
          }
          break;
        /* sqlite3_test_control(int) */
        case SQLITE_TESTCTRL_PRNG_SAVE:
        case SQLITE_TESTCTRL_PRNG_RESTORE:
        case SQLITE_TESTCTRL_PRNG_RESET:
        case SQLITE_TESTCTRL_BYTEORDER:
          if(nArg==2){
            rc2 = sqlite3_test_control(testctrl);
            isOk = testctrl==SQLITE_TESTCTRL_BYTEORDER ? 1 : 3;
          }
          break;
        /* sqlite3_test_control(int, uint) */
        case SQLITE_TESTCTRL_PENDING_BYTE:
          if(nArg==3){
            unsigned int opt = (unsigned int)integerValue(azArg[2]);
            rc2 = sqlite3_test_control(testctrl, opt);
            isOk = 3;
          }
          break;
        /* sqlite3_test_control(int, int, sqlite3*) */
        case SQLITE_TESTCTRL_PRNG_SEED:
          if(nArg==3 || nArg==4){
            int ii = (int)integerValue(azArg[2]);
            sqlite3 *db;
            if(ii==0 && strcmp(azArg[2],"random")==0){
              sqlite3_randomness(sizeof(ii),&ii);
              printf("-- random seed: %d\n", ii);
            }
            if(nArg==3){
              db = 0;
            }else{
              db = p->db;
              /* Make sure the schema has been loaded */
              sqlite3_table_column_metadata(db, 0, "x", 0, 0, 0, 0, 0, 0);
            }
            rc2 = sqlite3_test_control(testctrl, ii, db);
            isOk = 3;
          }
          break;
        /* sqlite3_test_control(int, int) */
        case SQLITE_TESTCTRL_ASSERT:
        case SQLITE_TESTCTRL_ALWAYS:
          if(nArg==3){
            int opt = booleanValue(azArg[2]);
            rc2 = sqlite3_test_control(testctrl, opt);
            isOk = 1;
          }
          break;
        /* sqlite3_test_control(int, int) */
        case SQLITE_TESTCTRL_LOCALTIME_FAULT:
        case SQLITE_TESTCTRL_NEVER_CORRUPT:
          if(nArg==3){
            int opt = booleanValue(azArg[2]);
            rc2 = sqlite3_test_control(testctrl, opt);
            isOk = 3;
          }
          break;
        /* sqlite3_test_control(sqlite3*) */
        case SQLITE_TESTCTRL_INTERNAL_FUNCTIONS:
          rc2 = sqlite3_test_control(testctrl, p->db);
          isOk = 3;
          break;
        case SQLITE_TESTCTRL_IMPOSTER:
          if(nArg==5){
            rc2 = sqlite3_test_control(testctrl, p->db,
                          azArg[2],
                          integerValue(azArg[3]),
                          integerValue(azArg[4]));
            isOk = 3;
          }
          break;
#ifdef YYCOVERAGE
        case SQLITE_TESTCTRL_PARSER_COVERAGE:
          if(nArg==2){
            sqlite3_test_control(testctrl, p->out);
            isOk = 3;
          }
#endif
      }
    }
    if(isOk==0 && iCtrl>=0){
      utf8_printf(p->out, "Usage: .testctrl %s %s\n", zCmd,aCtrl[iCtrl].zUsage);
      rc = 1;
    }else if(isOk==1){
      raw_printf(p->out, "%d\n", rc2);
    }else if(isOk==2){
      raw_printf(p->out, "0x%08x\n", rc2);
    }
  }else
#endif /* !defined(SQLITE_UNTESTABLE) */
  if(c=='t' && n>4 && strncmp(azArg[0], "timeout", n)==0){
    open_db(p, 0);
    sqlite3_busy_timeout(p->db, nArg>=2 ? (int)integerValue(azArg[1]) : 0);
  }else
  if(c=='t' && n>=5 && strncmp(azArg[0], "timer", n)==0){
    if(nArg==2){
      enableTimer = booleanValue(azArg[1]);
      if(enableTimer && !HAS_TIMER){
        raw_printf(stderr, "Error: timer not available on this system.\n");
        enableTimer = 0;
      }
    }else{
      raw_printf(stderr, "Usage: .timer on|off\n");
      rc = 1;
    }
  }else
#ifndef SQLITE_OMIT_TRACE
  if(c=='t' && strncmp(azArg[0], "trace", n)==0){
    int mType = 0;
    int jj;
    open_db(p, 0);
    for(jj=1; jj<nArg; jj++){
      const char *z = azArg[jj];
      if(z[0]=='-'){
        if(optionMatch(z, "expanded")){
          p->eTraceType = SHELL_TRACE_EXPANDED;
        }
#ifdef SQLITE_ENABLE_NORMALIZE
        else if(optionMatch(z, "normalized")){
          p->eTraceType = SHELL_TRACE_NORMALIZED;
        }
#endif
        else if(optionMatch(z, "plain")){
          p->eTraceType = SHELL_TRACE_PLAIN;
        }
        else if(optionMatch(z, "profile")){
          mType |= SQLITE_TRACE_PROFILE;
        }
        else if(optionMatch(z, "row")){
          mType |= SQLITE_TRACE_ROW;
        }
        else if(optionMatch(z, "stmt")){
          mType |= SQLITE_TRACE_STMT;
        }
        else if(optionMatch(z, "close")){
          mType |= SQLITE_TRACE_CLOSE;
        }
        else {
          raw_printf(stderr, "Unknown option \"%s\" on \".trace\"\n", z);
          rc = 1;
          goto meta_command_exit;
        }
      }else{
        output_file_close(p->traceOut);
        p->traceOut = output_file_open(azArg[1], 0);
      }
    }
    if(p->traceOut==0){
      sqlite3_trace_v2(p->db, 0, 0, 0);
    }else{
      if(mType==0) mType = SQLITE_TRACE_STMT;
      sqlite3_trace_v2(p->db, mType, sql_trace_callback, p);
    }
  }else
#endif /* !defined(SQLITE_OMIT_TRACE) */
#if defined(SQLITE_DEBUG) && !defined(SQLITE_OMIT_VIRTUALTABLE)
  if(c=='u' && strncmp(azArg[0], "unmodule", n)==0){
    int ii;
    int lenOpt;
    char *zOpt;
    if(nArg<2){
      raw_printf(stderr, "Usage: .unmodule [--allexcept] NAME ...\n");
      rc = 1;
      goto meta_command_exit;
    }
    open_db(p, 0);
    zOpt = azArg[1];
    if(zOpt[0]=='-' && zOpt[1]=='-' && zOpt[2]!=0) zOpt++;
    lenOpt = (int)strlen(zOpt);
    if(lenOpt>=3 && strncmp(zOpt, "-allexcept",lenOpt)==0){
      assert(azArg[nArg]==0);
      sqlite3_drop_modules(p->db, nArg>2 ? (const char**)(azArg+2) : 0);
    }else{
      for(ii=1; ii<nArg; ii++){
        sqlite3_create_module(p->db, azArg[ii], 0, 0);
      }
    }
  }else
#endif
#if SQLITE_USER_AUTHENTICATION
  if(c=='u' && strncmp(azArg[0], "user", n)==0){
    if(nArg<2){
      raw_printf(stderr, "Usage: .user SUBCOMMAND ...\n");
      rc = 1;
      goto meta_command_exit;
    }
    open_db(p, 0);
    if(strcmp(azArg[1],"login")==0){
      if(nArg!=4){
        raw_printf(stderr, "Usage: .user login USER PASSWORD\n");
        rc = 1;
        goto meta_command_exit;
      }
      rc = sqlite3_user_authenticate(p->db, azArg[2], azArg[3],
                                     strlen30(azArg[3]));
      if(rc){
        utf8_printf(stderr, "Authentication failed for user %s\n", azArg[2]);
        rc = 1;
      }
    }else if(strcmp(azArg[1],"add")==0){
      if(nArg!=5){
        raw_printf(stderr, "Usage: .user add USER PASSWORD ISADMIN\n");
        rc = 1;
        goto meta_command_exit;
      }
      rc = sqlite3_user_add(p->db, azArg[2], azArg[3], strlen30(azArg[3]),
                            booleanValue(azArg[4]));
      if(rc){
        raw_printf(stderr, "User-Add failed: %d\n", rc);
        rc = 1;
      }
    }else if(strcmp(azArg[1],"edit")==0){
      if(nArg!=5){
        raw_printf(stderr, "Usage: .user edit USER PASSWORD ISADMIN\n");
        rc = 1;
        goto meta_command_exit;
      }
      rc = sqlite3_user_change(p->db, azArg[2], azArg[3], strlen30(azArg[3]),
                              booleanValue(azArg[4]));
      if(rc){
        raw_printf(stderr, "User-Edit failed: %d\n", rc);
        rc = 1;
      }
    }else if(strcmp(azArg[1],"delete")==0){
      if(nArg!=3){
        raw_printf(stderr, "Usage: .user delete USER\n");
        rc = 1;
        goto meta_command_exit;
      }
      rc = sqlite3_user_delete(p->db, azArg[2]);
      if(rc){
        raw_printf(stderr, "User-Delete failed: %d\n", rc);
        rc = 1;
      }
    }else{
      raw_printf(stderr, "Usage: .user login|add|edit|delete ...\n");
      rc = 1;
      goto meta_command_exit;
    }
  }else
#endif /* SQLITE_USER_AUTHENTICATION */
  if(c=='v' && strncmp(azArg[0], "version", n)==0){
    utf8_printf(p->out, "SQLite %s %s\n" /*extra-version-info*/,
        sqlite3_libversion(), sqlite3_sourceid());
#if SQLITE_HAVE_ZLIB
    utf8_printf(p->out, "zlib version %s\n", zlibVersion());
#endif
#define CTIMEOPT_VAL_(opt) #opt
#define CTIMEOPT_VAL(opt) CTIMEOPT_VAL_(opt)
#if defined(__clang__) && defined(__clang_major__)
    utf8_printf(p->out, "clang-" CTIMEOPT_VAL(__clang_major__) "."
                    CTIMEOPT_VAL(__clang_minor__) "."
                    CTIMEOPT_VAL(__clang_patchlevel__) "\n");
#elif defined(_MSC_VER)
    utf8_printf(p->out, "msvc-" CTIMEOPT_VAL(_MSC_VER) "\n");
#elif defined(__GNUC__) && defined(__VERSION__)
    utf8_printf(p->out, "gcc-" __VERSION__ "\n");
#endif
  }else
  if(c=='v' && strncmp(azArg[0], "vfsinfo", n)==0){
    const char *zDbName = nArg==2 ? azArg[1] : "main";
    sqlite3_vfs *pVfs = 0;
    if(p->db){
      sqlite3_file_control(p->db, zDbName, SQLITE_FCNTL_VFS_POINTER, &pVfs);
      if(pVfs){
        utf8_printf(p->out, "vfs.zName = \"%s\"\n", pVfs->zName);
        raw_printf(p->out, "vfs.iVersion = %d\n", pVfs->iVersion);
        raw_printf(p->out, "vfs.szOsFile = %d\n", pVfs->szOsFile);
        raw_printf(p->out, "vfs.mxPathname = %d\n", pVfs->mxPathname);
      }
    }
  }else
  if(c=='v' && strncmp(azArg[0], "vfslist", n)==0){
    sqlite3_vfs *pVfs;
    sqlite3_vfs *pCurrent = 0;
    if(p->db){
      sqlite3_file_control(p->db, "main", SQLITE_FCNTL_VFS_POINTER, &pCurrent);
    }
    for(pVfs=sqlite3_vfs_find(0); pVfs; pVfs=pVfs->pNext){
      utf8_printf(p->out, "vfs.zName = \"%s\"%s\n", pVfs->zName,
           pVfs==pCurrent ? " <--- CURRENT" : "");
      raw_printf(p->out, "vfs.iVersion = %d\n", pVfs->iVersion);
      raw_printf(p->out, "vfs.szOsFile = %d\n", pVfs->szOsFile);
      raw_printf(p->out, "vfs.mxPathname = %d\n", pVfs->mxPathname);
      if(pVfs->pNext){
        raw_printf(p->out, "-----------------------------------\n");
      }
    }
  }else
  if(c=='v' && strncmp(azArg[0], "vfsname", n)==0){
    const char *zDbName = nArg==2 ? azArg[1] : "main";
    char *zVfsName = 0;
    if(p->db){
      sqlite3_file_control(p->db, zDbName, SQLITE_FCNTL_VFSNAME, &zVfsName);
      if(zVfsName){
        utf8_printf(p->out, "%s\n", zVfsName);
        sqlite3_free(zVfsName);
      }
    }
  }else
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_WHERETRACE)
  if(c=='w' && strncmp(azArg[0], "wheretrace", n)==0){
    sqlite3WhereTrace = nArg>=2 ? booleanValue(azArg[1]) : 0xff;
  }else
#endif
  if(c=='w' && strncmp(azArg[0], "width", n)==0){
    int j;
    assert(nArg<=ArraySize(azArg));
    for(j=1; j<nArg && j<ArraySize(p->colWidth); j++){
      p->colWidth[j-1] = (int)integerValue(azArg[j]);
    }
  }else
  {
    utf8_printf(stderr, "Error: unknown command or invalid arguments: "
      " \"%s\". Enter \".help\" for help\n", azArg[0]);
    rc = 1;
  }
meta_command_exit:
  if(p->outCount){
    p->outCount--;
    if(p->outCount==0) output_reset(p);
  }
  return rc;
}
dump_callback()
static int dump_callback (void * pArg, int nArg, char ** azArg, char ** azNotUsed) [static]
Definition at line 11879 of file shell.c.
References appendText(), ShellState::cMode, ShellState::db, freeColumnList(), freeText(), initText(), ShellState::mode, MODE_Insert, ShellState::nErr, ShellState::out, printSchemaLine(), quoteChar(), raw_printf, shell_exec(), sqlite3_free, sqlite3_mprintf, sqlite3_strglob, SQLITE_CORRUPT, tableColumnList(), toggleSelectOrder(), UNUSED_PARAMETER, utf8_printf, ShellState::writableSchema, ShellText::z, and ShellState::zDestTable.
Referenced by run_schema_dump_query().
                                                                              {
  int rc;
  const char *zTable;
  const char *zType;
  const char *zSql;
  ShellState *p = (ShellState *)pArg;
  UNUSED_PARAMETER(azNotUsed);
  if(nArg!=3 || azArg==0) return 0;
  zTable = azArg[0];
  zType = azArg[1];
  zSql = azArg[2];
  if(strcmp(zTable, "sqlite_sequence")==0){
    raw_printf(p->out, "DELETE FROM sqlite_sequence;\n");
  }else if(sqlite3_strglob("sqlite_stat?", zTable)==0){
    raw_printf(p->out, "ANALYZE sqlite_master;\n");
  }else if(strncmp(zTable, "sqlite_", 7)==0){
    return 0;
  }else if(strncmp(zSql, "CREATE VIRTUAL TABLE", 20)==0){
    char *zIns;
    if(!p->writableSchema){
      raw_printf(p->out, "PRAGMA writable_schema=ON;\n");
      p->writableSchema = 1;
    }
    zIns = sqlite3_mprintf(
       "INSERT INTO sqlite_master(type,name,tbl_name,rootpage,sql)"
       "VALUES('table','%q','%q',0,'%q');",
       zTable, zTable, zSql);
    utf8_printf(p->out, "%s\n", zIns);
    sqlite3_free(zIns);
    return 0;
  }else{
    printSchemaLine(p->out, zSql, ";\n");
  }
  if(strcmp(zType, "table")==0){
    ShellText sSelect;
    ShellText sTable;
    char **azCol;
    int i;
    char *savedDestTable;
    int savedMode;
    azCol = tableColumnList(p, zTable);
    if(azCol==0){
      p->nErr++;
      return 0;
    }
    /* Always quote the table name, even if it appears to be pure ascii,
    ** in case it is a keyword. Ex: INSERT INTO "table" ... */
    initText(&sTable);
    appendText(&sTable, zTable, quoteChar(zTable));
    /* If preserving the rowid, add a column list after the table name.
    ** In other words: "INSERT INTO tab(rowid,a,b,c,...) VALUES(...)"
    ** instead of the usual "INSERT INTO tab VALUES(...)".
    */
    if(azCol[0]){
      appendText(&sTable, "(", 0);
      appendText(&sTable, azCol[0], 0);
      for(i=1; azCol[i]; i++){
        appendText(&sTable, ",", 0);
        appendText(&sTable, azCol[i], quoteChar(azCol[i]));
      }
      appendText(&sTable, ")", 0);
    }
    /* Build an appropriate SELECT statement */
    initText(&sSelect);
    appendText(&sSelect, "SELECT ", 0);
    if(azCol[0]){
      appendText(&sSelect, azCol[0], 0);
      appendText(&sSelect, ",", 0);
    }
    for(i=1; azCol[i]; i++){
      appendText(&sSelect, azCol[i], quoteChar(azCol[i]));
      if(azCol[i+1]){
        appendText(&sSelect, ",", 0);
      }
    }
    freeColumnList(azCol);
    appendText(&sSelect, " FROM ", 0);
    appendText(&sSelect, zTable, quoteChar(zTable));
    savedDestTable = p->zDestTable;
    savedMode = p->mode;
    p->zDestTable = sTable.z;
    p->mode = p->cMode = MODE_Insert;
    rc = shell_exec(p, sSelect.z, 0);
    if((rc&0xff)==SQLITE_CORRUPT){
      raw_printf(p->out, "/****** CORRUPTION ERROR *******/\n");
      toggleSelectOrder(p->db);
      shell_exec(p, sSelect.z, 0);
      toggleSelectOrder(p->db);
    }
    p->zDestTable = savedDestTable;
    p->mode = savedMode;
    freeText(&sTable);
    freeText(&sSelect);
    if(rc) p->nErr++;
  }
  return 0;
}
editFunc()
static void editFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 9773 of file shell.c.
References sqlite3_context_db_handle, sqlite3_file_control, sqlite3_free, sqlite3_malloc64, sqlite3_mprintf, sqlite3_randomness, sqlite3_result_blob64, sqlite3_result_error, sqlite3_result_error_nomem, sqlite3_result_text64, sqlite3_value_blob, sqlite3_value_bytes, sqlite3_value_text, sqlite3_value_type, SQLITE_BLOB, SQLITE_FCNTL_TEMPFILENAME, SQLITE_NULL, SQLITE_UTF8, and time_test::x.
Referenced by open_db().
 {
  const char *zEditor;
  char *zTempFile = 0;
  sqlite3 *db;
  char *zCmd = 0;
  int bBin;
  int rc;
  int hasCRNL = 0;
  FILE *f = 0;
  sqlite3_int64 sz;
  sqlite3_int64 x;
  unsigned char *p = 0;
  if(argc==2){
    zEditor = (const char*)sqlite3_value_text(argv[1]);
  }else{
    zEditor = getenv("VISUAL");
  }
  if(zEditor==0){
    sqlite3_result_error(context, "no editor for edit()", -1);
    return;
  }
  if(sqlite3_value_type(argv[0])==SQLITE_NULL){
    sqlite3_result_error(context, "NULL input to edit()", -1);
    return;
  }
  db = sqlite3_context_db_handle(context);
  zTempFile = 0;
  sqlite3_file_control(db, 0, SQLITE_FCNTL_TEMPFILENAME, &zTempFile);
  if(zTempFile==0){
    sqlite3_uint64 r = 0;
    sqlite3_randomness(sizeof(r), &r);
    zTempFile = sqlite3_mprintf("temp%llx", r);
    if(zTempFile==0){
      sqlite3_result_error_nomem(context);
      return;
    }
  }
  bBin = sqlite3_value_type(argv[0])==SQLITE_BLOB;
  /* When writing the file to be edited, do \n to \r\n conversions on systems
  ** that want \r\n line endings */
  f = fopen(zTempFile, bBin ? "wb" : "w");
  if(f==0){
    sqlite3_result_error(context, "edit() cannot open temp file", -1);
    goto edit_func_end;
  }
  sz = sqlite3_value_bytes(argv[0]);
  if(bBin){
    x = fwrite(sqlite3_value_blob(argv[0]), 1, (size_t)sz, f);
  }else{
    const char *z = (const char*)sqlite3_value_text(argv[0]);
    /* Remember whether or not the value originally contained \r\n */
    if(z && strstr(z,"\r\n")!=0) hasCRNL = 1;
    x = fwrite(sqlite3_value_text(argv[0]), 1, (size_t)sz, f);
  }
  fclose(f);
  f = 0;
  if(x!=sz){
    sqlite3_result_error(context, "edit() could not write the whole file", -1);
    goto edit_func_end;
  }
  zCmd = sqlite3_mprintf("%s \"%s\"", zEditor, zTempFile);
  if(zCmd==0){
    sqlite3_result_error_nomem(context);
    goto edit_func_end;
  }
  rc = system(zCmd);
  sqlite3_free(zCmd);
  if(rc){
    sqlite3_result_error(context, "EDITOR returned non-zero", -1);
    goto edit_func_end;
  }
  f = fopen(zTempFile, "rb");
  if(f==0){
    sqlite3_result_error(context,
      "edit() cannot reopen temp file after edit", -1);
    goto edit_func_end;
  }
  fseek(f, 0, SEEK_END);
  sz = ftell(f);
  rewind(f);
  p = sqlite3_malloc64(sz+1);
  if(p==0){
    sqlite3_result_error_nomem(context);
    goto edit_func_end;
  }
  x = fread(p, 1, (size_t)sz, f);
  fclose(f);
  f = 0;
  if(x!=sz){
    sqlite3_result_error(context, "could not read back the whole file", -1);
    goto edit_func_end;
  }
  if(bBin){
    sqlite3_result_blob64(context, p, sz, sqlite3_free);
  }else{
    sqlite3_int64 i, j;
    if(hasCRNL){
      /* If the original contains \r\n then do no conversions back to \n */
      j = sz;
    }else{
      /* If the file did not originally contain \r\n then convert any new
      ** \r\n back into \n */
      for(i=j=0; i<sz; i++){
        if(p[i]=='\r' && p[i+1]=='\n') i++;
        p[j++] = p[i];
      }
      sz = j;
      p[sz] = 0;
    }
    sqlite3_result_text64(context, (const char*)p, sz,
                          sqlite3_free, SQLITE_UTF8);
  }
  p = 0;
edit_func_end:
  if(f) fclose(f);
  unlink(zTempFile);
  sqlite3_free(zTempFile);
  sqlite3_free(p);
}
endTimer()
static void endTimer (void) [static]
Definition at line 278 of file shell.c.
References sBegin, timeDiff(), and timeOfDay().
                          {
  if(enableTimer){
    sqlite3_int64 iEnd = timeOfDay();
    struct rusage sEnd;
    getrusage(RUSAGE_SELF, &sEnd);
    printf("Run Time: real %.3f user %f sys %f\n",
       (iEnd - iBegin)*0.001,
       timeDiff(&sBegin.ru_utime, &sEnd.ru_utime),
       timeDiff(&sBegin.ru_stime, &sEnd.ru_stime));
  }
}
eqp_append()
static void eqp_append (ShellState * p, int iEqpId, int p2, const char * zText) [static]
Definition at line 10283 of file shell.c.
References ShellState::autoEQPtest, EQPGraphRow::iEqpId, EQPGraphRow::iParentId, ShellState::out, EQPGraph::pLast, EQPGraphRow::pNext, EQPGraph::pRow, ShellState::sGraph, shell_out_of_memory(), sqlite3_malloc64, strlen30(), utf8_printf, and EQPGraphRow::zText.
Referenced by shell_callback(), and shell_exec().
                                                                            {
  EQPGraphRow *pNew;
  int nText = strlen30(zText);
  if(p->autoEQPtest){
    utf8_printf(p->out, "%d,%d,%s\n", iEqpId, p2, zText);
  }
  pNew = sqlite3_malloc64(sizeof(*pNew) + nText);
  if(pNew==0) shell_out_of_memory();
  pNew->iEqpId = iEqpId;
  pNew->iParentId = p2;
  memcpy(pNew->zText, zText, nText+1);
  pNew->pNext = 0;
  if(p->sGraph.pLast){
    p->sGraph.pLast->pNext = pNew;
  }else{
    p->sGraph.pRow = pNew;
  }
  p->sGraph.pLast = pNew;
}
eqp_next_row()
static EQPGraphRow* eqp_next_row (ShellState * p, int iEqpId, EQPGraphRow * pOld) [static]
Definition at line 10319 of file shell.c.
References EQPGraphRow::iParentId, EQPGraphRow::pNext, EQPGraph::pRow, and ShellState::sGraph.
Referenced by eqp_render_level().
                                                                              {
  EQPGraphRow *pRow = pOld ? pOld->pNext : p->sGraph.pRow;
  while(pRow && pRow->iParentId!=iEqpId) pRow = pRow->pNext;
  return pRow;
}
eqp_render()
static void eqp_render (ShellState * p) [static]
Definition at line 10348 of file shell.c.
References eqp_render_level(), eqp_reset(), ShellState::out, EQPGraphRow::pNext, EQPGraph::pRow, ShellState::sGraph, sqlite3_free, utf8_printf, EQPGraph::zPrefix, and EQPGraphRow::zText.
Referenced by shell_exec().
                                     {
  EQPGraphRow *pRow = p->sGraph.pRow;
  if(pRow){
    if(pRow->zText[0]=='-'){
      if(pRow->pNext==0){
        eqp_reset(p);
        return;
      }
      utf8_printf(p->out, "%s\n", pRow->zText+3);
      p->sGraph.pRow = pRow->pNext;
      sqlite3_free(pRow);
    }else{
      utf8_printf(p->out, "QUERY PLAN\n");
    }
    p->sGraph.zPrefix[0] = 0;
    eqp_render_level(p, 0);
    eqp_reset(p);
  }
}
eqp_render_level()
static void eqp_render_level (ShellState * p, int iEqpId) [static]
Definition at line 10328 of file shell.c.
References eqp_next_row(), EQPGraphRow::iEqpId, ShellState::out, ShellState::sGraph, strlen30(), utf8_printf, EQPGraph::zPrefix, and EQPGraphRow::zText.
Referenced by eqp_render().
                                                       {
  EQPGraphRow *pRow, *pNext;
  int n = strlen30(p->sGraph.zPrefix);
  char *z;
  for(pRow = eqp_next_row(p, iEqpId, 0); pRow; pRow = pNext){
    pNext = eqp_next_row(p, iEqpId, pRow);
    z = pRow->zText;
    utf8_printf(p->out, "%s%s%s\n", p->sGraph.zPrefix,
                pNext ? "|--" : "`--", z);
    if(n<(int)sizeof(p->sGraph.zPrefix)-7){
      memcpy(&p->sGraph.zPrefix[n], pNext ? "| " : " ", 4);
      eqp_render_level(p, pRow->iEqpId);
      p->sGraph.zPrefix[n] = 0;
    }
  }
}
eqp_reset()
static void eqp_reset (ShellState * p) [static]
Definition at line 10307 of file shell.c.
References EQPGraphRow::pNext, EQPGraph::pRow, ShellState::sGraph, and sqlite3_free.
Referenced by eqp_render().
                                    {
  EQPGraphRow *pRow, *pNext;
  for(pRow = p->sGraph.pRow; pRow; pRow = pNext){
    pNext = pRow->pNext;
    sqlite3_free(pRow);
  }
  memset(&p->sGraph, 0, sizeof(p->sGraph));
}
exec_prepared_stmt()
static void exec_prepared_stmt (ShellState * pArg, sqlite3_stmt * pStmt) [static]
Definition at line 11393 of file shell.c.
References ShellState::cMode, MODE_Insert, shell_callback(), sqlite3_column_count, sqlite3_column_name, sqlite3_column_text, sqlite3_column_type, sqlite3_free, sqlite3_malloc64, sqlite3_step, SQLITE_ABORT, SQLITE_BLOB, SQLITE_NOMEM, SQLITE_NULL, SQLITE_ROW, and time_test::x.
Referenced by shell_exec().
 {
  int rc;
  /* perform the first step. this will tell us if we
  ** have a result set or not and how wide it is.
  */
  rc = sqlite3_step(pStmt);
  /* if we have a result set... */
  if(SQLITE_ROW == rc){
    /* allocate space for col name ptr, value ptr, and type */
    int nCol = sqlite3_column_count(pStmt);
    void *pData = sqlite3_malloc64(3*nCol*sizeof(const char*) + 1);
    if(!pData){
      rc = SQLITE_NOMEM;
    }else{
      char **azCols = (char **)pData; /* Names of result columns */
      char **azVals = &azCols[nCol]; /* Results */
      int *aiTypes = (int *)&azVals[nCol]; /* Result types */
      int i, x;
      assert(sizeof(int) <= sizeof(char *));
      /* save off ptrs to column names */
      for(i=0; i<nCol; i++){
        azCols[i] = (char *)sqlite3_column_name(pStmt, i);
      }
      do{
        /* extract the data and data types */
        for(i=0; i<nCol; i++){
          aiTypes[i] = x = sqlite3_column_type(pStmt, i);
          if(x==SQLITE_BLOB && pArg && pArg->cMode==MODE_Insert){
            azVals[i] = "";
          }else{
            azVals[i] = (char*)sqlite3_column_text(pStmt, i);
          }
          if(!azVals[i] && (aiTypes[i]!=SQLITE_NULL)){
            rc = SQLITE_NOMEM;
            break; /* from for */
          }
        } /* end for */
        /* if data and types extracted successfully... */
        if(SQLITE_ROW == rc){
          /* call the supplied callback with the result row data */
          if(shell_callback(pArg, nCol, azVals, azCols, aiTypes)){
            rc = SQLITE_ABORT;
          }else{
            rc = sqlite3_step(pStmt);
          }
        }
      } while(SQLITE_ROW == rc);
      sqlite3_free(pData);
    }
  }
}
expertBestIndex()
static int expertBestIndex (sqlite3_vtab * pVtab, sqlite3_index_info * pIdxInfo) [static]
Definition at line 7143 of file shell.c.
References IdxTable::aCol, sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, sqlite3_index_info::aOrderBy, sqlite3_index_info::sqlite3_index_constraint_usage::argvIndex, IdxConstraint::bDesc, IdxConstraint::bRange, sqlite3_index_info::sqlite3_index_orderby::desc, sqlite3_index_info::estimatedCost, IdxConstraint::iCol, sqlite3_index_info::sqlite3_index_orderby::iColumn, idxMalloc(), idxNewConstraint(), IdxColumn::iPk, sqlite3_index_info::nConstraint, sqlite3_index_info::nOrderBy, IdxScan::pEq, ExpertVtab::pExpert, IdxConstraint::pLink, IdxConstraint::pNext, IdxScan::pNextScan, IdxScan::pOrder, IdxScan::pRange, sqlite3expert::pScan, IdxScan::pTab, ExpertVtab::pTab, sqlite3_vtab_collation, SQLITE_INDEX_CONSTRAINT_EQ, SQLITE_INDEX_CONSTRAINT_GE, SQLITE_INDEX_CONSTRAINT_GT, SQLITE_INDEX_CONSTRAINT_LE, SQLITE_INDEX_CONSTRAINT_LT, SQLITE_OK, and IdxColumn::zColl.
Referenced by idxRegisterVtab().
                                                                             {
  ExpertVtab *p = (ExpertVtab*)pVtab;
  int rc = SQLITE_OK;
  int n = 0;
  IdxScan *pScan;
  const int opmask =
    SQLITE_INDEX_CONSTRAINT_EQ | SQLITE_INDEX_CONSTRAINT_GT |
    SQLITE_INDEX_CONSTRAINT_LT | SQLITE_INDEX_CONSTRAINT_GE |
    SQLITE_INDEX_CONSTRAINT_LE;
  pScan = idxMalloc(&rc, sizeof(IdxScan));
  if(pScan){
    int i;
    /* Link the new scan object into the list */
    pScan->pTab = p->pTab;
    pScan->pNextScan = p->pExpert->pScan;
    p->pExpert->pScan = pScan;
    /* Add the constraints to the IdxScan object */
    for(i=0; i<pIdxInfo->nConstraint; i++){
      struct sqlite3_index_constraint *pCons = &pIdxInfo->aConstraint[i];
      if(pCons->usable
       && pCons->iColumn>=0
       && p->pTab->aCol[pCons->iColumn].iPk==0
       && (pCons->op & opmask)
      ){
        IdxConstraint *pNew;
        const char *zColl = sqlite3_vtab_collation(pIdxInfo, i);
        pNew = idxNewConstraint(&rc, zColl);
        if(pNew){
          pNew->iCol = pCons->iColumn;
          if(pCons->op==SQLITE_INDEX_CONSTRAINT_EQ){
            pNew->pNext = pScan->pEq;
            pScan->pEq = pNew;
          }else{
            pNew->bRange = 1;
            pNew->pNext = pScan->pRange;
            pScan->pRange = pNew;
          }
        }
        n++;
        pIdxInfo->aConstraintUsage[i].argvIndex = n;
      }
    }
    /* Add the ORDER BY to the IdxScan object */
    for(i=pIdxInfo->nOrderBy-1; i>=0; i--){
      int iCol = pIdxInfo->aOrderBy[i].iColumn;
      if(iCol>=0){
        IdxConstraint *pNew = idxNewConstraint(&rc, p->pTab->aCol[iCol].zColl);
        if(pNew){
          pNew->iCol = iCol;
          pNew->bDesc = pIdxInfo->aOrderBy[i].desc;
          pNew->pNext = pScan->pOrder;
          pNew->pLink = pScan->pOrder;
          pScan->pOrder = pNew;
          n++;
        }
      }
    }
  }
  pIdxInfo->estimatedCost = 1000000.0 / (n+1);
  return rc;
}
expertClose()
static int expertClose (sqlite3_vtab_cursor * cur) [static]
Definition at line 7238 of file shell.c.
References ExpertCsr::pData, sqlite3_finalize, sqlite3_free, and SQLITE_OK.
Referenced by idxRegisterVtab().
                                                {
  ExpertCsr *pCsr = (ExpertCsr*)cur;
  sqlite3_finalize(pCsr->pData);
  sqlite3_free(pCsr);
  return SQLITE_OK;
}
expertColumn()
static int expertColumn (sqlite3_vtab_cursor * cur, sqlite3_context * ctx, int i) [static]
Definition at line 7287 of file shell.c.
References ExpertCsr::pData, sqlite3_column_value, sqlite3_result_value, and SQLITE_OK.
Referenced by idxRegisterVtab().
                                                                              {
  ExpertCsr *pCsr = (ExpertCsr*)cur;
  sqlite3_value *pVal;
  pVal = sqlite3_column_value(pCsr->pData, i);
  if(pVal){
    sqlite3_result_value(ctx, pVal);
  }
  return SQLITE_OK;
}
expertConnect()
static int expertConnect (sqlite3 * db, void * pAux, int argc, const char *const * argv, sqlite3_vtab ** ppVtab, char ** pzErr) [static]
Definition at line 7101 of file shell.c.
References expertDequote(), idxMalloc(), ExpertVtab::pExpert, ExpertVtab::pTab, sqlite3expert::pTable, sqlite3_declare_vtab, sqlite3_free, sqlite3_mprintf, sqlite3_stricmp, SQLITE_ERROR, SQLITE_NOMEM, SQLITE_OK, and IdxTable::zName.
Referenced by idxRegisterVtab().
 {
  sqlite3expert *pExpert = (sqlite3expert*)pAux;
  ExpertVtab *p = 0;
  int rc;
  if(argc!=4){
    *pzErr = sqlite3_mprintf("internal error!");
    rc = SQLITE_ERROR;
  }else{
    char *zCreateTable = expertDequote(argv[3]);
    if(zCreateTable){
      rc = sqlite3_declare_vtab(db, zCreateTable);
      if(rc==SQLITE_OK){
        p = idxMalloc(&rc, sizeof(ExpertVtab));
      }
      if(rc==SQLITE_OK){
        p->pExpert = pExpert;
        p->pTab = pExpert->pTable;
        assert(sqlite3_stricmp(p->pTab->zName, argv[2])==0);
      }
      sqlite3_free(zCreateTable);
    }else{
      rc = SQLITE_NOMEM;
    }
  }
  *ppVtab = (sqlite3_vtab*)p;
  return rc;
}
expertDequote()
static char* expertDequote (const char * zIn) [static]
Definition at line 7069 of file shell.c.
References sqlite3_malloc, and STRLEN.
Referenced by expertConnect().
                                           {
  int n = STRLEN(zIn);
  char *zRet = sqlite3_malloc(n);
  assert(zIn[0]=='\'');
  assert(zIn[n-1]=='\'');
  if(zRet){
    int iOut = 0;
    int iIn = 0;
    for(iIn=1; iIn<(n-1); iIn++){
      if(zIn[iIn]=='\''){
        assert(zIn[iIn+1]=='\'');
        iIn++;
      }
      zRet[iOut++] = zIn[iIn];
    }
    zRet[iOut] = '\0';
  }
  return zRet;
}
expertDisconnect()
static int expertDisconnect (sqlite3_vtab * pVtab) [static]
Definition at line 7137 of file shell.c.
References sqlite3_free, and SQLITE_OK.
Referenced by idxRegisterVtab().
                                                {
  ExpertVtab *p = (ExpertVtab*)pVtab;
  sqlite3_free(p);
  return SQLITE_OK;
}
expertDotCommand()
static int expertDotCommand (ShellState * pState, char ** azArg, int nArg) [static]
Definition at line 11526 of file shell.c.
References ExpertInfo::bVerbose, ShellState::db, ShellState::expert, EXPERT_CONFIG_SAMPLE, integerValue(), ExpertInfo::pExpert, raw_printf, sqlite3_expert_config(), sqlite3_expert_new(), SQLITE_ERROR, SQLITE_OK, and strlen30().
Referenced by do_meta_command().
 {
  int rc = SQLITE_OK;
  char *zErr = 0;
  int i;
  int iSample = 0;
  assert(pState->expert.pExpert==0);
  memset(&pState->expert, 0, sizeof(ExpertInfo));
  for(i=1; rc==SQLITE_OK && i<nArg; i++){
    char *z = azArg[i];
    int n;
    if(z[0]=='-' && z[1]=='-') z++;
    n = strlen30(z);
    if(n>=2 && 0==strncmp(z, "-verbose", n)){
      pState->expert.bVerbose = 1;
    }
    else if(n>=2 && 0==strncmp(z, "-sample", n)){
      if(i==(nArg-1)){
        raw_printf(stderr, "option requires an argument: %s\n", z);
        rc = SQLITE_ERROR;
      }else{
        iSample = (int)integerValue(azArg[++i]);
        if(iSample<0 || iSample>100){
          raw_printf(stderr, "value out of range: %s\n", azArg[i]);
          rc = SQLITE_ERROR;
        }
      }
    }
    else{
      raw_printf(stderr, "unknown option: %s\n", z);
      rc = SQLITE_ERROR;
    }
  }
  if(rc==SQLITE_OK){
    pState->expert.pExpert = sqlite3_expert_new(pState->db, &zErr);
    if(pState->expert.pExpert==0){
      raw_printf(stderr, "sqlite3_expert_new: %s\n", zErr);
      rc = SQLITE_ERROR;
    }else{
      sqlite3_expert_config(
          pState->expert.pExpert, EXPERT_CONFIG_SAMPLE, iSample
      );
    }
  }
  return rc;
}
expertEof()
static int expertEof (sqlite3_vtab_cursor * cur) [static]
Definition at line 7251 of file shell.c.
References ExpertCsr::pData.
Referenced by idxRegisterVtab().
                                              {
  ExpertCsr *pCsr = (ExpertCsr*)cur;
  return pCsr->pData==0;
}
expertFilter()
static int expertFilter (sqlite3_vtab_cursor * cur, int idxNum, const char * idxStr, int argc, sqlite3_value ** argv) [static]
Definition at line 7300 of file shell.c.
References ExpertVtab::base, sqlite3expert::db, expertNext(), idxPrintfPrepareStmt(), ExpertCsr::pData, ExpertVtab::pExpert, ExpertVtab::pTab, sqlite3_vtab_cursor::pVtab, sqlite3_finalize, SQLITE_OK, sqlite3_vtab::zErrMsg, and IdxTable::zName.
Referenced by idxRegisterVtab().
 {
  ExpertCsr *pCsr = (ExpertCsr*)cur;
  ExpertVtab *pVtab = (ExpertVtab*)(cur->pVtab);
  sqlite3expert *pExpert = pVtab->pExpert;
  int rc;
  (void)idxNum;
  (void)idxStr;
  (void)argc;
  (void)argv;
  rc = sqlite3_finalize(pCsr->pData);
  pCsr->pData = 0;
  if(rc==SQLITE_OK){
    rc = idxPrintfPrepareStmt(pExpert->db, &pCsr->pData, &pVtab->base.zErrMsg,
        "SELECT * FROM main.%Q WHERE sample()", pVtab->pTab->zName
    );
  }
  if(rc==SQLITE_OK){
    rc = expertNext(cur);
  }
  return rc;
}
expertFinish()
static int expertFinish (ShellState * pState, int bCancel, char ** pzErr) [static]
Definition at line 11481 of file shell.c.
References ExpertInfo::bVerbose, ShellState::expert, EXPERT_REPORT_CANDIDATES, EXPERT_REPORT_INDEXES, EXPERT_REPORT_PLAN, EXPERT_REPORT_SQL, ShellState::out, ExpertInfo::pExpert, raw_printf, sqlite3_expert_analyze(), sqlite3_expert_count(), sqlite3_expert_destroy(), sqlite3_expert_report(), and SQLITE_OK.
Referenced by do_meta_command(), and shell_exec().
 {
  int rc = SQLITE_OK;
  sqlite3expert *p = pState->expert.pExpert;
  assert(p);
  assert(bCancel || pzErr==0 || *pzErr==0);
  if(bCancel==0){
    FILE *out = pState->out;
    int bVerbose = pState->expert.bVerbose;
    rc = sqlite3_expert_analyze(p, pzErr);
    if(rc==SQLITE_OK){
      int nQuery = sqlite3_expert_count(p);
      int i;
      if(bVerbose){
        const char *zCand = sqlite3_expert_report(p,0,EXPERT_REPORT_CANDIDATES);
        raw_printf(out, "-- Candidates -----------------------------\n");
        raw_printf(out, "%s\n", zCand);
      }
      for(i=0; i<nQuery; i++){
        const char *zSql = sqlite3_expert_report(p, i, EXPERT_REPORT_SQL);
        const char *zIdx = sqlite3_expert_report(p, i, EXPERT_REPORT_INDEXES);
        const char *zEQP = sqlite3_expert_report(p, i, EXPERT_REPORT_PLAN);
        if(zIdx==0) zIdx = "(no new indexes)\n";
        if(bVerbose){
          raw_printf(out, "-- Query %d --------------------------------\n",i+1);
          raw_printf(out, "%s\n\n", zSql);
        }
        raw_printf(out, "%s\n", zIdx);
        raw_printf(out, "%s\n", zEQP);
      }
    }
  }
  sqlite3_expert_destroy(p);
  pState->expert.pExpert = 0;
  return rc;
}
expertHandleSQL()
static int expertHandleSQL (ShellState * pState, const char * zSql, char ** pzErr) [static]
Definition at line 11461 of file shell.c.
References ShellState::expert, ExpertInfo::pExpert, and sqlite3_expert_sql().
Referenced by shell_exec().
 {
  assert(pState->expert.pExpert);
  assert(pzErr==0 || *pzErr==0);
  return sqlite3_expert_sql(pState->expert.pExpert, zSql, pzErr);
}
expertNext()
static int expertNext (sqlite3_vtab_cursor * cur) [static]
Definition at line 7259 of file shell.c.
References ExpertCsr::pData, sqlite3_finalize, sqlite3_step, SQLITE_OK, and SQLITE_ROW.
Referenced by expertFilter(), and idxRegisterVtab().
                                               {
  ExpertCsr *pCsr = (ExpertCsr*)cur;
  int rc = SQLITE_OK;
  assert(pCsr->pData);
  rc = sqlite3_step(pCsr->pData);
  if(rc!=SQLITE_ROW){
    rc = sqlite3_finalize(pCsr->pData);
    pCsr->pData = 0;
  }else{
    rc = SQLITE_OK;
  }
  return rc;
}
expertOpen()
static int expertOpen (sqlite3_vtab * pVTab, sqlite3_vtab_cursor ** ppCursor) [static]
Definition at line 7226 of file shell.c.
References idxMalloc(), and SQLITE_OK.
Referenced by idxRegisterVtab().
                                                                          {
  int rc = SQLITE_OK;
  ExpertCsr *pCsr;
  (void)pVTab;
  pCsr = idxMalloc(&rc, sizeof(ExpertCsr));
  *ppCursor = (sqlite3_vtab_cursor*)pCsr;
  return rc;
}
expertRowid()
static int expertRowid (sqlite3_vtab_cursor * cur, sqlite_int64 * pRowid) [static]
Definition at line 7278 of file shell.c.
References SQLITE_OK.
Referenced by idxRegisterVtab().
                                                                      {
  (void)cur;
  *pRowid = 0;
  return SQLITE_OK;
}
expertUpdate()
static int expertUpdate (sqlite3_vtab * pVtab, int nData, sqlite3_value ** azData, sqlite_int64 * pRowid) [static]
Definition at line 7210 of file shell.c.
References SQLITE_OK.
Referenced by idxRegisterVtab().
 {
  (void)pVtab;
  (void)nData;
  (void)azData;
  (void)pRowid;
  return SQLITE_OK;
}
explain_data_delete()
static void explain_data_delete (ShellState * p) [static]
Definition at line 11289 of file shell.c.
References ShellState::aiIndent, ShellState::iIndent, ShellState::nIndent, and sqlite3_free.
Referenced by shell_exec().
                                              {
  sqlite3_free(p->aiIndent);
  p->aiIndent = 0;
  p->nIndent = 0;
  p->iIndent = 0;
}
explain_data_prepare()
static void explain_data_prepare (ShellState * p, sqlite3_stmt * pSql) [static]
Definition at line 11206 of file shell.c.
References ShellState::aiIndent, ArraySize, ShellState::cMode, ShellState::iIndent, ShellState::mode, ShellState::nIndent, shell_out_of_memory(), sqlite3_column_count, sqlite3_column_int, sqlite3_column_name, sqlite3_column_text, sqlite3_free, sqlite3_realloc64, sqlite3_reset, sqlite3_sql, sqlite3_step, sqlite3_strnicmp, SQLITE_ROW, and str_in_array().
Referenced by shell_exec().
                                                                   {
  const char *zSql; /* The text of the SQL statement */
  const char *z; /* Used to check if this is an EXPLAIN */
  int *abYield = 0; /* True if op is an OP_Yield */
  int nAlloc = 0; /* Allocated size of p->aiIndent[], abYield */
  int iOp; /* Index of operation in p->aiIndent[] */
  const char *azNext[] = { "Next", "Prev", "VPrev", "VNext", "SorterNext", 0 };
  const char *azYield[] = { "Yield", "SeekLT", "SeekGT", "RowSetRead",
                            "Rewind", 0 };
  const char *azGoto[] = { "Goto", 0 };
  /* Try to figure out if this is really an EXPLAIN statement. If this
  ** cannot be verified, return early. */
  if(sqlite3_column_count(pSql)!=8){
    p->cMode = p->mode;
    return;
  }
  zSql = sqlite3_sql(pSql);
  if(zSql==0) return;
  for(z=zSql; *z==' ' || *z=='\t' || *z=='\n' || *z=='\f' || *z=='\r'; z++);
  if(sqlite3_strnicmp(z, "explain", 7)){
    p->cMode = p->mode;
    return;
  }
  for(iOp=0; SQLITE_ROW==sqlite3_step(pSql); iOp++){
    int i;
    int iAddr = sqlite3_column_int(pSql, 0);
    const char *zOp = (const char*)sqlite3_column_text(pSql, 1);
    /* Set p2 to the P2 field of the current opcode. Then, assuming that
    ** p2 is an instruction address, set variable p2op to the index of that
    ** instruction in the aiIndent[] array. p2 and p2op may be different if
    ** the current instruction is part of a sub-program generated by an
    ** SQL trigger or foreign key. */
    int p2 = sqlite3_column_int(pSql, 3);
    int p2op = (p2 + (iOp-iAddr));
    /* Grow the p->aiIndent array as required */
    if(iOp>=nAlloc){
      if(iOp==0){
        /* Do further verfication that this is explain output. Abort if
        ** it is not */
        static const char *explainCols[] = {
           "addr", "opcode", "p1", "p2", "p3", "p4", "p5", "comment" };
        int jj;
        for(jj=0; jj<ArraySize(explainCols); jj++){
          if(strcmp(sqlite3_column_name(pSql,jj),explainCols[jj])!=0){
            p->cMode = p->mode;
            sqlite3_reset(pSql);
            return;
          }
        }
      }
      nAlloc += 100;
      p->aiIndent = (int*)sqlite3_realloc64(p->aiIndent, nAlloc*sizeof(int));
      if(p->aiIndent==0) shell_out_of_memory();
      abYield = (int*)sqlite3_realloc64(abYield, nAlloc*sizeof(int));
      if(abYield==0) shell_out_of_memory();
    }
    abYield[iOp] = str_in_array(zOp, azYield);
    p->aiIndent[iOp] = 0;
    p->nIndent = iOp+1;
    if(str_in_array(zOp, azNext)){
      for(i=p2op; i<iOp; i++) p->aiIndent[i] += 2;
    }
    if(str_in_array(zOp, azGoto) && p2op<p->nIndent
     && (abYield[p2op] || sqlite3_column_int(pSql, 2))
    ){
      for(i=p2op; i<iOp; i++) p->aiIndent[i] += 2;
    }
  }
  p->iIndent = 0;
  sqlite3_free(abYield);
  sqlite3_reset(pSql);
}
fileLinkStat()
static int fileLinkStat (const char * zPath, struct stat * pStatBuf) [static]
Definition at line 2311 of file shell.c.
Referenced by fsdirFilter(), and fsdirNext().
 {
#if defined(_WIN32)
  int rc = lstat(zPath, pStatBuf);
  if(rc==0) statTimesToUtc(zPath, pStatBuf);
  return rc;
#else
  return lstat(zPath, pStatBuf);
#endif
}
fileStat()
static int fileStat (const char * zPath, struct stat * pStatBuf) [static]
Definition at line 2293 of file shell.c.
Referenced by makeDirectory(), and writeFile().
 {
#if defined(_WIN32)
  int rc = stat(zPath, pStatBuf);
  if(rc==0) statTimesToUtc(zPath, pStatBuf);
  return rc;
#else
  return stat(zPath, pStatBuf);
#endif
}
find_home_dir()
static char* find_home_dir (int clearFlag) [static]
Definition at line 18419 of file shell.c.
References sqlite3_snprintf, and strlen30().
Referenced by main(), and process_sqliterc().
                                         {
  static char *home_dir = NULL;
  if(clearFlag){
    free(home_dir);
    home_dir = 0;
    return 0;
  }
  if(home_dir) return home_dir;
#if !defined(_WIN32) && !defined(WIN32) && !defined(_WIN32_WCE) \
     && !defined(__RTP__) && !defined(_WRS_KERNEL)
  {
    struct passwd *pwent;
    uid_t uid = getuid();
    if((pwent=getpwuid(uid)) != NULL) {
      home_dir = pwent->pw_dir;
    }
  }
#endif
#if defined(_WIN32_WCE)
  /* Windows CE (arm-wince-mingw32ce-gcc) does not provide getenv()
   */
  home_dir = "/";
#else
#if defined(_WIN32) || defined(WIN32)
  if (!home_dir) {
    home_dir = getenv("USERPROFILE");
  }
#endif
  if (!home_dir) {
    home_dir = getenv("HOME");
  }
#if defined(_WIN32) || defined(WIN32)
  if (!home_dir) {
    char *zDrive, *zPath;
    int n;
    zDrive = getenv("HOMEDRIVE");
    zPath = getenv("HOMEPATH");
    if(zDrive && zPath){
      n = strlen30(zDrive) + strlen30(zPath) + 1;
      home_dir = malloc(n);
      if(home_dir==0) return 0;
      sqlite3_snprintf(n, home_dir, "%s%s", zDrive, zPath);
      return home_dir;
    }
    home_dir = "c:\\";
  }
#endif
#endif /* !_WIN32_WCE */
  if(home_dir){
    int n = strlen30(home_dir) + 1;
    char *z = malloc(n);
    if(z) memcpy(z, home_dir, n);
    home_dir = z;
  }
  return home_dir;
}
freeColumnList()
static void freeColumnList (char ** azCol) [static]
Definition at line 11746 of file shell.c.
References sqlite3_free.
Referenced by dump_callback(), and tableColumnList().
                                        {
  int i;
  for(i=1; azCol[i]; i++){
    sqlite3_free(azCol[i]);
  }
  /* azCol[0] is a static string */
  sqlite3_free(azCol);
}
freeText()
static void freeText (ShellText * p) [static]
Definition at line 737 of file shell.c.
References initText(), and ShellText::z.
Referenced by do_meta_command(), dump_callback(), and shellFakeSchema().
                                  {
  free(p->z);
  initText(p);
}
fsdirBestIndex()
static int fsdirBestIndex (sqlite3_vtab * tab, sqlite3_index_info * pIdxInfo) [static]
Definition at line 2902 of file shell.c.
References sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, sqlite3_index_info::sqlite3_index_constraint_usage::argvIndex, sqlite3_index_info::estimatedCost, sqlite3_index_info::estimatedRows, FSDIR_COLUMN_DIR, FSDIR_COLUMN_PATH, sqlite3_index_info::idxNum, sqlite3_index_info::nConstraint, sqlite3_index_info::sqlite3_index_constraint_usage::omit, SQLITE_CONSTRAINT, SQLITE_INDEX_CONSTRAINT_EQ, and SQLITE_OK.
Referenced by fsdirRegister().
 {
  int i; /* Loop over constraints */
  int idxPath = -1; /* Index in pIdxInfo->aConstraint of PATH= */
  int idxDir = -1; /* Index in pIdxInfo->aConstraint of DIR= */
  int seenPath = 0; /* True if an unusable PATH= constraint is seen */
  int seenDir = 0; /* True if an unusable DIR= constraint is seen */
  const struct sqlite3_index_constraint *pConstraint;
  (void)tab;
  pConstraint = pIdxInfo->aConstraint;
  for(i=0; i<pIdxInfo->nConstraint; i++, pConstraint++){
    if(pConstraint->op!=SQLITE_INDEX_CONSTRAINT_EQ) continue;
    switch(pConstraint->iColumn){
      case FSDIR_COLUMN_PATH: {
        if(pConstraint->usable){
          idxPath = i;
          seenPath = 0;
        }else if(idxPath<0){
          seenPath = 1;
        }
        break;
      }
      case FSDIR_COLUMN_DIR: {
        if(pConstraint->usable){
          idxDir = i;
          seenDir = 0;
        }else if(idxDir<0){
          seenDir = 1;
        }
        break;
      }
    }
  }
  if(seenPath || seenDir){
    /* If input parameters are unusable, disallow this plan */
    return SQLITE_CONSTRAINT;
  }
  if(idxPath<0){
    pIdxInfo->idxNum = 0;
    /* The pIdxInfo->estimatedCost should have been initialized to a huge
    ** number. Leave it unchanged. */
    pIdxInfo->estimatedRows = 0x7fffffff;
  }else{
    pIdxInfo->aConstraintUsage[idxPath].omit = 1;
    pIdxInfo->aConstraintUsage[idxPath].argvIndex = 1;
    if(idxDir>=0){
      pIdxInfo->aConstraintUsage[idxDir].omit = 1;
      pIdxInfo->aConstraintUsage[idxDir].argvIndex = 2;
      pIdxInfo->idxNum = 2;
      pIdxInfo->estimatedCost = 10.0;
    }else{
      pIdxInfo->idxNum = 1;
      pIdxInfo->estimatedCost = 100.0;
    }
  }
  return SQLITE_OK;
}
fsdirClose()
static int fsdirClose (sqlite3_vtab_cursor * cur) [static]
Definition at line 2673 of file shell.c.
References fsdirResetCursor(), sqlite3_free, and SQLITE_OK.
Referenced by fsdirRegister().
                                               {
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  fsdirResetCursor(pCur);
  sqlite3_free(pCur);
  return SQLITE_OK;
}
fsdirColumn()
static int fsdirColumn (sqlite3_vtab_cursor * cur, sqlite3_context * ctx, int i) [static]
Definition at line 2760 of file shell.c.
References FSDIR_COLUMN_DATA, FSDIR_COLUMN_MODE, FSDIR_COLUMN_MTIME, FSDIR_COLUMN_NAME, FSDIR_COLUMN_PATH, fsdir_cursor::nBase, readFileContents(), sqlite3_free, sqlite3_malloc64, sqlite3_result_error_nomem, sqlite3_result_int64, sqlite3_result_null, sqlite3_result_text, SQLITE_NOMEM, SQLITE_OK, SQLITE_TRANSIENT, fsdir_cursor::sStat, and fsdir_cursor::zPath.
Referenced by fsdirRegister().
 {
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  switch(i){
    case FSDIR_COLUMN_NAME: {
      sqlite3_result_text(ctx, &pCur->zPath[pCur->nBase], -1, SQLITE_TRANSIENT);
      break;
    }
    case FSDIR_COLUMN_MODE:
      sqlite3_result_int64(ctx, pCur->sStat.st_mode);
      break;
    case FSDIR_COLUMN_MTIME:
      sqlite3_result_int64(ctx, pCur->sStat.st_mtime);
      break;
    case FSDIR_COLUMN_DATA: {
      mode_t m = pCur->sStat.st_mode;
      if(S_ISDIR(m)){
        sqlite3_result_null(ctx);
#if !defined(_WIN32) && !defined(WIN32)
      }else if(S_ISLNK(m)){
        char aStatic[64];
        char *aBuf = aStatic;
        sqlite3_int64 nBuf = 64;
        int n;
        while(1){
          n = readlink(pCur->zPath, aBuf, nBuf);
          if(n<nBuf) break;
          if(aBuf!=aStatic) sqlite3_free(aBuf);
          nBuf = nBuf*2;
          aBuf = sqlite3_malloc64(nBuf);
          if(aBuf==0){
            sqlite3_result_error_nomem(ctx);
            return SQLITE_NOMEM;
          }
        }
        sqlite3_result_text(ctx, aBuf, n, SQLITE_TRANSIENT);
        if(aBuf!=aStatic) sqlite3_free(aBuf);
#endif
      }else{
        readFileContents(ctx, pCur->zPath);
      }
    }
    case FSDIR_COLUMN_PATH:
    default: {
      /* The FSDIR_COLUMN_PATH and FSDIR_COLUMN_DIR are input parameters.
      ** always return their values as NULL */
      break;
    }
  }
  return SQLITE_OK;
}
fsdirConnect()
static int fsdirConnect (sqlite3 * db, void * pAux, int argc, const char *const * argv, sqlite3_vtab ** ppVtab, char ** pzErr) [static]
Definition at line 2602 of file shell.c.
References FSDIR_SCHEMA, sqlite3_declare_vtab, sqlite3_malloc, sqlite3_vtab_config, SQLITE_NOMEM, SQLITE_OK, and SQLITE_VTAB_DIRECTONLY.
Referenced by fsdirRegister().
 {
  fsdir_tab *pNew = 0;
  int rc;
  (void)pAux;
  (void)argc;
  (void)argv;
  (void)pzErr;
  rc = sqlite3_declare_vtab(db, "CREATE TABLE x" FSDIR_SCHEMA);
  if(rc==SQLITE_OK){
    pNew = (fsdir_tab*)sqlite3_malloc(sizeof(*pNew));
    if(pNew==0) return SQLITE_NOMEM;
    memset(pNew, 0, sizeof(*pNew));
    sqlite3_vtab_config(db, SQLITE_VTAB_DIRECTONLY);
  }
  *ppVtab = (sqlite3_vtab*)pNew;
  return rc;
}
fsdirDisconnect()
static int fsdirDisconnect (sqlite3_vtab * pVtab) [static]
Definition at line 2629 of file shell.c.
References sqlite3_free, and SQLITE_OK.
Referenced by fsdirRegister().
                                               {
  sqlite3_free(pVtab);
  return SQLITE_OK;
}
fsdirEof()
static int fsdirEof (sqlite3_vtab_cursor * cur) [static]
Definition at line 2835 of file shell.c.
References fsdir_cursor::zPath.
Referenced by fsdirRegister().
                                             {
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  return (pCur->zPath==0);
}
fsdirFilter()
static int fsdirFilter (sqlite3_vtab_cursor * cur, int idxNum, const char * idxStr, int argc, sqlite3_value ** argv) [static]
Definition at line 2846 of file shell.c.
References fileLinkStat(), fsdirResetCursor(), fsdirSetErrmsg(), fsdir_cursor::nBase, sqlite3_mprintf, sqlite3_value_text, SQLITE_ERROR, SQLITE_NOMEM, SQLITE_OK, fsdir_cursor::sStat, fsdir_cursor::zBase, and fsdir_cursor::zPath.
Referenced by fsdirRegister().
 {
  const char *zDir = 0;
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  (void)idxStr;
  fsdirResetCursor(pCur);
  if(idxNum==0){
    fsdirSetErrmsg(pCur, "table function fsdir requires an argument");
    return SQLITE_ERROR;
  }
  assert(argc==idxNum && (argc==1 || argc==2));
  zDir = (const char*)sqlite3_value_text(argv[0]);
  if(zDir==0){
    fsdirSetErrmsg(pCur, "table function fsdir requires a non-NULL argument");
    return SQLITE_ERROR;
  }
  if(argc==2){
    pCur->zBase = (const char*)sqlite3_value_text(argv[1]);
  }
  if(pCur->zBase){
    pCur->nBase = (int)strlen(pCur->zBase)+1;
    pCur->zPath = sqlite3_mprintf("%s/%s", pCur->zBase, zDir);
  }else{
    pCur->zPath = sqlite3_mprintf("%s", zDir);
  }
  if(pCur->zPath==0){
    return SQLITE_NOMEM;
  }
  if(fileLinkStat(pCur->zPath, &pCur->sStat)){
    fsdirSetErrmsg(pCur, "cannot stat file: %s", pCur->zPath);
    return SQLITE_ERROR;
  }
  return SQLITE_OK;
}
fsdirNext()
static int fsdirNext (sqlite3_vtab_cursor * cur) [static]
Definition at line 2696 of file shell.c.
References fsdir_cursor::aLvl, fileLinkStat(), fsdirSetErrmsg(), fsdir_cursor::iLvl, fsdir_cursor::iRowid, fsdir_cursor::nLvl, FsdirLevel::pDir, sqlite3_free, sqlite3_mprintf, sqlite3_realloc64, SQLITE_ERROR, SQLITE_NOMEM, SQLITE_OK, fsdir_cursor::sStat, FsdirLevel::zDir, and fsdir_cursor::zPath.
Referenced by fsdirRegister().
                                              {
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  mode_t m = pCur->sStat.st_mode;
  pCur->iRowid++;
  if(S_ISDIR(m)){
    /* Descend into this directory */
    int iNew = pCur->iLvl + 1;
    FsdirLevel *pLvl;
    if(iNew>=pCur->nLvl){
      int nNew = iNew+1;
      sqlite3_int64 nByte = nNew*sizeof(FsdirLevel);
      FsdirLevel *aNew = (FsdirLevel*)sqlite3_realloc64(pCur->aLvl, nByte);
      if(aNew==0) return SQLITE_NOMEM;
      memset(&aNew[pCur->nLvl], 0, sizeof(FsdirLevel)*(nNew-pCur->nLvl));
      pCur->aLvl = aNew;
      pCur->nLvl = nNew;
    }
    pCur->iLvl = iNew;
    pLvl = &pCur->aLvl[iNew];
    
    pLvl->zDir = pCur->zPath;
    pCur->zPath = 0;
    pLvl->pDir = opendir(pLvl->zDir);
    if(pLvl->pDir==0){
      fsdirSetErrmsg(pCur, "cannot read directory: %s", pCur->zPath);
      return SQLITE_ERROR;
    }
  }
  while(pCur->iLvl>=0){
    FsdirLevel *pLvl = &pCur->aLvl[pCur->iLvl];
    struct dirent *pEntry = readdir(pLvl->pDir);
    if(pEntry){
      if(pEntry->d_name[0]=='.'){
       if(pEntry->d_name[1]=='.' && pEntry->d_name[2]=='\0') continue;
       if(pEntry->d_name[1]=='\0') continue;
      }
      sqlite3_free(pCur->zPath);
      pCur->zPath = sqlite3_mprintf("%s/%s", pLvl->zDir, pEntry->d_name);
      if(pCur->zPath==0) return SQLITE_NOMEM;
      if(fileLinkStat(pCur->zPath, &pCur->sStat)){
        fsdirSetErrmsg(pCur, "cannot stat file: %s", pCur->zPath);
        return SQLITE_ERROR;
      }
      return SQLITE_OK;
    }
    closedir(pLvl->pDir);
    sqlite3_free(pLvl->zDir);
    pLvl->pDir = 0;
    pLvl->zDir = 0;
    pCur->iLvl--;
  }
  /* EOF */
  sqlite3_free(pCur->zPath);
  pCur->zPath = 0;
  return SQLITE_OK;
}
fsdirOpen()
static int fsdirOpen (sqlite3_vtab * p, sqlite3_vtab_cursor ** ppCursor) [static]
Definition at line 2637 of file shell.c.
References fsdir_cursor::base, fsdir_cursor::iLvl, sqlite3_malloc, SQLITE_NOMEM, and SQLITE_OK.
Referenced by fsdirRegister().
                                                                     {
  fsdir_cursor *pCur;
  (void)p;
  pCur = sqlite3_malloc(sizeof(*pCur));
  if(pCur==0) return SQLITE_NOMEM;
  memset(pCur, 0, sizeof(*pCur));
  pCur->iLvl = -1;
  *ppCursor = &pCur->base;
  return SQLITE_OK;
}
fsdirRegister()
static int fsdirRegister (sqlite3 * db) [static]
Definition at line 2968 of file shell.c.
References fsdirBestIndex(), fsdirClose(), fsdirColumn(), fsdirConnect(), fsdirDisconnect(), fsdirEof(), fsdirFilter(), fsdirNext(), fsdirOpen(), fsdirRowid(), and sqlite3_create_module.
Referenced by sqlite3_fileio_init().
                                     {
  static sqlite3_module fsdirModule = {
    0, /* iVersion */
    0, /* xCreate */
    fsdirConnect, /* xConnect */
    fsdirBestIndex, /* xBestIndex */
    fsdirDisconnect, /* xDisconnect */
    0, /* xDestroy */
    fsdirOpen, /* xOpen - open a cursor */
    fsdirClose, /* xClose - close a cursor */
    fsdirFilter, /* xFilter - configure scan constraints */
    fsdirNext, /* xNext - advance a cursor */
    fsdirEof, /* xEof - check for end of scan */
    fsdirColumn, /* xColumn - read data */
    fsdirRowid, /* xRowid - read data */
    0, /* xUpdate */
    0, /* xBegin */
    0, /* xSync */
    0, /* xCommit */
    0, /* xRollback */
    0, /* xFindMethod */
    0, /* xRename */
    0, /* xSavepoint */
    0, /* xRelease */
    0, /* xRollbackTo */
    0, /* xShadowName */
  };
  int rc = sqlite3_create_module(db, "fsdir", &fsdirModule, 0);
  return rc;
}
fsdirResetCursor()
static void fsdirResetCursor (fsdir_cursor * pCur) [static]
Definition at line 2652 of file shell.c.
References fsdir_cursor::aLvl, fsdir_cursor::iLvl, fsdir_cursor::iRowid, fsdir_cursor::nBase, fsdir_cursor::nLvl, FsdirLevel::pDir, sqlite3_free, fsdir_cursor::zBase, FsdirLevel::zDir, and fsdir_cursor::zPath.
Referenced by fsdirClose(), and fsdirFilter().
                                                {
  int i;
  for(i=0; i<=pCur->iLvl; i++){
    FsdirLevel *pLvl = &pCur->aLvl[i];
    if(pLvl->pDir) closedir(pLvl->pDir);
    sqlite3_free(pLvl->zDir);
  }
  sqlite3_free(pCur->zPath);
  sqlite3_free(pCur->aLvl);
  pCur->aLvl = 0;
  pCur->zPath = 0;
  pCur->zBase = 0;
  pCur->nBase = 0;
  pCur->nLvl = 0;
  pCur->iLvl = -1;
  pCur->iRowid = 1;
}
fsdirRowid()
static int fsdirRowid (sqlite3_vtab_cursor * cur, sqlite_int64 * pRowid) [static]
Definition at line 2825 of file shell.c.
References fsdir_cursor::iRowid, and SQLITE_OK.
Referenced by fsdirRegister().
                                                                     {
  fsdir_cursor *pCur = (fsdir_cursor*)cur;
  *pRowid = pCur->iRowid;
  return SQLITE_OK;
}
fsdirSetErrmsg()
static void fsdirSetErrmsg (fsdir_cursor * pCur, const char * zFmt, ...) [static]
Definition at line 2685 of file shell.c.
References fsdir_cursor::base, sqlite3_vtab_cursor::pVtab, sqlite3_vmprintf, and sqlite3_vtab::zErrMsg.
Referenced by fsdirFilter(), and fsdirNext().
                                                                     {
  va_list ap;
  va_start(ap, zFmt);
  pCur->base.pVtab->zErrMsg = sqlite3_vmprintf(zFmt, ap);
  va_end(ap);
}
get2byteInt()
static unsigned int get2byteInt (unsigned char * a) [static]
Definition at line 13486 of file shell.c.
Referenced by shell_dbinfo_command().
                                                 {
  return (a[0]<<8) + a[1];
}
get4byteInt()
static unsigned int get4byteInt (unsigned char * a) [static]
Definition at line 13489 of file shell.c.
Referenced by shell_dbinfo_command().
                                                 {
  return (a[0]<<24) + (a[1]<<16) + (a[2]<<8) + a[3];
}
hash_step_vformat()
static void hash_step_vformat (SHA3Context * p, const char * zFormat, ...) [static]
Definition at line 1841 of file shell.c.
References SHA3Update(), and sqlite3_vsnprintf.
Referenced by sha3QueryFunc().
 {
  va_list ap;
  int n;
  char zBuf[50];
  va_start(ap, zFormat);
  sqlite3_vsnprintf(sizeof(zBuf),zBuf,zFormat,ap);
  va_end(ap);
  n = (int)strlen(zBuf);
  SHA3Update(p, (unsigned char*)zBuf, n);
}
hexDigitValue()
static int hexDigitValue (char c) [static]
Definition at line 668 of file shell.c.
Referenced by booleanValue(), and integerValue().
                                {
  if(c>='0' && c<='9') return c - '0';
  if(c>='a' && c<='f') return c - 'a' + 10;
  if(c>='A' && c<='F') return c - 'A' + 10;
  return -1;
}
idxAppendColDefn()
static char* idxAppendColDefn (int * pRc, char * zIn, IdxTable * pTab, IdxConstraint * pCons) [static]
Definition at line 7512 of file shell.c.
References IdxTable::aCol, IdxConstraint::bDesc, IdxConstraint::iCol, idxAppendText(), idxIdentifierRequiresQuotes(), sqlite3_stricmp, IdxConstraint::zColl, IdxColumn::zColl, and IdxColumn::zName.
Referenced by idxCreateFromCons().
 {
  char *zRet = zIn;
  IdxColumn *p = &pTab->aCol[pCons->iCol];
  if(zRet) zRet = idxAppendText(pRc, zRet, ", ");
  if(idxIdentifierRequiresQuotes(p->zName)){
    zRet = idxAppendText(pRc, zRet, "%Q", p->zName);
  }else{
    zRet = idxAppendText(pRc, zRet, "%s", p->zName);
  }
  if(sqlite3_stricmp(p->zColl, pCons->zColl)){
    if(idxIdentifierRequiresQuotes(pCons->zColl)){
      zRet = idxAppendText(pRc, zRet, " COLLATE %Q", pCons->zColl);
    }else{
      zRet = idxAppendText(pRc, zRet, " COLLATE %s", pCons->zColl);
    }
  }
  if(pCons->bDesc){
    zRet = idxAppendText(pRc, zRet, " DESC");
  }
  return zRet;
}
idxAppendText()
static char* idxAppendText (int * pRc, char * zIn, const char * zFmt, ...) [static]
Definition at line 7462 of file shell.c.
References sqlite3_free, sqlite3_malloc, sqlite3_vmprintf, SQLITE_NOMEM, SQLITE_OK, and STRLEN.
Referenced by idxAppendColDefn(), idxCreateVtabSchema(), idxFindIndexes(), idxPopulateOneStat1(), idxProcessOneTrigger(), and sqlite3_expert_analyze().
                                                                      {
  va_list ap;
  char *zAppend = 0;
  char *zRet = 0;
  int nIn = zIn ? STRLEN(zIn) : 0;
  int nAppend = 0;
  va_start(ap, zFmt);
  if(*pRc==SQLITE_OK){
    zAppend = sqlite3_vmprintf(zFmt, ap);
    if(zAppend){
      nAppend = STRLEN(zAppend);
      zRet = (char*)sqlite3_malloc(nIn + nAppend + 1);
    }
    if(zAppend && zRet){
      if(nIn) memcpy(zRet, zIn, nIn);
      memcpy(&zRet[nIn], zAppend, nAppend+1);
    }else{
      sqlite3_free(zRet);
      zRet = 0;
      *pRc = SQLITE_NOMEM;
    }
    sqlite3_free(zAppend);
    sqlite3_free(zIn);
  }
  va_end(ap);
  return zRet;
}
idxAuthCallback()
static int idxAuthCallback (void * pCtx, int eOp, const char * z3, const char * z4, const char * zDb, const char * zTrigger) [static]
Definition at line 7879 of file shell.c.
References IdxWrite::eOp, idxMalloc(), IdxTable::pNext, IdxWrite::pNext, IdxWrite::pTab, sqlite3expert::pTable, sqlite3expert::pWrite, sqlite3_stricmp, SQLITE_DELETE, SQLITE_INSERT, SQLITE_OK, SQLITE_UPDATE, and IdxTable::zName.
Referenced by sqlite3_expert_new().
 {
  int rc = SQLITE_OK;
  (void)z4;
  (void)zTrigger;
  if(eOp==SQLITE_INSERT || eOp==SQLITE_UPDATE || eOp==SQLITE_DELETE){
    if(sqlite3_stricmp(zDb, "main")==0){
      sqlite3expert *p = (sqlite3expert*)pCtx;
      IdxTable *pTab;
      for(pTab=p->pTable; pTab; pTab=pTab->pNext){
        if(0==sqlite3_stricmp(z3, pTab->zName)) break;
      }
      if(pTab){
        IdxWrite *pWrite;
        for(pWrite=p->pWrite; pWrite; pWrite=pWrite->pNext){
          if(pWrite->pTab==pTab && pWrite->eOp==eOp) break;
        }
        if(pWrite==0){
          pWrite = idxMalloc(&rc, sizeof(IdxWrite));
          if(rc==SQLITE_OK){
            pWrite->pTab = pTab;
            pWrite->eOp = eOp;
            pWrite->pNext = p->pWrite;
            p->pWrite = pWrite;
          }
        }
      }
    }
  }
  return rc;
}
idxBuildSampleTable()
static int idxBuildSampleTable (sqlite3expert * p, const char * zTab) [static]
Definition at line 8318 of file shell.c.
References sqlite3expert::dbv, sqlite3_exec, sqlite3_free, sqlite3_mprintf, SQLITE_NOMEM, SQLITE_OK, and UNIQUE_TABLE_NAME.
Referenced by idxPopulateStat1().
                                                                  {
  int rc;
  char *zSql;
  rc = sqlite3_exec(p->dbv,"DROP TABLE IF EXISTS temp."UNIQUE_TABLE_NAME,0,0,0);
  if(rc!=SQLITE_OK) return rc;
  zSql = sqlite3_mprintf(
      "CREATE TABLE temp." UNIQUE_TABLE_NAME " AS SELECT * FROM %Q", zTab
  );
  if(zSql==0) return SQLITE_NOMEM;
  rc = sqlite3_exec(p->dbv, zSql, 0, 0, 0);
  sqlite3_free(zSql);
  return rc;
}
idxConstraintFree()
static void idxConstraintFree (IdxConstraint * pConstraint) [static]
Definition at line 7742 of file shell.c.
References IdxConstraint::pNext, and sqlite3_free.
Referenced by idxScanFree().
                                                         {
  IdxConstraint *pNext;
  IdxConstraint *p;
  for(p=pConstraint; p; p=pNext){
    pNext = p->pNext;
    sqlite3_free(p);
  }
}
idxCreateCandidates()
static int idxCreateCandidates (sqlite3expert * p) [static]
Definition at line 7725 of file shell.c.
References idxCreateFromWhere(), IdxScan::pNextScan, IdxScan::pOrder, sqlite3expert::pScan, and SQLITE_OK.
Referenced by sqlite3_expert_analyze().
                                                {
  int rc = SQLITE_OK;
  IdxScan *pIter;
  for(pIter=p->pScan; pIter && rc==SQLITE_OK; pIter=pIter->pNextScan){
    rc = idxCreateFromWhere(p, pIter, 0);
    if(rc==SQLITE_OK && pIter->pOrder){
      rc = idxCreateFromWhere(p, pIter, pIter->pOrder);
    }
  }
  return rc;
}
idxCreateFromCons()
static int idxCreateFromCons (sqlite3expert * p, IdxScan * pScan, IdxConstraint * pEq, IdxConstraint * pTail) [static]
Definition at line 7617 of file shell.c.
References sqlite3expert::dbm, sqlite3expert::hIdx, idxAppendColDefn(), idxFindCompatible(), idxHashAdd(), idxIdentifierRequiresQuotes(), IdxConstraint::pLink, IdxScan::pTab, sqlite3expert::pzErrmsg, sqlite3_exec, sqlite3_free, sqlite3_mprintf, SQLITE_NOMEM, SQLITE_OK, IdxTable::zName, and zName.
Referenced by idxCreateFromWhere().
 {
  sqlite3 *dbm = p->dbm;
  int rc = SQLITE_OK;
  if((pEq || pTail) && 0==idxFindCompatible(&rc, dbm, pScan, pEq, pTail)){
    IdxTable *pTab = pScan->pTab;
    char *zCols = 0;
    char *zIdx = 0;
    IdxConstraint *pCons;
    unsigned int h = 0;
    const char *zFmt;
    for(pCons=pEq; pCons; pCons=pCons->pLink){
      zCols = idxAppendColDefn(&rc, zCols, pTab, pCons);
    }
    for(pCons=pTail; pCons; pCons=pCons->pLink){
      zCols = idxAppendColDefn(&rc, zCols, pTab, pCons);
    }
    if(rc==SQLITE_OK){
      /* Hash the list of columns to come up with a name for the index */
      const char *zTable = pScan->pTab->zName;
      char *zName; /* Index name */
      int i;
      for(i=0; zCols[i]; i++){
        h += ((h<<3) + zCols[i]);
      }
      zName = sqlite3_mprintf("%s_idx_%08x", zTable, h);
      if(zName==0){
        rc = SQLITE_NOMEM;
      }else{
        if(idxIdentifierRequiresQuotes(zTable)){
          zFmt = "CREATE INDEX '%q' ON %Q(%s)";
        }else{
          zFmt = "CREATE INDEX %s ON %s(%s)";
        }
        zIdx = sqlite3_mprintf(zFmt, zName, zTable, zCols);
        if(!zIdx){
          rc = SQLITE_NOMEM;
        }else{
          rc = sqlite3_exec(dbm, zIdx, 0, 0, p->pzErrmsg);
          idxHashAdd(&rc, &p->hIdx, zName, zIdx);
        }
        sqlite3_free(zName);
        sqlite3_free(zIdx);
      }
    }
    sqlite3_free(zCols);
  }
  return rc;
}
idxCreateFromWhere()
static int idxCreateFromWhere (sqlite3expert * p, IdxScan * pScan, IdxConstraint * pTail) [static]
Definition at line 7686 of file shell.c.
References idxCreateFromCons(), idxFindConstraint(), IdxScan::pEq, IdxConstraint::pLink, IdxConstraint::pNext, IdxScan::pRange, and SQLITE_OK.
Referenced by idxCreateCandidates().
 {
  IdxConstraint *p1 = 0;
  IdxConstraint *pCon;
  int rc;
  /* Gather up all the == constraints. */
  for(pCon=pScan->pEq; pCon; pCon=pCon->pNext){
    if(!idxFindConstraint(p1, pCon) && !idxFindConstraint(pTail, pCon)){
      pCon->pLink = p1;
      p1 = pCon;
    }
  }
  /* Create an index using the == constraints collected above. And the
  ** range constraint/ORDER BY terms passed in by the caller, if any. */
  rc = idxCreateFromCons(p, pScan, p1, pTail);
  /* If no range/ORDER BY passed by the caller, create a version of the
  ** index for each range constraint. */
  if(pTail==0){
    for(pCon=pScan->pRange; rc==SQLITE_OK && pCon; pCon=pCon->pNext){
      assert(pCon->pLink==0);
      if(!idxFindConstraint(p1, pCon) && !idxFindConstraint(pTail, pCon)){
        rc = idxCreateFromCons(p, pScan, p1, pCon);
      }
    }
  }
  return rc;
}
idxCreateVtabSchema()
static int idxCreateVtabSchema (sqlite3expert * p, char ** pzErrmsg) [static]
Definition at line 8017 of file shell.c.
References IdxTable::aCol, sqlite3expert::db, sqlite3expert::dbv, idxAppendText(), idxFinalize(), idxGetTableInfo(), idxPrepareStmt(), idxRegisterVtab(), IdxTable::nCol, IdxTable::pNext, sqlite3expert::pTable, sqlite3_column_text, sqlite3_exec, sqlite3_free, sqlite3_step, SQLITE_OK, SQLITE_ROW, IdxColumn::zColl, and IdxColumn::zName.
Referenced by sqlite3_expert_new().
                                                                 {
  int rc = idxRegisterVtab(p);
  sqlite3_stmt *pSchema = 0;
  /* For each table in the main db schema:
  **
  ** 1) Add an entry to the p->pTable list, and
  ** 2) Create the equivalent virtual table in dbv.
  */
  rc = idxPrepareStmt(p->db, &pSchema, pzErrmsg,
      "SELECT type, name, sql, 1 FROM sqlite_master "
      "WHERE type IN ('table','view') AND name NOT LIKE 'sqlite_%%' "
      " UNION ALL "
      "SELECT type, name, sql, 2 FROM sqlite_master "
      "WHERE type = 'trigger'"
      " AND tbl_name IN(SELECT name FROM sqlite_master WHERE type = 'view') "
      "ORDER BY 4, 1"
  );
  while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pSchema)){
    const char *zType = (const char*)sqlite3_column_text(pSchema, 0);
    const char *zName = (const char*)sqlite3_column_text(pSchema, 1);
    const char *zSql = (const char*)sqlite3_column_text(pSchema, 2);
    if(zType[0]=='v' || zType[1]=='r'){
      rc = sqlite3_exec(p->dbv, zSql, 0, 0, pzErrmsg);
    }else{
      IdxTable *pTab;
      rc = idxGetTableInfo(p->db, zName, &pTab, pzErrmsg);
      if(rc==SQLITE_OK){
        int i;
        char *zInner = 0;
        char *zOuter = 0;
        pTab->pNext = p->pTable;
        p->pTable = pTab;
        /* The statement the vtab will pass to sqlite3_declare_vtab() */
        zInner = idxAppendText(&rc, 0, "CREATE TABLE x(");
        for(i=0; i<pTab->nCol; i++){
          zInner = idxAppendText(&rc, zInner, "%s%Q COLLATE %s",
              (i==0 ? "" : ", "), pTab->aCol[i].zName, pTab->aCol[i].zColl
          );
        }
        zInner = idxAppendText(&rc, zInner, ")");
        /* The CVT statement to create the vtab */
        zOuter = idxAppendText(&rc, 0,
            "CREATE VIRTUAL TABLE %Q USING expert(%Q)", zName, zInner
        );
        if(rc==SQLITE_OK){
          rc = sqlite3_exec(p->dbv, zOuter, 0, 0, pzErrmsg);
        }
        sqlite3_free(zInner);
        sqlite3_free(zOuter);
      }
    }
  }
  idxFinalize(&rc, pSchema);
  return rc;
}
idxDatabaseError()
static void idxDatabaseError (sqlite3 * db, char ** pzErrmsg) [static]
Definition at line 7003 of file shell.c.
References sqlite3_errmsg, and sqlite3_mprintf.
Referenced by idxPrepareStmt(), idxProcessOneTrigger(), and sqlite3_expert_sql().
 {
  *pzErrmsg = sqlite3_mprintf("%s", sqlite3_errmsg(db));
}
idxFinalize()
static void idxFinalize (int * pRc, sqlite3_stmt * pStmt) [static]
Definition at line 7366 of file shell.c.
References sqlite3_finalize, and SQLITE_OK.
Referenced by idxCreateVtabSchema(), idxFindCompatible(), idxFindIndexes(), idxGetTableInfo(), idxLargestIndex(), idxPopulateOneStat1(), idxPopulateStat1(), idxProcessOneTrigger(), and sqlite3_expert_new().
                                                      {
  int rc = sqlite3_finalize(pStmt);
  if(*pRc==SQLITE_OK) *pRc = rc;
}
idxFindCompatible()
static int idxFindCompatible (int * pRc, sqlite3 * dbm, IdxScan * pScan, IdxConstraint * pEq, IdxConstraint * pTail) [static]
Definition at line 7550 of file shell.c.
References IdxConstraint::bFlag, IdxConstraint::iCol, idxFinalize(), idxPrintfPrepareStmt(), IdxConstraint::pLink, IdxScan::pTab, sqlite3_column_int, sqlite3_column_text, sqlite3_finalize, sqlite3_step, sqlite3_stricmp, SQLITE_OK, SQLITE_ROW, IdxConstraint::zColl, and IdxTable::zName.
Referenced by idxCreateFromCons().
 {
  const char *zTbl = pScan->pTab->zName;
  sqlite3_stmt *pIdxList = 0;
  IdxConstraint *pIter;
  int nEq = 0; /* Number of elements in pEq */
  int rc;
  /* Count the elements in list pEq */
  for(pIter=pEq; pIter; pIter=pIter->pLink) nEq++;
  rc = idxPrintfPrepareStmt(dbm, &pIdxList, 0, "PRAGMA index_list=%Q", zTbl);
  while(rc==SQLITE_OK && sqlite3_step(pIdxList)==SQLITE_ROW){
    int bMatch = 1;
    IdxConstraint *pT = pTail;
    sqlite3_stmt *pInfo = 0;
    const char *zIdx = (const char*)sqlite3_column_text(pIdxList, 1);
    /* Zero the IdxConstraint.bFlag values in the pEq list */
    for(pIter=pEq; pIter; pIter=pIter->pLink) pIter->bFlag = 0;
    rc = idxPrintfPrepareStmt(dbm, &pInfo, 0, "PRAGMA index_xInfo=%Q", zIdx);
    while(rc==SQLITE_OK && sqlite3_step(pInfo)==SQLITE_ROW){
      int iIdx = sqlite3_column_int(pInfo, 0);
      int iCol = sqlite3_column_int(pInfo, 1);
      const char *zColl = (const char*)sqlite3_column_text(pInfo, 4);
      if(iIdx<nEq){
        for(pIter=pEq; pIter; pIter=pIter->pLink){
          if(pIter->bFlag) continue;
          if(pIter->iCol!=iCol) continue;
          if(sqlite3_stricmp(pIter->zColl, zColl)) continue;
          pIter->bFlag = 1;
          break;
        }
        if(pIter==0){
          bMatch = 0;
          break;
        }
      }else{
        if(pT){
          if(pT->iCol!=iCol || sqlite3_stricmp(pT->zColl, zColl)){
            bMatch = 0;
            break;
          }
          pT = pT->pLink;
        }
      }
    }
    idxFinalize(&rc, pInfo);
    if(rc==SQLITE_OK && bMatch){
      sqlite3_finalize(pIdxList);
      return 1;
    }
  }
  idxFinalize(&rc, pIdxList);
  *pRc = rc;
  return 0;
}
idxFindConstraint()
static int idxFindConstraint (IdxConstraint * pList, IdxConstraint * p) [static]
Definition at line 7678 of file shell.c.
References IdxConstraint::iCol, and IdxConstraint::pLink.
Referenced by idxCreateFromWhere().
                                                                    {
  IdxConstraint *pCmp;
  for(pCmp=pList; pCmp; pCmp=pCmp->pLink){
    if(p->iCol==pCmp->iCol) return 1;
  }
  return 0;
}
idxFindIndexes()
int idxFindIndexes (sqlite3expert * p, char ** pzErr)
Definition at line 7814 of file shell.c.
References sqlite3expert::dbm, sqlite3expert::hIdx, idxAppendText(), idxFinalize(), idxHashAdd(), idxHashClear(), idxHashInit(), idxHashSearch(), idxPrintfPrepareStmt(), IdxHash::pFirst, IdxStatement::pNext, IdxHashEntry::pNext, sqlite3expert::pStatement, sqlite3_column_text, sqlite3_step, SQLITE_OK, SQLITE_ROW, STRLEN, IdxStatement::zEQP, IdxStatement::zIdx, IdxHashEntry::zKey, and IdxStatement::zSql.
Referenced by sqlite3_expert_analyze().
 {
  IdxStatement *pStmt;
  sqlite3 *dbm = p->dbm;
  int rc = SQLITE_OK;
  IdxHash hIdx;
  idxHashInit(&hIdx);
  for(pStmt=p->pStatement; rc==SQLITE_OK && pStmt; pStmt=pStmt->pNext){
    IdxHashEntry *pEntry;
    sqlite3_stmt *pExplain = 0;
    idxHashClear(&hIdx);
    rc = idxPrintfPrepareStmt(dbm, &pExplain, pzErr,
        "EXPLAIN QUERY PLAN %s", pStmt->zSql
    );
    while(rc==SQLITE_OK && sqlite3_step(pExplain)==SQLITE_ROW){
      /* int iId = sqlite3_column_int(pExplain, 0); */
      /* int iParent = sqlite3_column_int(pExplain, 1); */
      /* int iNotUsed = sqlite3_column_int(pExplain, 2); */
      const char *zDetail = (const char*)sqlite3_column_text(pExplain, 3);
      int nDetail = STRLEN(zDetail);
      int i;
      for(i=0; i<nDetail; i++){
        const char *zIdx = 0;
        if(memcmp(&zDetail[i], " USING INDEX ", 13)==0){
          zIdx = &zDetail[i+13];
        }else if(memcmp(&zDetail[i], " USING COVERING INDEX ", 22)==0){
          zIdx = &zDetail[i+22];
        }
        if(zIdx){
          const char *zSql;
          int nIdx = 0;
          while(zIdx[nIdx]!='\0' && (zIdx[nIdx]!=' ' || zIdx[nIdx+1]!='(')){
            nIdx++;
          }
          zSql = idxHashSearch(&p->hIdx, zIdx, nIdx);
          if(zSql){
            idxHashAdd(&rc, &hIdx, zSql, 0);
            if(rc) goto find_indexes_out;
          }
          break;
        }
      }
      if(zDetail[0]!='-'){
        pStmt->zEQP = idxAppendText(&rc, pStmt->zEQP, "%s\n", zDetail);
      }
    }
    for(pEntry=hIdx.pFirst; pEntry; pEntry=pEntry->pNext){
      pStmt->zIdx = idxAppendText(&rc, pStmt->zIdx, "%s;\n", pEntry->zKey);
    }
    idxFinalize(&rc, pExplain);
  }
 find_indexes_out:
  idxHashClear(&hIdx);
  return rc;
}
idxGetTableInfo()
static int idxGetTableInfo (sqlite3 * db, const char * zTab, IdxTable ** ppOut, char ** pzErrmsg) [static]
Definition at line 7381 of file shell.c.
References IdxTable::aCol, idxFinalize(), idxMalloc(), idxPrintfPrepareStmt(), IdxColumn::iPk, IdxTable::nCol, sqlite3_column_int, sqlite3_column_text, sqlite3_free, sqlite3_reset, sqlite3_step, sqlite3_table_column_metadata, SQLITE_OK, SQLITE_ROW, STRLEN, IdxColumn::zColl, IdxColumn::zName, and IdxTable::zName.
Referenced by idxCreateVtabSchema().
 {
  sqlite3_stmt *p1 = 0;
  int nCol = 0;
  int nTab = STRLEN(zTab);
  int nByte = sizeof(IdxTable) + nTab + 1;
  IdxTable *pNew = 0;
  int rc, rc2;
  char *pCsr = 0;
  rc = idxPrintfPrepareStmt(db, &p1, pzErrmsg, "PRAGMA table_info=%Q", zTab);
  while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(p1)){
    const char *zCol = (const char*)sqlite3_column_text(p1, 1);
    nByte += 1 + STRLEN(zCol);
    rc = sqlite3_table_column_metadata(
        db, "main", zTab, zCol, 0, &zCol, 0, 0, 0
    );
    nByte += 1 + STRLEN(zCol);
    nCol++;
  }
  rc2 = sqlite3_reset(p1);
  if(rc==SQLITE_OK) rc = rc2;
  nByte += sizeof(IdxColumn) * nCol;
  if(rc==SQLITE_OK){
    pNew = idxMalloc(&rc, nByte);
  }
  if(rc==SQLITE_OK){
    pNew->aCol = (IdxColumn*)&pNew[1];
    pNew->nCol = nCol;
    pCsr = (char*)&pNew->aCol[nCol];
  }
  nCol = 0;
  while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(p1)){
    const char *zCol = (const char*)sqlite3_column_text(p1, 1);
    int nCopy = STRLEN(zCol) + 1;
    pNew->aCol[nCol].zName = pCsr;
    pNew->aCol[nCol].iPk = sqlite3_column_int(p1, 5);
    memcpy(pCsr, zCol, nCopy);
    pCsr += nCopy;
    rc = sqlite3_table_column_metadata(
        db, "main", zTab, zCol, 0, &zCol, 0, 0, 0
    );
    if(rc==SQLITE_OK){
      nCopy = STRLEN(zCol) + 1;
      pNew->aCol[nCol].zColl = pCsr;
      memcpy(pCsr, zCol, nCopy);
      pCsr += nCopy;
    }
    nCol++;
  }
  idxFinalize(&rc, p1);
  if(rc!=SQLITE_OK){
    sqlite3_free(pNew);
    pNew = 0;
  }else{
    pNew->zName = pCsr;
    memcpy(pNew->zName, zTab, nTab+1);
  }
  *ppOut = pNew;
  return rc;
}
idxHashAdd()
static int idxHashAdd (int * pRc, IdxHash * pHash, const char * zKey, const char * zVal) [static]
Definition at line 6919 of file shell.c.
References IdxHash::aHash, idxHashString(), idxMalloc(), IdxHash::pFirst, IdxHashEntry::pHashNext, IdxHashEntry::pNext, STRLEN, IdxHashEntry::zKey, and IdxHashEntry::zVal.
Referenced by idxCreateFromCons(), and idxFindIndexes().
 {
  int nKey = STRLEN(zKey);
  int iHash = idxHashString(zKey, nKey);
  int nVal = (zVal ? STRLEN(zVal) : 0);
  IdxHashEntry *pEntry;
  assert(iHash>=0);
  for(pEntry=pHash->aHash[iHash]; pEntry; pEntry=pEntry->pHashNext){
    if(STRLEN(pEntry->zKey)==nKey && 0==memcmp(pEntry->zKey, zKey, nKey)){
      return 1;
    }
  }
  pEntry = idxMalloc(pRc, sizeof(IdxHashEntry) + nKey+1 + nVal+1);
  if(pEntry){
    pEntry->zKey = (char*)&pEntry[1];
    memcpy(pEntry->zKey, zKey, nKey);
    if(zVal){
      pEntry->zVal = &pEntry->zKey[nKey+1];
      memcpy(pEntry->zVal, zVal, nVal);
    }
    pEntry->pHashNext = pHash->aHash[iHash];
    pHash->aHash[iHash] = pEntry;
    pEntry->pNext = pHash->pFirst;
    pHash->pFirst = pEntry;
  }
  return 0;
}
idxHashClear()
static void idxHashClear (IdxHash * pHash) [static]
Definition at line 6887 of file shell.c.
References IdxHash::aHash, IDX_HASH_SIZE, IdxHashEntry::pHashNext, sqlite3_free, and IdxHashEntry::zVal2.
Referenced by idxFindIndexes(), and sqlite3_expert_destroy().
                                        {
  int i;
  for(i=0; i<IDX_HASH_SIZE; i++){
    IdxHashEntry *pEntry;
    IdxHashEntry *pNext;
    for(pEntry=pHash->aHash[i]; pEntry; pEntry=pNext){
      pNext = pEntry->pHashNext;
      sqlite3_free(pEntry->zVal2);
      sqlite3_free(pEntry);
    }
  }
  memset(pHash, 0, sizeof(IdxHash));
}
idxHashFind()
static IdxHashEntry* idxHashFind (IdxHash * pHash, const char * zKey, int nKey) [static]
Definition at line 6956 of file shell.c.
References IdxHash::aHash, idxHashString(), IdxHashEntry::pHashNext, STRLEN, and IdxHashEntry::zKey.
Referenced by idxHashSearch(), and idxPopulateOneStat1().
                                                                            {
  int iHash;
  IdxHashEntry *pEntry;
  if(nKey<0) nKey = STRLEN(zKey);
  iHash = idxHashString(zKey, nKey);
  assert(iHash>=0);
  for(pEntry=pHash->aHash[iHash]; pEntry; pEntry=pEntry->pHashNext){
    if(STRLEN(pEntry->zKey)==nKey && 0==memcmp(pEntry->zKey, zKey, nKey)){
      return pEntry;
    }
  }
  return 0;
}
idxHashInit()
static void idxHashInit (IdxHash * pHash) [static]
Definition at line 6880 of file shell.c.
Referenced by idxFindIndexes().
                                       {
  memset(pHash, 0, sizeof(IdxHash));
}
idxHashSearch()
static const char* idxHashSearch (IdxHash * pHash, const char * zKey, int nKey) [static]
Definition at line 6976 of file shell.c.
References idxHashFind(), and IdxHashEntry::zVal.
Referenced by idxFindIndexes().
                                                                            {
  IdxHashEntry *pEntry = idxHashFind(pHash, zKey, nKey);
  if(pEntry) return pEntry->zVal;
  return 0;
}
idxHashString()
static int idxHashString (const char * z, int n) [static]
Definition at line 6905 of file shell.c.
References IDX_HASH_SIZE.
Referenced by idxHashAdd(), and idxHashFind().
                                              {
  unsigned int ret = 0;
  int i;
  for(i=0; i<n; i++){
    ret += (ret<<3) + (unsigned char)(z[i]);
  }
  return (int)(ret % IDX_HASH_SIZE);
}
idxIdentifierRequiresQuotes()
static int idxIdentifierRequiresQuotes (const char * zId) [static]
Definition at line 7494 of file shell.c.
Referenced by idxAppendColDefn(), and idxCreateFromCons().
                                                       {
  int i;
  for(i=0; zId[i]; i++){
    if(!(zId[i]=='_')
     && !(zId[i]>='0' && zId[i]<='9')
     && !(zId[i]>='a' && zId[i]<='z')
     && !(zId[i]>='A' && zId[i]<='Z')
    ){
      return 1;
    }
  }
  return 0;
}
idxLargestIndex()
static int idxLargestIndex (sqlite3 * db, int * pnMax, char ** pzErr) [static]
Definition at line 8198 of file shell.c.
References idxFinalize(), idxPrepareStmt(), sqlite3_column_int, sqlite3_step, SQLITE_OK, and SQLITE_ROW.
Referenced by idxPopulateStat1().
                                                                 {
  int rc = SQLITE_OK;
  const char *zMax =
    "SELECT max(i.seqno) FROM "
    " sqlite_master AS s, "
    " pragma_index_list(s.name) AS l, "
    " pragma_index_info(l.name) AS i "
    "WHERE s.type = 'table'";
  sqlite3_stmt *pMax = 0;
  *pnMax = 0;
  rc = idxPrepareStmt(db, &pMax, pzErr, zMax);
  if(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pMax)){
    *pnMax = sqlite3_column_int(pMax, 0) + 1;
  }
  idxFinalize(&rc, pMax);
  return rc;
}
idxMalloc()
static void* idxMalloc (int * pRc, int nByte) [static]
Definition at line 6864 of file shell.c.
References sqlite3_malloc, SQLITE_NOMEM, and SQLITE_OK.
Referenced by expertBestIndex(), expertConnect(), expertOpen(), idxAuthCallback(), idxGetTableInfo(), idxHashAdd(), idxNewConstraint(), idxPopulateOneStat1(), idxPopulateStat1(), sqlite3_expert_new(), and sqlite3_expert_sql().
                                           {
  void *pRet;
  assert(*pRc==SQLITE_OK);
  assert(nByte>0);
  pRet = sqlite3_malloc(nByte);
  if(pRet){
    memset(pRet, 0, nByte);
  }else{
    *pRc = SQLITE_NOMEM;
  }
  return pRet;
}
idxNewConstraint()
static IdxConstraint* idxNewConstraint (int * pRc, const char * zColl) [static]
Definition at line 6986 of file shell.c.
References idxMalloc(), SQLITE_OK, STRLEN, and IdxConstraint::zColl.
Referenced by expertBestIndex().
                                                                   {
  IdxConstraint *pNew;
  int nColl = STRLEN(zColl);
  assert(*pRc==SQLITE_OK);
  pNew = (IdxConstraint*)idxMalloc(pRc, sizeof(IdxConstraint) * nColl + 1);
  if(pNew){
    pNew->zColl = (char*)&pNew[1];
    memcpy(pNew->zColl, zColl, nColl+1);
  }
  return pNew;
}
idxPopulateOneStat1()
static int idxPopulateOneStat1 (sqlite3expert * p, sqlite3_stmt * pIndexXInfo, sqlite3_stmt * pWriteStat, const char * zTab, const char * zIdx, char ** pzErr) [static]
Definition at line 8218 of file shell.c.
References sqlite3expert::db, sqlite3expert::dbv, sqlite3expert::hIdx, idxAppendText(), idxFinalize(), idxHashFind(), idxMalloc(), idxPrepareStmt(), sqlite3expert::iSample, sqlite3_bind_text, sqlite3_column_int, sqlite3_column_text, sqlite3_free, sqlite3_mprintf, sqlite3_reset, sqlite3_step, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, SQLITE_STATIC, STRLEN, UNIQUE_TABLE_NAME, and IdxHashEntry::zVal2.
Referenced by idxPopulateStat1().
 {
  char *zCols = 0;
  char *zOrder = 0;
  char *zQuery = 0;
  int nCol = 0;
  int i;
  sqlite3_stmt *pQuery = 0;
  int *aStat = 0;
  int rc = SQLITE_OK;
  assert(p->iSample>0);
  /* Formulate the query text */
  sqlite3_bind_text(pIndexXInfo, 1, zIdx, -1, SQLITE_STATIC);
  while(SQLITE_OK==rc && SQLITE_ROW==sqlite3_step(pIndexXInfo)){
    const char *zComma = zCols==0 ? "" : ", ";
    const char *zName = (const char*)sqlite3_column_text(pIndexXInfo, 0);
    const char *zColl = (const char*)sqlite3_column_text(pIndexXInfo, 1);
    zCols = idxAppendText(&rc, zCols,
        "%sx.%Q IS rem(%d, x.%Q) COLLATE %s", zComma, zName, nCol, zName, zColl
    );
    zOrder = idxAppendText(&rc, zOrder, "%s%d", zComma, ++nCol);
  }
  sqlite3_reset(pIndexXInfo);
  if(rc==SQLITE_OK){
    if(p->iSample==100){
      zQuery = sqlite3_mprintf(
          "SELECT %s FROM %Q x ORDER BY %s", zCols, zTab, zOrder
      );
    }else{
      zQuery = sqlite3_mprintf(
          "SELECT %s FROM temp."UNIQUE_TABLE_NAME" x ORDER BY %s", zCols, zOrder
      );
    }
  }
  sqlite3_free(zCols);
  sqlite3_free(zOrder);
  /* Formulate the query text */
  if(rc==SQLITE_OK){
    sqlite3 *dbrem = (p->iSample==100 ? p->db : p->dbv);
    rc = idxPrepareStmt(dbrem, &pQuery, pzErr, zQuery);
  }
  sqlite3_free(zQuery);
  if(rc==SQLITE_OK){
    aStat = (int*)idxMalloc(&rc, sizeof(int)*(nCol+1));
  }
  if(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pQuery)){
    IdxHashEntry *pEntry;
    char *zStat = 0;
    for(i=0; i<=nCol; i++) aStat[i] = 1;
    while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pQuery)){
      aStat[0]++;
      for(i=0; i<nCol; i++){
        if(sqlite3_column_int(pQuery, i)==0) break;
      }
      for(/*no-op*/; i<nCol; i++){
        aStat[i+1]++;
      }
    }
    if(rc==SQLITE_OK){
      int s0 = aStat[0];
      zStat = sqlite3_mprintf("%d", s0);
      if(zStat==0) rc = SQLITE_NOMEM;
      for(i=1; rc==SQLITE_OK && i<=nCol; i++){
        zStat = idxAppendText(&rc, zStat, " %d", (s0+aStat[i]/2) / aStat[i]);
      }
    }
    if(rc==SQLITE_OK){
      sqlite3_bind_text(pWriteStat, 1, zTab, -1, SQLITE_STATIC);
      sqlite3_bind_text(pWriteStat, 2, zIdx, -1, SQLITE_STATIC);
      sqlite3_bind_text(pWriteStat, 3, zStat, -1, SQLITE_STATIC);
      sqlite3_step(pWriteStat);
      rc = sqlite3_reset(pWriteStat);
    }
    pEntry = idxHashFind(&p->hIdx, zIdx, STRLEN(zIdx));
    if(pEntry){
      assert(pEntry->zVal2==0);
      pEntry->zVal2 = zStat;
    }else{
      sqlite3_free(zStat);
    }
  }
  sqlite3_free(aStat);
  idxFinalize(&rc, pQuery);
  return rc;
}
idxPopulateStat1()
static int idxPopulateStat1 (sqlite3expert * p, char ** pzErr) [static]
Definition at line 8342 of file shell.c.
References IdxRemCtx::aSlot, sqlite3expert::db, sqlite3expert::dbm, sqlite3expert::dbv, idxBuildSampleTable(), idxFinalize(), idxLargestIndex(), idxMalloc(), idxPopulateOneStat1(), idxPrepareStmt(), idxRemFunc(), idxSampleFunc(), sqlite3expert::iSample, IdxSampleCtx::iTarget, IdxSampleCtx::nRet, IdxSampleCtx::nRow, IdxRemCtx::nSlot, sqlite3_column_int64, sqlite3_column_text, sqlite3_create_function, sqlite3_exec, sqlite3_free, sqlite3_step, SQLITE_OK, SQLITE_ROW, SQLITE_UTF8, IdxSampleCtx::target, UNIQUE_TABLE_NAME, and IdxRemCtx::IdxRemSlot::z.
Referenced by sqlite3_expert_analyze().
                                                           {
  int rc = SQLITE_OK;
  int nMax =0;
  struct IdxRemCtx *pCtx = 0;
  struct IdxSampleCtx samplectx;
  int i;
  i64 iPrev = -100000;
  sqlite3_stmt *pAllIndex = 0;
  sqlite3_stmt *pIndexXInfo = 0;
  sqlite3_stmt *pWrite = 0;
  const char *zAllIndex =
    "SELECT s.rowid, s.name, l.name FROM "
    " sqlite_master AS s, "
    " pragma_index_list(s.name) AS l "
    "WHERE s.type = 'table'";
  const char *zIndexXInfo =
    "SELECT name, coll FROM pragma_index_xinfo(?) WHERE key";
  const char *zWrite = "INSERT INTO sqlite_stat1 VALUES(?, ?, ?)";
  /* If iSample==0, no sqlite_stat1 data is required. */
  if(p->iSample==0) return SQLITE_OK;
  rc = idxLargestIndex(p->dbm, &nMax, pzErr);
  if(nMax<=0 || rc!=SQLITE_OK) return rc;
  rc = sqlite3_exec(p->dbm, "ANALYZE; PRAGMA writable_schema=1", 0, 0, 0);
  if(rc==SQLITE_OK){
    int nByte = sizeof(struct IdxRemCtx) + (sizeof(struct IdxRemSlot) * nMax);
    pCtx = (struct IdxRemCtx*)idxMalloc(&rc, nByte);
  }
  if(rc==SQLITE_OK){
    sqlite3 *dbrem = (p->iSample==100 ? p->db : p->dbv);
    rc = sqlite3_create_function(
        dbrem, "rem", 2, SQLITE_UTF8, (void*)pCtx, idxRemFunc, 0, 0
    );
  }
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(
        p->db, "sample", 0, SQLITE_UTF8, (void*)&samplectx, idxSampleFunc, 0, 0
    );
  }
  if(rc==SQLITE_OK){
    pCtx->nSlot = nMax+1;
    rc = idxPrepareStmt(p->dbm, &pAllIndex, pzErr, zAllIndex);
  }
  if(rc==SQLITE_OK){
    rc = idxPrepareStmt(p->dbm, &pIndexXInfo, pzErr, zIndexXInfo);
  }
  if(rc==SQLITE_OK){
    rc = idxPrepareStmt(p->dbm, &pWrite, pzErr, zWrite);
  }
  while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pAllIndex)){
    i64 iRowid = sqlite3_column_int64(pAllIndex, 0);
    const char *zTab = (const char*)sqlite3_column_text(pAllIndex, 1);
    const char *zIdx = (const char*)sqlite3_column_text(pAllIndex, 2);
    if(p->iSample<100 && iPrev!=iRowid){
      samplectx.target = (double)p->iSample / 100.0;
      samplectx.iTarget = p->iSample;
      samplectx.nRow = 0.0;
      samplectx.nRet = 0.0;
      rc = idxBuildSampleTable(p, zTab);
      if(rc!=SQLITE_OK) break;
    }
    rc = idxPopulateOneStat1(p, pIndexXInfo, pWrite, zTab, zIdx, pzErr);
    iPrev = iRowid;
  }
  if(rc==SQLITE_OK && p->iSample<100){
    rc = sqlite3_exec(p->dbv,
        "DROP TABLE IF EXISTS temp." UNIQUE_TABLE_NAME, 0,0,0
    );
  }
  idxFinalize(&rc, pAllIndex);
  idxFinalize(&rc, pIndexXInfo);
  idxFinalize(&rc, pWrite);
  for(i=0; i<pCtx->nSlot; i++){
    sqlite3_free(pCtx->aSlot[i].z);
  }
  sqlite3_free(pCtx);
  if(rc==SQLITE_OK){
    rc = sqlite3_exec(p->dbm, "ANALYZE sqlite_master", 0, 0, 0);
  }
  sqlite3_exec(p->db, "DROP TABLE IF EXISTS temp."UNIQUE_TABLE_NAME,0,0,0);
  return rc;
}
idxPrepareStmt()
static int idxPrepareStmt (sqlite3 * db, sqlite3_stmt ** ppStmt, char ** pzErrmsg, const char * zSql) [static]
Definition at line 7013 of file shell.c.
References idxDatabaseError(), sqlite3_prepare_v2, and SQLITE_OK.
Referenced by idxCreateVtabSchema(), idxLargestIndex(), idxPopulateOneStat1(), idxPopulateStat1(), and idxPrintfPrepareStmt().
 {
  int rc = sqlite3_prepare_v2(db, zSql, -1, ppStmt, 0);
  if(rc!=SQLITE_OK){
    *ppStmt = 0;
    idxDatabaseError(db, pzErrmsg);
  }
  return rc;
}
idxPrintfPrepareStmt()
static int idxPrintfPrepareStmt (sqlite3 * db, sqlite3_stmt ** ppStmt, char ** pzErrmsg, const char * zFmt, ...) [static]
Definition at line 7030 of file shell.c.
References idxPrepareStmt(), sqlite3_free, sqlite3_vmprintf, and SQLITE_NOMEM.
Referenced by expertFilter(), idxFindCompatible(), idxFindIndexes(), idxGetTableInfo(), idxProcessOneTrigger(), and sqlite3_expert_new().
 {
  va_list ap;
  int rc;
  char *zSql;
  va_start(ap, zFmt);
  zSql = sqlite3_vmprintf(zFmt, ap);
  if(zSql==0){
    rc = SQLITE_NOMEM;
  }else{
    rc = idxPrepareStmt(db, ppStmt, pzErrmsg, zSql);
    sqlite3_free(zSql);
  }
  va_end(ap);
  return rc;
}
idxProcessOneTrigger()
static int idxProcessOneTrigger (sqlite3expert * p, IdxWrite * pWrite, char ** pzErr) [static]
Definition at line 7917 of file shell.c.
References IdxTable::aCol, sqlite3expert::db, sqlite3expert::dbv, IdxWrite::eOp, idxAppendText(), idxDatabaseError(), idxFinalize(), idxPrintfPrepareStmt(), IdxTable::nCol, IdxWrite::pTab, sqlite3_column_text, sqlite3_exec, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, SQLITE_DELETE, SQLITE_INSERT, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, SQLITE_UPDATE, UNIQUE_TABLE_NAME, IdxColumn::zName, and IdxTable::zName.
Referenced by idxProcessTriggers().
 {
  static const char *zInt = UNIQUE_TABLE_NAME;
  static const char *zDrop = "DROP TABLE " UNIQUE_TABLE_NAME;
  IdxTable *pTab = pWrite->pTab;
  const char *zTab = pTab->zName;
  const char *zSql =
    "SELECT 'CREATE TEMP' || substr(sql, 7) FROM sqlite_master "
    "WHERE tbl_name = %Q AND type IN ('table', 'trigger') "
    "ORDER BY type;";
  sqlite3_stmt *pSelect = 0;
  int rc = SQLITE_OK;
  char *zWrite = 0;
  /* Create the table and its triggers in the temp schema */
  rc = idxPrintfPrepareStmt(p->db, &pSelect, pzErr, zSql, zTab, zTab);
  while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pSelect)){
    const char *zCreate = (const char*)sqlite3_column_text(pSelect, 0);
    rc = sqlite3_exec(p->dbv, zCreate, 0, 0, pzErr);
  }
  idxFinalize(&rc, pSelect);
  /* Rename the table in the temp schema to zInt */
  if(rc==SQLITE_OK){
    char *z = sqlite3_mprintf("ALTER TABLE temp.%Q RENAME TO %Q", zTab, zInt);
    if(z==0){
      rc = SQLITE_NOMEM;
    }else{
      rc = sqlite3_exec(p->dbv, z, 0, 0, pzErr);
      sqlite3_free(z);
    }
  }
  switch(pWrite->eOp){
    case SQLITE_INSERT: {
      int i;
      zWrite = idxAppendText(&rc, zWrite, "INSERT INTO %Q VALUES(", zInt);
      for(i=0; i<pTab->nCol; i++){
        zWrite = idxAppendText(&rc, zWrite, "%s?", i==0 ? "" : ", ");
      }
      zWrite = idxAppendText(&rc, zWrite, ")");
      break;
    }
    case SQLITE_UPDATE: {
      int i;
      zWrite = idxAppendText(&rc, zWrite, "UPDATE %Q SET ", zInt);
      for(i=0; i<pTab->nCol; i++){
        zWrite = idxAppendText(&rc, zWrite, "%s%Q=?", i==0 ? "" : ", ",
            pTab->aCol[i].zName
        );
      }
      break;
    }
    default: {
      assert(pWrite->eOp==SQLITE_DELETE);
      if(rc==SQLITE_OK){
        zWrite = sqlite3_mprintf("DELETE FROM %Q", zInt);
        if(zWrite==0) rc = SQLITE_NOMEM;
      }
    }
  }
  if(rc==SQLITE_OK){
    sqlite3_stmt *pX = 0;
    rc = sqlite3_prepare_v2(p->dbv, zWrite, -1, &pX, 0);
    idxFinalize(&rc, pX);
    if(rc!=SQLITE_OK){
      idxDatabaseError(p->dbv, pzErr);
    }
  }
  sqlite3_free(zWrite);
  if(rc==SQLITE_OK){
    rc = sqlite3_exec(p->dbv, zDrop, 0, 0, pzErr);
  }
  return rc;
}
idxProcessTriggers()
static int idxProcessTriggers (sqlite3expert * p, char ** pzErr) [static]
Definition at line 7999 of file shell.c.
References idxProcessOneTrigger(), IdxWrite::pNext, sqlite3expert::pWrite, and SQLITE_OK.
Referenced by sqlite3_expert_analyze().
                                                             {
  int rc = SQLITE_OK;
  IdxWrite *pEnd = 0;
  IdxWrite *pFirst = p->pWrite;
  while(rc==SQLITE_OK && pFirst!=pEnd){
    IdxWrite *pIter;
    for(pIter=pFirst; rc==SQLITE_OK && pIter!=pEnd; pIter=pIter->pNext){
      rc = idxProcessOneTrigger(p, pIter, pzErr);
    }
    pEnd = pFirst;
    pFirst = p->pWrite;
  }
  return rc;
}
idxRegisterVtab()
static int idxRegisterVtab (sqlite3expert * p) [static]
Definition at line 7328 of file shell.c.
References sqlite3expert::dbv, expertBestIndex(), expertClose(), expertColumn(), expertConnect(), expertDisconnect(), expertEof(), expertFilter(), expertNext(), expertOpen(), expertRowid(), expertUpdate(), and sqlite3_create_module.
Referenced by idxCreateVtabSchema().
                                            {
  static sqlite3_module expertModule = {
    2, /* iVersion */
    expertConnect, /* xCreate - create a table */
    expertConnect, /* xConnect - connect to an existing table */
    expertBestIndex, /* xBestIndex - Determine search strategy */
    expertDisconnect, /* xDisconnect - Disconnect from a table */
    expertDisconnect, /* xDestroy - Drop a table */
    expertOpen, /* xOpen - open a cursor */
    expertClose, /* xClose - close a cursor */
    expertFilter, /* xFilter - configure scan constraints */
    expertNext, /* xNext - advance a cursor */
    expertEof, /* xEof */
    expertColumn, /* xColumn - read data */
    expertRowid, /* xRowid - read data */
    expertUpdate, /* xUpdate - write data */
    0, /* xBegin - begin transaction */
    0, /* xSync - sync transaction */
    0, /* xCommit - commit transaction */
    0, /* xRollback - rollback transaction */
    0, /* xFindFunction - function overloading */
    0, /* xRename - rename the table */
    0, /* xSavepoint */
    0, /* xRelease */
    0, /* xRollbackTo */
    0, /* xShadowName */
  };
  return sqlite3_create_module(p->dbv, "expert", &expertModule, (void*)p);
}
idxRemFunc()
static void idxRemFunc (sqlite3_context * pCtx, int argc, sqlite3_value ** argv) [static]
Definition at line 8125 of file shell.c.
References IdxRemCtx::aSlot, sqlite3_realloc, sqlite3_result_blob, sqlite3_result_double, sqlite3_result_error_nomem, sqlite3_result_int64, sqlite3_result_text, sqlite3_user_data, sqlite3_value_blob, sqlite3_value_bytes, sqlite3_value_double, sqlite3_value_int, sqlite3_value_int64, sqlite3_value_text, sqlite3_value_type, SQLITE_BLOB, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, SQLITE_TEXT, and SQLITE_TRANSIENT.
Referenced by idxPopulateStat1().
 {
  struct IdxRemCtx *p = (struct IdxRemCtx*)sqlite3_user_data(pCtx);
  struct IdxRemSlot *pSlot;
  int iSlot;
  assert(argc==2);
  iSlot = sqlite3_value_int(argv[0]);
  assert(iSlot<=p->nSlot);
  pSlot = &p->aSlot[iSlot];
  switch(pSlot->eType){
    case SQLITE_NULL:
      /* no-op */
      break;
    case SQLITE_INTEGER:
      sqlite3_result_int64(pCtx, pSlot->iVal);
      break;
    case SQLITE_FLOAT:
      sqlite3_result_double(pCtx, pSlot->rVal);
      break;
    case SQLITE_BLOB:
      sqlite3_result_blob(pCtx, pSlot->z, pSlot->n, SQLITE_TRANSIENT);
      break;
    case SQLITE_TEXT:
      sqlite3_result_text(pCtx, pSlot->z, pSlot->n, SQLITE_TRANSIENT);
      break;
  }
  pSlot->eType = sqlite3_value_type(argv[1]);
  switch(pSlot->eType){
    case SQLITE_NULL:
      /* no-op */
      break;
    case SQLITE_INTEGER:
      pSlot->iVal = sqlite3_value_int64(argv[1]);
      break;
    case SQLITE_FLOAT:
      pSlot->rVal = sqlite3_value_double(argv[1]);
      break;
    case SQLITE_BLOB:
    case SQLITE_TEXT: {
      int nByte = sqlite3_value_bytes(argv[1]);
      if(nByte>pSlot->nByte){
        char *zNew = (char*)sqlite3_realloc(pSlot->z, nByte*2);
        if(zNew==0){
          sqlite3_result_error_nomem(pCtx);
          return;
        }
        pSlot->nByte = nByte*2;
        pSlot->z = zNew;
      }
      pSlot->n = nByte;
      if(pSlot->eType==SQLITE_BLOB){
        memcpy(pSlot->z, sqlite3_value_blob(argv[1]), nByte);
      }else{
        memcpy(pSlot->z, sqlite3_value_text(argv[1]), nByte);
      }
      break;
    }
  }
}
idxSampleFunc()
static void idxSampleFunc (sqlite3_context * pCtx, int argc, sqlite3_value ** argv) [static]
Definition at line 8084 of file shell.c.
References IdxSampleCtx::iTarget, IdxSampleCtx::nRet, IdxSampleCtx::nRow, sqlite3_randomness, sqlite3_result_int, sqlite3_user_data, and IdxSampleCtx::target.
Referenced by idxPopulateStat1().
 {
  struct IdxSampleCtx *p = (struct IdxSampleCtx*)sqlite3_user_data(pCtx);
  int bRet;
  (void)argv;
  assert(argc==0);
  if(p->nRow==0.0){
    bRet = 1;
  }else{
    bRet = (p->nRet / p->nRow) <= p->target;
    if(bRet==0){
      unsigned short rnd;
      sqlite3_randomness(2, (void*)&rnd);
      bRet = ((int)rnd % 100) <= p->iTarget;
    }
  }
  sqlite3_result_int(pCtx, bRet);
  p->nRow += 1.0;
  p->nRet += (double)bRet;
}
idxScanFree()
static void idxScanFree (IdxScan * pScan, IdxScan * pLast) [static]
Definition at line 7756 of file shell.c.
References idxConstraintFree(), IdxScan::pEq, IdxScan::pNextScan, IdxScan::pOrder, IdxScan::pRange, and sqlite3_free.
Referenced by sqlite3_expert_destroy(), and sqlite3_expert_sql().
                                                       {
  IdxScan *p;
  IdxScan *pNext;
  for(p=pScan; p!=pLast; p=pNext){
    pNext = p->pNextScan;
    idxConstraintFree(p->pOrder);
    idxConstraintFree(p->pEq);
    idxConstraintFree(p->pRange);
    sqlite3_free(p);
  }
}
idxStatementFree()
static void idxStatementFree (IdxStatement * pStatement, IdxStatement * pLast) [static]
Definition at line 7772 of file shell.c.
References IdxStatement::pNext, sqlite3_free, IdxStatement::zEQP, and IdxStatement::zIdx.
Referenced by sqlite3_expert_destroy(), and sqlite3_expert_sql().
                                                                           {
  IdxStatement *p;
  IdxStatement *pNext;
  for(p=pStatement; p!=pLast; p=pNext){
    pNext = p->pNext;
    sqlite3_free(p->zEQP);
    sqlite3_free(p->zIdx);
    sqlite3_free(p);
  }
}
idxTableFree()
static void idxTableFree (IdxTable * pTab) [static]
Definition at line 7786 of file shell.c.
References IdxTable::pNext, and sqlite3_free.
Referenced by sqlite3_expert_destroy().
                                        {
  IdxTable *pIter;
  IdxTable *pNext;
  for(pIter=pTab; pIter; pIter=pNext){
    pNext = pIter->pNext;
    sqlite3_free(pIter);
  }
}
idxWriteFree()
static void idxWriteFree (IdxWrite * pTab) [static]
Definition at line 7798 of file shell.c.
References IdxWrite::pNext, and sqlite3_free.
Referenced by sqlite3_expert_destroy().
                                        {
  IdxWrite *pIter;
  IdxWrite *pNext;
  for(pIter=pTab; pIter; pIter=pNext){
    pNext = pIter->pNext;
    sqlite3_free(pIter);
  }
}
import_append_char()
static void import_append_char (ImportCtx * p, int c) [static]
Definition at line 13083 of file shell.c.
References ImportCtx::n, ImportCtx::nAlloc, shell_out_of_memory(), sqlite3_realloc64, and ImportCtx::z.
Referenced by ascii_read_one_field(), csv_read_one_field(), and do_meta_command().
                                                   {
  if(p->n+1>=p->nAlloc){
    p->nAlloc += p->nAlloc + 100;
    p->z = sqlite3_realloc64(p->z, p->nAlloc);
    if(p->z==0) shell_out_of_memory();
  }
  p->z[p->n++] = (char)c;
}
initText()
static void initText (ShellText * p) [static]
Definition at line 734 of file shell.c.
Referenced by do_meta_command(), dump_callback(), freeText(), and shellFakeSchema().
                                  {
  memset(p, 0, sizeof(*p));
}
integerValue()
static sqlite3_int64 integerValue (const char * zArg) [static]
Definition at line 678 of file shell.c.
References ArraySize, hexDigitValue(), IsDigit, sqlite3_stricmp, and time_test::x.
Referenced by booleanValue(), do_meta_command(), expertDotCommand(), and main().
                                                   {
  sqlite3_int64 v = 0;
  static const struct { char *zSuffix; int iMult; } aMult[] = {
    { "KiB", 1024 },
    { "MiB", 1024*1024 },
    { "GiB", 1024*1024*1024 },
    { "KB", 1000 },
    { "MB", 1000000 },
    { "GB", 1000000000 },
    { "K", 1000 },
    { "M", 1000000 },
    { "G", 1000000000 },
  };
  int i;
  int isNeg = 0;
  if(zArg[0]=='-'){
    isNeg = 1;
    zArg++;
  }else if(zArg[0]=='+'){
    zArg++;
  }
  if(zArg[0]=='0' && zArg[1]=='x'){
    int x;
    zArg += 2;
    while((x = hexDigitValue(zArg[0]))>=0){
      v = (v<<4) + x;
      zArg++;
    }
  }else{
    while(IsDigit(zArg[0])){
      v = v*10 + zArg[0] - '0';
      zArg++;
    }
  }
  for(i=0; i<ArraySize(aMult); i++){
    if(sqlite3_stricmp(aMult[i].zSuffix, zArg)==0){
      v *= aMult[i].iMult;
      break;
    }
  }
  return isNeg? -v : v;
}
interrupt_handler()
static void interrupt_handler (int NotUsed) [static]
Definition at line 10174 of file shell.c.
References sqlite3_interrupt, and UNUSED_PARAMETER.
Referenced by main().
                                          {
  UNUSED_PARAMETER(NotUsed);
  seenInterrupt++;
  if(seenInterrupt>2) exit(1);
  if(globalDb) sqlite3_interrupt(globalDb);
}
isatty()
int isatty (int)
Referenced by main(), and Tclsqlite_Unload().
isNumber()
static int isNumber (const char * z, int * realnum) [static]
Definition at line 529 of file shell.c.
References IsDigit.
Referenced by shell_callback().
                                                {
  if(*z=='-' || *z=='+') z++;
  if(!IsDigit(*z)){
    return 0;
  }
  z++;
  if(realnum) *realnum = 0;
  while(IsDigit(*z)){ z++; }
  if(*z=='.'){
    z++;
    if(!IsDigit(*z)) return 0;
    while(IsDigit(*z)){ z++; }
    if(realnum) *realnum = 1;
  }
  if(*z=='e' || *z=='E'){
    z++;
    if(*z=='+' || *z=='-') z++;
    if(!IsDigit(*z)) return 0;
    while(IsDigit(*z)){ z++; }
    if(realnum) *realnum = 1;
  }
  return *z==0;
}
KeccakF1600Step()
static void KeccakF1600Step (SHA3Context * p) [static]
Definition at line 1390 of file shell.c.
References a00, a01, a02, a03, a04, a10, a11, a12, a13, a14, a20, a21, a22, a23, a24, a30, a31, a32, a33, a34, a40, a41, a42, a43, a44, and ROL64.
Referenced by SHA3Update().
                                           {
  int i;
  u64 b0, b1, b2, b3, b4;
  u64 c0, c1, c2, c3, c4;
  u64 d0, d1, d2, d3, d4;
  static const u64 RC[] = {
    0x0000000000000001ULL, 0x0000000000008082ULL,
    0x800000000000808aULL, 0x8000000080008000ULL,
    0x000000000000808bULL, 0x0000000080000001ULL,
    0x8000000080008081ULL, 0x8000000000008009ULL,
    0x000000000000008aULL, 0x0000000000000088ULL,
    0x0000000080008009ULL, 0x000000008000000aULL,
    0x000000008000808bULL, 0x800000000000008bULL,
    0x8000000000008089ULL, 0x8000000000008003ULL,
    0x8000000000008002ULL, 0x8000000000000080ULL,
    0x000000000000800aULL, 0x800000008000000aULL,
    0x8000000080008081ULL, 0x8000000000008080ULL,
    0x0000000080000001ULL, 0x8000000080008008ULL
  };
# define a00 (p->u.s[0])
# define a01 (p->u.s[1])
# define a02 (p->u.s[2])
# define a03 (p->u.s[3])
# define a04 (p->u.s[4])
# define a10 (p->u.s[5])
# define a11 (p->u.s[6])
# define a12 (p->u.s[7])
# define a13 (p->u.s[8])
# define a14 (p->u.s[9])
# define a20 (p->u.s[10])
# define a21 (p->u.s[11])
# define a22 (p->u.s[12])
# define a23 (p->u.s[13])
# define a24 (p->u.s[14])
# define a30 (p->u.s[15])
# define a31 (p->u.s[16])
# define a32 (p->u.s[17])
# define a33 (p->u.s[18])
# define a34 (p->u.s[19])
# define a40 (p->u.s[20])
# define a41 (p->u.s[21])
# define a42 (p->u.s[22])
# define a43 (p->u.s[23])
# define a44 (p->u.s[24])
# define ROL64(a,x) ((a<<x)|(a>>(64-x)))
  for(i=0; i<24; i+=4){
    c0 = a00^a10^a20^a30^a40;
    c1 = a01^a11^a21^a31^a41;
    c2 = a02^a12^a22^a32^a42;
    c3 = a03^a13^a23^a33^a43;
    c4 = a04^a14^a24^a34^a44;
    d0 = c4^ROL64(c1, 1);
    d1 = c0^ROL64(c2, 1);
    d2 = c1^ROL64(c3, 1);
    d3 = c2^ROL64(c4, 1);
    d4 = c3^ROL64(c0, 1);
    b0 = (a00^d0);
    b1 = ROL64((a11^d1), 44);
    b2 = ROL64((a22^d2), 43);
    b3 = ROL64((a33^d3), 21);
    b4 = ROL64((a44^d4), 14);
    a00 = b0 ^((~b1)& b2);
    a00 ^= RC[i];
    a11 = b1 ^((~b2)& b3);
    a22 = b2 ^((~b3)& b4);
    a33 = b3 ^((~b4)& b0);
    a44 = b4 ^((~b0)& b1);
    b2 = ROL64((a20^d0), 3);
    b3 = ROL64((a31^d1), 45);
    b4 = ROL64((a42^d2), 61);
    b0 = ROL64((a03^d3), 28);
    b1 = ROL64((a14^d4), 20);
    a20 = b0 ^((~b1)& b2);
    a31 = b1 ^((~b2)& b3);
    a42 = b2 ^((~b3)& b4);
    a03 = b3 ^((~b4)& b0);
    a14 = b4 ^((~b0)& b1);
    b4 = ROL64((a40^d0), 18);
    b0 = ROL64((a01^d1), 1);
    b1 = ROL64((a12^d2), 6);
    b2 = ROL64((a23^d3), 25);
    b3 = ROL64((a34^d4), 8);
    a40 = b0 ^((~b1)& b2);
    a01 = b1 ^((~b2)& b3);
    a12 = b2 ^((~b3)& b4);
    a23 = b3 ^((~b4)& b0);
    a34 = b4 ^((~b0)& b1);
    b1 = ROL64((a10^d0), 36);
    b2 = ROL64((a21^d1), 10);
    b3 = ROL64((a32^d2), 15);
    b4 = ROL64((a43^d3), 56);
    b0 = ROL64((a04^d4), 27);
    a10 = b0 ^((~b1)& b2);
    a21 = b1 ^((~b2)& b3);
    a32 = b2 ^((~b3)& b4);
    a43 = b3 ^((~b4)& b0);
    a04 = b4 ^((~b0)& b1);
    b3 = ROL64((a30^d0), 41);
    b4 = ROL64((a41^d1), 2);
    b0 = ROL64((a02^d2), 62);
    b1 = ROL64((a13^d3), 55);
    b2 = ROL64((a24^d4), 39);
    a30 = b0 ^((~b1)& b2);
    a41 = b1 ^((~b2)& b3);
    a02 = b2 ^((~b3)& b4);
    a13 = b3 ^((~b4)& b0);
    a24 = b4 ^((~b0)& b1);
    c0 = a00^a20^a40^a10^a30;
    c1 = a11^a31^a01^a21^a41;
    c2 = a22^a42^a12^a32^a02;
    c3 = a33^a03^a23^a43^a13;
    c4 = a44^a14^a34^a04^a24;
    d0 = c4^ROL64(c1, 1);
    d1 = c0^ROL64(c2, 1);
    d2 = c1^ROL64(c3, 1);
    d3 = c2^ROL64(c4, 1);
    d4 = c3^ROL64(c0, 1);
    b0 = (a00^d0);
    b1 = ROL64((a31^d1), 44);
    b2 = ROL64((a12^d2), 43);
    b3 = ROL64((a43^d3), 21);
    b4 = ROL64((a24^d4), 14);
    a00 = b0 ^((~b1)& b2);
    a00 ^= RC[i+1];
    a31 = b1 ^((~b2)& b3);
    a12 = b2 ^((~b3)& b4);
    a43 = b3 ^((~b4)& b0);
    a24 = b4 ^((~b0)& b1);
    b2 = ROL64((a40^d0), 3);
    b3 = ROL64((a21^d1), 45);
    b4 = ROL64((a02^d2), 61);
    b0 = ROL64((a33^d3), 28);
    b1 = ROL64((a14^d4), 20);
    a40 = b0 ^((~b1)& b2);
    a21 = b1 ^((~b2)& b3);
    a02 = b2 ^((~b3)& b4);
    a33 = b3 ^((~b4)& b0);
    a14 = b4 ^((~b0)& b1);
    b4 = ROL64((a30^d0), 18);
    b0 = ROL64((a11^d1), 1);
    b1 = ROL64((a42^d2), 6);
    b2 = ROL64((a23^d3), 25);
    b3 = ROL64((a04^d4), 8);
    a30 = b0 ^((~b1)& b2);
    a11 = b1 ^((~b2)& b3);
    a42 = b2 ^((~b3)& b4);
    a23 = b3 ^((~b4)& b0);
    a04 = b4 ^((~b0)& b1);
    b1 = ROL64((a20^d0), 36);
    b2 = ROL64((a01^d1), 10);
    b3 = ROL64((a32^d2), 15);
    b4 = ROL64((a13^d3), 56);
    b0 = ROL64((a44^d4), 27);
    a20 = b0 ^((~b1)& b2);
    a01 = b1 ^((~b2)& b3);
    a32 = b2 ^((~b3)& b4);
    a13 = b3 ^((~b4)& b0);
    a44 = b4 ^((~b0)& b1);
    b3 = ROL64((a10^d0), 41);
    b4 = ROL64((a41^d1), 2);
    b0 = ROL64((a22^d2), 62);
    b1 = ROL64((a03^d3), 55);
    b2 = ROL64((a34^d4), 39);
    a10 = b0 ^((~b1)& b2);
    a41 = b1 ^((~b2)& b3);
    a22 = b2 ^((~b3)& b4);
    a03 = b3 ^((~b4)& b0);
    a34 = b4 ^((~b0)& b1);
    c0 = a00^a40^a30^a20^a10;
    c1 = a31^a21^a11^a01^a41;
    c2 = a12^a02^a42^a32^a22;
    c3 = a43^a33^a23^a13^a03;
    c4 = a24^a14^a04^a44^a34;
    d0 = c4^ROL64(c1, 1);
    d1 = c0^ROL64(c2, 1);
    d2 = c1^ROL64(c3, 1);
    d3 = c2^ROL64(c4, 1);
    d4 = c3^ROL64(c0, 1);
    b0 = (a00^d0);
    b1 = ROL64((a21^d1), 44);
    b2 = ROL64((a42^d2), 43);
    b3 = ROL64((a13^d3), 21);
    b4 = ROL64((a34^d4), 14);
    a00 = b0 ^((~b1)& b2);
    a00 ^= RC[i+2];
    a21 = b1 ^((~b2)& b3);
    a42 = b2 ^((~b3)& b4);
    a13 = b3 ^((~b4)& b0);
    a34 = b4 ^((~b0)& b1);
    b2 = ROL64((a30^d0), 3);
    b3 = ROL64((a01^d1), 45);
    b4 = ROL64((a22^d2), 61);
    b0 = ROL64((a43^d3), 28);
    b1 = ROL64((a14^d4), 20);
    a30 = b0 ^((~b1)& b2);
    a01 = b1 ^((~b2)& b3);
    a22 = b2 ^((~b3)& b4);
    a43 = b3 ^((~b4)& b0);
    a14 = b4 ^((~b0)& b1);
    b4 = ROL64((a10^d0), 18);
    b0 = ROL64((a31^d1), 1);
    b1 = ROL64((a02^d2), 6);
    b2 = ROL64((a23^d3), 25);
    b3 = ROL64((a44^d4), 8);
    a10 = b0 ^((~b1)& b2);
    a31 = b1 ^((~b2)& b3);
    a02 = b2 ^((~b3)& b4);
    a23 = b3 ^((~b4)& b0);
    a44 = b4 ^((~b0)& b1);
    b1 = ROL64((a40^d0), 36);
    b2 = ROL64((a11^d1), 10);
    b3 = ROL64((a32^d2), 15);
    b4 = ROL64((a03^d3), 56);
    b0 = ROL64((a24^d4), 27);
    a40 = b0 ^((~b1)& b2);
    a11 = b1 ^((~b2)& b3);
    a32 = b2 ^((~b3)& b4);
    a03 = b3 ^((~b4)& b0);
    a24 = b4 ^((~b0)& b1);
    b3 = ROL64((a20^d0), 41);
    b4 = ROL64((a41^d1), 2);
    b0 = ROL64((a12^d2), 62);
    b1 = ROL64((a33^d3), 55);
    b2 = ROL64((a04^d4), 39);
    a20 = b0 ^((~b1)& b2);
    a41 = b1 ^((~b2)& b3);
    a12 = b2 ^((~b3)& b4);
    a33 = b3 ^((~b4)& b0);
    a04 = b4 ^((~b0)& b1);
    c0 = a00^a30^a10^a40^a20;
    c1 = a21^a01^a31^a11^a41;
    c2 = a42^a22^a02^a32^a12;
    c3 = a13^a43^a23^a03^a33;
    c4 = a34^a14^a44^a24^a04;
    d0 = c4^ROL64(c1, 1);
    d1 = c0^ROL64(c2, 1);
    d2 = c1^ROL64(c3, 1);
    d3 = c2^ROL64(c4, 1);
    d4 = c3^ROL64(c0, 1);
    b0 = (a00^d0);
    b1 = ROL64((a01^d1), 44);
    b2 = ROL64((a02^d2), 43);
    b3 = ROL64((a03^d3), 21);
    b4 = ROL64((a04^d4), 14);
    a00 = b0 ^((~b1)& b2);
    a00 ^= RC[i+3];
    a01 = b1 ^((~b2)& b3);
    a02 = b2 ^((~b3)& b4);
    a03 = b3 ^((~b4)& b0);
    a04 = b4 ^((~b0)& b1);
    b2 = ROL64((a10^d0), 3);
    b3 = ROL64((a11^d1), 45);
    b4 = ROL64((a12^d2), 61);
    b0 = ROL64((a13^d3), 28);
    b1 = ROL64((a14^d4), 20);
    a10 = b0 ^((~b1)& b2);
    a11 = b1 ^((~b2)& b3);
    a12 = b2 ^((~b3)& b4);
    a13 = b3 ^((~b4)& b0);
    a14 = b4 ^((~b0)& b1);
    b4 = ROL64((a20^d0), 18);
    b0 = ROL64((a21^d1), 1);
    b1 = ROL64((a22^d2), 6);
    b2 = ROL64((a23^d3), 25);
    b3 = ROL64((a24^d4), 8);
    a20 = b0 ^((~b1)& b2);
    a21 = b1 ^((~b2)& b3);
    a22 = b2 ^((~b3)& b4);
    a23 = b3 ^((~b4)& b0);
    a24 = b4 ^((~b0)& b1);
    b1 = ROL64((a30^d0), 36);
    b2 = ROL64((a31^d1), 10);
    b3 = ROL64((a32^d2), 15);
    b4 = ROL64((a33^d3), 56);
    b0 = ROL64((a34^d4), 27);
    a30 = b0 ^((~b1)& b2);
    a31 = b1 ^((~b2)& b3);
    a32 = b2 ^((~b3)& b4);
    a33 = b3 ^((~b4)& b0);
    a34 = b4 ^((~b0)& b1);
    b3 = ROL64((a40^d0), 41);
    b4 = ROL64((a41^d1), 2);
    b0 = ROL64((a42^d2), 62);
    b1 = ROL64((a43^d3), 55);
    b2 = ROL64((a44^d4), 39);
    a40 = b0 ^((~b1)& b2);
    a41 = b1 ^((~b2)& b3);
    a42 = b2 ^((~b3)& b4);
    a43 = b3 ^((~b4)& b0);
    a44 = b4 ^((~b0)& b1);
  }
}
line_contains_semicolon()
static int line_contains_semicolon (const char * z, int N) [static]
Definition at line 18212 of file shell.c.
Referenced by process_input().
                                                        {
  int i;
  for(i=0; i<N; i++){ if(z[i]==';') return 1; }
  return 0;
}
line_is_command_terminator()
static int line_is_command_terminator (const char * zLine) [static]
Definition at line 18247 of file shell.c.
References _all_whitespace(), IsSpace, and ToLower.
Referenced by process_input().
                                                        {
  while(IsSpace(zLine[0])){ zLine++; };
  if(zLine[0]=='/' && _all_whitespace(&zLine[1])){
    return 1; /* Oracle */
  }
  if(ToLower(zLine[0])=='g' && ToLower(zLine[1])=='o'
         && _all_whitespace(&zLine[2])){
    return 1; /* SQL Server */
  }
  return 0;
}
line_is_complete()
static int line_is_complete (char * zSql, int nSql) [static]
Definition at line 18273 of file shell.c.
References sqlite3_complete.
Referenced by process_input().
                                                 {
  int rc;
  if(zSql==0) return 1;
  zSql[nSql] = ';';
  zSql[nSql+1] = 0;
  rc = sqlite3_complete(zSql);
  zSql[nSql] = 0;
  return rc;
}
lintDotCommand()
static int lintDotCommand (ShellState * pState, char ** azArg, int nArg) [static]
Definition at line 13996 of file shell.c.
References lintFkeyIndexes(), raw_printf, sqlite3_strnicmp, SQLITE_ERROR, strlen30(), and usage().
Referenced by do_meta_command().
 {
  int n;
  n = (nArg>=2 ? strlen30(azArg[1]) : 0);
  if(n<1 || sqlite3_strnicmp(azArg[1], "fkey-indexes", n)) goto usage;
  return lintFkeyIndexes(pState, azArg, nArg);
 usage:
  raw_printf(stderr, "Usage %s sub-command ?switches...?\n", azArg[0]);
  raw_printf(stderr, "Where sub-commands are:\n");
  raw_printf(stderr, " fkey-indexes\n");
  return SQLITE_ERROR;
}
lintFkeyIndexes()
static int lintFkeyIndexes (ShellState * pState, char ** azArg, int nArg) [static]
Definition at line 13820 of file shell.c.
References ShellState::db, ShellState::out, raw_printf, shellFkeyCollateClause(), sqlite3_bind_int, sqlite3_column_text, sqlite3_create_function, sqlite3_errmsg, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, sqlite3_strglob, sqlite3_stricmp, sqlite3_strnicmp, SQLITE_ERROR, SQLITE_OK, SQLITE_ROW, SQLITE_UTF8, and strlen30().
Referenced by lintDotCommand().
 {
  sqlite3 *db = pState->db; /* Database handle to query "main" db of */
  FILE *out = pState->out; /* Stream to write non-error output to */
  int bVerbose = 0; /* If -verbose is present */
  int bGroupByParent = 0; /* If -groupbyparent is present */
  int i; /* To iterate through azArg[] */
  const char *zIndent = ""; /* How much to indent CREATE INDEX by */
  int rc; /* Return code */
  sqlite3_stmt *pSql = 0; /* Compiled version of SQL statement below */
  /*
  ** This SELECT statement returns one row for each foreign key constraint
  ** in the schema of the main database. The column values are:
  **
  ** 0. The text of an SQL statement similar to:
  **
  ** "EXPLAIN QUERY PLAN SELECT 1 FROM child_table WHERE child_key=?"
  **
  ** This SELECT is similar to the one that the foreign keys implementation
  ** needs to run internally on child tables. If there is an index that can
  ** be used to optimize this query, then it can also be used by the FK
  ** implementation to optimize DELETE or UPDATE statements on the parent
  ** table.
  **
  ** 1. A GLOB pattern suitable for sqlite3_strglob(). If the plan output by
  ** the EXPLAIN QUERY PLAN command matches this pattern, then the schema
  ** contains an index that can be used to optimize the query.
  **
  ** 2. Human readable text that describes the child table and columns. e.g.
  **
  ** "child_table(child_key1, child_key2)"
  **
  ** 3. Human readable text that describes the parent table and columns. e.g.
  **
  ** "parent_table(parent_key1, parent_key2)"
  **
  ** 4. A full CREATE INDEX statement for an index that could be used to
  ** optimize DELETE or UPDATE statements on the parent table. e.g.
  **
  ** "CREATE INDEX child_table_child_key ON child_table(child_key)"
  **
  ** 5. The name of the parent table.
  **
  ** These six values are used by the C logic below to generate the report.
  */
  const char *zSql =
  "SELECT "
    " 'EXPLAIN QUERY PLAN SELECT 1 FROM ' || quote(s.name) || ' WHERE '"
    " || group_concat(quote(s.name) || '.' || quote(f.[from]) || '=?' "
    " || fkey_collate_clause("
    " f.[table], COALESCE(f.[to], p.[name]), s.name, f.[from]),' AND ')"
    ", "
    " 'SEARCH TABLE ' || s.name || ' USING COVERING INDEX*('"
    " || group_concat('*=?', ' AND ') || ')'"
    ", "
    " s.name || '(' || group_concat(f.[from], ', ') || ')'"
    ", "
    " f.[table] || '(' || group_concat(COALESCE(f.[to], p.[name])) || ')'"
    ", "
    " 'CREATE INDEX ' || quote(s.name ||'_'|| group_concat(f.[from], '_'))"
    " || ' ON ' || quote(s.name) || '('"
    " || group_concat(quote(f.[from]) ||"
    " fkey_collate_clause("
    " f.[table], COALESCE(f.[to], p.[name]), s.name, f.[from]), ', ')"
    " || ');'"
    ", "
    " f.[table] "
    "FROM sqlite_master AS s, pragma_foreign_key_list(s.name) AS f "
    "LEFT JOIN pragma_table_info AS p ON (pk-1=seq AND p.arg=f.[table]) "
    "GROUP BY s.name, f.id "
    "ORDER BY (CASE WHEN ? THEN f.[table] ELSE s.name END)"
  ;
  const char *zGlobIPK = "SEARCH TABLE * USING INTEGER PRIMARY KEY (rowid=?)";
  for(i=2; i<nArg; i++){
    int n = strlen30(azArg[i]);
    if(n>1 && sqlite3_strnicmp("-verbose", azArg[i], n)==0){
      bVerbose = 1;
    }
    else if(n>1 && sqlite3_strnicmp("-groupbyparent", azArg[i], n)==0){
      bGroupByParent = 1;
      zIndent = " ";
    }
    else{
      raw_printf(stderr, "Usage: %s %s ?-verbose? ?-groupbyparent?\n",
          azArg[0], azArg[1]
      );
      return SQLITE_ERROR;
    }
  }
  /* Register the fkey_collate_clause() SQL function */
  rc = sqlite3_create_function(db, "fkey_collate_clause", 4, SQLITE_UTF8,
      0, shellFkeyCollateClause, 0, 0
  );
  if(rc==SQLITE_OK){
    rc = sqlite3_prepare_v2(db, zSql, -1, &pSql, 0);
  }
  if(rc==SQLITE_OK){
    sqlite3_bind_int(pSql, 1, bGroupByParent);
  }
  if(rc==SQLITE_OK){
    int rc2;
    char *zPrev = 0;
    while(SQLITE_ROW==sqlite3_step(pSql)){
      int res = -1;
      sqlite3_stmt *pExplain = 0;
      const char *zEQP = (const char*)sqlite3_column_text(pSql, 0);
      const char *zGlob = (const char*)sqlite3_column_text(pSql, 1);
      const char *zFrom = (const char*)sqlite3_column_text(pSql, 2);
      const char *zTarget = (const char*)sqlite3_column_text(pSql, 3);
      const char *zCI = (const char*)sqlite3_column_text(pSql, 4);
      const char *zParent = (const char*)sqlite3_column_text(pSql, 5);
      rc = sqlite3_prepare_v2(db, zEQP, -1, &pExplain, 0);
      if(rc!=SQLITE_OK) break;
      if(SQLITE_ROW==sqlite3_step(pExplain)){
        const char *zPlan = (const char*)sqlite3_column_text(pExplain, 3);
        res = (
              0==sqlite3_strglob(zGlob, zPlan)
           || 0==sqlite3_strglob(zGlobIPK, zPlan)
        );
      }
      rc = sqlite3_finalize(pExplain);
      if(rc!=SQLITE_OK) break;
      if(res<0){
        raw_printf(stderr, "Error: internal error");
        break;
      }else{
        if(bGroupByParent
        && (bVerbose || res==0)
        && (zPrev==0 || sqlite3_stricmp(zParent, zPrev))
        ){
          raw_printf(out, "-- Parent table %s\n", zParent);
          sqlite3_free(zPrev);
          zPrev = sqlite3_mprintf("%s", zParent);
        }
        if(res==0){
          raw_printf(out, "%s%s --> %s\n", zIndent, zCI, zTarget);
        }else if(bVerbose){
          raw_printf(out, "%s/* no extra indexes required for %s -> %s */\n",
              zIndent, zFrom, zTarget
          );
        }
      }
    }
    sqlite3_free(zPrev);
    if(rc!=SQLITE_OK){
      raw_printf(stderr, "%s\n", sqlite3_errmsg(db));
    }
    rc2 = sqlite3_finalize(pSql);
    if(rc==SQLITE_OK && rc2!=SQLITE_OK){
      rc = rc2;
      raw_printf(stderr, "%s\n", sqlite3_errmsg(db));
    }
  }else{
    raw_printf(stderr, "%s\n", sqlite3_errmsg(db));
  }
  return rc;
}
local_getline()
static char* local_getline (char * zLine, FILE * in) [static]
Definition at line 584 of file shell.c.
References shell_out_of_memory(), sqlite3_free, and strlen30().
Referenced by one_input_line().
                                                 {
  int nLine = zLine==0 ? 0 : 100;
  int n = 0;
  while(1){
    if(n+100>nLine){
      nLine = nLine*2 + 100;
      zLine = realloc(zLine, nLine);
      if(zLine==0) shell_out_of_memory();
    }
    if(fgets(&zLine[n], nLine - n, in)==0){
      if(n==0){
        free(zLine);
        return 0;
      }
      zLine[n] = 0;
      break;
    }
    while(zLine[n]) n++;
    if(n>0 && zLine[n-1]=='\n'){
      n--;
      if(n>0 && zLine[n-1]=='\r') n--;
      zLine[n] = 0;
      break;
    }
  }
#if defined(_WIN32) || defined(WIN32)
  /* For interactive input on Windows systems, translate the
  ** multi-byte characterset characters into UTF-8. */
  if(stdin_is_interactive && in==stdin){
    char *zTrans = sqlite3_win32_mbcs_to_utf8_v2(zLine, 0);
    if(zTrans){
      int nTrans = strlen30(zTrans)+1;
      if(nTrans>nLine){
        zLine = realloc(zLine, nTrans);
        if(zLine==0) shell_out_of_memory();
      }
      memcpy(zLine, zTrans, nTrans);
      sqlite3_free(zTrans);
    }
  }
#endif /* defined(_WIN32) || defined(WIN32) */
  return zLine;
}
lsModeFunc()
static void lsModeFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 2537 of file shell.c.
References sqlite3_result_text, sqlite3_value_int, and SQLITE_TRANSIENT.
Referenced by sqlite3_fileio_init().
 {
  int i;
  int iMode = sqlite3_value_int(argv[0]);
  char z[16];
  (void)argc;
  if(S_ISLNK(iMode)){
    z[0] = 'l';
  }else if(S_ISREG(iMode)){
    z[0] = '-';
  }else if(S_ISDIR(iMode)){
    z[0] = 'd';
  }else{
    z[0] = '?';
  }
  for(i=0; i<3; i++){
    int m = (iMode >> ((2-i)*3));
    char *a = &z[1 + i*3];
    a[0] = (m & 0x4) ? 'r' : '-';
    a[1] = (m & 0x2) ? 'w' : '-';
    a[2] = (m & 0x1) ? 'x' : '-';
  }
  z[10] = '\0';
  sqlite3_result_text(context, z, -1, SQLITE_TRANSIENT);
}
main()
int SQLITE_CDECL main (int argc, char ** argv)
Definition at line 18665 of file shell.c.
References ShellState::autoEQP, AUTOEQP_full, AUTOEQP_on, clearTempFile(), close_db(), cmdline_option_value(), ShellState::cMode, ShellState::colSeparator, main3::data, ShellState::db, do_meta_command(), ShellState::doXdgOpen, find_home_dir(), GETPID, ShellState::in, integerValue(), interrupt_handler(), isatty(), main_init(), ShellState::mode, MODE_Ascii, MODE_Column, MODE_Csv, MODE_Html, MODE_Line, MODE_List, MODE_Quote, ShellState::nullValue, open_db(), OPEN_DB_ZIPFILE, ShellState::openFlags, ShellState::openMode, ShellState::out, output_reset(), printBold(), process_input(), process_sqliterc(), raw_printf, ShellState::rowSeparator, ShellState::scanstatsOn, SEP_Record, SEP_Unit, session_close_all, set_table_name(), setBinaryMode, shell_exec(), SHELL_OPEN_APPENDVFS, SHELL_OPEN_DESERIALIZE, SHELL_OPEN_READONLY, SHELL_OPEN_ZIPFILE, shell_out_of_memory(), shell_read_history, shell_stifle_history, shell_write_history, ShellState::shellFlgs, ShellSetFlag, SHFLG_Backslash, SHFLG_Echo, SHFLG_Lookaside, SHFLG_Pagecache, ShellState::showHeader, sqlite3_appendvfs_init(), sqlite3_config(), sqlite3_free, sqlite3_initialize(), sqlite3_libversion, sqlite3_shutdown(), sqlite3_snprintf, sqlite3_sourceid, sqlite3_vfs_find, sqlite3_vfs_register, sqlite3MemTraceActivate(), SQLITE_CDECL, SQLITE_CONFIG_HEAP, SQLITE_CONFIG_LOOKASIDE, SQLITE_CONFIG_MMAP_SIZE, SQLITE_CONFIG_PAGECACHE, SQLITE_CONFIG_SORTERREF_SIZE, SQLITE_OPEN_NOFOLLOW, SQLITE_SOURCE_ID, ShellState::statsOn, strlen30(), ShellState::szMax, usage(), utf8_printf, verify_uninitialized(), ShellState::zDbFilename, and ShellState::zFreeOnClose.
                                            {
#else
int SQLITE_CDECL wmain(int argc, wchar_t **wargv){
  char **argv;
#endif
  char *zErrMsg = 0;
  ShellState data;
  const char *zInitFile = 0;
  int i;
  int rc = 0;
  int warnInmemoryDb = 0;
  int readStdin = 1;
  int nCmd = 0;
  char **azCmd = 0;
  const char *zVfs = 0; /* Value of -vfs command-line option */
#if !SQLITE_SHELL_IS_UTF8
  char **argvToFree = 0;
  int argcToFree = 0;
#endif
  setBinaryMode(stdin, 0);
  setvbuf(stderr, 0, _IONBF, 0); /* Make sure stderr is unbuffered */
  stdin_is_interactive = isatty(0);
  stdout_is_console = isatty(1);
#if !defined(_WIN32_WCE)
  if(getenv("SQLITE_DEBUG_BREAK")){
    if(isatty(0) && isatty(2)){
      fprintf(stderr,
          "attach debugger to process %d and press any key to continue.\n",
          GETPID());
      fgetc(stdin);
    }else{
#if defined(_WIN32) || defined(WIN32)
      DebugBreak();
#elif defined(SIGTRAP)
      raise(SIGTRAP);
#endif
    }
  }
#endif
#if USE_SYSTEM_SQLITE+0!=1
  if(strncmp(sqlite3_sourceid(),SQLITE_SOURCE_ID,60)!=0){
    utf8_printf(stderr, "SQLite header and source version mismatch\n%s\n%s\n",
            sqlite3_sourceid(), SQLITE_SOURCE_ID);
    exit(1);
  }
#endif
  main_init(&data);
  /* On Windows, we must translate command-line arguments into UTF-8.
  ** The SQLite memory allocator subsystem has to be enabled in order to
  ** do this. But we want to run an sqlite3_shutdown() afterwards so that
  ** subsequent sqlite3_config() calls will work. So copy all results into
  ** memory that does not come from the SQLite memory allocator.
  */
#if !SQLITE_SHELL_IS_UTF8
  sqlite3_initialize();
  argvToFree = malloc(sizeof(argv[0])*argc*2);
  argcToFree = argc;
  argv = argvToFree + argc;
  if(argv==0) shell_out_of_memory();
  for(i=0; i<argc; i++){
    char *z = sqlite3_win32_unicode_to_utf8(wargv[i]);
    int n;
    if(z==0) shell_out_of_memory();
    n = (int)strlen(z);
    argv[i] = malloc(n+1);
    if(argv[i]==0) shell_out_of_memory();
    memcpy(argv[i], z, n+1);
    argvToFree[i] = argv[i];
    sqlite3_free(z);
  }
  sqlite3_shutdown();
#endif
  assert(argc>=1 && argv && argv[0]);
  Argv0 = argv[0];
  /* Make sure we have a valid signal handler early, before anything
  ** else is done.
  */
#ifdef SIGINT
  signal(SIGINT, interrupt_handler);
#elif (defined(_WIN32) || defined(WIN32)) && !defined(_WIN32_WCE)
  SetConsoleCtrlHandler(ConsoleCtrlHandler, TRUE);
#endif
#ifdef SQLITE_SHELL_DBNAME_PROC
  {
    /* If the SQLITE_SHELL_DBNAME_PROC macro is defined, then it is the name
    ** of a C-function that will provide the name of the database file. Use
    ** this compile-time option to embed this shell program in larger
    ** applications. */
    extern void SQLITE_SHELL_DBNAME_PROC(const char**);
    SQLITE_SHELL_DBNAME_PROC(&data.zDbFilename);
    warnInmemoryDb = 0;
  }
#endif
  /* Do an initial pass through the command-line argument to locate
  ** the name of the database file, the name of the initialization file,
  ** the size of the alternative malloc heap,
  ** and the first command to execute.
  */
  verify_uninitialized();
  for(i=1; i<argc; i++){
    char *z;
    z = argv[i];
    if(z[0]!='-'){
      if(data.zDbFilename==0){
        data.zDbFilename = z;
      }else{
        /* Excesss arguments are interpreted as SQL (or dot-commands) and
        ** mean that nothing is read from stdin */
        readStdin = 0;
        nCmd++;
        azCmd = realloc(azCmd, sizeof(azCmd[0])*nCmd);
        if(azCmd==0) shell_out_of_memory();
        azCmd[nCmd-1] = z;
      }
    }
    if(z[1]=='-') z++;
    if(strcmp(z,"-separator")==0
     || strcmp(z,"-nullvalue")==0
     || strcmp(z,"-newline")==0
     || strcmp(z,"-cmd")==0
    ){
      (void)cmdline_option_value(argc, argv, ++i);
    }else if(strcmp(z,"-init")==0){
      zInitFile = cmdline_option_value(argc, argv, ++i);
    }else if(strcmp(z,"-batch")==0){
      /* Need to check for batch mode here to so we can avoid printing
      ** informational messages (like from process_sqliterc) before
      ** we do the actual processing of arguments later in a second pass.
      */
      stdin_is_interactive = 0;
    }else if(strcmp(z,"-heap")==0){
#if defined(SQLITE_ENABLE_MEMSYS3) || defined(SQLITE_ENABLE_MEMSYS5)
      const char *zSize;
      sqlite3_int64 szHeap;
      zSize = cmdline_option_value(argc, argv, ++i);
      szHeap = integerValue(zSize);
      if(szHeap>0x7fff0000) szHeap = 0x7fff0000;
      sqlite3_config(SQLITE_CONFIG_HEAP, malloc((int)szHeap), (int)szHeap, 64);
#else
      (void)cmdline_option_value(argc, argv, ++i);
#endif
    }else if(strcmp(z,"-pagecache")==0){
      int n, sz;
      sz = (int)integerValue(cmdline_option_value(argc,argv,++i));
      if(sz>70000) sz = 70000;
      if(sz<0) sz = 0;
      n = (int)integerValue(cmdline_option_value(argc,argv,++i));
      sqlite3_config(SQLITE_CONFIG_PAGECACHE,
                    (n>0 && sz>0) ? malloc(n*sz) : 0, sz, n);
      data.shellFlgs |= SHFLG_Pagecache;
    }else if(strcmp(z,"-lookaside")==0){
      int n, sz;
      sz = (int)integerValue(cmdline_option_value(argc,argv,++i));
      if(sz<0) sz = 0;
      n = (int)integerValue(cmdline_option_value(argc,argv,++i));
      if(n<0) n = 0;
      sqlite3_config(SQLITE_CONFIG_LOOKASIDE, sz, n);
      if(sz*n==0) data.shellFlgs &= ~SHFLG_Lookaside;
#ifdef SQLITE_ENABLE_VFSTRACE
    }else if(strcmp(z,"-vfstrace")==0){
      extern int vfstrace_register(
         const char *zTraceName,
         const char *zOldVfsName,
         int (*xOut)(const char*,void*),
         void *pOutArg,
         int makeDefault
      );
      vfstrace_register("trace",0,(int(*)(const char*,void*))fputs,stderr,1);
#endif
#ifdef SQLITE_ENABLE_MULTIPLEX
    }else if(strcmp(z,"-multiplex")==0){
      extern int sqlite3_multiple_initialize(const char*,int);
      sqlite3_multiplex_initialize(0, 1);
#endif
    }else if(strcmp(z,"-mmap")==0){
      sqlite3_int64 sz = integerValue(cmdline_option_value(argc,argv,++i));
      sqlite3_config(SQLITE_CONFIG_MMAP_SIZE, sz, sz);
#ifdef SQLITE_ENABLE_SORTER_REFERENCES
    }else if(strcmp(z,"-sorterref")==0){
      sqlite3_int64 sz = integerValue(cmdline_option_value(argc,argv,++i));
      sqlite3_config(SQLITE_CONFIG_SORTERREF_SIZE, (int)sz);
#endif
    }else if(strcmp(z,"-vfs")==0){
      zVfs = cmdline_option_value(argc, argv, ++i);
#ifdef SQLITE_HAVE_ZLIB
    }else if(strcmp(z,"-zip")==0){
      data.openMode = SHELL_OPEN_ZIPFILE;
#endif
    }else if(strcmp(z,"-append")==0){
      data.openMode = SHELL_OPEN_APPENDVFS;
#ifdef SQLITE_ENABLE_DESERIALIZE
    }else if(strcmp(z,"-deserialize")==0){
      data.openMode = SHELL_OPEN_DESERIALIZE;
    }else if(strcmp(z,"-maxsize")==0 && i+1<argc){
      data.szMax = integerValue(argv[++i]);
#endif
    }else if(strcmp(z,"-readonly")==0){
      data.openMode = SHELL_OPEN_READONLY;
    }else if(strcmp(z,"-nofollow")==0){
      data.openFlags = SQLITE_OPEN_NOFOLLOW;
#if !defined(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_HAVE_ZLIB)
    }else if(strncmp(z, "-A",2)==0){
      /* All remaining command-line arguments are passed to the ".archive"
      ** command, so ignore them */
      break;
#endif
    }else if(strcmp(z, "-memtrace")==0){
      sqlite3MemTraceActivate(stderr);
    }
  }
  verify_uninitialized();
#ifdef SQLITE_SHELL_INIT_PROC
  {
    /* If the SQLITE_SHELL_INIT_PROC macro is defined, then it is the name
    ** of a C-function that will perform initialization actions on SQLite that
    ** occur just before or after sqlite3_initialize(). Use this compile-time
    ** option to embed this shell program in larger applications. */
    extern void SQLITE_SHELL_INIT_PROC(void);
    SQLITE_SHELL_INIT_PROC();
  }
#else
  /* All the sqlite3_config() calls have now been made. So it is safe
  ** to call sqlite3_initialize() and process any command line -vfs option. */
  sqlite3_initialize();
#endif
  if(zVfs){
    sqlite3_vfs *pVfs = sqlite3_vfs_find(zVfs);
    if(pVfs){
      sqlite3_vfs_register(pVfs, 1);
    }else{
      utf8_printf(stderr, "no such VFS: \"%s\"\n", argv[i]);
      exit(1);
    }
  }
  if(data.zDbFilename==0){
#ifndef SQLITE_OMIT_MEMORYDB
    data.zDbFilename = ":memory:";
    warnInmemoryDb = argc==1;
#else
    utf8_printf(stderr,"%s: Error: no database filename specified\n", Argv0);
    return 1;
#endif
  }
  data.out = stdout;
  sqlite3_appendvfs_init(0,0,0);
  /* Go ahead and open the database file if it already exists. If the
  ** file does not exist, delay opening it. This prevents empty database
  ** files from being created if a user mistypes the database name argument
  ** to the sqlite command-line tool.
  */
  if(access(data.zDbFilename, 0)==0){
    open_db(&data, 0);
  }
  /* Process the initialization file if there is one. If no -init option
  ** is given on the command line, look for a file named ~/.sqliterc and
  ** try to process it.
  */
  process_sqliterc(&data,zInitFile);
  /* Make a second pass through the command-line argument and set
  ** options. This second pass is delayed until after the initialization
  ** file is processed so that the command-line arguments will override
  ** settings in the initialization file.
  */
  for(i=1; i<argc; i++){
    char *z = argv[i];
    if(z[0]!='-') continue;
    if(z[1]=='-'){ z++; }
    if(strcmp(z,"-init")==0){
      i++;
    }else if(strcmp(z,"-html")==0){
      data.mode = MODE_Html;
    }else if(strcmp(z,"-list")==0){
      data.mode = MODE_List;
    }else if(strcmp(z,"-quote")==0){
      data.mode = MODE_Quote;
    }else if(strcmp(z,"-line")==0){
      data.mode = MODE_Line;
    }else if(strcmp(z,"-column")==0){
      data.mode = MODE_Column;
    }else if(strcmp(z,"-csv")==0){
      data.mode = MODE_Csv;
      memcpy(data.colSeparator,",",2);
#ifdef SQLITE_HAVE_ZLIB
    }else if(strcmp(z,"-zip")==0){
      data.openMode = SHELL_OPEN_ZIPFILE;
#endif
    }else if(strcmp(z,"-append")==0){
      data.openMode = SHELL_OPEN_APPENDVFS;
#ifdef SQLITE_ENABLE_DESERIALIZE
    }else if(strcmp(z,"-deserialize")==0){
      data.openMode = SHELL_OPEN_DESERIALIZE;
    }else if(strcmp(z,"-maxsize")==0 && i+1<argc){
      data.szMax = integerValue(argv[++i]);
#endif
    }else if(strcmp(z,"-readonly")==0){
      data.openMode = SHELL_OPEN_READONLY;
    }else if(strcmp(z,"-nofollow")==0){
      data.openFlags |= SQLITE_OPEN_NOFOLLOW;
    }else if(strcmp(z,"-ascii")==0){
      data.mode = MODE_Ascii;
      sqlite3_snprintf(sizeof(data.colSeparator), data.colSeparator,
                       SEP_Unit);
      sqlite3_snprintf(sizeof(data.rowSeparator), data.rowSeparator,
                       SEP_Record);
    }else if(strcmp(z,"-separator")==0){
      sqlite3_snprintf(sizeof(data.colSeparator), data.colSeparator,
                       "%s",cmdline_option_value(argc,argv,++i));
    }else if(strcmp(z,"-newline")==0){
      sqlite3_snprintf(sizeof(data.rowSeparator), data.rowSeparator,
                       "%s",cmdline_option_value(argc,argv,++i));
    }else if(strcmp(z,"-nullvalue")==0){
      sqlite3_snprintf(sizeof(data.nullValue), data.nullValue,
                       "%s",cmdline_option_value(argc,argv,++i));
    }else if(strcmp(z,"-header")==0){
      data.showHeader = 1;
    }else if(strcmp(z,"-noheader")==0){
      data.showHeader = 0;
    }else if(strcmp(z,"-echo")==0){
      ShellSetFlag(&data, SHFLG_Echo);
    }else if(strcmp(z,"-eqp")==0){
      data.autoEQP = AUTOEQP_on;
    }else if(strcmp(z,"-eqpfull")==0){
      data.autoEQP = AUTOEQP_full;
    }else if(strcmp(z,"-stats")==0){
      data.statsOn = 1;
    }else if(strcmp(z,"-scanstats")==0){
      data.scanstatsOn = 1;
    }else if(strcmp(z,"-backslash")==0){
      /* Undocumented command-line option: -backslash
      ** Causes C-style backslash escapes to be evaluated in SQL statements
      ** prior to sending the SQL into SQLite. Useful for injecting
      ** crazy bytes in the middle of SQL statements for testing and debugging.
      */
      ShellSetFlag(&data, SHFLG_Backslash);
    }else if(strcmp(z,"-bail")==0){
      bail_on_error = 1;
    }else if(strcmp(z,"-version")==0){
      printf("%s %s\n", sqlite3_libversion(), sqlite3_sourceid());
      return 0;
    }else if(strcmp(z,"-interactive")==0){
      stdin_is_interactive = 1;
    }else if(strcmp(z,"-batch")==0){
      stdin_is_interactive = 0;
    }else if(strcmp(z,"-heap")==0){
      i++;
    }else if(strcmp(z,"-pagecache")==0){
      i+=2;
    }else if(strcmp(z,"-lookaside")==0){
      i+=2;
    }else if(strcmp(z,"-mmap")==0){
      i++;
    }else if(strcmp(z,"-memtrace")==0){
      i++;
#ifdef SQLITE_ENABLE_SORTER_REFERENCES
    }else if(strcmp(z,"-sorterref")==0){
      i++;
#endif
    }else if(strcmp(z,"-vfs")==0){
      i++;
#ifdef SQLITE_ENABLE_VFSTRACE
    }else if(strcmp(z,"-vfstrace")==0){
      i++;
#endif
#ifdef SQLITE_ENABLE_MULTIPLEX
    }else if(strcmp(z,"-multiplex")==0){
      i++;
#endif
    }else if(strcmp(z,"-help")==0){
      usage(1);
    }else if(strcmp(z,"-cmd")==0){
      /* Run commands that follow -cmd first and separately from commands
      ** that simply appear on the command-line. This seems goofy. It would
      ** be better if all commands ran in the order that they appear. But
      ** we retain the goofy behavior for historical compatibility. */
      if(i==argc-1) break;
      z = cmdline_option_value(argc,argv,++i);
      if(z[0]=='.'){
        rc = do_meta_command(z, &data);
        if(rc && bail_on_error) return rc==2 ? 0 : rc;
      }else{
        open_db(&data, 0);
        rc = shell_exec(&data, z, &zErrMsg);
        if(zErrMsg!=0){
          utf8_printf(stderr,"Error: %s\n", zErrMsg);
          if(bail_on_error) return rc!=0 ? rc : 1;
        }else if(rc!=0){
          utf8_printf(stderr,"Error: unable to process SQL \"%s\"\n", z);
          if(bail_on_error) return rc;
        }
      }
#if !defined(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_HAVE_ZLIB)
    }else if(strncmp(z, "-A", 2)==0){
      if(nCmd>0){
        utf8_printf(stderr, "Error: cannot mix regular SQL or dot-commands"
                            " with \"%s\"\n", z);
        return 1;
      }
      open_db(&data, OPEN_DB_ZIPFILE);
      if(z[2]){
        argv[i] = &z[2];
        arDotCommand(&data, 1, argv+(i-1), argc-(i-1));
      }else{
        arDotCommand(&data, 1, argv+i, argc-i);
      }
      readStdin = 0;
      break;
#endif
    }else{
      utf8_printf(stderr,"%s: Error: unknown option: %s\n", Argv0, z);
      raw_printf(stderr,"Use -help for a list of options.\n");
      return 1;
    }
    data.cMode = data.mode;
  }
  if(!readStdin){
    /* Run all arguments that do not begin with '-' as if they were separate
    ** command-line inputs, except for the argToSkip argument which contains
    ** the database filename.
    */
    for(i=0; i<nCmd; i++){
      if(azCmd[i][0]=='.'){
        rc = do_meta_command(azCmd[i], &data);
        if(rc) return rc==2 ? 0 : rc;
      }else{
        open_db(&data, 0);
        rc = shell_exec(&data, azCmd[i], &zErrMsg);
        if(zErrMsg!=0){
          utf8_printf(stderr,"Error: %s\n", zErrMsg);
          return rc!=0 ? rc : 1;
        }else if(rc!=0){
          utf8_printf(stderr,"Error: unable to process SQL: %s\n", azCmd[i]);
          return rc;
        }
      }
    }
    free(azCmd);
  }else{
    /* Run commands received from standard input
    */
    if(stdin_is_interactive){
      char *zHome;
      char *zHistory;
      int nHistory;
      printf(
        "SQLite version %s %.19s\n" /*extra-version-info*/
        "Enter \".help\" for usage hints.\n",
        sqlite3_libversion(), sqlite3_sourceid()
      );
      if(warnInmemoryDb){
        printf("Connected to a ");
        printBold("transient in-memory database");
        printf(".\nUse \".open FILENAME\" to reopen on a "
               "persistent database.\n");
      }
      zHistory = getenv("SQLITE_HISTORY");
      if(zHistory){
        zHistory = strdup(zHistory);
      }else if((zHome = find_home_dir(0))!=0){
        nHistory = strlen30(zHome) + 20;
        if((zHistory = malloc(nHistory))!=0){
          sqlite3_snprintf(nHistory, zHistory,"%s/.sqlite_history", zHome);
        }
      }
      if(zHistory){ shell_read_history(zHistory); }
#if HAVE_READLINE || HAVE_EDITLINE
      rl_attempted_completion_function = readline_completion;
#elif HAVE_LINENOISE
      linenoiseSetCompletionCallback(linenoise_completion);
#endif
      data.in = 0;
      rc = process_input(&data);
      if(zHistory){
        shell_stifle_history(2000);
        shell_write_history(zHistory);
        free(zHistory);
      }
    }else{
      data.in = stdin;
      rc = process_input(&data);
    }
  }
  set_table_name(&data, 0);
  if(data.db){
    session_close_all(&data);
    close_db(data.db);
  }
  sqlite3_free(data.zFreeOnClose);
  find_home_dir(1);
  output_reset(&data);
  data.doXdgOpen = 0;
  clearTempFile(&data);
#if !SQLITE_SHELL_IS_UTF8
  for(i=0; i<argcToFree; i++) free(argvToFree[i]);
  free(argvToFree);
#endif
  /* Clear the global data structure so that valgrind will detect memory
  ** leaks */
  memset(&data, 0, sizeof(data));
  return rc;
}
main_init()
static void main_init (ShellState * data) [static]
Definition at line 18607 of file shell.c.
References ShellState::autoExplain, ShellState::cMode, ShellState::colSeparator, ShellState::mode, MODE_List, ShellState::normalMode, printBold(), ShellState::rowSeparator, SEP_Column, SEP_Row, ShellState::shellFlgs, shellLog(), SHFLG_Lookaside, ShellState::showHeader, sqlite3_config(), sqlite3_snprintf, SQLITE_CONFIG_LOG, SQLITE_CONFIG_MULTITHREAD, SQLITE_CONFIG_URI, and verify_uninitialized().
Referenced by main().
                                        {
  memset(data, 0, sizeof(*data));
  data->normalMode = data->cMode = data->mode = MODE_List;
  data->autoExplain = 1;
  memcpy(data->colSeparator,SEP_Column, 2);
  memcpy(data->rowSeparator,SEP_Row, 2);
  data->showHeader = 0;
  data->shellFlgs = SHFLG_Lookaside;
  verify_uninitialized();
  sqlite3_config(SQLITE_CONFIG_URI, 1);
  sqlite3_config(SQLITE_CONFIG_LOG, shellLog, data);
  sqlite3_config(SQLITE_CONFIG_MULTITHREAD);
  sqlite3_snprintf(sizeof(mainPrompt), mainPrompt,"sqlite> ");
  sqlite3_snprintf(sizeof(continuePrompt), continuePrompt," ...> ");
}
makeDirectory()
static int makeDirectory (const char * zFile) [static]
Definition at line 2335 of file shell.c.
References fileStat(), sqlite3_free, sqlite3_mprintf, SQLITE_ERROR, SQLITE_NOMEM, and SQLITE_OK.
Referenced by writefileFunc().
 {
  char *zCopy = sqlite3_mprintf("%s", zFile);
  int rc = SQLITE_OK;
  if(zCopy==0){
    rc = SQLITE_NOMEM;
  }else{
    int nCopy = (int)strlen(zCopy);
    int i = 1;
    while(rc==SQLITE_OK){
      struct stat sStat;
      int rc2;
      for(; zCopy[i]!='/' && i<nCopy; i++);
      if(i==nCopy) break;
      zCopy[i] = '\0';
      rc2 = fileStat(zCopy, &sStat);
      if(rc2!=0){
        if(mkdir(zCopy, 0777)) rc = SQLITE_ERROR;
      }else{
        if(!S_ISDIR(sStat.st_mode)) rc = SQLITE_ERROR;
      }
      zCopy[i] = '/';
      i++;
    }
    sqlite3_free(zCopy);
  }
  return rc;
}
memtraceFree()
static void memtraceFree (void * p) [static]
Definition at line 4145 of file shell.c.
References sqlite3_mem_methods::xFree, and sqlite3_mem_methods::xSize.
Referenced by memtraceRealloc().
                                 {
  if(p==0) return;
  if(memtraceOut){
    fprintf(memtraceOut, "MEMTRACE: free %d bytes\n", memtraceBase.xSize(p));
  }
  memtraceBase.xFree(p);
}
memtraceInit()
static int memtraceInit (void * p) [static]
Definition at line 4170 of file shell.c.
References sqlite3_mem_methods::xInit.
                                {
  return memtraceBase.xInit(p);
}
memtraceMalloc()
static void* memtraceMalloc (int n) [static]
Definition at line 4138 of file shell.c.
References sqlite3_mem_methods::xMalloc, and sqlite3_mem_methods::xRoundup.
Referenced by memtraceRealloc().
                                  {
  if(memtraceOut){
    fprintf(memtraceOut, "MEMTRACE: allocate %d bytes\n",
            memtraceBase.xRoundup(n));
  }
  return memtraceBase.xMalloc(n);
}
memtraceRealloc()
static void* memtraceRealloc (void * p, int n) [static]
Definition at line 4152 of file shell.c.
References memtraceFree(), memtraceMalloc(), sqlite3_mem_methods::xRealloc, sqlite3_mem_methods::xRoundup, and sqlite3_mem_methods::xSize.
                                            {
  if(p==0) return memtraceMalloc(n);
  if(n==0){
    memtraceFree(p);
    return 0;
  }
  if(memtraceOut){
    fprintf(memtraceOut, "MEMTRACE: resize %d -> %d bytes\n",
            memtraceBase.xSize(p), memtraceBase.xRoundup(n));
  }
  return memtraceBase.xRealloc(p, n);
}
memtraceRoundup()
static int memtraceRoundup (int n) [static]
Definition at line 4167 of file shell.c.
References sqlite3_mem_methods::xRoundup.
                                 {
  return memtraceBase.xRoundup(n);
}
memtraceShutdown()
static void memtraceShutdown (void * p) [static]
Definition at line 4173 of file shell.c.
References sqlite3_mem_methods::xShutdown.
                                     {
  memtraceBase.xShutdown(p);
}
memtraceSize()
static int memtraceSize (void * p) [static]
Definition at line 4164 of file shell.c.
References sqlite3_mem_methods::xSize.
                                {
  return memtraceBase.xSize(p);
}
newTempFile()
static void newTempFile (ShellState * p, const char * zSuffix) [static]
Definition at line 13743 of file shell.c.
References clearTempFile(), ShellState::db, raw_printf, sqlite3_file_control, sqlite3_free, sqlite3_mprintf, sqlite3_randomness, SQLITE_FCNTL_TEMPFILENAME, and ShellState::zTempFile.
Referenced by do_meta_command().
                                                           {
  clearTempFile(p);
  sqlite3_free(p->zTempFile);
  p->zTempFile = 0;
  if(p->db){
    sqlite3_file_control(p->db, 0, SQLITE_FCNTL_TEMPFILENAME, &p->zTempFile);
  }
  if(p->zTempFile==0){
    sqlite3_uint64 r;
    sqlite3_randomness(sizeof(r), &r);
    p->zTempFile = sqlite3_mprintf("temp%llx.%s", r, zSuffix);
  }else{
    p->zTempFile = sqlite3_mprintf("%z.%s", p->zTempFile, zSuffix);
  }
  if(p->zTempFile==0){
    raw_printf(stderr, "out of memory\n");
    exit(1);
  }
}
one_input_line()
static char* one_input_line (FILE * in, char * zPrior, int isContinuation) [static]
Definition at line 643 of file shell.c.
References continuePrompt, local_getline(), and mainPrompt.
Referenced by process_input().
                                                                       {
  char *zPrompt;
  char *zResult;
  if(in!=0){
    zResult = local_getline(zPrior, in);
  }else{
    zPrompt = isContinuation ? continuePrompt : mainPrompt;
#if SHELL_USE_LOCAL_GETLINE
    printf("%s", zPrompt);
    fflush(stdout);
    zResult = local_getline(zPrior, stdin);
#else
    free(zPrior);
    zResult = shell_readline(zPrompt);
    if(zResult && *zResult) shell_add_history(zResult);
#endif
  }
  return zResult;
}
open_db()
static void open_db (ShellState * p, int openFlags) [static]
Definition at line 12687 of file shell.c.
References ShellState::db, deduceDatabaseType(), editFunc(), OPEN_DB_KEEPALIVE, OPEN_DB_ZIPFILE, ShellState::openFlags, ShellState::openMode, readFile(), SHELL_OPEN_APPENDVFS, SHELL_OPEN_DESERIALIZE, SHELL_OPEN_HEXDB, SHELL_OPEN_NORMAL, SHELL_OPEN_READONLY, SHELL_OPEN_UNSPEC, SHELL_OPEN_ZIPFILE, shellAddSchemaName(), shellEscapeCrnl(), shellIdQuote(), shellInt32(), shellModuleSchema(), shellPutsFunc(), sqlite3_completion_init(), sqlite3_create_function, sqlite3_deserialize(), sqlite3_enable_load_extension(), sqlite3_errcode, sqlite3_errmsg, sqlite3_exec, sqlite3_file_control, sqlite3_fileio_init(), sqlite3_free, sqlite3_mprintf, sqlite3_open, sqlite3_open_v2, sqlite3_shathree_init(), SQLITE_DESERIALIZE_FREEONCLOSE, SQLITE_DESERIALIZE_RESIZEABLE, SQLITE_FCNTL_SIZE_LIMIT, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_UTF8, ShellState::szMax, utf8_printf, and ShellState::zDbFilename.
Referenced by do_meta_command(), main(), runOneSqlLine(), and shell_dbinfo_command().
                                                 {
  if(p->db==0){
    if(p->openMode==SHELL_OPEN_UNSPEC){
      if(p->zDbFilename==0 || p->zDbFilename[0]==0){
        p->openMode = SHELL_OPEN_NORMAL;
      }else{
        p->openMode = (u8)deduceDatabaseType(p->zDbFilename,
                             (openFlags & OPEN_DB_ZIPFILE)!=0);
      }
    }
    switch(p->openMode){
      case SHELL_OPEN_APPENDVFS: {
        sqlite3_open_v2(p->zDbFilename, &p->db,
           SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|p->openFlags, "apndvfs");
        break;
      }
      case SHELL_OPEN_HEXDB:
      case SHELL_OPEN_DESERIALIZE: {
        sqlite3_open(0, &p->db);
        break;
      }
      case SHELL_OPEN_ZIPFILE: {
        sqlite3_open(":memory:", &p->db);
        break;
      }
      case SHELL_OPEN_READONLY: {
        sqlite3_open_v2(p->zDbFilename, &p->db,
            SQLITE_OPEN_READONLY|p->openFlags, 0);
        break;
      }
      case SHELL_OPEN_UNSPEC:
      case SHELL_OPEN_NORMAL: {
        sqlite3_open_v2(p->zDbFilename, &p->db,
           SQLITE_OPEN_READWRITE|SQLITE_OPEN_CREATE|p->openFlags, 0);
        break;
      }
    }
    globalDb = p->db;
    if(p->db==0 || SQLITE_OK!=sqlite3_errcode(p->db)){
      utf8_printf(stderr,"Error: unable to open database \"%s\": %s\n",
          p->zDbFilename, sqlite3_errmsg(p->db));
      if(openFlags & OPEN_DB_KEEPALIVE){
        sqlite3_open(":memory:", &p->db);
        return;
      }
      exit(1);
    }
#ifndef SQLITE_OMIT_LOAD_EXTENSION
    sqlite3_enable_load_extension(p->db, 1);
#endif
    sqlite3_fileio_init(p->db, 0, 0);
    sqlite3_shathree_init(p->db, 0, 0);
    sqlite3_completion_init(p->db, 0, 0);
#if !defined(SQLITE_OMIT_VIRTUALTABLE) && defined(SQLITE_ENABLE_DBPAGE_VTAB)
    sqlite3_dbdata_init(p->db, 0, 0);
#endif
#ifdef SQLITE_HAVE_ZLIB
    sqlite3_zipfile_init(p->db, 0, 0);
    sqlite3_sqlar_init(p->db, 0, 0);
#endif
    sqlite3_create_function(p->db, "shell_add_schema", 3, SQLITE_UTF8, 0,
                            shellAddSchemaName, 0, 0);
    sqlite3_create_function(p->db, "shell_module_schema", 1, SQLITE_UTF8, 0,
                            shellModuleSchema, 0, 0);
    sqlite3_create_function(p->db, "shell_putsnl", 1, SQLITE_UTF8, p,
                            shellPutsFunc, 0, 0);
    sqlite3_create_function(p->db, "shell_escape_crnl", 1, SQLITE_UTF8, 0,
                            shellEscapeCrnl, 0, 0);
    sqlite3_create_function(p->db, "shell_int32", 2, SQLITE_UTF8, 0,
                            shellInt32, 0, 0);
    sqlite3_create_function(p->db, "shell_idquote", 1, SQLITE_UTF8, 0,
                            shellIdQuote, 0, 0);
#ifndef SQLITE_NOHAVE_SYSTEM
    sqlite3_create_function(p->db, "edit", 1, SQLITE_UTF8, 0,
                            editFunc, 0, 0);
    sqlite3_create_function(p->db, "edit", 2, SQLITE_UTF8, 0,
                            editFunc, 0, 0);
#endif
    if(p->openMode==SHELL_OPEN_ZIPFILE){
      char *zSql = sqlite3_mprintf(
         "CREATE VIRTUAL TABLE zip USING zipfile(%Q);", p->zDbFilename);
      sqlite3_exec(p->db, zSql, 0, 0, 0);
      sqlite3_free(zSql);
    }
#ifdef SQLITE_ENABLE_DESERIALIZE
    else
    if(p->openMode==SHELL_OPEN_DESERIALIZE || p->openMode==SHELL_OPEN_HEXDB){
      int rc;
      int nData = 0;
      unsigned char *aData;
      if(p->openMode==SHELL_OPEN_DESERIALIZE){
        aData = (unsigned char*)readFile(p->zDbFilename, &nData);
      }else{
        aData = readHexDb(p, &nData);
        if(aData==0){
          return;
        }
      }
      rc = sqlite3_deserialize(p->db, "main", aData, nData, nData,
                   SQLITE_DESERIALIZE_RESIZEABLE |
                   SQLITE_DESERIALIZE_FREEONCLOSE);
      if(rc){
        utf8_printf(stderr, "Error: sqlite3_deserialize() returns %d\n", rc);
      }
      if(p->szMax>0){
        sqlite3_file_control(p->db, "main", SQLITE_FCNTL_SIZE_LIMIT, &p->szMax);
      }
    }
#endif
  }
}
optionMatch()
static int optionMatch (const char * zStr, const char * zOpt) [static]
Definition at line 13706 of file shell.c.
Referenced by do_meta_command().
                                                          {
  if(zStr[0]!='-') return 0;
  zStr++;
  if(zStr[0]=='-') zStr++;
  return strcmp(zStr, zOpt)==0;
}
output_c_string()
static void output_c_string (FILE * out, const char * z) [static]
Definition at line 10051 of file shell.c.
References raw_printf.
Referenced by do_meta_command(), shell_callback(), and shellAuth().
                                                     {
  unsigned int c;
  fputc('"', out);
  while((c = *(z++))!=0){
    if(c=='\\'){
      fputc(c, out);
      fputc(c, out);
    }else if(c=='"'){
      fputc('\\', out);
      fputc('"', out);
    }else if(c=='\t'){
      fputc('\\', out);
      fputc('t', out);
    }else if(c=='\n'){
      fputc('\\', out);
      fputc('n', out);
    }else if(c=='\r'){
      fputc('\\', out);
      fputc('r', out);
    }else if(!isprint(c&0xff)){
      raw_printf(out, "\\%03o", c&0xff);
    }else{
      fputc(c, out);
    }
  }
  fputc('"', out);
}
output_csv()
static void output_csv (ShellState * p, const char * z, int bSep) [static]
Definition at line 10143 of file shell.c.
References ShellState::colSeparator, ShellState::nullValue, ShellState::out, sqlite3_free, sqlite3_mprintf, strlen30(), and utf8_printf.
Referenced by shell_callback().
                                                              {
  FILE *out = p->out;
  if(z==0){
    utf8_printf(out,"%s",p->nullValue);
  }else{
    int i;
    int nSep = strlen30(p->colSeparator);
    for(i=0; z[i]; i++){
      if(needCsvQuote[((unsigned char*)z)[i]]
         || (z[i]==p->colSeparator[0] &&
             (nSep==1 || memcmp(z, p->colSeparator, nSep)==0))){
        i = 0;
        break;
      }
    }
    if(i==0){
      char *zQuoted = sqlite3_mprintf("\"%w\"", z);
      utf8_printf(out, "%s", zQuoted);
      sqlite3_free(zQuoted);
    }else{
      utf8_printf(out, "%s", z);
    }
  }
  if(bSep){
    utf8_printf(p->out, "%s", p->colSeparator);
  }
}
output_file_close()
static void output_file_close (FILE * f) [static]
Definition at line 12971 of file shell.c.
Referenced by do_meta_command(), and output_reset().
                                      {
  if(f && f!=stdout && f!=stderr) fclose(f);
}
output_file_open()
static FILE* output_file_open (const char * zFile, int bTextMode) [static]
Definition at line 12980 of file shell.c.
References utf8_printf.
Referenced by do_meta_command().
                                                               {
  FILE *f;
  if(strcmp(zFile,"stdout")==0){
    f = stdout;
  }else if(strcmp(zFile, "stderr")==0){
    f = stderr;
  }else if(strcmp(zFile, "off")==0){
    f = 0;
  }else{
    f = fopen(zFile, bTextMode ? "w" : "wb");
    if(f==0){
      utf8_printf(stderr, "Error: cannot open \"%s\"\n", zFile);
    }
  }
  return f;
}
output_hex_blob()
static void output_hex_blob (FILE * out, const void * pBlob, int nBlob) [static]
Definition at line 9917 of file shell.c.
References raw_printf.
Referenced by shell_callback().
                                                                    {
  int i;
  char *zBlob = (char *)pBlob;
  raw_printf(out,"X'");
  for(i=0; i<nBlob; i++){ raw_printf(out,"%02x",zBlob[i]&0xff); }
  raw_printf(out,"'");
}
output_html_string()
static void output_html_string (FILE * out, const char * z) [static]
Definition at line 10083 of file shell.c.
References raw_printf, and utf8_printf.
Referenced by shell_callback().
                                                        {
  int i;
  if(z==0) z = "";
  while(*z){
    for(i=0; z[i]
            && z[i]!='<'
            && z[i]!='&'
            && z[i]!='>'
            && z[i]!='\"'
            && z[i]!='\'';
        i++){}
    if(i>0){
      utf8_printf(out,"%.*s",i,z);
    }
    if(z[i]=='<'){
      raw_printf(out,"&lt;");
    }else if(z[i]=='&'){
      raw_printf(out,"&amp;");
    }else if(z[i]=='>'){
      raw_printf(out,"&gt;");
    }else if(z[i]=='\"'){
      raw_printf(out,"&quot;");
    }else if(z[i]=='\''){
      raw_printf(out,"&#39;");
    }else{
      break;
    }
    z += i + 1;
  }
}
output_quoted_escaped_string()
static void output_quoted_escaped_string (FILE * out, const char * z) [static]
Definition at line 9990 of file shell.c.
References raw_printf, setBinaryMode, setTextMode, unused_string(), and utf8_printf.
Referenced by shell_callback().
                                                                  {
  int i;
  char c;
  setBinaryMode(out, 1);
  for(i=0; (c = z[i])!=0 && c!='\'' && c!='\n' && c!='\r'; i++){}
  if(c==0){
    utf8_printf(out,"'%s'",z);
  }else{
    const char *zNL = 0;
    const char *zCR = 0;
    int nNL = 0;
    int nCR = 0;
    char zBuf1[20], zBuf2[20];
    for(i=0; z[i]; i++){
      if(z[i]=='\n') nNL++;
      if(z[i]=='\r') nCR++;
    }
    if(nNL){
      raw_printf(out, "replace(");
      zNL = unused_string(z, "\\n", "\\012", zBuf1);
    }
    if(nCR){
      raw_printf(out, "replace(");
      zCR = unused_string(z, "\\r", "\\015", zBuf2);
    }
    raw_printf(out, "'");
    while(*z){
      for(i=0; (c = z[i])!=0 && c!='\n' && c!='\r' && c!='\''; i++){}
      if(c=='\'') i++;
      if(i){
        utf8_printf(out, "%.*s", i, z);
        z += i;
      }
      if(c=='\''){
        raw_printf(out, "'");
        continue;
      }
      if(c==0){
        break;
      }
      z++;
      if(c=='\n'){
        raw_printf(out, "%s", zNL);
        continue;
      }
      raw_printf(out, "%s", zCR);
    }
    raw_printf(out, "'");
    if(nCR){
      raw_printf(out, ",'%s',char(13))", zCR);
    }
    if(nNL){
      raw_printf(out, ",'%s',char(10))", zNL);
    }
  }
  setTextMode(out, 1);
}
output_quoted_string()
static void output_quoted_string (FILE * out, const char * z) [static]
Definition at line 9951 of file shell.c.
References raw_printf, setBinaryMode, setTextMode, and utf8_printf.
Referenced by shell_callback().
                                                          {
  int i;
  char c;
  setBinaryMode(out, 1);
  for(i=0; (c = z[i])!=0 && c!='\''; i++){}
  if(c==0){
    utf8_printf(out,"'%s'",z);
  }else{
    raw_printf(out, "'");
    while(*z){
      for(i=0; (c = z[i])!=0 && c!='\''; i++){}
      if(c=='\'') i++;
      if(i){
        utf8_printf(out, "%.*s", i, z);
        z += i;
      }
      if(c=='\''){
        raw_printf(out, "'");
        continue;
      }
      if(c==0){
        break;
      }
      z++;
    }
    raw_printf(out, "'");
  }
  setTextMode(out, 1);
}
output_reset()
static void output_reset (ShellState * p) [static]
Definition at line 13436 of file shell.c.
References ShellState::doXdgOpen, ShellState::out, ShellState::outfile, output_file_close(), outputModePop(), pclose(), sqlite3_free, sqlite3_mprintf, sqlite3_sleep, utf8_printf, and ShellState::zTempFile.
Referenced by do_meta_command(), main(), and process_input().
                                       {
  if(p->outfile[0]=='|'){
#ifndef SQLITE_OMIT_POPEN
    pclose(p->out);
#endif
  }else{
    output_file_close(p->out);
#ifndef SQLITE_NOHAVE_SYSTEM
    if(p->doXdgOpen){
      const char *zXdgOpenCmd =
#if defined(_WIN32)
      "start";
#elif defined(__APPLE__)
      "open";
#else
      "xdg-open";
#endif
      char *zCmd;
      zCmd = sqlite3_mprintf("%s %s", zXdgOpenCmd, p->zTempFile);
      if(system(zCmd)){
        utf8_printf(stderr, "Failed: [%s]\n", zCmd);
      }
      sqlite3_free(zCmd);
      outputModePop(p);
      p->doXdgOpen = 0;
      sqlite3_sleep(100);
    }
#endif /* !defined(SQLITE_NOHAVE_SYSTEM) */
  }
  p->outfile[0] = 0;
  p->out = stdout;
}
outputModePop()
static void outputModePop (ShellState * p) [static]
Definition at line 9908 of file shell.c.
References ShellState::colSeparator, ShellState::colSepPrior, ShellState::mode, ShellState::modePrior, ShellState::rowSeparator, and ShellState::rowSepPrior.
Referenced by output_reset().
                                        {
  p->mode = p->modePrior;
  memcpy(p->colSeparator, p->colSepPrior, sizeof(p->colSeparator));
  memcpy(p->rowSeparator, p->rowSepPrior, sizeof(p->rowSeparator));
}
outputModePush()
static void outputModePush (ShellState * p) [static]
Definition at line 9903 of file shell.c.
References ShellState::colSeparator, ShellState::colSepPrior, ShellState::mode, ShellState::modePrior, ShellState::rowSeparator, and ShellState::rowSepPrior.
Referenced by do_meta_command().
                                         {
  p->modePrior = p->mode;
  memcpy(p->colSepPrior, p->colSeparator, sizeof(p->colSeparator));
  memcpy(p->rowSepPrior, p->rowSeparator, sizeof(p->rowSeparator));
}
pclose()
int pclose (FILE *)
Referenced by do_meta_command(), and output_reset().
popen()
FILE* popen (const char * , const char *)
Referenced by do_meta_command().
printBold()
static void printBold (const char * zText) [static]
Definition at line 18638 of file shell.c.
Referenced by main(), and main_init().
                                        {
  printf("\033[1m%s\033[0m", zText);
}
printSchemaLine()
static void printSchemaLine (FILE * out, const char * z, const char * zTail) [static]
Definition at line 10249 of file shell.c.
References sqlite3_strglob, and utf8_printf.
Referenced by dump_callback(), printSchemaLineN(), and shell_callback().
                                                                        {
  if(z==0) return;
  if(zTail==0) return;
  if(sqlite3_strglob("CREATE TABLE ['\"]*", z)==0){
    utf8_printf(out, "CREATE TABLE IF NOT EXISTS %s%s", z+13, zTail);
  }else{
    utf8_printf(out, "%s%s", z, zTail);
  }
}
printSchemaLineN()
static void printSchemaLineN (FILE * out, char * z, int n, const char * zTail) [static]
Definition at line 10258 of file shell.c.
References printSchemaLine().
Referenced by shell_callback().
                                                                          {
  char c = z[n];
  z[n] = 0;
  printSchemaLine(out, z, zTail);
  z[n] = c;
}
process_input()
static int process_input (ShellState * p) [static]
Definition at line 18329 of file shell.c.
References _all_whitespace(), clearTempFile(), do_meta_command(), ShellState::in, IsSpace, line_contains_semicolon(), line_is_command_terminator(), line_is_complete(), ShellState::lineno, one_input_line(), ShellState::out, ShellState::outCount, output_reset(), runOneSqlLine(), shell_out_of_memory(), ShellHasFlag, SHFLG_Echo, sqlite3_complete, and strlen30().
Referenced by do_meta_command(), main(), process_sqliterc(), and showHelp().
                                       {
  char *zLine = 0; /* A single input line */
  char *zSql = 0; /* Accumulated SQL text */
  int nLine; /* Length of current line */
  int nSql = 0; /* Bytes of zSql[] used */
  int nAlloc = 0; /* Allocated zSql[] space */
  int nSqlPrior = 0; /* Bytes of zSql[] used by prior line */
  int rc; /* Error code */
  int errCnt = 0; /* Number of errors seen */
  int startline = 0; /* Line number for start of current input */
  p->lineno = 0;
  while(errCnt==0 || !bail_on_error || (p->in==0 && stdin_is_interactive)){
    fflush(p->out);
    zLine = one_input_line(p->in, zLine, nSql>0);
    if(zLine==0){
      /* End of input */
      if(p->in==0 && stdin_is_interactive) printf("\n");
      break;
    }
    if(seenInterrupt){
      if(p->in!=0) break;
      seenInterrupt = 0;
    }
    p->lineno++;
    if(nSql==0 && _all_whitespace(zLine)){
      if(ShellHasFlag(p, SHFLG_Echo)) printf("%s\n", zLine);
      continue;
    }
    if(zLine && (zLine[0]=='.' || zLine[0]=='#') && nSql==0){
      if(ShellHasFlag(p, SHFLG_Echo)) printf("%s\n", zLine);
      if(zLine[0]=='.'){
        rc = do_meta_command(zLine, p);
        if(rc==2){ /* exit requested */
          break;
        }else if(rc){
          errCnt++;
        }
      }
      continue;
    }
    if(line_is_command_terminator(zLine) && line_is_complete(zSql, nSql)){
      memcpy(zLine,";",2);
    }
    nLine = strlen30(zLine);
    if(nSql+nLine+2>=nAlloc){
      nAlloc = nSql+nLine+100;
      zSql = realloc(zSql, nAlloc);
      if(zSql==0) shell_out_of_memory();
    }
    nSqlPrior = nSql;
    if(nSql==0){
      int i;
      for(i=0; zLine[i] && IsSpace(zLine[i]); i++){}
      assert(nAlloc>0 && zSql!=0);
      memcpy(zSql, zLine+i, nLine+1-i);
      startline = p->lineno;
      nSql = nLine-i;
    }else{
      zSql[nSql++] = '\n';
      memcpy(zSql+nSql, zLine, nLine+1);
      nSql += nLine;
    }
    if(nSql && line_contains_semicolon(&zSql[nSqlPrior], nSql-nSqlPrior)
                && sqlite3_complete(zSql)){
      errCnt += runOneSqlLine(p, zSql, p->in, startline);
      nSql = 0;
      if(p->outCount){
        output_reset(p);
        p->outCount = 0;
      }else{
        clearTempFile(p);
      }
    }else if(nSql && _all_whitespace(zSql)){
      if(ShellHasFlag(p, SHFLG_Echo)) printf("%s\n", zSql);
      nSql = 0;
    }
  }
  if(nSql && !_all_whitespace(zSql)){
    errCnt += runOneSqlLine(p, zSql, p->in, startline);
  }
  free(zSql);
  free(zLine);
  return errCnt>0;
}
process_sqliterc()
static void process_sqliterc (ShellState * p, const char * sqliterc_override) [static]
Definition at line 18490 of file shell.c.
References find_home_dir(), ShellState::in, ShellState::lineno, process_input(), raw_printf, sqlite3_free, sqlite3_mprintf, and utf8_printf.
Referenced by main().
 {
  char *home_dir = NULL;
  const char *sqliterc = sqliterc_override;
  char *zBuf = 0;
  FILE *inSaved = p->in;
  int savedLineno = p->lineno;
  if (sqliterc == NULL) {
    home_dir = find_home_dir(0);
    if(home_dir==0){
      raw_printf(stderr, "-- warning: cannot find home directory;"
                      " cannot read ~/.sqliterc\n");
      return;
    }
    zBuf = sqlite3_mprintf("%s/.sqliterc",home_dir);
    sqliterc = zBuf;
  }
  p->in = fopen(sqliterc,"rb");
  if(p->in){
    if(stdin_is_interactive){
      utf8_printf(stderr,"-- Loading resources from %s\n",sqliterc);
    }
    process_input(p);
    fclose(p->in);
  }
  p->in = inSaved;
  p->lineno = savedLineno;
  sqlite3_free(zBuf);
}
progress_handler()
static int progress_handler (void * pClientData) [static]
Definition at line 10372 of file shell.c.
References ShellState::flgProgress, ShellState::mxProgress, ShellState::nProgress, ShellState::out, raw_printf, SHELL_PROGRESS_ONCE, SHELL_PROGRESS_QUIET, and SHELL_PROGRESS_RESET.
Referenced by do_meta_command().
                                               {
  ShellState *p = (ShellState*)pClientData;
  p->nProgress++;
  if(p->nProgress>=p->mxProgress && p->mxProgress>0){
    raw_printf(p->out, "Progress limit reached (%u)\n", p->nProgress);
    if(p->flgProgress & SHELL_PROGRESS_RESET) p->nProgress = 0;
    if(p->flgProgress & SHELL_PROGRESS_ONCE) p->mxProgress = 0;
    return 1;
  }
  if((p->flgProgress & SHELL_PROGRESS_QUIET)==0){
    raw_printf(p->out, "Progress %u\n", p->nProgress);
  }
  return 0;
}
quoteChar()
static char quoteChar (const char * zName) [static]
Definition at line 794 of file shell.c.
References sqlite3_keyword_check.
Referenced by do_meta_command(), dump_callback(), set_table_name(), shell_callback(), shellAddSchemaName(), and shellFakeSchema().
                                        {
  int i;
  if(!isalpha((unsigned char)zName[0]) && zName[0]!='_') return '"';
  for(i=0; zName[i]; i++){
    if(!isalnum((unsigned char)zName[i]) && zName[i]!='_') return '"';
  }
  return sqlite3_keyword_check(zName, i) ? '"' : 0;
}
readFile()
static char* readFile (const char * zName, int * pnByte) [static]
Definition at line 12328 of file shell.c.
References session_close_all, sqlite3_free, and sqlite3_malloc64.
Referenced by do_meta_command(), and open_db().
                                                     {
  FILE *in = fopen(zName, "rb");
  long nIn;
  size_t nRead;
  char *pBuf;
  if(in==0) return 0;
  fseek(in, 0, SEEK_END);
  nIn = ftell(in);
  rewind(in);
  pBuf = sqlite3_malloc64(nIn+1);
  if(pBuf==0){ fclose(in); return 0; }
  nRead = fread(pBuf, nIn, 1, in);
  fclose(in);
  if(nRead!=1){
    sqlite3_free(pBuf);
    return 0;
  }
  pBuf[nIn] = 0;
  if(pnByte) *pnByte = nIn;
  return pBuf;
}
readFileContents()
static void readFileContents (sqlite3_context * ctx, const char * zName) [static]
Definition at line 2165 of file shell.c.
References sqlite3_context_db_handle, sqlite3_free, sqlite3_limit, sqlite3_malloc64, sqlite3_result_blob64, sqlite3_result_error_code, sqlite3_result_error_nomem, SQLITE_IOERR, SQLITE_LIMIT_LENGTH, and SQLITE_TOOBIG.
Referenced by fsdirColumn(), and readfileFunc().
                                                                     {
  FILE *in;
  sqlite3_int64 nIn;
  void *pBuf;
  sqlite3 *db;
  int mxBlob;
  in = fopen(zName, "rb");
  if(in==0){
    /* File does not exist or is unreadable. Leave the result set to NULL. */
    return;
  }
  fseek(in, 0, SEEK_END);
  nIn = ftell(in);
  rewind(in);
  db = sqlite3_context_db_handle(ctx);
  mxBlob = sqlite3_limit(db, SQLITE_LIMIT_LENGTH, -1);
  if(nIn>mxBlob){
    sqlite3_result_error_code(ctx, SQLITE_TOOBIG);
    fclose(in);
    return;
  }
  pBuf = sqlite3_malloc64(nIn ? nIn : 1);
  if(pBuf==0){
    sqlite3_result_error_nomem(ctx);
    fclose(in);
    return;
  }
  if(nIn==(sqlite3_int64)fread(pBuf, 1, (size_t)nIn, in)){
    sqlite3_result_blob64(ctx, pBuf, nIn, sqlite3_free);
  }else{
    sqlite3_result_error_code(ctx, SQLITE_IOERR);
    sqlite3_free(pBuf);
  }
  fclose(in);
}
readfileFunc()
static void readfileFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 2207 of file shell.c.
References readFileContents(), sqlite3_value_text, and zName.
Referenced by sqlite3_fileio_init().
 {
  const char *zName;
  (void)(argc); /* Unused parameter */
  zName = (const char*)sqlite3_value_text(argv[0]);
  if(zName==0) return;
  readFileContents(context, zName);
}
resolve_backslashes()
static void resolve_backslashes (char * z) [static]
Definition at line 12890 of file shell.c.
Referenced by do_meta_command(), and runOneSqlLine().
                                        {
  int i, j;
  char c;
  while(*z && *z!='\\') z++;
  for(i=j=0; (c = z[i])!=0; i++, j++){
    if(c=='\\' && z[i+1]!=0){
      c = z[++i];
      if(c=='a'){
        c = '\a';
      }else if(c=='b'){
        c = '\b';
      }else if(c=='t'){
        c = '\t';
      }else if(c=='n'){
        c = '\n';
      }else if(c=='v'){
        c = '\v';
      }else if(c=='f'){
        c = '\f';
      }else if(c=='r'){
        c = '\r';
      }else if(c=='"'){
        c = '"';
      }else if(c=='\''){
        c = '\'';
      }else if(c=='\\'){
        c = '\\';
      }else if(c>='0' && c<='7'){
        c -= '0';
        if(z[i+1]>='0' && z[i+1]<='7'){
          i++;
          c = (c<<3) + z[i] - '0';
          if(z[i+1]>='0' && z[i+1]<='7'){
            i++;
            c = (c<<3) + z[i] - '0';
          }
        }
      }
    }
    z[j] = c;
  }
  if(j<i) z[j] = 0;
}
restore_debug_trace_modes()
static void restore_debug_trace_modes (void) [static]
Definition at line 11317 of file shell.c.
Referenced by shell_exec().
                                           {
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_SELECTTRACE)
  sqlite3SelectTrace = savedSelectTrace;
#endif
#if defined(SQLITE_DEBUG) && defined(SQLITE_ENABLE_WHERETRACE)
  sqlite3WhereTrace = savedWhereTrace;
#endif
}
run_schema_dump_query()
static int run_schema_dump_query (ShellState * p, const char * zQuery) [static]
Definition at line 11991 of file shell.c.
References ShellState::db, dump_callback(), ShellState::out, raw_printf, sqlite3_exec, sqlite3_free, sqlite3_snprintf, SQLITE_CORRUPT, strlen30(), and utf8_printf.
Referenced by do_meta_command().
 {
  int rc;
  char *zErr = 0;
  rc = sqlite3_exec(p->db, zQuery, dump_callback, p, &zErr);
  if(rc==SQLITE_CORRUPT){
    char *zQ2;
    int len = strlen30(zQuery);
    raw_printf(p->out, "/****** CORRUPTION ERROR *******/\n");
    if(zErr){
      utf8_printf(p->out, "/****** %s ******/\n", zErr);
      sqlite3_free(zErr);
      zErr = 0;
    }
    zQ2 = malloc(len+100);
    if(zQ2==0) return rc;
    sqlite3_snprintf(len+100, zQ2, "%s ORDER BY rowid DESC", zQuery);
    rc = sqlite3_exec(p->db, zQ2, dump_callback, p, &zErr);
    if(rc){
      utf8_printf(p->out, "/****** ERROR: %s ******/\n", zErr);
    }else{
      rc = SQLITE_CORRUPT;
    }
    sqlite3_free(zErr);
    free(zQ2);
  }
  return rc;
}
run_table_dump_query()
static int run_table_dump_query (ShellState * p, const char * zSelect, const char * zFirstRow) [static]
Definition at line 10872 of file shell.c.
References ShellState::db, ShellState::nErr, ShellState::out, raw_printf, sqlite3_column_count, sqlite3_column_text, sqlite3_errmsg, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_step, SQLITE_CORRUPT, SQLITE_OK, SQLITE_ROW, and utf8_printf.
Referenced by do_meta_command().
 {
  sqlite3_stmt *pSelect;
  int rc;
  int nResult;
  int i;
  const char *z;
  rc = sqlite3_prepare_v2(p->db, zSelect, -1, &pSelect, 0);
  if(rc!=SQLITE_OK || !pSelect){
    utf8_printf(p->out, "/**** ERROR: (%d) %s *****/\n", rc,
                sqlite3_errmsg(p->db));
    if((rc&0xff)!=SQLITE_CORRUPT) p->nErr++;
    return rc;
  }
  rc = sqlite3_step(pSelect);
  nResult = sqlite3_column_count(pSelect);
  while(rc==SQLITE_ROW){
    if(zFirstRow){
      utf8_printf(p->out, "%s", zFirstRow);
      zFirstRow = 0;
    }
    z = (const char*)sqlite3_column_text(pSelect, 0);
    utf8_printf(p->out, "%s", z);
    for(i=1; i<nResult; i++){
      utf8_printf(p->out, ",%s", sqlite3_column_text(pSelect, i));
    }
    if(z==0) z = "";
    while(z[0] && (z[0]!='-' || z[1]!='-')) z++;
    if(z[0]){
      raw_printf(p->out, "\n;\n");
    }else{
      raw_printf(p->out, ";\n");
    }
    rc = sqlite3_step(pSelect);
  }
  rc = sqlite3_finalize(pSelect);
  if(rc!=SQLITE_OK){
    utf8_printf(p->out, "/**** ERROR: (%d) %s *****/\n", rc,
                sqlite3_errmsg(p->db));
    if((rc&0xff)!=SQLITE_CORRUPT) p->nErr++;
  }
  return rc;
}
runOneSqlLine()
static int runOneSqlLine (ShellState * p, char * zSql, FILE * in, int startline) [static]
Definition at line 18286 of file shell.c.
References BEGIN_TIMER, ShellState::db, END_TIMER, ShellState::flgProgress, ShellState::nProgress, open_db(), ShellState::out, raw_printf, resolve_backslashes(), shell_exec(), SHELL_PROGRESS_RESET, ShellHasFlag, SHFLG_Backslash, SHFLG_CountChanges, sqlite3_changes, sqlite3_errmsg, sqlite3_free, sqlite3_snprintf, sqlite3_total_changes, and utf8_printf.
Referenced by process_input().
                                                                            {
  int rc;
  char *zErrMsg = 0;
  open_db(p, 0);
  if(ShellHasFlag(p,SHFLG_Backslash)) resolve_backslashes(zSql);
  if(p->flgProgress & SHELL_PROGRESS_RESET) p->nProgress = 0;
  BEGIN_TIMER;
  rc = shell_exec(p, zSql, &zErrMsg);
  END_TIMER;
  if(rc || zErrMsg){
    char zPrefix[100];
    if(in!=0 || !stdin_is_interactive){
      sqlite3_snprintf(sizeof(zPrefix), zPrefix,
                       "Error: near line %d:", startline);
    }else{
      sqlite3_snprintf(sizeof(zPrefix), zPrefix, "Error:");
    }
    if(zErrMsg!=0){
      utf8_printf(stderr, "%s %s\n", zPrefix, zErrMsg);
      sqlite3_free(zErrMsg);
      zErrMsg = 0;
    }else{
      utf8_printf(stderr, "%s %s\n", zPrefix, sqlite3_errmsg(p->db));
    }
    return 1;
  }else if(ShellHasFlag(p, SHFLG_CountChanges)){
    raw_printf(p->out, "changes: %3d total_changes: %d\n",
            sqlite3_changes(p->db), sqlite3_total_changes(p->db));
  }
  return 0;
}
save_err_msg()
static char* save_err_msg (sqlite3 * db) [static]
Definition at line 10922 of file shell.c.
References ArraySize, sqlite3_errmsg, sqlite3_malloc64, sqlite3_snprintf, strlen30(), and utf8_printf.
Referenced by shell_exec().
 {
  int nErrMsg = 1+strlen30(sqlite3_errmsg(db));
  char *zErrMsg = sqlite3_malloc64(nErrMsg);
  if(zErrMsg){
    memcpy(zErrMsg, sqlite3_errmsg(db), nErrMsg);
  }
  return zErrMsg;
}
set_table_name()
static void set_table_name (ShellState * p, const char * zName) [static]
Definition at line 10836 of file shell.c.
References quoteChar(), shell_out_of_memory(), strlen30(), and ShellState::zDestTable.
Referenced by do_meta_command(), and main().
                                                            {
  int i, n;
  char cQuote;
  char *z;
  if(p->zDestTable){
    free(p->zDestTable);
    p->zDestTable = 0;
  }
  if(zName==0) return;
  cQuote = quoteChar(zName);
  n = strlen30(zName);
  if(cQuote) n += n+2;
  z = p->zDestTable = malloc(n+1);
  if(z==0) shell_out_of_memory();
  n = 0;
  if(cQuote) z[n++] = cQuote;
  for(i=0; zName[i]; i++){
    z[n++] = zName[i];
    if(zName[i]==cQuote) z[n++] = cQuote;
  }
  if(cQuote) z[n++] = cQuote;
  z[n] = 0;
}
setOrClearFlag()
static void setOrClearFlag (ShellState * p, unsigned mFlag, const char * zArg) [static]
Definition at line 12960 of file shell.c.
References booleanValue(), ShellClearFlag, and ShellSetFlag.
Referenced by do_meta_command().
                                                                           {
  if(booleanValue(zArg)){
    ShellSetFlag(p, mFlag);
  }else{
    ShellClearFlag(p, mFlag);
  }
}
SHA3Final()
static unsigned char* SHA3Final (SHA3Context * p) [static]
Definition at line 1780 of file shell.c.
References SHA3Context::ixMask, SHA3Context::nLoaded, SHA3Context::nRate, SHA3Update(), SHA3Context::u, and SHA3Context::x.
Referenced by sha3Func(), and sha3QueryFunc().
                                               {
  unsigned int i;
  if(p->nLoaded==p->nRate-1){
    const unsigned char c1 = 0x86;
    SHA3Update(p, &c1, 1);
  }else{
    const unsigned char c2 = 0x06;
    const unsigned char c3 = 0x80;
    SHA3Update(p, &c2, 1);
    p->nLoaded = p->nRate - 1;
    SHA3Update(p, &c3, 1);
  }
  for(i=0; i<p->nRate; i++){
    p->u.x[i+p->nRate] = p->u.x[i^p->ixMask];
  }
  return &p->u.x[p->nRate];
}
sha3Func()
static void sha3Func (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 1809 of file shell.c.
References eType, SHA3Final(), SHA3Init(), SHA3Update(), sqlite3_result_blob, sqlite3_result_error, sqlite3_value_blob, sqlite3_value_bytes, sqlite3_value_int, sqlite3_value_text, sqlite3_value_type, SQLITE_BLOB, SQLITE_NULL, and SQLITE_TRANSIENT.
Referenced by sqlite3_shathree_init().
 {
  SHA3Context cx;
  int eType = sqlite3_value_type(argv[0]);
  int nByte = sqlite3_value_bytes(argv[0]);
  int iSize;
  if(argc==1){
    iSize = 256;
  }else{
    iSize = sqlite3_value_int(argv[1]);
    if(iSize!=224 && iSize!=256 && iSize!=384 && iSize!=512){
      sqlite3_result_error(context, "SHA3 size should be one of: 224 256 "
                                    "384 512", -1);
      return;
    }
  }
  if(eType==SQLITE_NULL) return;
  SHA3Init(&cx, iSize);
  if(eType==SQLITE_BLOB){
    SHA3Update(&cx, sqlite3_value_blob(argv[0]), nByte);
  }else{
    SHA3Update(&cx, sqlite3_value_text(argv[0]), nByte);
  }
  sqlite3_result_blob(context, SHA3Final(&cx), iSize/8, SQLITE_TRANSIENT);
}
SHA3Init()
static void SHA3Init (SHA3Context * p, int iSize) [static]
Definition at line 1712 of file shell.c.
References SHA3Context::ixMask, and SHA3Context::nRate.
Referenced by sha3Func(), and sha3QueryFunc().
                                               {
  memset(p, 0, sizeof(*p));
  if(iSize>=128 && iSize<=512){
    p->nRate = (1600 - ((iSize + 31)&~31)*2)/8;
  }else{
    p->nRate = (1600 - 2*256)/8;
  }
#if SHA3_BYTEORDER==1234
  /* Known to be little-endian at compile-time. No-op */
#elif SHA3_BYTEORDER==4321
  p->ixMask = 7; /* Big-endian */
#else
  {
    static unsigned int one = 1;
    if(1==*(unsigned char*)&one){
      /* Little endian. No byte swapping. */
      p->ixMask = 0;
    }else{
      /* Big endian. Byte swap. */
      p->ixMask = 7;
    }
  }
#endif
}
sha3QueryFunc()
static void sha3QueryFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 1888 of file shell.c.
References hash_step_vformat(), SHA3Final(), SHA3Init(), SHA3Update(), sqlite3_column_blob, sqlite3_column_bytes, sqlite3_column_count, sqlite3_column_double, sqlite3_column_int64, sqlite3_column_text, sqlite3_column_type, sqlite3_context_db_handle, sqlite3_errmsg, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_result_blob, sqlite3_result_error, sqlite3_sql, sqlite3_step, sqlite3_stmt_readonly, sqlite3_value_int, sqlite3_value_text, SQLITE_BLOB, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, SQLITE_ROW, SQLITE_TEXT, SQLITE_TRANSIENT, and time_test::x.
Referenced by sqlite3_shathree_init().
 {
  sqlite3 *db = sqlite3_context_db_handle(context);
  const char *zSql = (const char*)sqlite3_value_text(argv[0]);
  sqlite3_stmt *pStmt = 0;
  int nCol; /* Number of columns in the result set */
  int i; /* Loop counter */
  int rc;
  int n;
  const char *z;
  SHA3Context cx;
  int iSize;
  if(argc==1){
    iSize = 256;
  }else{
    iSize = sqlite3_value_int(argv[1]);
    if(iSize!=224 && iSize!=256 && iSize!=384 && iSize!=512){
      sqlite3_result_error(context, "SHA3 size should be one of: 224 256 "
                                    "384 512", -1);
      return;
    }
  }
  if(zSql==0) return;
  SHA3Init(&cx, iSize);
  while(zSql[0]){
    rc = sqlite3_prepare_v2(db, zSql, -1, &pStmt, &zSql);
    if(rc){
      char *zMsg = sqlite3_mprintf("error SQL statement [%s]: %s",
                                   zSql, sqlite3_errmsg(db));
      sqlite3_finalize(pStmt);
      sqlite3_result_error(context, zMsg, -1);
      sqlite3_free(zMsg);
      return;
    }
    if(!sqlite3_stmt_readonly(pStmt)){
      char *zMsg = sqlite3_mprintf("non-query: [%s]", sqlite3_sql(pStmt));
      sqlite3_finalize(pStmt);
      sqlite3_result_error(context, zMsg, -1);
      sqlite3_free(zMsg);
      return;
    }
    nCol = sqlite3_column_count(pStmt);
    z = sqlite3_sql(pStmt);
    n = (int)strlen(z);
    hash_step_vformat(&cx,"S%d:",n);
    SHA3Update(&cx,(unsigned char*)z,n);
    /* Compute a hash over the result of the query */
    while(SQLITE_ROW==sqlite3_step(pStmt)){
      SHA3Update(&cx,(const unsigned char*)"R",1);
      for(i=0; i<nCol; i++){
        switch(sqlite3_column_type(pStmt,i)){
          case SQLITE_NULL: {
            SHA3Update(&cx, (const unsigned char*)"N",1);
            break;
          }
          case SQLITE_INTEGER: {
            sqlite3_uint64 u;
            int j;
            unsigned char x[9];
            sqlite3_int64 v = sqlite3_column_int64(pStmt,i);
            memcpy(&u, &v, 8);
            for(j=8; j>=1; j--){
              x[j] = u & 0xff;
              u >>= 8;
            }
            x[0] = 'I';
            SHA3Update(&cx, x, 9);
            break;
          }
          case SQLITE_FLOAT: {
            sqlite3_uint64 u;
            int j;
            unsigned char x[9];
            double r = sqlite3_column_double(pStmt,i);
            memcpy(&u, &r, 8);
            for(j=8; j>=1; j--){
              x[j] = u & 0xff;
              u >>= 8;
            }
            x[0] = 'F';
            SHA3Update(&cx,x,9);
            break;
          }
          case SQLITE_TEXT: {
            int n2 = sqlite3_column_bytes(pStmt, i);
            const unsigned char *z2 = sqlite3_column_text(pStmt, i);
            hash_step_vformat(&cx,"T%d:",n2);
            SHA3Update(&cx, z2, n2);
            break;
          }
          case SQLITE_BLOB: {
            int n2 = sqlite3_column_bytes(pStmt, i);
            const unsigned char *z2 = sqlite3_column_blob(pStmt, i);
            hash_step_vformat(&cx,"B%d:",n2);
            SHA3Update(&cx, z2, n2);
            break;
          }
        }
      }
    }
    sqlite3_finalize(pStmt);
  }
  sqlite3_result_blob(context, SHA3Final(&cx), iSize/8, SQLITE_TRANSIENT);
}
SHA3Update()
static void SHA3Update (SHA3Context * p, const unsigned char * aData, unsigned int nData) [static]
Definition at line 1741 of file shell.c.
References SHA3Context::ixMask, KeccakF1600Step(), SHA3Context::nLoaded, SHA3Context::nRate, SHA3Context::s, SHA3Context::u, and SHA3Context::x.
Referenced by hash_step_vformat(), SHA3Final(), sha3Func(), and sha3QueryFunc().
 {
  unsigned int i = 0;
#if SHA3_BYTEORDER==1234
  if((p->nLoaded % 8)==0 && ((aData - (const unsigned char*)0)&7)==0){
    for(; i+7<nData; i+=8){
      p->u.s[p->nLoaded/8] ^= *(u64*)&aData[i];
      p->nLoaded += 8;
      if(p->nLoaded>=p->nRate){
        KeccakF1600Step(p);
        p->nLoaded = 0;
      }
    }
  }
#endif
  for(; i<nData; i++){
#if SHA3_BYTEORDER==1234
    p->u.x[p->nLoaded] ^= aData[i];
#elif SHA3_BYTEORDER==4321
    p->u.x[p->nLoaded^0x07] ^= aData[i];
#else
    p->u.x[p->nLoaded^p->ixMask] ^= aData[i];
#endif
    p->nLoaded++;
    if(p->nLoaded==p->nRate){
      KeccakF1600Step(p);
      p->nLoaded = 0;
    }
  }
}
shell_callback()
static int shell_callback (void * pArg, int nArg, char ** azArg, char ** azCol, int * aiType) [static]
Definition at line 10392 of file shell.c.
References ShellState::actualWidth, ShellState::aiIndent, ArraySize, ShellState::cMode, ShellState::cnt, ShellState::colSeparator, ShellState::colWidth, eqp_append(), ShellState::iIndent, isNumber(), IsSpace, MODE_Ascii, MODE_Column, MODE_Csv, MODE_EQP, MODE_Explain, MODE_Html, MODE_Insert, MODE_Line, MODE_List, MODE_Pretty, MODE_Quote, MODE_Semi, MODE_Tcl, ShellState::nIndent, ShellState::nullValue, ShellState::out, output_c_string(), output_csv(), output_hex_blob(), output_html_string(), output_quoted_escaped_string(), output_quoted_string(), printSchemaLine(), printSchemaLineN(), ShellState::pStmt, quoteChar(), raw_printf, ShellState::rowSeparator, SEP_Row, setBinaryMode, setTextMode, ShellHasFlag, SHFLG_Newlines, ShellState::showHeader, sqlite3_column_blob, sqlite3_column_bytes, sqlite3_column_double, sqlite3_free, sqlite3_mprintf, sqlite3_snprintf, sqlite3_strlike, SQLITE_BLOB, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, SQLITE_TEXT, strlen30(), strlenChar(), utf8_printf, utf8_width_print(), wsToEol(), and ShellState::zDestTable.
Referenced by callback(), and exec_prepared_stmt().
 {
  int i;
  ShellState *p = (ShellState*)pArg;
  if(azArg==0) return 0;
  switch(p->cMode){
    case MODE_Line: {
      int w = 5;
      if(azArg==0) break;
      for(i=0; i<nArg; i++){
        int len = strlen30(azCol[i] ? azCol[i] : "");
        if(len>w) w = len;
      }
      if(p->cnt++>0) utf8_printf(p->out, "%s", p->rowSeparator);
      for(i=0; i<nArg; i++){
        utf8_printf(p->out,"%*s = %s%s", w, azCol[i],
                azArg[i] ? azArg[i] : p->nullValue, p->rowSeparator);
      }
      break;
    }
    case MODE_Explain:
    case MODE_Column: {
      static const int aExplainWidths[] = {4, 13, 4, 4, 4, 13, 2, 13};
      const int *colWidth;
      int showHdr;
      char *rowSep;
      int nWidth;
      if(p->cMode==MODE_Column){
        colWidth = p->colWidth;
        nWidth = ArraySize(p->colWidth);
        showHdr = p->showHeader;
        rowSep = p->rowSeparator;
      }else{
        colWidth = aExplainWidths;
        nWidth = ArraySize(aExplainWidths);
        showHdr = 1;
        rowSep = SEP_Row;
      }
      if(p->cnt++==0){
        for(i=0; i<nArg; i++){
          int w, n;
          if(i<nWidth){
            w = colWidth[i];
          }else{
            w = 0;
          }
          if(w==0){
            w = strlenChar(azCol[i] ? azCol[i] : "");
            if(w<10) w = 10;
            n = strlenChar(azArg && azArg[i] ? azArg[i] : p->nullValue);
            if(w<n) w = n;
          }
          if(i<ArraySize(p->actualWidth)){
            p->actualWidth[i] = w;
          }
          if(showHdr){
            utf8_width_print(p->out, w, azCol[i]);
            utf8_printf(p->out, "%s", i==nArg-1 ? rowSep : " ");
          }
        }
        if(showHdr){
          for(i=0; i<nArg; i++){
            int w;
            if(i<ArraySize(p->actualWidth)){
               w = p->actualWidth[i];
               if(w<0) w = -w;
            }else{
               w = 10;
            }
            utf8_printf(p->out,"%-*.*s%s",w,w,
                   "----------------------------------------------------------"
                   "----------------------------------------------------------",
                    i==nArg-1 ? rowSep : " ");
          }
        }
      }
      if(azArg==0) break;
      for(i=0; i<nArg; i++){
        int w;
        if(i<ArraySize(p->actualWidth)){
           w = p->actualWidth[i];
        }else{
           w = 10;
        }
        if(p->cMode==MODE_Explain && azArg[i] && strlenChar(azArg[i])>w){
          w = strlenChar(azArg[i]);
        }
        if(i==1 && p->aiIndent && p->pStmt){
          if(p->iIndent<p->nIndent){
            utf8_printf(p->out, "%*.s", p->aiIndent[p->iIndent], "");
          }
          p->iIndent++;
        }
        utf8_width_print(p->out, w, azArg[i] ? azArg[i] : p->nullValue);
        utf8_printf(p->out, "%s", i==nArg-1 ? rowSep : " ");
      }
      break;
    }
    case MODE_Semi: { /* .schema and .fullschema output */
      printSchemaLine(p->out, azArg[0], ";\n");
      break;
    }
    case MODE_Pretty: { /* .schema and .fullschema with --indent */
      char *z;
      int j;
      int nParen = 0;
      char cEnd = 0;
      char c;
      int nLine = 0;
      assert(nArg==1);
      if(azArg[0]==0) break;
      if(sqlite3_strlike("CREATE VIEW%", azArg[0], 0)==0
       || sqlite3_strlike("CREATE TRIG%", azArg[0], 0)==0
      ){
        utf8_printf(p->out, "%s;\n", azArg[0]);
        break;
      }
      z = sqlite3_mprintf("%s", azArg[0]);
      j = 0;
      for(i=0; IsSpace(z[i]); i++){}
      for(; (c = z[i])!=0; i++){
        if(IsSpace(c)){
          if(z[j-1]=='\r') z[j-1] = '\n';
          if(IsSpace(z[j-1]) || z[j-1]=='(') continue;
        }else if((c=='(' || c==')') && j>0 && IsSpace(z[j-1])){
          j--;
        }
        z[j++] = c;
      }
      while(j>0 && IsSpace(z[j-1])){ j--; }
      z[j] = 0;
      if(strlen30(z)>=79){
        for(i=j=0; (c = z[i])!=0; i++){ /* Copy from z[i] back to z[j] */
          if(c==cEnd){
            cEnd = 0;
          }else if(c=='"' || c=='\'' || c=='`'){
            cEnd = c;
          }else if(c=='['){
            cEnd = ']';
          }else if(c=='-' && z[i+1]=='-'){
            cEnd = '\n';
          }else if(c=='('){
            nParen++;
          }else if(c==')'){
            nParen--;
            if(nLine>0 && nParen==0 && j>0){
              printSchemaLineN(p->out, z, j, "\n");
              j = 0;
            }
          }
          z[j++] = c;
          if(nParen==1 && cEnd==0
           && (c=='(' || c=='\n' || (c==',' && !wsToEol(z+i+1)))
          ){
            if(c=='\n') j--;
            printSchemaLineN(p->out, z, j, "\n ");
            j = 0;
            nLine++;
            while(IsSpace(z[i+1])){ i++; }
          }
        }
        z[j] = 0;
      }
      printSchemaLine(p->out, z, ";\n");
      sqlite3_free(z);
      break;
    }
    case MODE_List: {
      if(p->cnt++==0 && p->showHeader){
        for(i=0; i<nArg; i++){
          utf8_printf(p->out,"%s%s",azCol[i],
                  i==nArg-1 ? p->rowSeparator : p->colSeparator);
        }
      }
      if(azArg==0) break;
      for(i=0; i<nArg; i++){
        char *z = azArg[i];
        if(z==0) z = p->nullValue;
        utf8_printf(p->out, "%s", z);
        if(i<nArg-1){
          utf8_printf(p->out, "%s", p->colSeparator);
        }else{
          utf8_printf(p->out, "%s", p->rowSeparator);
        }
      }
      break;
    }
    case MODE_Html: {
      if(p->cnt++==0 && p->showHeader){
        raw_printf(p->out,"<TR>");
        for(i=0; i<nArg; i++){
          raw_printf(p->out,"<TH>");
          output_html_string(p->out, azCol[i]);
          raw_printf(p->out,"</TH>\n");
        }
        raw_printf(p->out,"</TR>\n");
      }
      if(azArg==0) break;
      raw_printf(p->out,"<TR>");
      for(i=0; i<nArg; i++){
        raw_printf(p->out,"<TD>");
        output_html_string(p->out, azArg[i] ? azArg[i] : p->nullValue);
        raw_printf(p->out,"</TD>\n");
      }
      raw_printf(p->out,"</TR>\n");
      break;
    }
    case MODE_Tcl: {
      if(p->cnt++==0 && p->showHeader){
        for(i=0; i<nArg; i++){
          output_c_string(p->out,azCol[i] ? azCol[i] : "");
          if(i<nArg-1) utf8_printf(p->out, "%s", p->colSeparator);
        }
        utf8_printf(p->out, "%s", p->rowSeparator);
      }
      if(azArg==0) break;
      for(i=0; i<nArg; i++){
        output_c_string(p->out, azArg[i] ? azArg[i] : p->nullValue);
        if(i<nArg-1) utf8_printf(p->out, "%s", p->colSeparator);
      }
      utf8_printf(p->out, "%s", p->rowSeparator);
      break;
    }
    case MODE_Csv: {
      setBinaryMode(p->out, 1);
      if(p->cnt++==0 && p->showHeader){
        for(i=0; i<nArg; i++){
          output_csv(p, azCol[i] ? azCol[i] : "", i<nArg-1);
        }
        utf8_printf(p->out, "%s", p->rowSeparator);
      }
      if(nArg>0){
        for(i=0; i<nArg; i++){
          output_csv(p, azArg[i], i<nArg-1);
        }
        utf8_printf(p->out, "%s", p->rowSeparator);
      }
      setTextMode(p->out, 1);
      break;
    }
    case MODE_Insert: {
      if(azArg==0) break;
      utf8_printf(p->out,"INSERT INTO %s",p->zDestTable);
      if(p->showHeader){
        raw_printf(p->out,"(");
        for(i=0; i<nArg; i++){
          if(i>0) raw_printf(p->out, ",");
          if(quoteChar(azCol[i])){
            char *z = sqlite3_mprintf("\"%w\"", azCol[i]);
            utf8_printf(p->out, "%s", z);
            sqlite3_free(z);
          }else{
            raw_printf(p->out, "%s", azCol[i]);
          }
        }
        raw_printf(p->out,")");
      }
      p->cnt++;
      for(i=0; i<nArg; i++){
        raw_printf(p->out, i>0 ? "," : " VALUES(");
        if((azArg[i]==0) || (aiType && aiType[i]==SQLITE_NULL)){
          utf8_printf(p->out,"NULL");
        }else if(aiType && aiType[i]==SQLITE_TEXT){
          if(ShellHasFlag(p, SHFLG_Newlines)){
            output_quoted_string(p->out, azArg[i]);
          }else{
            output_quoted_escaped_string(p->out, azArg[i]);
          }
        }else if(aiType && aiType[i]==SQLITE_INTEGER){
          utf8_printf(p->out,"%s", azArg[i]);
        }else if(aiType && aiType[i]==SQLITE_FLOAT){
          char z[50];
          double r = sqlite3_column_double(p->pStmt, i);
          sqlite3_uint64 ur;
          memcpy(&ur,&r,sizeof(r));
          if(ur==0x7ff0000000000000LL){
            raw_printf(p->out, "1e999");
          }else if(ur==0xfff0000000000000LL){
            raw_printf(p->out, "-1e999");
          }else{
            sqlite3_snprintf(50,z,"%!.20g", r);
            raw_printf(p->out, "%s", z);
          }
        }else if(aiType && aiType[i]==SQLITE_BLOB && p->pStmt){
          const void *pBlob = sqlite3_column_blob(p->pStmt, i);
          int nBlob = sqlite3_column_bytes(p->pStmt, i);
          output_hex_blob(p->out, pBlob, nBlob);
        }else if(isNumber(azArg[i], 0)){
          utf8_printf(p->out,"%s", azArg[i]);
        }else if(ShellHasFlag(p, SHFLG_Newlines)){
          output_quoted_string(p->out, azArg[i]);
        }else{
          output_quoted_escaped_string(p->out, azArg[i]);
        }
      }
      raw_printf(p->out,");\n");
      break;
    }
    case MODE_Quote: {
      if(azArg==0) break;
      if(p->cnt==0 && p->showHeader){
        for(i=0; i<nArg; i++){
          if(i>0) raw_printf(p->out, ",");
          output_quoted_string(p->out, azCol[i]);
        }
        raw_printf(p->out,"\n");
      }
      p->cnt++;
      for(i=0; i<nArg; i++){
        if(i>0) raw_printf(p->out, ",");
        if((azArg[i]==0) || (aiType && aiType[i]==SQLITE_NULL)){
          utf8_printf(p->out,"NULL");
        }else if(aiType && aiType[i]==SQLITE_TEXT){
          output_quoted_string(p->out, azArg[i]);
        }else if(aiType && aiType[i]==SQLITE_INTEGER){
          utf8_printf(p->out,"%s", azArg[i]);
        }else if(aiType && aiType[i]==SQLITE_FLOAT){
          char z[50];
          double r = sqlite3_column_double(p->pStmt, i);
          sqlite3_snprintf(50,z,"%!.20g", r);
          raw_printf(p->out, "%s", z);
        }else if(aiType && aiType[i]==SQLITE_BLOB && p->pStmt){
          const void *pBlob = sqlite3_column_blob(p->pStmt, i);
          int nBlob = sqlite3_column_bytes(p->pStmt, i);
          output_hex_blob(p->out, pBlob, nBlob);
        }else if(isNumber(azArg[i], 0)){
          utf8_printf(p->out,"%s", azArg[i]);
        }else{
          output_quoted_string(p->out, azArg[i]);
        }
      }
      raw_printf(p->out,"\n");
      break;
    }
    case MODE_Ascii: {
      if(p->cnt++==0 && p->showHeader){
        for(i=0; i<nArg; i++){
          if(i>0) utf8_printf(p->out, "%s", p->colSeparator);
          utf8_printf(p->out,"%s",azCol[i] ? azCol[i] : "");
        }
        utf8_printf(p->out, "%s", p->rowSeparator);
      }
      if(azArg==0) break;
      for(i=0; i<nArg; i++){
        if(i>0) utf8_printf(p->out, "%s", p->colSeparator);
        utf8_printf(p->out,"%s",azArg[i] ? azArg[i] : p->nullValue);
      }
      utf8_printf(p->out, "%s", p->rowSeparator);
      break;
    }
    case MODE_EQP: {
      eqp_append(p, atoi(azArg[0]), atoi(azArg[1]), azArg[3]);
      break;
    }
  }
  return 0;
}
shell_dbinfo_command()
static int shell_dbinfo_command (ShellState * p, int nArg, char ** azArg) [static]
Definition at line 13498 of file shell.c.
References ArraySize, ShellState::db, db_int(), get2byteInt(), get4byteInt(), open_db(), ShellState::out, raw_printf, sqlite3_bind_text, sqlite3_column_blob, sqlite3_column_bytes, sqlite3_compileoption_used, sqlite3_errmsg, sqlite3_file_control, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, SQLITE_FCNTL_DATA_VERSION, SQLITE_ROW, SQLITE_STATIC, utf8_printf, and zName.
Referenced by do_meta_command().
                                                                      {
  static const struct { const char *zName; int ofst; } aField[] = {
     { "file change counter:", 24 },
     { "database page count:", 28 },
     { "freelist page count:", 36 },
     { "schema cookie:", 40 },
     { "schema format:", 44 },
     { "default cache size:", 48 },
     { "autovacuum top root:", 52 },
     { "incremental vacuum:", 64 },
     { "text encoding:", 56 },
     { "user version:", 60 },
     { "application id:", 68 },
     { "software version:", 96 },
  };
  static const struct { const char *zName; const char *zSql; } aQuery[] = {
     { "number of tables:",
       "SELECT count(*) FROM %s WHERE type='table'" },
     { "number of indexes:",
       "SELECT count(*) FROM %s WHERE type='index'" },
     { "number of triggers:",
       "SELECT count(*) FROM %s WHERE type='trigger'" },
     { "number of views:",
       "SELECT count(*) FROM %s WHERE type='view'" },
     { "schema size:",
       "SELECT total(length(sql)) FROM %s" },
  };
  int i, rc;
  unsigned iDataVersion;
  char *zSchemaTab;
  char *zDb = nArg>=2 ? azArg[1] : "main";
  sqlite3_stmt *pStmt = 0;
  unsigned char aHdr[100];
  open_db(p, 0);
  if(p->db==0) return 1;
  rc = sqlite3_prepare_v2(p->db,
             "SELECT data FROM sqlite_dbpage(?1) WHERE pgno=1",
             -1, &pStmt, 0);
  if(rc){
    if(!sqlite3_compileoption_used("ENABLE_DBPAGE_VTAB")){
      utf8_printf(stderr, "the \".dbinfo\" command requires the "
                          "-DSQLITE_ENABLE_DBPAGE_VTAB compile-time options\n");
    }else{
      utf8_printf(stderr, "error: %s\n", sqlite3_errmsg(p->db));
    }
    sqlite3_finalize(pStmt);
    return 1;
  }
  sqlite3_bind_text(pStmt, 1, zDb, -1, SQLITE_STATIC);
  if(sqlite3_step(pStmt)==SQLITE_ROW
   && sqlite3_column_bytes(pStmt,0)>100
  ){
    memcpy(aHdr, sqlite3_column_blob(pStmt,0), 100);
    sqlite3_finalize(pStmt);
  }else{
    raw_printf(stderr, "unable to read database header\n");
    sqlite3_finalize(pStmt);
    return 1;
  }
  i = get2byteInt(aHdr+16);
  if(i==1) i = 65536;
  utf8_printf(p->out, "%-20s %d\n", "database page size:", i);
  utf8_printf(p->out, "%-20s %d\n", "write format:", aHdr[18]);
  utf8_printf(p->out, "%-20s %d\n", "read format:", aHdr[19]);
  utf8_printf(p->out, "%-20s %d\n", "reserved bytes:", aHdr[20]);
  for(i=0; i<ArraySize(aField); i++){
    int ofst = aField[i].ofst;
    unsigned int val = get4byteInt(aHdr + ofst);
    utf8_printf(p->out, "%-20s %u", aField[i].zName, val);
    switch(ofst){
      case 56: {
        if(val==1) raw_printf(p->out, " (utf8)");
        if(val==2) raw_printf(p->out, " (utf16le)");
        if(val==3) raw_printf(p->out, " (utf16be)");
      }
    }
    raw_printf(p->out, "\n");
  }
  if(zDb==0){
    zSchemaTab = sqlite3_mprintf("main.sqlite_master");
  }else if(strcmp(zDb,"temp")==0){
    zSchemaTab = sqlite3_mprintf("%s", "sqlite_temp_master");
  }else{
    zSchemaTab = sqlite3_mprintf("\"%w\".sqlite_master", zDb);
  }
  for(i=0; i<ArraySize(aQuery); i++){
    char *zSql = sqlite3_mprintf(aQuery[i].zSql, zSchemaTab);
    int val = db_int(p, zSql);
    sqlite3_free(zSql);
    utf8_printf(p->out, "%-20s %d\n", aQuery[i].zName, val);
  }
  sqlite3_free(zSchemaTab);
  sqlite3_file_control(p->db, zDb, SQLITE_FCNTL_DATA_VERSION, &iDataVersion);
  utf8_printf(p->out, "%-20s %u\n", "data version", iDataVersion);
  return 0;
}
shell_exec()
static int shell_exec (ShellState * pArg, const char * zSql, char ** pzErrMsg) [static]
Definition at line 11590 of file shell.c.
References ShellState::autoEQP, AUTOEQP_full, AUTOEQP_trigger, ShellState::autoExplain, bind_prepared_stmt(), ShellState::cMode, ShellState::cnt, ShellState::db, disable_debug_trace_modes(), display_scanstats(), display_stats(), eqp_append(), eqp_render(), exec_prepared_stmt(), ShellState::expert, expertFinish(), expertHandleSQL(), explain_data_delete(), explain_data_prepare(), IsSpace, ShellState::mode, MODE_EQP, MODE_Explain, ShellState::out, ExpertInfo::pExpert, ShellState::pStmt, restore_debug_trace_modes(), save_err_msg(), ShellState::scanstatsOn, ShellHasFlag, SHFLG_Echo, sqlite3_column_int, sqlite3_column_text, sqlite3_db_config, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_sql, sqlite3_step, sqlite3_stmt_isexplain, SQLITE_DBCONFIG_TRIGGER_EQP, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, ShellState::statsOn, and utf8_printf.
Referenced by do_meta_command(), dump_callback(), main(), and runOneSqlLine().
 {
  sqlite3_stmt *pStmt = NULL; /* Statement to execute. */
  int rc = SQLITE_OK; /* Return Code */
  int rc2;
  const char *zLeftover; /* Tail of unprocessed SQL */
  sqlite3 *db = pArg->db;
  if(pzErrMsg){
    *pzErrMsg = NULL;
  }
#ifndef SQLITE_OMIT_VIRTUALTABLE
  if(pArg->expert.pExpert){
    rc = expertHandleSQL(pArg, zSql, pzErrMsg);
    return expertFinish(pArg, (rc!=SQLITE_OK), pzErrMsg);
  }
#endif
  while(zSql[0] && (SQLITE_OK == rc)){
    static const char *zStmtSql;
    rc = sqlite3_prepare_v2(db, zSql, -1, &pStmt, &zLeftover);
    if(SQLITE_OK != rc){
      if(pzErrMsg){
        *pzErrMsg = save_err_msg(db);
      }
    }else{
      if(!pStmt){
        /* this happens for a comment or white-space */
        zSql = zLeftover;
        while(IsSpace(zSql[0])) zSql++;
        continue;
      }
      zStmtSql = sqlite3_sql(pStmt);
      if(zStmtSql==0) zStmtSql = "";
      while(IsSpace(zStmtSql[0])) zStmtSql++;
      /* save off the prepared statment handle and reset row count */
      if(pArg){
        pArg->pStmt = pStmt;
        pArg->cnt = 0;
      }
      /* echo the sql statement if echo on */
      if(pArg && ShellHasFlag(pArg, SHFLG_Echo)){
        utf8_printf(pArg->out, "%s\n", zStmtSql ? zStmtSql : zSql);
      }
      /* Show the EXPLAIN QUERY PLAN if .eqp is on */
      if(pArg && pArg->autoEQP && sqlite3_stmt_isexplain(pStmt)==0){
        sqlite3_stmt *pExplain;
        char *zEQP;
        int triggerEQP = 0;
        disable_debug_trace_modes();
        sqlite3_db_config(db, SQLITE_DBCONFIG_TRIGGER_EQP, -1, &triggerEQP);
        if(pArg->autoEQP>=AUTOEQP_trigger){
          sqlite3_db_config(db, SQLITE_DBCONFIG_TRIGGER_EQP, 1, 0);
        }
        zEQP = sqlite3_mprintf("EXPLAIN QUERY PLAN %s", zStmtSql);
        rc = sqlite3_prepare_v2(db, zEQP, -1, &pExplain, 0);
        if(rc==SQLITE_OK){
          while(sqlite3_step(pExplain)==SQLITE_ROW){
            const char *zEQPLine = (const char*)sqlite3_column_text(pExplain,3);
            int iEqpId = sqlite3_column_int(pExplain, 0);
            int iParentId = sqlite3_column_int(pExplain, 1);
            if(zEQPLine[0]=='-') eqp_render(pArg);
            eqp_append(pArg, iEqpId, iParentId, zEQPLine);
          }
          eqp_render(pArg);
        }
        sqlite3_finalize(pExplain);
        sqlite3_free(zEQP);
        if(pArg->autoEQP>=AUTOEQP_full){
          /* Also do an EXPLAIN for ".eqp full" mode */
          zEQP = sqlite3_mprintf("EXPLAIN %s", zStmtSql);
          rc = sqlite3_prepare_v2(db, zEQP, -1, &pExplain, 0);
          if(rc==SQLITE_OK){
            pArg->cMode = MODE_Explain;
            explain_data_prepare(pArg, pExplain);
            exec_prepared_stmt(pArg, pExplain);
            explain_data_delete(pArg);
          }
          sqlite3_finalize(pExplain);
          sqlite3_free(zEQP);
        }
        if(pArg->autoEQP>=AUTOEQP_trigger && triggerEQP==0){
          sqlite3_db_config(db, SQLITE_DBCONFIG_TRIGGER_EQP, 0, 0);
          /* Reprepare pStmt before reactiving trace modes */
          sqlite3_finalize(pStmt);
          sqlite3_prepare_v2(db, zSql, -1, &pStmt, 0);
          if(pArg) pArg->pStmt = pStmt;
        }
        restore_debug_trace_modes();
      }
      if(pArg){
        pArg->cMode = pArg->mode;
        if(pArg->autoExplain){
          if(sqlite3_stmt_isexplain(pStmt)==1){
            pArg->cMode = MODE_Explain;
          }
          if(sqlite3_stmt_isexplain(pStmt)==2){
            pArg->cMode = MODE_EQP;
          }
        }
        /* If the shell is currently in ".explain" mode, gather the extra
        ** data required to add indents to the output.*/
        if(pArg->cMode==MODE_Explain){
          explain_data_prepare(pArg, pStmt);
        }
      }
      bind_prepared_stmt(pArg, pStmt);
      exec_prepared_stmt(pArg, pStmt);
      explain_data_delete(pArg);
      eqp_render(pArg);
      /* print usage stats if stats on */
      if(pArg && pArg->statsOn){
        display_stats(db, pArg, 0);
      }
      /* print loop-counters if required */
      if(pArg && pArg->scanstatsOn){
        display_scanstats(db, pArg);
      }
      /* Finalize the statement just executed. If this fails, save a
      ** copy of the error message. Otherwise, set zSql to point to the
      ** next statement to execute. */
      rc2 = sqlite3_finalize(pStmt);
      if(rc!=SQLITE_NOMEM) rc = rc2;
      if(rc==SQLITE_OK){
        zSql = zLeftover;
        while(IsSpace(zSql[0])) zSql++;
      }else if(pzErrMsg){
        *pzErrMsg = save_err_msg(db);
      }
      /* clear saved stmt handle */
      if(pArg){
        pArg->pStmt = NULL;
      }
    }
  } /* end while */
  return rc;
}
shell_out_of_memory()
static void shell_out_of_memory (void) [static]
Definition at line 464 of file shell.c.
References raw_printf, sqlite3_free, sqlite3_vmprintf, SQLITE_CDECL, and utf8_printf.
Referenced by appendText(), do_meta_command(), eqp_append(), explain_data_prepare(), import_append_char(), local_getline(), main(), process_input(), set_table_name(), tableColumnList(), and tryToCloneData().
                                     {
  raw_printf(stderr,"Error: out of memory\n");
  exit(1);
}
shellAddSchemaName()
static void shellAddSchemaName (sqlite3_context * pCtx, int nVal, sqlite3_value ** apVal) [static]
Definition at line 889 of file shell.c.
References aPrefix, quoteChar(), shellFakeSchema(), sqlite3_context_db_handle, sqlite3_free, sqlite3_mprintf, sqlite3_result_text, sqlite3_result_value, sqlite3_stricmp, sqlite3_value_text, strlen30(), UNUSED_PARAMETER, and zName.
Referenced by open_db().
 {
  static const char *aPrefix[] = {
     "TABLE",
     "INDEX",
     "UNIQUE INDEX",
     "VIEW",
     "TRIGGER",
     "VIRTUAL TABLE"
  };
  int i = 0;
  const char *zIn = (const char*)sqlite3_value_text(apVal[0]);
  const char *zSchema = (const char*)sqlite3_value_text(apVal[1]);
  const char *zName = (const char*)sqlite3_value_text(apVal[2]);
  sqlite3 *db = sqlite3_context_db_handle(pCtx);
  UNUSED_PARAMETER(nVal);
  if(zIn!=0 && strncmp(zIn, "CREATE ", 7)==0){
    for(i=0; i<(int)(sizeof(aPrefix)/sizeof(aPrefix[0])); i++){
      int n = strlen30(aPrefix[i]);
      if(strncmp(zIn+7, aPrefix[i], n)==0 && zIn[n+7]==' '){
        char *z = 0;
        char *zFake = 0;
        if(zSchema){
          char cQuote = quoteChar(zSchema);
          if(cQuote && sqlite3_stricmp(zSchema,"temp")!=0){
            z = sqlite3_mprintf("%.*s \"%w\".%s", n+7, zIn, zSchema, zIn+n+8);
          }else{
            z = sqlite3_mprintf("%.*s %s.%s", n+7, zIn, zSchema, zIn+n+8);
          }
        }
        if(zName
         && aPrefix[i][0]=='V'
         && (zFake = shellFakeSchema(db, zSchema, zName))!=0
        ){
          if(z==0){
            z = sqlite3_mprintf("%s\n/* %s */", zIn, zFake);
          }else{
            z = sqlite3_mprintf("%z\n/* %s */", z, zFake);
          }
          free(zFake);
        }
        if(z){
          sqlite3_result_text(pCtx, z, -1, sqlite3_free);
          return;
        }
      }
    }
  }
  sqlite3_result_value(pCtx, apVal[0]);
}
shellAuth()
static int shellAuth (void * pClientData, int op, const char * zA1, const char * zA2, const char * zA3, const char * zA4) [static]
Definition at line 10201 of file shell.c.
References ShellState::out, output_c_string(), raw_printf, SQLITE_OK, and utf8_printf.
Referenced by do_meta_command().
 {
  ShellState *p = (ShellState*)pClientData;
  static const char *azAction[] = { 0,
     "CREATE_INDEX", "CREATE_TABLE", "CREATE_TEMP_INDEX",
     "CREATE_TEMP_TABLE", "CREATE_TEMP_TRIGGER", "CREATE_TEMP_VIEW",
     "CREATE_TRIGGER", "CREATE_VIEW", "DELETE",
     "DROP_INDEX", "DROP_TABLE", "DROP_TEMP_INDEX",
     "DROP_TEMP_TABLE", "DROP_TEMP_TRIGGER", "DROP_TEMP_VIEW",
     "DROP_TRIGGER", "DROP_VIEW", "INSERT",
     "PRAGMA", "READ", "SELECT",
     "TRANSACTION", "UPDATE", "ATTACH",
     "DETACH", "ALTER_TABLE", "REINDEX",
     "ANALYZE", "CREATE_VTABLE", "DROP_VTABLE",
     "FUNCTION", "SAVEPOINT", "RECURSIVE"
  };
  int i;
  const char *az[4];
  az[0] = zA1;
  az[1] = zA2;
  az[2] = zA3;
  az[3] = zA4;
  utf8_printf(p->out, "authorizer: %s", azAction[op]);
  for(i=0; i<4; i++){
    raw_printf(p->out, " ");
    if(az[i]){
      output_c_string(p->out, az[i]);
    }else{
      raw_printf(p->out, "NULL");
    }
  }
  raw_printf(p->out, "\n");
  return SQLITE_OK;
}
shellDatabaseError()
static int shellDatabaseError (sqlite3 * db) [static]
Definition at line 13598 of file shell.c.
References sqlite3_errmsg, and utf8_printf.
Referenced by do_meta_command().
                                          {
  const char *zErr = sqlite3_errmsg(db);
  utf8_printf(stderr, "Error: %s\n", zErr);
  return 1;
}
shellDeleteFile()
int shellDeleteFile (const char * zFilename)
Definition at line 13716 of file shell.c.
References sqlite3_free.
Referenced by clearTempFile(), and do_meta_command().
                                          {
  int rc;
#ifdef _WIN32
  wchar_t *z = sqlite3_win32_utf8_to_unicode(zFilename);
  rc = _wunlink(z);
  sqlite3_free(z);
#else
  rc = unlink(zFilename);
#endif
  return rc;
}
shellEscapeCrnl()
static void shellEscapeCrnl (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 12592 of file shell.c.
References sqlite3_free, sqlite3_malloc64, sqlite3_result_error_nomem, sqlite3_result_text, sqlite3_result_value, sqlite3_value_bytes, sqlite3_value_text, SQLITE_TRANSIENT, UNUSED_PARAMETER, and unused_string().
Referenced by open_db().
 {
  const char *zText = (const char*)sqlite3_value_text(argv[0]);
  UNUSED_PARAMETER(argc);
  if(zText[0]=='\''){
    int nText = sqlite3_value_bytes(argv[0]);
    int i;
    char zBuf1[20];
    char zBuf2[20];
    const char *zNL = 0;
    const char *zCR = 0;
    int nCR = 0;
    int nNL = 0;
    for(i=0; zText[i]; i++){
      if(zNL==0 && zText[i]=='\n'){
        zNL = unused_string(zText, "\\n", "\\012", zBuf1);
        nNL = (int)strlen(zNL);
      }
      if(zCR==0 && zText[i]=='\r'){
        zCR = unused_string(zText, "\\r", "\\015", zBuf2);
        nCR = (int)strlen(zCR);
      }
    }
    if(zNL || zCR){
      int iOut = 0;
      i64 nMax = (nNL > nCR) ? nNL : nCR;
      i64 nAlloc = nMax * nText + (nMax+64)*2;
      char *zOut = (char*)sqlite3_malloc64(nAlloc);
      if(zOut==0){
        sqlite3_result_error_nomem(context);
        return;
      }
      if(zNL && zCR){
        memcpy(&zOut[iOut], "replace(replace(", 16);
        iOut += 16;
      }else{
        memcpy(&zOut[iOut], "replace(", 8);
        iOut += 8;
      }
      for(i=0; zText[i]; i++){
        if(zText[i]=='\n'){
          memcpy(&zOut[iOut], zNL, nNL);
          iOut += nNL;
        }else if(zText[i]=='\r'){
          memcpy(&zOut[iOut], zCR, nCR);
          iOut += nCR;
        }else{
          zOut[iOut] = zText[i];
          iOut++;
        }
      }
      if(zNL){
        memcpy(&zOut[iOut], ",'", 2); iOut += 2;
        memcpy(&zOut[iOut], zNL, nNL); iOut += nNL;
        memcpy(&zOut[iOut], "', char(10))", 12); iOut += 12;
      }
      if(zCR){
        memcpy(&zOut[iOut], ",'", 2); iOut += 2;
        memcpy(&zOut[iOut], zCR, nCR); iOut += nCR;
        memcpy(&zOut[iOut], "', char(13))", 12); iOut += 12;
      }
      sqlite3_result_text(context, zOut, iOut, SQLITE_TRANSIENT);
      sqlite3_free(zOut);
      return;
    }
  }
  sqlite3_result_value(context, argv[0]);
}
shellFakeSchema()
static char* shellFakeSchema (sqlite3 * db, const char * zSchema, const char * zName) [static]
Definition at line 807 of file shell.c.
References appendText(), freeText(), initText(), quoteChar(), sqlite3_column_text, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, sqlite3_stricmp, SQLITE_ROW, and ShellText::z.
Referenced by shellAddSchemaName(), and shellModuleSchema().
 {
  sqlite3_stmt *pStmt = 0;
  char *zSql;
  ShellText s;
  char cQuote;
  char *zDiv = "(";
  int nRow = 0;
  zSql = sqlite3_mprintf("PRAGMA \"%w\".table_info=%Q;",
                         zSchema ? zSchema : "main", zName);
  sqlite3_prepare_v2(db, zSql, -1, &pStmt, 0);
  sqlite3_free(zSql);
  initText(&s);
  if(zSchema){
    cQuote = quoteChar(zSchema);
    if(cQuote && sqlite3_stricmp(zSchema,"temp")==0) cQuote = 0;
    appendText(&s, zSchema, cQuote);
    appendText(&s, ".", 0);
  }
  cQuote = quoteChar(zName);
  appendText(&s, zName, cQuote);
  while(sqlite3_step(pStmt)==SQLITE_ROW){
    const char *zCol = (const char*)sqlite3_column_text(pStmt, 1);
    nRow++;
    appendText(&s, zDiv, 0);
    zDiv = ",";
    cQuote = quoteChar(zCol);
    appendText(&s, zCol, cQuote);
  }
  appendText(&s, ")", 0);
  sqlite3_finalize(pStmt);
  if(nRow==0){
    freeText(&s);
    s.z = 0;
  }
  return s.z;
}
shellFinalize()
void shellFinalize (int * pRc, sqlite3_stmt * pStmt)
Definition at line 14068 of file shell.c.
References raw_printf, sqlite3_db_handle, sqlite3_errmsg, sqlite3_finalize, and SQLITE_OK.
Referenced by shellReset().
 {
  if(pStmt){
    sqlite3 *db = sqlite3_db_handle(pStmt);
    int rc = sqlite3_finalize(pStmt);
    if(*pRc==SQLITE_OK){
      if(rc!=SQLITE_OK){
        raw_printf(stderr, "SQL error: %s\n", sqlite3_errmsg(db));
      }
      *pRc = rc;
    }
  }
}
shellFkeyCollateClause()
static void shellFkeyCollateClause (sqlite3_context * pCtx, int nVal, sqlite3_value ** apVal) [static]
Definition at line 13779 of file shell.c.
References sqlite3_context_db_handle, sqlite3_free, sqlite3_mprintf, sqlite3_result_text, sqlite3_stricmp, sqlite3_table_column_metadata, sqlite3_value_text, SQLITE_OK, SQLITE_STATIC, and SQLITE_TRANSIENT.
Referenced by lintFkeyIndexes().
 {
  sqlite3 *db = sqlite3_context_db_handle(pCtx);
  const char *zParent;
  const char *zParentCol;
  const char *zParentSeq;
  const char *zChild;
  const char *zChildCol;
  const char *zChildSeq = 0; /* Initialize to avoid false-positive warning */
  int rc;
  assert(nVal==4);
  zParent = (const char*)sqlite3_value_text(apVal[0]);
  zParentCol = (const char*)sqlite3_value_text(apVal[1]);
  zChild = (const char*)sqlite3_value_text(apVal[2]);
  zChildCol = (const char*)sqlite3_value_text(apVal[3]);
  sqlite3_result_text(pCtx, "", -1, SQLITE_STATIC);
  rc = sqlite3_table_column_metadata(
      db, "main", zParent, zParentCol, 0, &zParentSeq, 0, 0, 0
  );
  if(rc==SQLITE_OK){
    rc = sqlite3_table_column_metadata(
        db, "main", zChild, zChildCol, 0, &zChildSeq, 0, 0, 0
    );
  }
  if(rc==SQLITE_OK && sqlite3_stricmp(zParentSeq, zChildSeq)){
    char *z = sqlite3_mprintf(" COLLATE %s", zParentSeq);
    sqlite3_result_text(pCtx, z, -1, SQLITE_TRANSIENT);
    sqlite3_free(z);
  }
}
shellIdQuote()
static void shellIdQuote (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 12566 of file shell.c.
References sqlite3_free, sqlite3_mprintf, sqlite3_result_text, sqlite3_value_text, and UNUSED_PARAMETER.
Referenced by open_db(), and shellReset().
 {
  const char *zName = (const char*)sqlite3_value_text(argv[0]);
  UNUSED_PARAMETER(argc);
  if(zName){
    char *z = sqlite3_mprintf("\"%w\"", zName);
    sqlite3_result_text(context, z, -1, sqlite3_free);
  }
}
shellInt32()
static void shellInt32 (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 12538 of file shell.c.
References sqlite3_result_int64, sqlite3_value_blob, sqlite3_value_bytes, sqlite3_value_int, and UNUSED_PARAMETER.
Referenced by open_db().
 {
  const unsigned char *pBlob;
  int nBlob;
  int iInt;
  UNUSED_PARAMETER(argc);
  nBlob = sqlite3_value_bytes(argv[0]);
  pBlob = (const unsigned char*)sqlite3_value_blob(argv[0]);
  iInt = sqlite3_value_int(argv[1]);
  if(iInt>=0 && (iInt+1)*4<=nBlob){
    const unsigned char *a = &pBlob[iInt*4];
    sqlite3_int64 iVal = ((sqlite3_int64)a[0]<<24)
                       + ((sqlite3_int64)a[1]<<16)
                       + ((sqlite3_int64)a[2]<< 8)
                       + ((sqlite3_int64)a[3]<< 0);
    sqlite3_result_int64(context, iVal);
  }
}
shellLog()
static void shellLog (void * pArg, int iErrCode, const char * zMsg) [static]
Definition at line 9732 of file shell.c.
References ShellState::pLog, and utf8_printf.
Referenced by main_init().
                                                                {
  ShellState *p = (ShellState*)pArg;
  if(p->pLog==0) return;
  utf8_printf(p->pLog, "(%d) %s\n", iErrCode, zMsg);
  fflush(p->pLog);
}
shellModuleSchema()
static void shellModuleSchema (sqlite3_context * pCtx, int nVal, sqlite3_value ** apVal) [static]
Definition at line 855 of file shell.c.
References shellFakeSchema(), sqlite3_context_db_handle, sqlite3_free, sqlite3_mprintf, sqlite3_result_text, sqlite3_value_text, UNUSED_PARAMETER, and zName.
Referenced by open_db().
 {
  const char *zName = (const char*)sqlite3_value_text(apVal[0]);
  char *zFake = shellFakeSchema(sqlite3_context_db_handle(pCtx), 0, zName);
  UNUSED_PARAMETER(nVal);
  if(zFake){
    sqlite3_result_text(pCtx, sqlite3_mprintf("/* %s */", zFake),
                        -1, sqlite3_free);
    free(zFake);
  }
}
shellPrepare()
static void shellPrepare (sqlite3 * db, int * pRc, const char * zSql, sqlite3_stmt ** ppStmt) [static]
Definition at line 14014 of file shell.c.
References raw_printf, sqlite3_errcode, sqlite3_errmsg, sqlite3_prepare_v2, and SQLITE_OK.
Referenced by shellPreparePrintf(), and shellReset().
 {
  *ppStmt = 0;
  if(*pRc==SQLITE_OK){
    int rc = sqlite3_prepare_v2(db, zSql, -1, ppStmt, 0);
    if(rc!=SQLITE_OK){
      raw_printf(stderr, "sql error: %s (%d)\n",
          sqlite3_errmsg(db), sqlite3_errcode(db)
      );
      *pRc = rc;
    }
  }
}
shellPreparePrintf()
void shellPreparePrintf (sqlite3 * db, int * pRc, sqlite3_stmt ** ppStmt, const char * zFmt, ...)
Definition at line 14039 of file shell.c.
References shellPrepare(), sqlite3_free, sqlite3_vmprintf, SQLITE_NOMEM, and SQLITE_OK.
Referenced by shellReset().
 {
  *ppStmt = 0;
  if(*pRc==SQLITE_OK){
    va_list ap;
    char *z;
    va_start(ap, zFmt);
    z = sqlite3_vmprintf(zFmt, ap);
    va_end(ap);
    if(z==0){
      *pRc = SQLITE_NOMEM;
    }else{
      shellPrepare(db, pRc, z, ppStmt);
      sqlite3_free(z);
    }
  }
}
shellPutsFunc()
static void shellPutsFunc (sqlite3_context * pCtx, int nVal, sqlite3_value ** apVal) [static]
Definition at line 9745 of file shell.c.
References ShellState::out, sqlite3_result_value, sqlite3_user_data, sqlite3_value_text, and utf8_printf.
Referenced by open_db(), and shellReset().
 {
  ShellState *p = (ShellState*)sqlite3_user_data(pCtx);
  (void)nVal;
  utf8_printf(p->out, "%s\n", sqlite3_value_text(apVal[0]));
  sqlite3_result_value(pCtx, apVal[0]);
}
shellReset()
void shellReset (int * pRc, sqlite3_stmt * pStmt)
Definition at line 14090 of file shell.c.
References close_db(), ShellState::db, deduceDatabaseType(), ShellState::openMode, ShellState::out, raw_printf, SHELL_OPEN_APPENDVFS, SHELL_OPEN_UNSPEC, SHELL_OPEN_ZIPFILE, shellFinalize(), shellIdQuote(), shellPrepare(), shellPreparePrintf(), shellPutsFunc(), showHelp(), sqlite3_bind_int, sqlite3_bind_parameter_index, sqlite3_bind_text, sqlite3_close, sqlite3_column_int, sqlite3_column_text, sqlite3_create_function, sqlite3_db_handle, sqlite3_errmsg, sqlite3_exec, sqlite3_fileio_init(), sqlite3_free, sqlite3_malloc64, sqlite3_mprintf, sqlite3_open, sqlite3_open_v2, sqlite3_randomness, sqlite3_reset, sqlite3_snprintf, sqlite3_sql, sqlite3_step, sqlite3_stricmp, sqlite3_strnicmp, sqlite3_table_column_metadata, sqlite3_vmprintf, SQLITE_ERROR, SQLITE_NOMEM, SQLITE_OK, SQLITE_OPEN_CREATE, SQLITE_OPEN_READONLY, SQLITE_OPEN_READWRITE, SQLITE_ROW, SQLITE_STATIC, SQLITE_TRANSIENT, SQLITE_UTF8, strlen30(), and utf8_printf.
 {
  int rc = sqlite3_reset(pStmt);
  if(*pRc==SQLITE_OK){
    if(rc!=SQLITE_OK){
      sqlite3 *db = sqlite3_db_handle(pStmt);
      raw_printf(stderr, "SQL error: %s\n", sqlite3_errmsg(db));
    }
    *pRc = rc;
  }
}
showHelp()
static int showHelp (FILE * out, const char * zPattern) [static]
Definition at line 12250 of file shell.c.
References ArraySize, azHelp, process_input(), sqlite3_free, sqlite3_mprintf, sqlite3_strglob, sqlite3_strlike, and utf8_printf.
Referenced by do_meta_command(), and shellReset().
                                                    {
  int i = 0;
  int j = 0;
  int n = 0;
  char *zPat;
  if(zPattern==0
   || zPattern[0]=='0'
   || strcmp(zPattern,"-a")==0
   || strcmp(zPattern,"-all")==0
  ){
    /* Show all commands, but only one line per command */
    if(zPattern==0) zPattern = "";
    for(i=0; i<ArraySize(azHelp); i++){
      if(azHelp[i][0]=='.' || zPattern[0]){
        utf8_printf(out, "%s\n", azHelp[i]);
        n++;
      }
    }
  }else{
    /* Look for commands that for which zPattern is an exact prefix */
    zPat = sqlite3_mprintf(".%s*", zPattern);
    for(i=0; i<ArraySize(azHelp); i++){
      if(sqlite3_strglob(zPat, azHelp[i])==0){
        utf8_printf(out, "%s\n", azHelp[i]);
        j = i+1;
        n++;
      }
    }
    sqlite3_free(zPat);
    if(n){
      if(n==1){
        /* when zPattern is a prefix of exactly one command, then include the
        ** details of that command, which should begin at offset j */
        while(j<ArraySize(azHelp)-1 && azHelp[j][0]!='.'){
          utf8_printf(out, "%s\n", azHelp[j]);
          j++;
        }
      }
      return n;
    }
    /* Look for commands that contain zPattern anywhere. Show the complete
    ** text of all commands that match. */
    zPat = sqlite3_mprintf("%%%s%%", zPattern);
    for(i=0; i<ArraySize(azHelp); i++){
      if(azHelp[i][0]=='.') j = i;
      if(sqlite3_strlike(zPat, azHelp[i], 0)==0){
        utf8_printf(out, "%s\n", azHelp[j]);
        while(j<ArraySize(azHelp)-1 && azHelp[j+1][0]!='.'){
          j++;
          utf8_printf(out, "%s\n", azHelp[j]);
        }
        i = j;
        n++;
      }
    }
    sqlite3_free(zPat);
  }
  return n;
}
sql_trace_callback()
static int sql_trace_callback (unsigned mType, void * pArg, void * pP, void * pX) [static]
Definition at line 13001 of file shell.c.
References ShellState::eTraceType, SHELL_TRACE_EXPANDED, SHELL_TRACE_NORMALIZED, sqlite3_expanded_sql, sqlite3_normalized_sql, sqlite3_sql, SQLITE_TRACE_CLOSE, SQLITE_TRACE_PROFILE, SQLITE_TRACE_ROW, SQLITE_TRACE_STMT, strlen30(), ShellState::traceOut, and utf8_printf.
Referenced by do_meta_command().
 {
  ShellState *p = (ShellState*)pArg;
  sqlite3_stmt *pStmt;
  const char *zSql;
  int nSql;
  if(p->traceOut==0) return 0;
  if(mType==SQLITE_TRACE_CLOSE){
    utf8_printf(p->traceOut, "-- closing database connection\n");
    return 0;
  }
  if(mType!=SQLITE_TRACE_ROW && ((const char*)pX)[0]=='-'){
    zSql = (const char*)pX;
  }else{
    pStmt = (sqlite3_stmt*)pP;
    switch(p->eTraceType){
      case SHELL_TRACE_EXPANDED: {
        zSql = sqlite3_expanded_sql(pStmt);
        break;
      }
#ifdef SQLITE_ENABLE_NORMALIZE
      case SHELL_TRACE_NORMALIZED: {
        zSql = sqlite3_normalized_sql(pStmt);
        break;
      }
#endif
      default: {
        zSql = sqlite3_sql(pStmt);
        break;
      }
    }
  }
  if(zSql==0) return 0;
  nSql = strlen30(zSql);
  while(nSql>0 && zSql[nSql-1]==';'){ nSql--; }
  switch(mType){
    case SQLITE_TRACE_ROW:
    case SQLITE_TRACE_STMT: {
      utf8_printf(p->traceOut, "%.*s;\n", nSql, zSql);
      break;
    }
    case SQLITE_TRACE_PROFILE: {
      sqlite3_int64 nNanosec = *(sqlite3_int64*)pX;
      utf8_printf(p->traceOut, "%.*s; -- %lld ns\n", nSql, zSql, nNanosec);
      break;
    }
  }
  return 0;
}
sqlite3_appendvfs_init()
int sqlite3_appendvfs_init (sqlite3 * db, char ** pzErrMsg, const sqlite3_api_routines * pApi)
Definition at line 4080 of file shell.c.
References sqlite3_vfs::iVersion, sqlite3_vfs::pAppData, sqlite3_auto_extension, sqlite3_vfs_find, sqlite3_vfs_register, SQLITE_EXTENSION_INIT2, SQLITE_OK, SQLITE_OK_LOAD_PERMANENTLY, and sqlite3_vfs::szOsFile.
Referenced by main().
 {
  int rc = SQLITE_OK;
  sqlite3_vfs *pOrig;
  SQLITE_EXTENSION_INIT2(pApi);
  (void)pzErrMsg;
  (void)db;
  pOrig = sqlite3_vfs_find(0);
  apnd_vfs.iVersion = pOrig->iVersion;
  apnd_vfs.pAppData = pOrig;
  apnd_vfs.szOsFile = pOrig->szOsFile + sizeof(ApndFile);
  rc = sqlite3_vfs_register(&apnd_vfs, 0);
#ifdef APPENDVFS_TEST
  if(rc==SQLITE_OK){
    rc = sqlite3_auto_extension((void(*)(void))apndvfsRegister);
  }
#endif
  if(rc==SQLITE_OK) rc = SQLITE_OK_LOAD_PERMANENTLY;
  return rc;
}
sqlite3_completion_init()
int sqlite3_completion_init (sqlite3 * db, char ** pzErrMsg, const sqlite3_api_routines * pApi)
Definition at line 3522 of file shell.c.
References sqlite3CompletionVtabInit(), SQLITE_EXTENSION_INIT1, SQLITE_EXTENSION_INIT2, and SQLITE_OK.
Referenced by open_db().
 {
  int rc = SQLITE_OK;
  SQLITE_EXTENSION_INIT2(pApi);
  (void)(pzErrMsg); /* Unused parameter */
#ifndef SQLITE_OMIT_VIRTUALTABLE
  rc = sqlite3CompletionVtabInit(db);
#endif
  return rc;
}
sqlite3_expert_analyze()
int sqlite3_expert_analyze (sqlite3expert * p, char ** pzErr)
Definition at line 8569 of file shell.c.
References sqlite3expert::bRun, sqlite3expert::hIdx, idxAppendText(), idxCreateCandidates(), idxFindIndexes(), idxPopulateStat1(), idxProcessTriggers(), IdxHash::pFirst, IdxHashEntry::pNext, SQLITE_OK, sqlite3expert::zCandidates, IdxHashEntry::zVal, and IdxHashEntry::zVal2.
Referenced by expertFinish().
                                                          {
  int rc;
  IdxHashEntry *pEntry;
  /* Do trigger processing to collect any extra IdxScan structures */
  rc = idxProcessTriggers(p, pzErr);
  /* Create candidate indexes within the in-memory database file */
  if(rc==SQLITE_OK){
    rc = idxCreateCandidates(p);
  }
  /* Generate the stat1 data */
  if(rc==SQLITE_OK){
    rc = idxPopulateStat1(p, pzErr);
  }
  /* Formulate the EXPERT_REPORT_CANDIDATES text */
  for(pEntry=p->hIdx.pFirst; pEntry; pEntry=pEntry->pNext){
    p->zCandidates = idxAppendText(&rc, p->zCandidates,
        "%s;%s%s\n", pEntry->zVal,
        pEntry->zVal2 ? " -- stat1: " : "", pEntry->zVal2
    );
  }
  /* Figure out which of the candidate indexes are preferred by the query
  ** planner and report the results to the user. */
  if(rc==SQLITE_OK){
    rc = idxFindIndexes(p, pzErr);
  }
  if(rc==SQLITE_OK){
    p->bRun = 1;
  }
  return rc;
}
sqlite3_expert_config()
int sqlite3_expert_config (sqlite3expert * p, int op, ...)
Definition at line 8500 of file shell.c.
References EXPERT_CONFIG_SAMPLE, sqlite3expert::iSample, SQLITE_NOTFOUND, and SQLITE_OK.
Referenced by expertDotCommand().
                                                        {
  int rc = SQLITE_OK;
  va_list ap;
  va_start(ap, op);
  switch(op){
    case EXPERT_CONFIG_SAMPLE: {
      int iVal = va_arg(ap, int);
      if(iVal<0) iVal = 0;
      if(iVal>100) iVal = 100;
      p->iSample = iVal;
      break;
    }
    default:
      rc = SQLITE_NOTFOUND;
      break;
  }
  va_end(ap);
  return rc;
}
sqlite3_expert_count()
int sqlite3_expert_count (sqlite3expert * p)
Definition at line 8610 of file shell.c.
References IdxStatement::iId, and sqlite3expert::pStatement.
Referenced by expertFinish().
                                          {
  int nRet = 0;
  if(p->pStatement) nRet = p->pStatement->iId+1;
  return nRet;
}
sqlite3_expert_destroy()
void sqlite3_expert_destroy (sqlite3expert * p)
Definition at line 8645 of file shell.c.
References sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, sqlite3_index_info::aOrderBy, sqlite3_index_info::sqlite3_index_constraint_usage::argvIndex, sqlite3expert::dbm, sqlite3expert::dbv, sqlite3_index_info::sqlite3_index_orderby::desc, sqlite3_index_info::estimatedCost, sqlite3_index_info::estimatedRows, eType, sqlite3expert::hIdx, sqlite3_index_info::sqlite3_index_orderby::iColumn, idxHashClear(), sqlite3_index_info::idxNum, idxScanFree(), idxStatementFree(), idxTableFree(), idxWriteFree(), sqlite3_index_info::nConstraint, sqlite3_index_info::nOrderBy, sqlite3_index_info::sqlite3_index_constraint_usage::omit, sqlite3_index_info::orderByConsumed, sqlite3expert::pScan, sqlite3expert::pStatement, sqlite3expert::pTable, sqlite3_vtab_cursor::pVtab, sqlite3expert::pWrite, sqlite3_bind_int64, sqlite3_bind_text, sqlite3_close, sqlite3_column_blob, sqlite3_column_bytes, sqlite3_column_int, sqlite3_create_module, sqlite3_declare_vtab, sqlite3_errmsg, sqlite3_finalize, sqlite3_free, sqlite3_malloc64, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_reset, sqlite3_result_blob, sqlite3_result_double, sqlite3_result_int, sqlite3_result_int64, sqlite3_result_null, sqlite3_result_text, sqlite3_step, sqlite3_value_int, sqlite3_value_text, SQLITE_CONSTRAINT, SQLITE_EXTENSION_INIT1, SQLITE_EXTENSION_INIT2, SQLITE_INDEX_CONSTRAINT_EQ, SQLITE_NOMEM, SQLITE_OK, SQLITE_ROW, SQLITE_TRANSIENT, X, sqlite3expert::zCandidates, and zName.
Referenced by expertFinish(), and sqlite3_expert_new().
                                             {
  if(p){
    sqlite3_close(p->dbm);
    sqlite3_close(p->dbv);
    idxScanFree(p->pScan, 0);
    idxStatementFree(p->pStatement, 0);
    idxTableFree(p->pTable);
    idxWriteFree(p->pWrite);
    idxHashClear(&p->hIdx);
    sqlite3_free(p->zCandidates);
    sqlite3_free(p);
  }
}
sqlite3_expert_new()
 sqlite3expert * sqlite3_expert_new (sqlite3 * db, char ** pzErr)
Definition at line 8439 of file shell.c.
References sqlite3expert::db, sqlite3expert::dbm, sqlite3expert::dbv, idxAuthCallback(), idxCreateVtabSchema(), idxFinalize(), idxMalloc(), idxPrintfPrepareStmt(), sqlite3expert::iSample, sqlite3_column_text, sqlite3_db_config, sqlite3_exec, sqlite3_expert_destroy(), sqlite3_open, sqlite3_set_authorizer, sqlite3_step, SQLITE_DBCONFIG_TRIGGER_EQP, SQLITE_OK, and SQLITE_ROW.
Referenced by expertDotCommand().
                                                               {
  int rc = SQLITE_OK;
  sqlite3expert *pNew;
  pNew = (sqlite3expert*)idxMalloc(&rc, sizeof(sqlite3expert));
  /* Open two in-memory databases to work with. The "vtab database" (dbv)
  ** will contain a virtual table corresponding to each real table in
  ** the user database schema, and a copy of each view. It is used to
  ** collect information regarding the WHERE, ORDER BY and other clauses
  ** of the user's query.
  */
  if(rc==SQLITE_OK){
    pNew->db = db;
    pNew->iSample = 100;
    rc = sqlite3_open(":memory:", &pNew->dbv);
  }
  if(rc==SQLITE_OK){
    rc = sqlite3_open(":memory:", &pNew->dbm);
    if(rc==SQLITE_OK){
      sqlite3_db_config(pNew->dbm, SQLITE_DBCONFIG_TRIGGER_EQP, 1, (int*)0);
    }
  }
  
  /* Copy the entire schema of database [db] into [dbm]. */
  if(rc==SQLITE_OK){
    sqlite3_stmt *pSql;
    rc = idxPrintfPrepareStmt(pNew->db, &pSql, pzErrmsg,
        "SELECT sql FROM sqlite_master WHERE name NOT LIKE 'sqlite_%%'"
        " AND sql NOT LIKE 'CREATE VIRTUAL %%'"
    );
    while(rc==SQLITE_OK && SQLITE_ROW==sqlite3_step(pSql)){
      const char *zSql = (const char*)sqlite3_column_text(pSql, 0);
      rc = sqlite3_exec(pNew->dbm, zSql, 0, 0, pzErrmsg);
    }
    idxFinalize(&rc, pSql);
  }
  /* Create the vtab schema */
  if(rc==SQLITE_OK){
    rc = idxCreateVtabSchema(pNew, pzErrmsg);
  }
  /* Register the auth callback with dbv */
  if(rc==SQLITE_OK){
    sqlite3_set_authorizer(pNew->dbv, idxAuthCallback, (void*)pNew);
  }
  /* If an error has occurred, free the new object and reutrn NULL. Otherwise,
  ** return the new sqlite3expert handle. */
  if(rc!=SQLITE_OK){
    sqlite3_expert_destroy(pNew);
    pNew = 0;
  }
  return pNew;
}
sqlite3_expert_report()
const char * sqlite3_expert_report (sqlite3expert * p, int iStmt, int eReport)
Definition at line 8619 of file shell.c.
References sqlite3expert::bRun, EXPERT_REPORT_CANDIDATES, EXPERT_REPORT_INDEXES, EXPERT_REPORT_PLAN, EXPERT_REPORT_SQL, IdxStatement::iId, IdxStatement::pNext, sqlite3expert::pStatement, sqlite3expert::zCandidates, IdxStatement::zEQP, IdxStatement::zIdx, and IdxStatement::zSql.
Referenced by expertFinish().
                                                                           {
  const char *zRet = 0;
  IdxStatement *pStmt;
  if(p->bRun==0) return 0;
  for(pStmt=p->pStatement; pStmt && pStmt->iId!=iStmt; pStmt=pStmt->pNext);
  switch(eReport){
    case EXPERT_REPORT_SQL:
      if(pStmt) zRet = pStmt->zSql;
      break;
    case EXPERT_REPORT_INDEXES:
      if(pStmt) zRet = pStmt->zIdx;
      break;
    case EXPERT_REPORT_PLAN:
      if(pStmt) zRet = pStmt->zEQP;
      break;
    case EXPERT_REPORT_CANDIDATES:
      zRet = p->zCandidates;
      break;
  }
  return zRet;
}
sqlite3_expert_sql()
int sqlite3_expert_sql (sqlite3expert * p, const char * zSql, char ** pzErr)
Definition at line 8524 of file shell.c.
References sqlite3expert::bRun, sqlite3expert::dbv, idxDatabaseError(), idxMalloc(), idxScanFree(), idxStatementFree(), IdxStatement::iId, IdxStatement::pNext, sqlite3expert::pScan, sqlite3expert::pStatement, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_sql, SQLITE_MISUSE, SQLITE_OK, STRLEN, and IdxStatement::zSql.
Referenced by expertHandleSQL().
 {
  IdxScan *pScanOrig = p->pScan;
  IdxStatement *pStmtOrig = p->pStatement;
  int rc = SQLITE_OK;
  const char *zStmt = zSql;
  if(p->bRun) return SQLITE_MISUSE;
  while(rc==SQLITE_OK && zStmt && zStmt[0]){
    sqlite3_stmt *pStmt = 0;
    rc = sqlite3_prepare_v2(p->dbv, zStmt, -1, &pStmt, &zStmt);
    if(rc==SQLITE_OK){
      if(pStmt){
        IdxStatement *pNew;
        const char *z = sqlite3_sql(pStmt);
        int n = STRLEN(z);
        pNew = (IdxStatement*)idxMalloc(&rc, sizeof(IdxStatement) + n+1);
        if(rc==SQLITE_OK){
          pNew->zSql = (char*)&pNew[1];
          memcpy(pNew->zSql, z, n+1);
          pNew->pNext = p->pStatement;
          if(p->pStatement) pNew->iId = p->pStatement->iId+1;
          p->pStatement = pNew;
        }
        sqlite3_finalize(pStmt);
      }
    }else{
      idxDatabaseError(p->dbv, pzErr);
    }
  }
  if(rc!=SQLITE_OK){
    idxScanFree(p->pScan, pScanOrig);
    idxStatementFree(p->pStatement, pStmtOrig);
    p->pScan = pScanOrig;
    p->pStatement = pStmtOrig;
  }
  return rc;
}
sqlite3_fileio_init()
int sqlite3_fileio_init (sqlite3 * db, char ** pzErrMsg, const sqlite3_api_routines * pApi)
Definition at line 3006 of file shell.c.
References fsdirRegister(), lsModeFunc(), readfileFunc(), sqlite3_create_function, SQLITE_DIRECTONLY, SQLITE_EXTENSION_INIT1, SQLITE_EXTENSION_INIT2, SQLITE_OK, SQLITE_UTF8, and writefileFunc().
Referenced by open_db(), and shellReset().
 {
  int rc = SQLITE_OK;
  SQLITE_EXTENSION_INIT2(pApi);
  (void)pzErrMsg; /* Unused parameter */
  rc = sqlite3_create_function(db, "readfile", 1,
                               SQLITE_UTF8|SQLITE_DIRECTONLY, 0,
                               readfileFunc, 0, 0);
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(db, "writefile", -1,
                                 SQLITE_UTF8|SQLITE_DIRECTONLY, 0,
                                 writefileFunc, 0, 0);
  }
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(db, "lsmode", 1, SQLITE_UTF8, 0,
                                 lsModeFunc, 0, 0);
  }
  if(rc==SQLITE_OK){
    rc = fsdirRegister(db);
  }
  return rc;
}
sqlite3_shathree_init()
int sqlite3_shathree_init (sqlite3 * db, char ** pzErrMsg, const sqlite3_api_routines * pApi)
Definition at line 2002 of file shell.c.
References sha3Func(), sha3QueryFunc(), sqlite3_create_function, SQLITE_DETERMINISTIC, SQLITE_DIRECTONLY, SQLITE_EXTENSION_INIT1, SQLITE_EXTENSION_INIT2, SQLITE_INNOCUOUS, SQLITE_OK, and SQLITE_UTF8.
Referenced by open_db().
 {
  int rc = SQLITE_OK;
  SQLITE_EXTENSION_INIT2(pApi);
  (void)pzErrMsg; /* Unused parameter */
  rc = sqlite3_create_function(db, "sha3", 1,
                      SQLITE_UTF8 | SQLITE_INNOCUOUS | SQLITE_DETERMINISTIC,
                      0, sha3Func, 0, 0);
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(db, "sha3", 2,
                      SQLITE_UTF8 | SQLITE_INNOCUOUS | SQLITE_DETERMINISTIC,
                      0, sha3Func, 0, 0);
  }
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(db, "sha3_query", 1,
                      SQLITE_UTF8 | SQLITE_DIRECTONLY,
                      0, sha3QueryFunc, 0, 0);
  }
  if(rc==SQLITE_OK){
    rc = sqlite3_create_function(db, "sha3_query", 2,
                      SQLITE_UTF8 | SQLITE_DIRECTONLY,
                      0, sha3QueryFunc, 0, 0);
  }
  return rc;
}
sqlite3CompletionVtabInit()
int sqlite3CompletionVtabInit (sqlite3 * db)
Definition at line 3511 of file shell.c.
References sqlite3_create_module, and SQLITE_OK.
Referenced by sqlite3_completion_init().
                                          {
  int rc = SQLITE_OK;
#ifndef SQLITE_OMIT_VIRTUALTABLE
  rc = sqlite3_create_module(db, "completion", &completionModule, 0);
#endif
  return rc;
}
sqlite3MemTraceActivate()
int sqlite3MemTraceActivate (FILE * out)
Definition at line 4190 of file shell.c.
References sqlite3_config(), SQLITE_CONFIG_GETMALLOC, SQLITE_CONFIG_MALLOC, SQLITE_OK, and sqlite3_mem_methods::xMalloc.
Referenced by main().
                                      {
  int rc = SQLITE_OK;
  if(memtraceBase.xMalloc==0){
    rc = sqlite3_config(SQLITE_CONFIG_GETMALLOC, &memtraceBase);
    if(rc==SQLITE_OK){
      rc = sqlite3_config(SQLITE_CONFIG_MALLOC, &ersaztMethods);
    }
  }
  memtraceOut = out;
  return rc;
}
sqlite3MemTraceDeactivate()
int sqlite3MemTraceDeactivate (void)
Definition at line 4203 of file shell.c.
References sqlite3_index_info::aConstraint, sqlite3_index_info::aConstraintUsage, ALWAYS, sqlite3_index_info::sqlite3_index_constraint_usage::argvIndex, main3::cur, list_test::E, sqlite3_index_info::estimatedCost, sqlite3_index_info::idxNum, sqlite3_vfs::iVersion, MIN, sqlite3_index_info::nConstraint, nName, sqlite3_index_info::sqlite3_index_constraint_usage::omit, sqlite3_vtab_cursor::pVtab, sqlite3_aggregate_context, sqlite3_config(), sqlite3_create_function, sqlite3_create_module, sqlite3_declare_vtab, sqlite3_free, sqlite3_malloc, sqlite3_malloc64, sqlite3_mprintf, sqlite3_overload_function, sqlite3_realloc64, sqlite3_result_blob, sqlite3_result_error, sqlite3_result_error_code, sqlite3_result_error_nomem, sqlite3_result_int, sqlite3_result_int64, sqlite3_result_text, sqlite3_result_value, sqlite3_stricmp, sqlite3_user_data, sqlite3_value_blob, sqlite3_value_bytes, sqlite3_value_int, sqlite3_value_int64, sqlite3_value_text, sqlite3_value_type, sqlite3_vfs_find, sqlite3_vmprintf, sqlite3_vtab_config, sqlite3_vtab_nochange, sqlite3_vtab_on_conflict, SQLITE_BLOB, SQLITE_CONFIG_MALLOC, SQLITE_CONSTRAINT, SQLITE_ERROR, SQLITE_EXTENSION_INIT1, SQLITE_EXTENSION_INIT2, SQLITE_IGNORE, SQLITE_INDEX_CONSTRAINT_EQ, SQLITE_INNOCUOUS, SQLITE_NOMEM, SQLITE_NULL, SQLITE_OK, SQLITE_REPLACE, SQLITE_STATIC, SQLITE_TRANSIENT, SQLITE_UTF8, SQLITE_VTAB_DIRECTONLY, sqlite3_vfs::xCurrentTime, sqlite3_vfs::xCurrentTimeInt64, sqlite3_mem_methods::xMalloc, and zName.
                                   {
  int rc = SQLITE_OK;
  if(memtraceBase.xMalloc!=0){
    rc = sqlite3_config(SQLITE_CONFIG_MALLOC, &memtraceBase);
    if(rc==SQLITE_OK){
      memset(&memtraceBase, 0, sizeof(memtraceBase));
    }
  }
  memtraceOut = 0;
  return rc;
}
str_in_array()
static int str_in_array (const char * zStr, const char ** azArray) [static]
Definition at line 11180 of file shell.c.
Referenced by explain_data_prepare().
                                                               {
  int i;
  for(i=0; azArray[i]; i++){
    if(0==strcmp(zStr, azArray[i])) return 1;
  }
  return 0;
}
strlen30()
static int strlen30 (const char * z) [static]
Definition at line 557 of file shell.c.
Referenced by appendText(), close_db(), do_meta_command(), eqp_append(), eqp_render_level(), expertDotCommand(), find_home_dir(), lintDotCommand(), lintFkeyIndexes(), local_getline(), main(), output_csv(), process_input(), run_schema_dump_query(), save_err_msg(), set_table_name(), shell_callback(), shellAddSchemaName(), shellReset(), sql_trace_callback(), and tryToCloneData().
                                  {
  const char *z2 = z;
  while(*z2){ z2++; }
  return 0x3fffffff & (int)(z2 - z);
}
strlenChar()
static int strlenChar (const char * z) [static]
Definition at line 567 of file shell.c.
Referenced by shell_callback().
                                    {
  int n = 0;
  while(*z){
    if((0xc0&*(z++))!=0x80) n++;
  }
  return n;
}
tableColumnList()
static char** tableColumnList (ShellState * p, const char * zTab) [static]
Definition at line 11768 of file shell.c.
References ShellState::db, freeColumnList(), shell_out_of_memory(), ShellHasFlag, SHFLG_PreserveRowid, sqlite3_column_int, sqlite3_column_text, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_realloc, sqlite3_step, sqlite3_stricmp, sqlite3_table_column_metadata, SQLITE_OK, and SQLITE_ROW.
Referenced by dump_callback().
                                                              {
  char **azCol = 0;
  sqlite3_stmt *pStmt;
  char *zSql;
  int nCol = 0;
  int nAlloc = 0;
  int nPK = 0; /* Number of PRIMARY KEY columns seen */
  int isIPK = 0; /* True if one PRIMARY KEY column of type INTEGER */
  int preserveRowid = ShellHasFlag(p, SHFLG_PreserveRowid);
  int rc;
  zSql = sqlite3_mprintf("PRAGMA table_info=%Q", zTab);
  rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
  sqlite3_free(zSql);
  if(rc) return 0;
  while(sqlite3_step(pStmt)==SQLITE_ROW){
    if(nCol>=nAlloc-2){
      nAlloc = nAlloc*2 + nCol + 10;
      azCol = sqlite3_realloc(azCol, nAlloc*sizeof(azCol[0]));
      if(azCol==0) shell_out_of_memory();
    }
    azCol[++nCol] = sqlite3_mprintf("%s", sqlite3_column_text(pStmt, 1));
    if(sqlite3_column_int(pStmt, 5)){
      nPK++;
      if(nPK==1
       && sqlite3_stricmp((const char*)sqlite3_column_text(pStmt,2),
                          "INTEGER")==0
      ){
        isIPK = 1;
      }else{
        isIPK = 0;
      }
    }
  }
  sqlite3_finalize(pStmt);
  if(azCol==0) return 0;
  azCol[0] = 0;
  azCol[nCol+1] = 0;
  /* The decision of whether or not a rowid really needs to be preserved
  ** is tricky. We never need to preserve a rowid for a WITHOUT ROWID table
  ** or a table with an INTEGER PRIMARY KEY. We are unable to preserve
  ** rowids on tables where the rowid is inaccessible because there are other
  ** columns in the table named "rowid", "_rowid_", and "oid".
  */
  if(preserveRowid && isIPK){
    /* If a single PRIMARY KEY column with type INTEGER was seen, then it
    ** might be an alise for the ROWID. But it might also be a WITHOUT ROWID
    ** table or a INTEGER PRIMARY KEY DESC column, neither of which are
    ** ROWID aliases. To distinguish these cases, check to see if
    ** there is a "pk" entry in "PRAGMA index_list". There will be
    ** no "pk" index if the PRIMARY KEY really is an alias for the ROWID.
    */
    zSql = sqlite3_mprintf("SELECT 1 FROM pragma_index_list(%Q)"
                           " WHERE origin='pk'", zTab);
    rc = sqlite3_prepare_v2(p->db, zSql, -1, &pStmt, 0);
    sqlite3_free(zSql);
    if(rc){
      freeColumnList(azCol);
      return 0;
    }
    rc = sqlite3_step(pStmt);
    sqlite3_finalize(pStmt);
    preserveRowid = rc==SQLITE_ROW;
  }
  if(preserveRowid){
    /* Only preserve the rowid if we can find a name to use for the
    ** rowid */
    static char *azRowid[] = { "rowid", "_rowid_", "oid" };
    int i, j;
    for(j=0; j<3; j++){
      for(i=1; i<=nCol; i++){
        if(sqlite3_stricmp(azRowid[j],azCol[i])==0) break;
      }
      if(i>nCol){
        /* At this point, we know that azRowid[j] is not the name of any
        ** ordinary column in the table. Verify that azRowid[j] is a valid
        ** name for the rowid before adding it to azCol[0]. WITHOUT ROWID
        ** tables will fail this last check */
        rc = sqlite3_table_column_metadata(p->db,0,zTab,azRowid[j],0,0,0,0,0);
        if(rc==SQLITE_OK) azCol[0] = azRowid[j];
        break;
      }
    }
  }
  return azCol;
}
test_breakpoint()
static void test_breakpoint (void) [static]
Definition at line 13060 of file shell.c.
Referenced by do_meta_command().
                                 {
  static int nCall = 0;
  nCall++;
}
testcase_glob()
static int testcase_glob (const char * zGlob, const char * z) [static]
Definition at line 13627 of file shell.c.
References IsDigit, and IsSpace.
Referenced by do_meta_command().
                                                          {
  int c, c2;
  int invert;
  int seen;
  while((c = (*(zGlob++)))!=0){
    if(IsSpace(c)){
      if(!IsSpace(*z)) return 0;
      while(IsSpace(*zGlob)) zGlob++;
      while(IsSpace(*z)) z++;
    }else if(c=='*'){
      while((c=(*(zGlob++))) == '*' || c=='?'){
        if(c=='?' && (*(z++))==0) return 0;
      }
      if(c==0){
        return 1;
      }else if(c=='['){
        while(*z && testcase_glob(zGlob-1,z)==0){
          z++;
        }
        return (*z)!=0;
      }
      while((c2 = (*(z++)))!=0){
        while(c2!=c){
          c2 = *(z++);
          if(c2==0) return 0;
        }
        if(testcase_glob(zGlob,z)) return 1;
      }
      return 0;
    }else if(c=='?'){
      if((*(z++))==0) return 0;
    }else if(c=='['){
      int prior_c = 0;
      seen = 0;
      invert = 0;
      c = *(z++);
      if(c==0) return 0;
      c2 = *(zGlob++);
      if(c2=='^'){
        invert = 1;
        c2 = *(zGlob++);
      }
      if(c2==']'){
        if(c==']') seen = 1;
        c2 = *(zGlob++);
      }
      while(c2 && c2!=']'){
        if(c2=='-' && zGlob[0]!=']' && zGlob[0]!=0 && prior_c>0){
          c2 = *(zGlob++);
          if(c>=prior_c && c<=c2) seen = 1;
          prior_c = 0;
        }else{
          if(c==c2){
            seen = 1;
          }
          prior_c = c2;
        }
        c2 = *(zGlob++);
      }
      if(c2==0 || (seen ^ invert)==0) return 0;
    }else if(c=='#'){
      if((z[0]=='-' || z[0]=='+') && IsDigit(z[1])) z++;
      if(!IsDigit(z[0])) return 0;
      z++;
      while(IsDigit(z[0])){ z++; }
    }else{
      if(c!=(*(z++))) return 0;
    }
  }
  while(IsSpace(*z)){ z++; }
  return *z==0;
}
timeDiff()
static double timeDiff (struct timeval * pStart, struct timeval * pEnd) [static]
Definition at line 270 of file shell.c.
Referenced by endTimer().
                                                                    {
  return (pEnd->tv_usec - pStart->tv_usec)*0.000001 +
         (double)(pEnd->tv_sec - pStart->tv_sec);
}
timeOfDay()
static sqlite3_int64 timeOfDay (void) [static]
Definition at line 228 of file shell.c.
References sqlite3_vfs::iVersion, sqlite3_vfs_find, sqlite3_vfs::xCurrentTime, and sqlite3_vfs::xCurrentTimeInt64.
Referenced by beginTimer(), and endTimer().
                                    {
  static sqlite3_vfs *clockVfs = 0;
  sqlite3_int64 t;
  if(clockVfs==0) clockVfs = sqlite3_vfs_find(0);
  if(clockVfs->iVersion>=2 && clockVfs->xCurrentTimeInt64!=0){
    clockVfs->xCurrentTimeInt64(clockVfs, &t);
  }else{
    double r;
    clockVfs->xCurrentTime(clockVfs, &r);
    t = (sqlite3_int64)(r*86400000.0);
  }
  return t;
}
toggleSelectOrder()
static void toggleSelectOrder (sqlite3 * db) [static]
Definition at line 11859 of file shell.c.
References sqlite3_column_int, sqlite3_exec, sqlite3_finalize, sqlite3_prepare_v2, sqlite3_snprintf, sqlite3_step, and SQLITE_ROW.
Referenced by dump_callback().
                                          {
  sqlite3_stmt *pStmt = 0;
  int iSetting = 0;
  char zStmt[100];
  sqlite3_prepare_v2(db, "PRAGMA reverse_unordered_selects", -1, &pStmt, 0);
  if(sqlite3_step(pStmt)==SQLITE_ROW){
    iSetting = sqlite3_column_int(pStmt, 0);
  }
  sqlite3_finalize(pStmt);
  sqlite3_snprintf(sizeof(zStmt), zStmt,
       "PRAGMA reverse_unordered_selects(%d)", !iSetting);
  sqlite3_exec(db, zStmt, 0, 0, 0);
}
tryToClone()
static void tryToClone (ShellState * p, const char * zNewDb) [static]
Definition at line 13407 of file shell.c.
References close_db(), ShellState::db, sqlite3_errmsg, sqlite3_exec, sqlite3_open, tryToCloneData(), tryToCloneSchema(), and utf8_printf.
Referenced by do_meta_command().
                                                         {
  int rc;
  sqlite3 *newDb = 0;
  if(access(zNewDb,0)==0){
    utf8_printf(stderr, "File \"%s\" already exists.\n", zNewDb);
    return;
  }
  rc = sqlite3_open(zNewDb, &newDb);
  if(rc){
    utf8_printf(stderr, "Cannot create output database: %s\n",
            sqlite3_errmsg(newDb));
  }else{
    sqlite3_exec(p->db, "PRAGMA writable_schema=ON;", 0, 0, 0);
    sqlite3_exec(newDb, "BEGIN EXCLUSIVE;", 0, 0, 0);
    tryToCloneSchema(p, newDb, "type='table'", tryToCloneData);
    tryToCloneSchema(p, newDb, "type!='table'", 0);
    sqlite3_exec(newDb, "COMMIT;", 0, 0, 0);
    sqlite3_exec(p->db, "PRAGMA writable_schema=OFF;", 0, 0, 0);
  }
  close_db(newDb);
}
tryToCloneData()
static void tryToCloneData (ShellState * p, sqlite3 * newDb, const char * zTable) [static]
Definition at line 13222 of file shell.c.
References ShellState::db, shell_out_of_memory(), sqlite3_bind_blob, sqlite3_bind_double, sqlite3_bind_int64, sqlite3_bind_null, sqlite3_bind_text, sqlite3_column_blob, sqlite3_column_bytes, sqlite3_column_count, sqlite3_column_double, sqlite3_column_int64, sqlite3_column_text, sqlite3_column_type, sqlite3_errmsg, sqlite3_extended_errcode, sqlite3_finalize, sqlite3_free, sqlite3_malloc64, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_reset, sqlite3_snprintf, sqlite3_step, SQLITE_BLOB, SQLITE_DONE, SQLITE_FLOAT, SQLITE_INTEGER, SQLITE_NULL, SQLITE_OK, SQLITE_ROW, SQLITE_STATIC, SQLITE_TEXT, strlen30(), and utf8_printf.
Referenced by tryToClone().
 {
  sqlite3_stmt *pQuery = 0;
  sqlite3_stmt *pInsert = 0;
  char *zQuery = 0;
  char *zInsert = 0;
  int rc;
  int i, j, n;
  int nTable = strlen30(zTable);
  int k = 0;
  int cnt = 0;
  const int spinRate = 10000;
  zQuery = sqlite3_mprintf("SELECT * FROM \"%w\"", zTable);
  rc = sqlite3_prepare_v2(p->db, zQuery, -1, &pQuery, 0);
  if(rc){
    utf8_printf(stderr, "Error %d: %s on [%s]\n",
            sqlite3_extended_errcode(p->db), sqlite3_errmsg(p->db),
            zQuery);
    goto end_data_xfer;
  }
  n = sqlite3_column_count(pQuery);
  zInsert = sqlite3_malloc64(200 + nTable + n*3);
  if(zInsert==0) shell_out_of_memory();
  sqlite3_snprintf(200+nTable,zInsert,
                   "INSERT OR IGNORE INTO \"%s\" VALUES(?", zTable);
  i = strlen30(zInsert);
  for(j=1; j<n; j++){
    memcpy(zInsert+i, ",?", 2);
    i += 2;
  }
  memcpy(zInsert+i, ");", 3);
  rc = sqlite3_prepare_v2(newDb, zInsert, -1, &pInsert, 0);
  if(rc){
    utf8_printf(stderr, "Error %d: %s on [%s]\n",
            sqlite3_extended_errcode(newDb), sqlite3_errmsg(newDb),
            zQuery);
    goto end_data_xfer;
  }
  for(k=0; k<2; k++){
    while((rc = sqlite3_step(pQuery))==SQLITE_ROW){
      for(i=0; i<n; i++){
        switch(sqlite3_column_type(pQuery, i)){
          case SQLITE_NULL: {
            sqlite3_bind_null(pInsert, i+1);
            break;
          }
          case SQLITE_INTEGER: {
            sqlite3_bind_int64(pInsert, i+1, sqlite3_column_int64(pQuery,i));
            break;
          }
          case SQLITE_FLOAT: {
            sqlite3_bind_double(pInsert, i+1, sqlite3_column_double(pQuery,i));
            break;
          }
          case SQLITE_TEXT: {
            sqlite3_bind_text(pInsert, i+1,
                             (const char*)sqlite3_column_text(pQuery,i),
                             -1, SQLITE_STATIC);
            break;
          }
          case SQLITE_BLOB: {
            sqlite3_bind_blob(pInsert, i+1, sqlite3_column_blob(pQuery,i),
                                            sqlite3_column_bytes(pQuery,i),
                                            SQLITE_STATIC);
            break;
          }
        }
      } /* End for */
      rc = sqlite3_step(pInsert);
      if(rc!=SQLITE_OK && rc!=SQLITE_ROW && rc!=SQLITE_DONE){
        utf8_printf(stderr, "Error %d: %s\n", sqlite3_extended_errcode(newDb),
                        sqlite3_errmsg(newDb));
      }
      sqlite3_reset(pInsert);
      cnt++;
      if((cnt%spinRate)==0){
        printf("%c\b", "|/-\\"[(cnt/spinRate)%4]);
        fflush(stdout);
      }
    } /* End while */
    if(rc==SQLITE_DONE) break;
    sqlite3_finalize(pQuery);
    sqlite3_free(zQuery);
    zQuery = sqlite3_mprintf("SELECT * FROM \"%w\" ORDER BY rowid DESC;",
                             zTable);
    rc = sqlite3_prepare_v2(p->db, zQuery, -1, &pQuery, 0);
    if(rc){
      utf8_printf(stderr, "Warning: cannot step \"%s\" backwards", zTable);
      break;
    }
  } /* End for(k=0...) */
end_data_xfer:
  sqlite3_finalize(pQuery);
  sqlite3_finalize(pInsert);
  sqlite3_free(zQuery);
  sqlite3_free(zInsert);
}
tryToCloneSchema()
static void tryToCloneSchema (ShellState * p, sqlite3 * newDb, const char * zWhere, void(*)(ShellState *, sqlite3 *, const char *) xForEach) [static]
Definition at line 13332 of file shell.c.
References ShellState::db, sqlite3_column_text, sqlite3_errmsg, sqlite3_exec, sqlite3_extended_errcode, sqlite3_finalize, sqlite3_free, sqlite3_mprintf, sqlite3_prepare_v2, sqlite3_step, SQLITE_DONE, SQLITE_ROW, utf8_printf, and zName.
Referenced by tryToClone().
 {
  sqlite3_stmt *pQuery = 0;
  char *zQuery = 0;
  int rc;
  const unsigned char *zName;
  const unsigned char *zSql;
  char *zErrMsg = 0;
  zQuery = sqlite3_mprintf("SELECT name, sql FROM sqlite_master"
                           " WHERE %s", zWhere);
  rc = sqlite3_prepare_v2(p->db, zQuery, -1, &pQuery, 0);
  if(rc){
    utf8_printf(stderr, "Error: (%d) %s on [%s]\n",
                    sqlite3_extended_errcode(p->db), sqlite3_errmsg(p->db),
                    zQuery);
    goto end_schema_xfer;
  }
  while((rc = sqlite3_step(pQuery))==SQLITE_ROW){
    zName = sqlite3_column_text(pQuery, 0);
    zSql = sqlite3_column_text(pQuery, 1);
    printf("%s... ", zName); fflush(stdout);
    sqlite3_exec(newDb, (const char*)zSql, 0, 0, &zErrMsg);
    if(zErrMsg){
      utf8_printf(stderr, "Error: %s\nSQL: [%s]\n", zErrMsg, zSql);
      sqlite3_free(zErrMsg);
      zErrMsg = 0;
    }
    if(xForEach){
      xForEach(p, newDb, (const char*)zName);
    }
    printf("done\n");
  }
  if(rc!=SQLITE_DONE){
    sqlite3_finalize(pQuery);
    sqlite3_free(zQuery);
    zQuery = sqlite3_mprintf("SELECT name, sql FROM sqlite_master"
                             " WHERE %s ORDER BY rowid DESC", zWhere);
    rc = sqlite3_prepare_v2(p->db, zQuery, -1, &pQuery, 0);
    if(rc){
      utf8_printf(stderr, "Error: (%d) %s on [%s]\n",
                      sqlite3_extended_errcode(p->db), sqlite3_errmsg(p->db),
                      zQuery);
      goto end_schema_xfer;
    }
    while((rc = sqlite3_step(pQuery))==SQLITE_ROW){
      zName = sqlite3_column_text(pQuery, 0);
      zSql = sqlite3_column_text(pQuery, 1);
      printf("%s... ", zName); fflush(stdout);
      sqlite3_exec(newDb, (const char*)zSql, 0, 0, &zErrMsg);
      if(zErrMsg){
        utf8_printf(stderr, "Error: %s\nSQL: [%s]\n", zErrMsg, zSql);
        sqlite3_free(zErrMsg);
        zErrMsg = 0;
      }
      if(xForEach){
        xForEach(p, newDb, (const char*)zName);
      }
      printf("done\n");
    }
  }
end_schema_xfer:
  sqlite3_finalize(pQuery);
  sqlite3_free(zQuery);
}
unused_string()
static const char* unused_string (const char * z, const char * zA, const char * zB, char * zBuf) [static]
Definition at line 9932 of file shell.c.
References sqlite3_snprintf.
Referenced by output_quoted_escaped_string(), and shellEscapeCrnl().
 {
  unsigned i = 0;
  if(strstr(z, zA)==0) return zA;
  if(strstr(z, zB)==0) return zB;
  do{
    sqlite3_snprintf(20,zBuf,"(%s%u)", zA, i++);
  }while(strstr(z,zBuf)!=0);
  return zBuf;
}
usage()
static void usage (int showDetail) [static]
Definition at line 18580 of file shell.c.
References raw_printf, and utf8_printf.
Referenced by lintDotCommand(), and main().
                                 {
  utf8_printf(stderr,
      "Usage: %s [OPTIONS] FILENAME [SQL]\n"
      "FILENAME is the name of an SQLite database. A new database is created\n"
      "if the file does not previously exist.\n", Argv0);
  if(showDetail){
    utf8_printf(stderr, "OPTIONS include:\n%s", zOptions);
  }else{
    raw_printf(stderr, "Use the -help option for additional information\n");
  }
  exit(1);
}
utf8_width_print()
static void utf8_width_print (FILE * pOut, int w, const char * zUtf) [static]
Definition at line 501 of file shell.c.
References utf8_printf.
Referenced by shell_callback().
                                                                 {
  int i;
  int n;
  int aw = w<0 ? -w : w;
  char zBuf[1000];
  if(aw>(int)sizeof(zBuf)/3) aw = (int)sizeof(zBuf)/3;
  for(i=n=0; zUtf[i]; i++){
    if((zUtf[i]&0xc0)!=0x80){
      n++;
      if(n==aw){
        do{ i++; }while((zUtf[i]&0xc0)==0x80);
        break;
      }
    }
  }
  if(n>=aw){
    utf8_printf(pOut, "%.*s", i, zUtf);
  }else if(w<0){
    utf8_printf(pOut, "%*s%s", aw-n, "", zUtf);
  }else{
    utf8_printf(pOut, "%s%*s", zUtf, aw-n, "");
  }
}
verify_uninitialized()
static void verify_uninitialized (void) [static]
Definition at line 18597 of file shell.c.
References sqlite3_config(), SQLITE_MISUSE, and utf8_printf.
Referenced by main(), and main_init().
                                      {
  if(sqlite3_config(-1)==SQLITE_MISUSE){
    utf8_printf(stdout, "WARNING: attempt to configure SQLite after"
                        " initialization.\n");
  }
}
writeFile()
static int writeFile (sqlite3_context * pCtx, const char * zFile, sqlite3_value * pData, mode_t mode, sqlite3_int64 mtime) [static]
Definition at line 2375 of file shell.c.
References fileStat(), sqlite3_free, sqlite3_result_int64, sqlite3_value_blob, sqlite3_value_bytes, and sqlite3_value_text.
Referenced by writefileFunc().
 {
#if !defined(_WIN32) && !defined(WIN32)
  if(S_ISLNK(mode)){
    const char *zTo = (const char*)sqlite3_value_text(pData);
    if(symlink(zTo, zFile)<0) return 1;
  }else
#endif
  {
    if(S_ISDIR(mode)){
      if(mkdir(zFile, mode)){
        /* The mkdir() call to create the directory failed. This might not
        ** be an error though - if there is already a directory at the same
        ** path and either the permissions already match or can be changed
        ** to do so using chmod(), it is not an error. */
        struct stat sStat;
        if(errno!=EEXIST
         || 0!=fileStat(zFile, &sStat)
         || !S_ISDIR(sStat.st_mode)
         || ((sStat.st_mode&0777)!=(mode&0777) && 0!=chmod(zFile, mode&0777))
        ){
          return 1;
        }
      }
    }else{
      sqlite3_int64 nWrite = 0;
      const char *z;
      int rc = 0;
      FILE *out = fopen(zFile, "wb");
      if(out==0) return 1;
      z = (const char*)sqlite3_value_blob(pData);
      if(z){
        sqlite3_int64 n = fwrite(z, 1, sqlite3_value_bytes(pData), out);
        nWrite = sqlite3_value_bytes(pData);
        if(nWrite!=n){
          rc = 1;
        }
      }
      fclose(out);
      if(rc==0 && mode && chmod(zFile, mode & 0777)){
        rc = 1;
      }
      if(rc) return 2;
      sqlite3_result_int64(pCtx, nWrite);
    }
  }
  if(mtime>=0){
#if defined(_WIN32)
    /* Windows */
    FILETIME lastAccess;
    FILETIME lastWrite;
    SYSTEMTIME currentTime;
    LONGLONG intervals;
    HANDLE hFile;
    LPWSTR zUnicodeName;
    extern LPWSTR sqlite3_win32_utf8_to_unicode(const char*);
    GetSystemTime(&currentTime);
    SystemTimeToFileTime(&currentTime, &lastAccess);
    intervals = Int32x32To64(mtime, 10000000) + 116444736000000000;
    lastWrite.dwLowDateTime = (DWORD)intervals;
    lastWrite.dwHighDateTime = intervals >> 32;
    zUnicodeName = sqlite3_win32_utf8_to_unicode(zFile);
    if(zUnicodeName==0){
      return 1;
    }
    hFile = CreateFileW(
      zUnicodeName, FILE_WRITE_ATTRIBUTES, 0, NULL, OPEN_EXISTING,
      FILE_FLAG_BACKUP_SEMANTICS, NULL
    );
    sqlite3_free(zUnicodeName);
    if(hFile!=INVALID_HANDLE_VALUE){
      BOOL bResult = SetFileTime(hFile, NULL, &lastAccess, &lastWrite);
      CloseHandle(hFile);
      return !bResult;
    }else{
      return 1;
    }
#elif defined(AT_FDCWD) && 0 /* utimensat() is not universally available */
    /* Recent unix */
    struct timespec times[2];
    times[0].tv_nsec = times[1].tv_nsec = 0;
    times[0].tv_sec = time(0);
    times[1].tv_sec = mtime;
    if(utimensat(AT_FDCWD, zFile, times, AT_SYMLINK_NOFOLLOW)){
      return 1;
    }
#else
    /* Legacy unix */
    struct timeval times[2];
    times[0].tv_usec = times[1].tv_usec = 0;
    times[0].tv_sec = time(0);
    times[1].tv_sec = mtime;
    if(utimes(zFile, times)){
      return 1;
    }
#endif
  }
  return 0;
}
writefileFunc()
static void writefileFunc (sqlite3_context * context, int argc, sqlite3_value ** argv) [static]
Definition at line 2487 of file shell.c.
References ctxErrorMsg(), makeDirectory(), sqlite3_result_error, sqlite3_value_int, sqlite3_value_int64, sqlite3_value_text, SQLITE_OK, and writeFile().
Referenced by sqlite3_fileio_init().
 {
  const char *zFile;
  mode_t mode = 0;
  int res;
  sqlite3_int64 mtime = -1;
  if(argc<2 || argc>4){
    sqlite3_result_error(context,
        "wrong number of arguments to function writefile()", -1
    );
    return;
  }
  zFile = (const char*)sqlite3_value_text(argv[0]);
  if(zFile==0) return;
  if(argc>=3){
    mode = (mode_t)sqlite3_value_int(argv[2]);
  }
  if(argc==4){
    mtime = sqlite3_value_int64(argv[3]);
  }
  res = writeFile(context, zFile, argv[1], mode, mtime);
  if(res==1 && errno==ENOENT){
    if(makeDirectory(zFile)==SQLITE_OK){
      res = writeFile(context, zFile, argv[1], mode, mtime);
    }
  }
  if(argc>2 && res!=0){
    if(S_ISLNK(mode)){
      ctxErrorMsg(context, "failed to create symlink: %s", zFile);
    }else if(S_ISDIR(mode)){
      ctxErrorMsg(context, "failed to create directory: %s", zFile);
    }else{
      ctxErrorMsg(context, "failed to write file: %s", zFile);
    }
  }
}
wsToEol()
static int wsToEol (const char * z) [static]
Definition at line 10269 of file shell.c.
References IsSpace.
Referenced by shell_callback().
                                 {
  int i;
  for(i=0; z[i]; i++){
    if(z[i]=='\n') return 1;
    if(IsSpace(z[i])) continue;
    if(z[i]=='-' && z[i+1]=='-') return 1;
    return 0;
  }
  return 1;
}
Variable Documentation
apnd_io_methods
const sqlite3_io_methods apnd_io_methods [static]
Initial value:
= {
  3,
  apndClose,
  apndRead,
  apndWrite,
  apndTruncate,
  apndSync,
  apndFileSize,
  apndLock,
  apndUnlock,
  apndCheckReservedLock,
  apndFileControl,
  apndSectorSize,
  apndDeviceCharacteristics,
  apndShmMap,
  apndShmLock,
  apndShmBarrier,
  apndShmUnmap,
  apndFetch,
  apndUnfetch
}
Definition at line 3696 of file shell.c.
Referenced by apndOpen().
apnd_vfs
 sqlite3_vfs apnd_vfs [static]
Initial value:
= {
  3,
  0,
  1024,
  0,
  "apndvfs",
  0,
  apndOpen,
  apndDelete,
  apndAccess,
  apndFullPathname,
  apndDlOpen,
  apndDlError,
  apndDlSym,
  apndDlClose,
  apndRandomness,
  apndSleep,
  apndCurrentTime,
  apndGetLastError,
  apndCurrentTimeInt64,
  apndSetSystemCall,
  apndGetSystemCall,
  apndNextSystemCall
}
Definition at line 3671 of file shell.c.
apndDlSym
void(*)(void) apndDlSym(sqlite3_vfs *pVfs, void *p, const char *zSym) [static]
Definition at line 3660 of file shell.c.
Referenced by apndDlError().
Argv0
char* Argv0 [static]
Definition at line 422 of file shell.c.
azHelp
const char* azHelp[] [static]
Definition at line 12031 of file shell.c.
Referenced by showHelp().
bail_on_error
int bail_on_error = 0 [static]
Definition at line 391 of file shell.c.
completionModule
 sqlite3_module completionModule [static]
Initial value:
= {
  0,
  0,
  completionConnect,
  completionBestIndex,
  completionDisconnect,
  0,
  completionOpen,
  completionClose,
  completionFilter,
  completionNext,
  completionEof,
  completionColumn,
  completionRowid,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
}
Definition at line 3482 of file shell.c.
continuePrompt
char continuePrompt[20] [static]
Definition at line 429 of file shell.c.
Referenced by one_input_line().
enableTimer
int enableTimer = 0 [static]
Definition at line 225 of file shell.c.
ersaztMethods
 sqlite3_mem_methods ersaztMethods [static]
Initial value:
= {
  memtraceMalloc,
  memtraceFree,
  memtraceRealloc,
  memtraceSize,
  memtraceRoundup,
  memtraceInit,
  memtraceShutdown,
  0
}
Definition at line 4178 of file shell.c.
globalDb
 sqlite3* globalDb = 0 [static]
Definition at line 411 of file shell.c.
iBegin
 sqlite3_int64 iBegin [static]
Definition at line 257 of file shell.c.
mainPrompt
char mainPrompt[20] [static]
Definition at line 428 of file shell.c.
Referenced by one_input_line().
memtraceBase
 sqlite3_mem_methods memtraceBase [static]
Definition at line 4134 of file shell.c.
memtraceOut
FILE* memtraceOut [static]
Definition at line 4135 of file shell.c.
modeDescr
const char* modeDescr[] [static]
Initial value:
= {
  "line",
  "column",
  "list",
  "semi",
  "html",
  "insert",
  "quote",
  "tcl",
  "csv",
  "explain",
  "ascii",
  "prettyprint",
  "eqp"
}
Definition at line 9700 of file shell.c.
needCsvQuote
const char needCsvQuote[] [static]
Initial value:
= {
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
}
Definition at line 10118 of file shell.c.
sBegin
struct rusage sBegin [static]
Definition at line 256 of file shell.c.
Referenced by beginTimer(), and endTimer().
seenInterrupt
volatile int seenInterrupt = 0 [static]
Definition at line 416 of file shell.c.
stdin_is_interactive
int stdin_is_interactive = 1 [static]
Definition at line 397 of file shell.c.
stdout_is_console
int stdout_is_console = 1 [static]
Definition at line 404 of file shell.c.
zOptions
const char zOptions[] [static]
Definition at line 18526 of file shell.c.